### ISSUE TITLE
cross app invocation issue.

### ISSUE THREAD

**Issue by sxcooler** [apache/servicecomb-java-chassis#1072]
env: sc 1.1.0, java-chassis 1.1.0, using RestTemplate
I've got an issue that cross app invocation doesn't work.
When I turned my consumers appId to the same of producer, everything goes well, but if I use different appId and follow this doc https://docs.servicecomb.io/java-chassis/zh_CN/general-development/cross-app-invocation.html using colon to separate appId & serviceName, I got this:
```
2019-01-24 18:39:45.607 ERROR 63053 --- [pool-1-thread-1] aultExceptionToProducerResponseConverter : invoke failed, invocation=PRODUCER rest business-service.hello.callFooRest

java.lang.IllegalStateException: Probably invoke a service before it is registered, or no instance found for it, appId=sms, name=sms:ljq-sms-center
	at org.apache.servicecomb.core.provider.consumer.ConsumerProviderManager.createReferenceConfig(ConsumerProviderManager.java:61) ~[java-chassis-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.provider.consumer.ConsumerProviderManager.createReferenceConfig(ConsumerProviderManager.java:87) ~[java-chassis-core-1.1.0.jar:1.1.0]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_181]
	at org.apache.servicecomb.foundation.common.concurrent.ConcurrentHashMapEx.computeIfAbsent(ConcurrentHashMapEx.java:56) ~[foundation-common-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.provider.consumer.ConsumerProviderManager.getReferenceConfig(ConsumerProviderManager.java:91) ~[java-chassis-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.SCBEngine.getReferenceConfigForInvoke(SCBEngine.java:327) ~[java-chassis-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.findReferenceConfig(CseClientHttpRequest.java:170) ~[provider-springmvc-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.createRequestMeta(CseClientHttpRequest.java:152) ~[provider-springmvc-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.execute(CseClientHttpRequest.java:138) ~[provider-springmvc-1.1.0.jar:1.1.0]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:660) ~[spring-web-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:629) ~[spring-web-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:398) ~[spring-web-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.apache.servicecomb.provider.springmvc.reference.RestTemplateWrapper.postForObject(RestTemplateWrapper.java:119) ~[provider-springmvc-1.1.0.jar:1.1.0]
	at com.baolongxing.loan.HelloImpl.callFooRest(HelloImpl.java:108) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.doInvoke(SwaggerProducerOperation.java:180) [swagger-invocation-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.syncInvoke(SwaggerProducerOperation.java:165) [swagger-invocation-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.invoke(SwaggerProducerOperation.java:119) [swagger-invocation-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.handle(ProducerOperationHandler.java:40) [java-chassis-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.Invocation.next(Invocation.java:189) [java-chassis-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.doInvoke(AbstractRestInvocation.java:204) [common-rest-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke(AbstractRestInvocation.java:177) [common-rest-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor(AbstractRestInvocation.java:161) [common-rest-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(AbstractRestInvocation.java:144) [common-rest-1.1.0.jar:1.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
```

**Comment by wujimin** [comment]
1.producer should allow cross app invocation
2.producer should upgrade microservice version

**Comment by sxcooler** [comment]
@wujimin I've read the doc, set the allow cross property, and I was using the development environment.

**Comment by wujimin** [comment]
currently, even in development environment, only when swagger changed, will register microservice again.
so for your scenes, still need to upgrade microservice version.

**Comment by sxcooler** [comment]
@wujimin OK, I'll try again.
