### ISSUE TITLE
When return type is ResponseEntity<Void>, it will get NPE.  I try to fix it

### ISSUE THREAD

**Issue by kakulisen** [apache/servicecomb-java-chassis#1122]
```
Caused by: java.lang.NullPointerException: null
	at org.apache.servicecomb.swagger.converter.SwaggerToClassGenerator.convertModel(SwaggerToClassGenerator.java:280) ~[classes/:na]
	at org.apache.servicecomb.swagger.converter.SwaggerToClassGenerator.convertRef(SwaggerToClassGenerator.java:285) ~[classes/:na]
	at org.apache.servicecomb.swagger.converter.model.RefModelConverter.doConvert(RefModelConverter.java:29) ~[classes/:na]
	at org.apache.servicecomb.swagger.converter.AbstractConverter.convert(AbstractConverter.java:44) ~[classes/:na]
	at org.apache.servicecomb.swagger.converter.ConverterMgr.findJavaType(ConverterMgr.java:189) ~[classes/:na]
	at org.apache.servicecomb.swagger.converter.SwaggerToClassGenerator.convert(SwaggerToClassGenerator.java:256) ~[classes/:na]
	at org.apache.servicecomb.swagger.converter.SwaggerToClassGenerator.convertResponses(SwaggerToClassGenerator.java:191) ~[classes/:na]
	at org.apache.servicecomb.swagger.converter.SwaggerToClassGenerator.convert(SwaggerToClassGenerator.java:142) ~[classes/:na]
	at org.apache.servicecomb.core.definition.SchemaMeta.<init>(SchemaMeta.java:70) ~[classes/:na]
	at org.apache.servicecomb.core.definition.loader.SchemaLoader.registerSchema(SchemaLoader.java:85) ~[classes/:na]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.createSchema(ProducerSchemaFactory.java:133) ~[classes/:na]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.createSchema(ProducerSchemaFactory.java:54) ~[classes/:na]
	at org.apache.servicecomb.core.definition.schema.AbstractSchemaFactory.getOrCreateSchema(AbstractSchemaFactory.java:58) ~[classes/:na]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.getOrCreateProducerSchema(ProducerSchemaFactory.java:76) ~[classes/:na]
	at org.apache.servicecomb.provider.rest.common.RestProducerProvider.init(RestProducerProvider.java:45) ~[classes/:na]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.init(ProducerProviderManager.java:51) ~[classes/:na]
	at org.apache.servicecomb.core.SCBEngine.doInit(SCBEngine.java:235) ~[classes/:na]
	at org.apache.servicecomb.core.SCBEngine.init(SCBEngine.java:206) ~[classes/:na]
	... 13 common frames omitted
```

Find the code in OperationGenerator.java like below.  If the type of return is void, it will return null and that is right.  But,  when the type of return is ResponseEntity\<Void\>,  it will get NPE in the future.
```
  protected Model createResponseModel() {
    Type responseType = providerMethod.getReturnType();
    if (ReflectionUtils.isVoid(responseType)) {
      return null;
    }

    ResponseTypeProcessor processor = context.findResponseTypeProcessor(responseType);
    return processor.process(this, providerMethod.getGenericReturnType());
  }
```
![image](https://user-images.githubusercontent.com/16425825/54006557-bb04d000-4198-11e9-83c0-45a626c09823.png)

So, in order to solve this problem,  I write code in DefaultResponseTypeProcessor.java like below. And then all is right
```java
  protected Model doProcess(OperationGenerator operationGenerator, Type responseType) {
    // for ResponseEntity<Void>
    if (ReflectionUtils.isVoid(responseType)) {
      return null;
    }

    ParamUtils.addDefinitions(operationGenerator.getSwagger(), responseType);
    Property property = ModelConverters.getInstance().readAsProperty(responseType);
    return new PropertyModelConverter().propertyToModel(property);
  }
```
I want to know if this is appropriate, how do you think?

**Comment by kakulisen** [comment]
Here is my API operation
```java
  @PutMapping(path = "/putSome")
  public ResponseEntity<Void> putSome(){
    return new ResponseEntity<Void>(HttpStatus.OK);
  }
```

**Comment by wujimin** [comment]
:+1: 

for the latest code, a little changed:
org.apache.servicecomb.swagger.generator.core.processor.response.DefaultResponseTypeProcessor#doProcess
```
  protected Model doProcess(OperationGenerator operationGenerator, Type responseType) {
    if (ReflectionUtils.isVoid(responseType)) {
      return null;
    }

    ParamUtils.addDefinitions(operationGenerator.getSwagger(), responseType);
    Property property = ModelConverters.getInstance().readAsProperty(responseType);
    return new PropertyModelConverter().propertyToModel(property);
  }
```

do you mind raise a PR for this?

**Comment by kakulisen** [comment]
Thanks for your reply,  I will submit a PR later

**Comment by wujimin** [comment]
thanks for your PR, already merged.
