### ISSUE TITLE
启动项目报空指针是什么原因

### ISSUE THREAD

**Issue by Jie2019-01-01** [apache/servicecomb-java-chassis#1130]
2019-03-13 17:26:33.145  INFO 7640 --- [  restartedMain] o.a.s.c.definition.loader.SchemaLoader   : register schema start.servicecomb.io/NetDiscService/catalog
2019-03-13 17:26:33.212  INFO 7640 --- [  restartedMain] o.a.s.common.javassist.JavassistUtils    : create CtClass cse.gen.start.servicecomb.io.NetDiscService.catalog.queryCatalogAndRoleByUseridBody in classLoader org.springframework.boot.devtools.restart.classloader.RestartClassLoader@32de30e0.
2019-03-13 17:26:33.228  INFO 7640 --- [  restartedMain] o.a.s.common.javassist.JavassistUtils    : create class cse.gen.start.servicecomb.io.NetDiscService.catalog.queryCatalogAndRoleByUseridBody in classLoader org.springframework.boot.devtools.restart.classloader.RestartClassLoader@32de30e0.
2019-03-13 17:26:33.230 ERROR 7640 --- [  restartedMain] o.a.s.core.definition.SchemaMeta         : Unhandled exception to service NetDiscService schema catalog
2019-03-13 17:26:33.233  INFO 7640 --- [  restartedMain] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2019-03-13 17:26:33.242 ERROR 7640 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: ServiceComb init failed.
	at org.apache.servicecomb.core.SCBEngine.init(SCBEngine.java:183) ~[java-chassis-core-1.0.0.jar:1.0.0]
	at org.apache.servicecomb.core.CseApplicationListener.onApplicationEvent(CseApplicationListener.java:74) ~[java-chassis-core-1.0.0.jar:1.0.0]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) ~[spring-context-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.finished(EventPublishingRunListener.java:100) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.callFinishedListener(SpringApplicationRunListeners.java:79) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.finished(SpringApplicationRunListeners.java:72) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at io.matryoshka.gat.GatMain.main(GatMain.java:19) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_181]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.5.2.RELEASE.jar:1.5.2.RELEASE]
Caused by: java.lang.NullPointerException: null
	at org.apache.servicecomb.common.javassist.CtType.<init>(CtType.java:52) ~[common-javassist-1.0.0.jar:1.0.0]
	at org.apache.servicecomb.common.javassist.MethodConfig.addParameter(MethodConfig.java:72) ~[common-javassist-1.0.0.jar:1.0.0]
	at org.apache.servicecomb.swagger.converter.SwaggerToClassGenerator.convertToInterface(SwaggerToClassGenerator.java:229) ~[swagger-generator-core-1.0.0.jar:1.0.0]
	at org.apache.servicecomb.swagger.converter.SwaggerToClassGenerator.convert(SwaggerToClassGenerator.java:144) ~[swagger-generator-core-1.0.0.jar:1.0.0]
	at org.apache.servicecomb.core.definition.SchemaMeta.<init>(SchemaMeta.java:70) ~[java-chassis-core-1.0.0.jar:1.0.0]
	at org.apache.servicecomb.core.definition.loader.SchemaLoader.registerSchema(SchemaLoader.java:95) ~[java-chassis-core-1.0.0.jar:1.0.0]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.createSchema(ProducerSchemaFactory.java:133) ~[java-chassis-core-1.0.0.jar:1.0.0]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.createSchema(ProducerSchemaFactory.java:50) ~[java-chassis-core-1.0.0.jar:1.0.0]
	at org.apache.servicecomb.core.definition.schema.AbstractSchemaFactory.getOrCreateSchema(AbstractSchemaFactory.java:65) ~[java-chassis-core-1.0.0.jar:1.0.0]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.getOrCreateProducerSchema(ProducerSchemaFactory.java:83) ~[java-chassis-core-1.0.0.jar:1.0.0]
	at org.apache.servicecomb.provider.rest.common.RestProducerProvider.init(RestProducerProvider.java:48) ~[provider-rest-common-1.0.0.jar:1.0.0]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.init(ProducerProviderManager.java:56) ~[java-chassis-core-1.0.0.jar:1.0.0]
	at org.apache.servicecomb.core.SCBEngine.doInit(SCBEngine.java:202) ~[java-chassis-core-1.0.0.jar:1.0.0]
	at org.apache.servicecomb.core.SCBEngine.init(SCBEngine.java:178) ~[java-chassis-core-1.0.0.jar:1.0.0]
	... 18 common frames omitted

**Comment by wujimin** [comment]
please provide a reproduce project, thanks

**Comment by Jie2019-01-01** [comment]
谢谢你们的回复, 我的问题已经解决了, 主要是因为使用了swagger2中的@ApiImplicitParam注解造成的, 打扰了, 再次表示感谢!

At 2019-03-14 01:19:47, "wujimin" <notifications@github.com> wrote:


please provide a reproduce project, thanks

**Comment by wujimin** [comment]
maybe you write wrong datatype in ApiImplicitParam, eg: "int" to express "integer"
you can read: https://docs.swagger.io/spec.htm
