### ISSUE TITLE
IllegalArgumentException at ConfigurationSpringInitializer#getProperties 

### ISSUE THREAD

**Issue by houjibo** [apache/servicecomb-java-chassis#1133]
Method of ConfigurationSpringInitializer#getProperties with environment.getProperty(propertyName) throw an IllegalArgumentException

Suggest to modify setEnvironment around this.getAllProperties(environment) , setIgnoreUnresolvableNestedPlaceholders as true！

Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'ip' in value "jdbc:postgresql://${ip}:${port}/pt"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174) ~[spring-core-4.3.22.RELEASE.jar:4.3.22.RELEASE]
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126) ~[spring-core-4.3.22.RELEASE.jar:4.3.22.RELEASE]
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:236) ~[spring-core-4.3.22.RELEASE.jar:4.3.22.RELEASE]
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210) ~[spring-core-4.3.22.RELEASE.jar:4.3.22.RELEASE]
	at org.springframework.core.env.AbstractPropertyResolver.resolveNestedPlaceholders(AbstractPropertyResolver.java:227) ~[spring-core-4.3.22.RELEASE.jar:4.3.22.RELEASE]
	at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:84) ~[spring-core-4.3.22.RELEASE.jar:4.3.22.RELEASE]
	at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:61) ~[spring-core-4.3.22.RELEASE.jar:4.3.22.RELEASE]
	at org.springframework.core.env.AbstractEnvironment.getProperty(AbstractEnvironment.java:531) ~[spring-core-4.3.22.RELEASE.jar:4.3.22.RELEASE]
	at org.apache.servicecomb.config.ConfigurationSpringInitializer.getProperties(ConfigurationSpringInitializer.java:141) ~[foundation-config-1.1.0.jar:1.1.0]

**Comment by liangrongjie** [comment]
explanation above issue：
 There are some placeholders that cannot be replaced during the startup phase.（eg：`jdbc:postgresql://${ip}:${port}/pt`, database  endpoint can only be obtained from the service center after service registration）  

`ConfigurationSpringInitializer#setEnvironment(Environment)` will be invoked automatic (for `implements EnvironmentAware`) after bean created&Initialized，then call stack is as follows：
```java
ConfigurationSpringInitializer#setEnvironment(...)
ConfigurationSpringInitializer#getAllProperties(...)
ConfigurationSpringInitializer#getProperties(...)
AbstractEnvironment#getProperty(...)
......
```
at `AbstractPropertyResolver#resolveNestedPlaceholders`  used `AbstractEnvironment#propertyResolver`(not ConfigurationSpringInitializer ) to  resolve placeholder; although `ConfigurationSpringInitializer   extends PropertyPlaceholderConfigurer` & `ignoreUnresolvablePlaceholders=true` and can be used to replace placeholders and not throw exceptions

**Comment by liubao68** [comment]
I created a PR to fix this: https://github.com/apache/servicecomb-java-chassis/pull/1854/files

Users can add a configuration in `microservice.yaml`

```
servicecomb:
  config:
    ignoreResolveFailure: true 
```
to ignore place holder resolve error
