### ISSUE TITLE
1.1.0，微服务互相调用报错，请升级到1.2.0-SNAPSHOT以上

### ISSUE THREAD

**Issue by sxcooler** [apache/servicecomb-java-chassis#1148]
在调一个post接口时遇到以下问题，换用1.2.0-SNAPSHOT的java-chassis解决：
```
2019-03-25 12:26:41.061 ERROR 7115 --- [pool-1-thread-1] o.a.s.s.consumer.MicroserviceVersions    : Failed to setInstances, appId=foobar, microserviceName=demo-bar.

java.lang.NullPointerException: null
	at org.apache.servicecomb.swagger.SwaggerUtils.validateSwagger(SwaggerUtils.java:80) ~[swagger-generator-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.definition.SchemaUtils.parseSwagger(SchemaUtils.java:49) ~[java-chassis-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.definition.schema.ConsumerSchemaFactory.loadSwagger(ConsumerSchemaFactory.java:77) ~[java-chassis-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.definition.schema.ConsumerSchemaFactory.createSchema(ConsumerSchemaFactory.java:54) ~[java-chassis-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.definition.schema.ConsumerSchemaFactory.createSchema(ConsumerSchemaFactory.java:33) ~[java-chassis-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.definition.schema.AbstractSchemaFactory.getOrCreateSchema(AbstractSchemaFactory.java:58) ~[java-chassis-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.definition.schema.ConsumerSchemaFactory.createConsumerSchema(ConsumerSchemaFactory.java:47) ~[java-chassis-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.definition.MicroserviceVersionMeta.<init>(MicroserviceVersionMeta.java:45) ~[java-chassis-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.definition.MicroserviceVersionMetaFactory.create(MicroserviceVersionMetaFactory.java:38) ~[java-chassis-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceVersions.lambda$setInstances$0(MicroserviceVersions.java:182) [service-registry-1.1.0.jar:1.1.0]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_181]
	at org.apache.servicecomb.foundation.common.concurrent.ConcurrentHashMapEx.computeIfAbsent(ConcurrentHashMapEx.java:56) ~[foundation-common-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceVersions.setInstances(MicroserviceVersions.java:180) [service-registry-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceVersions.safeSetInstances(MicroserviceVersions.java:160) [service-registry-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceVersions.pullInstances(MicroserviceVersions.java:155) [service-registry-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceVersions.submitPull(MicroserviceVersions.java:127) [service-registry-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceManager.lambda$getOrCreateMicroserviceVersions$0(MicroserviceManager.java:55) [service-registry-1.1.0.jar:1.1.0]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_181]
	at org.apache.servicecomb.foundation.common.concurrent.ConcurrentHashMapEx.computeIfAbsent(ConcurrentHashMapEx.java:56) ~[foundation-common-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceManager.getOrCreateMicroserviceVersions(MicroserviceManager.java:53) [service-registry-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceManager.getOrCreateMicroserviceVersionRule(MicroserviceManager.java:79) [service-registry-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.serviceregistry.consumer.AppManager.getOrCreateMicroserviceVersionRule(AppManager.java:67) ~[service-registry-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.provider.consumer.ReferenceConfig.<init>(ReferenceConfig.java:37) ~[java-chassis-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.provider.consumer.ConsumerProviderManager.createReferenceConfig(ConsumerProviderManager.java:56) ~[java-chassis-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.provider.consumer.ConsumerProviderManager.createReferenceConfig(ConsumerProviderManager.java:87) ~[java-chassis-core-1.1.0.jar:1.1.0]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_181]
	at org.apache.servicecomb.foundation.common.concurrent.ConcurrentHashMapEx.computeIfAbsent(ConcurrentHashMapEx.java:56) ~[foundation-common-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.provider.consumer.ConsumerProviderManager.getReferenceConfig(ConsumerProviderManager.java:91) ~[java-chassis-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.SCBEngine.getReferenceConfigForInvoke(SCBEngine.java:327) ~[java-chassis-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.findReferenceConfig(CseClientHttpRequest.java:170) ~[provider-springmvc-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.createRequestMeta(CseClientHttpRequest.java:152) ~[provider-springmvc-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.execute(CseClientHttpRequest.java:138) ~[provider-springmvc-1.1.0.jar:1.1.0]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:660) ~[spring-web-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:621) ~[spring-web-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:539) ~[spring-web-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.apache.servicecomb.provider.springmvc.reference.RestTemplateWrapper.exchange(RestTemplateWrapper.java:178) ~[provider-springmvc-1.1.0.jar:1.1.0]
	at com.example.foobar.demo.HelloImpl.postRiskIdentity(HelloImpl.java:140) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.doInvoke(SwaggerProducerOperation.java:180) ~[swagger-invocation-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.syncInvoke(SwaggerProducerOperation.java:165) ~[swagger-invocation-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.invoke(SwaggerProducerOperation.java:119) ~[swagger-invocation-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.handle(ProducerOperationHandler.java:40) ~[java-chassis-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.core.Invocation.next(Invocation.java:189) ~[java-chassis-core-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.doInvoke(AbstractRestInvocation.java:204) ~[common-rest-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke(AbstractRestInvocation.java:177) ~[common-rest-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor(AbstractRestInvocation.java:161) ~[common-rest-1.1.0.jar:1.1.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(AbstractRestInvocation.java:144) ~[common-rest-1.1.0.jar:1.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]

2019-03-25 12:37:27.815  INFO 7455 --- [pool-1-thread-1] o.a.s.s.consumer.MicroserviceManager     : remove microservice, appId=foobar, microserviceName=demo-bar.
2019-03-25 12:37:27.816  INFO 7455 --- [pool-1-thread-1] o.a.s.s.consumer.MicroserviceVersions    : create MicroserviceVersionRule, appId=foobar, microserviceName=demo-bar, versionRule=0.0.0+.
2019-03-25 12:37:27.846  INFO 7455 --- [pool-1-thread-1] o.a.s.f.common.utils.SPIServiceUtils     : Found SPI service org.apache.servicecomb.swagger.invocation.exception.ExceptionToProducerResponseConverter, count=5.
2019-03-25 12:37:27.846  INFO 7455 --- [pool-1-thread-1] o.a.s.f.common.utils.SPIServiceUtils     :   0. com.example.foobar.demobar.converter.ConstraintViolationExceptionToProducerResponseConverter.
2019-03-25 12:37:27.846  INFO 7455 --- [pool-1-thread-1] o.a.s.f.common.utils.SPIServiceUtils     :   1. org.apache.servicecomb.swagger.invocation.validator.ConstraintViolationExceptionToProducerResponseConverter.
2019-03-25 12:37:27.846  INFO 7455 --- [pool-1-thread-1] o.a.s.f.common.utils.SPIServiceUtils     :   2. org.apache.servicecomb.swagger.invocation.exception.InvocationExceptionToProducerResponseConverter.
2019-03-25 12:37:27.846  INFO 7455 --- [pool-1-thread-1] o.a.s.f.common.utils.SPIServiceUtils     :   3. org.apache.servicecomb.swagger.invocation.exception.DefaultExceptionToProducerResponseConverter.
2019-03-25 12:37:27.846  INFO 7455 --- [pool-1-thread-1] o.a.s.f.common.utils.SPIServiceUtils     :   4. com.example.foobar.demobar.converter.CustomExceptionToProducerResponseConverter.

2019-03-25 12:37:27.848 ERROR 7455 --- [pool-1-thread-1] stomExceptionToProducerResponseConverter : java.lang.IllegalStateException: Probably invoke a service before it is registered, or no instance found for it, appId=foobar, name=demo-bar
at org.apache.servicecomb.core.provider.consumer.ConsumerProviderManager.createReferenceConfig(ConsumerProviderManager.java:61)
at org.apache.servicecomb.core.provider.consumer.ConsumerProviderManager.createReferenceConfig(ConsumerProviderManager.java:87)
at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
at org.apache.servicecomb.foundation.common.concurrent.ConcurrentHashMapEx.computeIfAbsent(ConcurrentHashMapEx.java:56)
at org.apache.servicecomb.core.provider.consumer.ConsumerProviderManager.getReferenceConfig(ConsumerProviderManager.java:91)
at org.apache.servicecomb.core.SCBEngine.getReferenceConfigForInvoke(SCBEngine.java:327)
at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.findReferenceConfig(CseClientHttpRequest.java:170)
at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.createRequestMeta(CseClientHttpRequest.java:152)
at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.execute(CseClientHttpRequest.java:138)
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:660)
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:621)
at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:539)
at org.apache.servicecomb.provider.springmvc.reference.RestTemplateWrapper.exchange(RestTemplateWrapper.java:178)
at com.example.foobar.demo.HelloImpl.postRiskIdentity(HelloImpl.java:140)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.doInvoke(SwaggerProducerOperation.java:180)
at org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.syncInvoke(SwaggerProducerOperation.java:165)
at org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.invoke(SwaggerProducerOperation.java:119)
at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.handle(ProducerOperationHandler.java:40)
at org.apache.servicecomb.core.Invocation.next(Invocation.java:189)
at org.apache.servicecomb.common.rest.AbstractRestInvocation.doInvoke(AbstractRestInvocation.java:204)
at org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke(AbstractRestInvocation.java:177)
at org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor(AbstractRestInvocation.java:161)
at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(AbstractRestInvocation.java:144)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```
我的代码：
```
@GetMapping(path = "/post-risk-identity")
public void postRiskIdentity() {
    String json = "{\"content\": \"some valid json\"}";
    HttpHeaders headers = new HttpHeaders();
    headers.setContentType(MediaType.APPLICATION_JSON_UTF8);
    headers.set("appId", "testApp");
    headers.set("userId", "32");
    HttpEntity entity = new HttpEntity(JSON.parseObject(json, Map.class), headers);

    ResponseEntity<String> responseEntity = restTemplate.exchange(
            "cse://demo-bar/identity/new", HttpMethod.POST, entity, String.class);
}
```
其中json我隐去了，但肯定是有效的。
我项目的pom：
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <groupId>com.example.foobar</groupId>
    <artifactId>demo</artifactId>
    <version>1.0-SNAPSHOT</version>
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.19.RELEASE</version>
        <relativePath/>
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java-chassis.version>1.1.0</java-chassis.version>
        <pulsar.version>2.2.1</pulsar.version>
        <mybatis-plus.version>3.1.0</mybatis-plus.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.servicecomb</groupId>
                <artifactId>java-chassis-dependencies</artifactId>
                <version>${java-chassis.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>spring-boot-starter-provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-validator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>jedis</artifactId>
                    <groupId>redis.clients</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-freemarker</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>${mybatis-plus.version}</version>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>${mybatis-plus.version}</version>
        </dependency>
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>3.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>2.10.1</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.56</version>
        </dependency>
        <dependency>
            <groupId>org.apache.pulsar</groupId>
            <artifactId>pulsar-client-original</artifactId>
            <version>${pulsar.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>transport-highway</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>transport-rest-vertx</artifactId>
        </dependency>
        <dependency>
            <groupId>com.example.foobar</groupId>
            <artifactId>demo-foo</artifactId>
            <version>1.0-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.example.foobar</groupId>
            <artifactId>demo-bar</artifactId>
            <version>1.0-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <artifactId>HikariCP</artifactId>
                    <groupId>com.zaxxer</groupId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/bin</outputDirectory>
                            <classifier>exec</classifier>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.6</version>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <Class-Path>.</Class-Path>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```
就是基于1.1.0的spring-boot的archetype生成的项目改了改

-----------------
所有代码都不用变，只要把java-chassis的版本改成1.2.0-SNAPSHOT就能解决，个人感觉这样的问题对于一个已经孵化完成的Apache基金会项目的一个正式版本而言还是挺严重的。
之所以1.2.0已经解决的问题提出来，是因为目前1.2.0还没有正式发布，方便遇到同样问题的开发者搜索。

**Comment by liubao68** [comment]
谢谢。这个问题的说明参考： https://bbs.huaweicloud.com/forum/thread-13817-1-1.html  通过google 检索关键字 "SwaggerUtils.validateSwagger java.lang.NullPointerException" 也能够找到答案

**Comment by sxcooler** [comment]
那还是空schema的问题……抱歉，我以为是新问题，那我关掉？

**Comment by liubao68** [comment]
Already fixed in 1.2.0, close.
