### ISSUE TITLE
日期类型怎么自定义转换格式？

### ISSUE THREAD

**Issue by myVictor** [apache/servicecomb-java-chassis#1166]
异常信息如下：

com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.util.Date` from String "2019-4-3 12:07:00": not a valid representation (error: Failed to parse Date value '2019-4-3 12:07:00': Failed to parse date "2019-4-3 12:07:00": Invalid number: 4-)
 at [Source: (org.apache.servicecomb.foundation.vertx.stream.BufferInputStream); line: 2, column: 12] (through reference chain: com.cz073586.attachment.dao.db1.model.AttachmentInfo["createAt"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1549)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:911)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseDate(StdDeserializer.java:524)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseDate(StdDeserializer.java:467)
	at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateBasedDeserializer._parseDate(DateDeserializers.java:195)
	at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:285)
	at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:268)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3084)
	at org.apache.servicecomb.common.rest.codec.param.BodyProcessorCreator$BodyProcessor.getValue(BodyProcessorCreator.java:104)
	at org.apache.servicecomb.common.rest.codec.RestCodec.restToArgs(RestCodec.java:62)
	at org.apache.servicecomb.common.rest.filter.inner.ServerRestArgsFilter.afterReceiveRequest(ServerRestArgsFilter.java:60)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.prepareInvoke(AbstractRestInvocation.java:192)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke(AbstractRestInvocation.java:171)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor(AbstractRestInvocation.java:161)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(AbstractRestInvocation.java:144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

**Comment by heyile** [comment]
@myVictor  可以在启动 main 方法里面设置.
```
  public static void main(String[] args) throws Exception {
    
    // 全局设置时间解析格式
    RestObjectMapperFactory.getRestObjectMapper().setDateFormat(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"));

  }
```

**Comment by myVictor** [comment]
好的 ，谢谢。

**Comment by Arvinxiaoweihao** [comment]
failed to decode response body, exception is [Cannot deserialize value of type `java.util.Date` from String "2019-08-17 00:00:00": not a valid representation (error: Failed to parse Date value '2019-08-17 00:00:00': Failed to parse date "2019-08-17 00:00:00": Invalid time zone indicator ' ')

**Comment by yhs0092** [comment]
@Arvinxiaoweihao  你的这个错误看上去是客户端接到服务端的应答后，无法反序列化应答body。需要你在客户端也设置一下日期格式，保持和服务端一致。
设置方法可以参考 @heyile  的回复

**Comment by Arvinxiaoweihao** [comment]
服务通过网关请求到对应的服务和契约，上面的配置需要放到网关才能正常，而且服务端返回页面的数据格式也要和网关配置的格式一致。通过网关的请求也只能接收与网关时间格式相同的日期数据，否则报错。测试了几次，返回数据现在正常的格式。网关做路由功能，默认不处理时间格式的话，数据通过网关就会统一是这种格式"yyyy-MM-dd'T'HH:mm:ss.SSSZ"，而且时间都是延迟一天，16:00:00

**Comment by wujimin** [comment]
`yyyy-MM-dd'T'HH:mm:ss.SSSZ`，这是ISO8601格式
所谓“时间都是延迟一天”，是个误解，因为Z表示的是UTC时间，这种表达，即使跨时区也没有问题
而"2019-08-17 00:00:00"这种方式，跨时区时，就搞不清楚到底是哪个时间了

**Comment by Arvinxiaoweihao** [comment]
在网关配置此时间格式
RestObjectMapperFactory.getRestObjectMapper().setDateFormat(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"));
页面返回的时间数据按这个格式显示，但是页面更新时如果以此格式传入然后用date接收，在服务端的更新接口和保存接口就会报请求有问题
{
    "message": "Parameter is not valid for operation [service-name.schemaId.methodId]. Parameter is [request]. Processor is [body]."
}

**Comment by Arvinxiaoweihao** [comment]
如果是按swagger的默认带时区的格式2019-07-23T03:49:12.820Z，传参接口请求正常，这个配置是不是在网关和服务都要全局配置才能保证接口都没问题，等会继续测试下

**Comment by Arvinxiaoweihao** [comment]
在服务都和网关都处理一次时间格式后，测试显示都正常了，jackson的字段注解
@JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
对于页面请求数据格式处理没效果，但是对于服务中心的swagger测试是有效的，swagger测试和页面的测试结果不同，这让人有时怀疑自己了

**Comment by wujimin** [comment]
1.建议直接使用ISO9601，js是可以直接处理的（ie8不行）
```
new Date(Date.parse("2019-09-17T00:00:00Z"))
Tue Sep 17 2019 08:00:00 GMT+0800 (中国标准时间)
```
2.如果实在要改（不考虑时区问题），则链路上所有进程都需要修改
其实估计是系统中所有进程都要修改，否则有的进程要这样，有的要那样，没法判定：
```
RestObjectMapperFactory.getRestObjectMapper().setDateFormat(……)
```
