### ISSUE TITLE
使用本地注册中心，自己调用自己，有一个类型转换的错误

### ISSUE THREAD

**Issue by johnyannj** [apache/servicecomb-java-chassis#1186]
使用-Dlocal.registry.file指定注册中心文件

一个简单接口
```
@RestSchema(schemaId = "helloId")
@RequestMapping("/")
public class HelloService {

    @RequestMapping(value = "/hello", method= RequestMethod.GET)
    public String hello(@PathVariable(name = "name") String name) {
        return name;
    }
}
```
简单配置
```
APPLICATION_ID: helloTest #Application name
service_description: #Service description
  name: hello #Microservice name
  version: 1.0.0 #Service version
servicecomb:
  rest:
    address: 0.0.0.0:8080

```
同一进程里，自己调用自己
```
 CseRestTemplate cseRestTemplate = new CseRestTemplate();
        String xiaoming = cseRestTemplate.getForObject("cse://hello/hello?name={}", String.class, "xiaoming");
```

异常如下：
```
java.lang.ClassCastException: org.apache.servicecomb.serviceregistry.consumer.MicroserviceVersion cannot be cast to org.apache.servicecomb.core.definition.MicroserviceVersionMeta

	at org.apache.servicecomb.core.provider.consumer.ReferenceConfig.getMicroserviceMeta(ReferenceConfig.java:54)
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.createRequestMeta(CseClientHttpRequest.java:154)
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.execute(CseClientHttpRequest.java:138)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:734)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:669)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:310)
	at com.huawei.nuwa.cse.test.HmacTest.test(HmacTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
```

**Comment by yhs0092** [comment]
你好，建议参照文档 [本地开发和测试](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/local-develop-test.html) 中 “跨进程调用” 的描述，配置一下再试试看？

**Comment by johnyannj** [comment]
@yhs0092 我的目的是想进程内调用， 自己调用自己来实现单元测试
我配置了
System.setProperty("local.registry.file", "notExistJustForceLocal");
也报相同的错误。

**Comment by wujimin** [comment]
please check your boot log about:
1."create local config:", what's the list of config file names
2."microserviceVersionFactory is ", what's the class name

**Comment by yhs0092** [comment]
在服务的启动日志里搜索 `microserviceVersionFactory is`，能搜到什么内容吗？
如果找到的内容不是`microserviceVersionFactory is org.apache.servicecomb.core.definition.PrivateMicroserviceVersionMetaFactory.` 这样的，那么在日志里搜索一下`create local config`关键字，应该能找到类似这样的内容，它展示了ServiceComb-Java-Chassis启动时加载了哪些配置文件
```
[2019-04-19 15:38:38,467][INFO][main][]create local config: org.apache.servicecomb.config.ConfigUtil.createLocalConfig(ConfigUtil.java:118)
[2019-04-19 15:38:38,467][INFO][main][] jar:file:/D:/.m2/repo/org/apache/servicecomb/java-chassis-core/1.3.0-SNAPSHOT/java-chassis-core-1.3.0-SNAPSHOT.jar!/microservice.yaml. org.apache.servicecomb.config.ConfigUtil.createLocalConfig(ConfigUtil.java:120)
[2019-04-19 15:38:38,468][INFO][main][] jar:file:/D:/.m2/repo/org/apache/servicecomb/solution-basic/1.3.0-SNAPSHOT/solution-basic-1.3.0-SNAPSHOT.jar!/microservice.yaml. org.apache.servicecomb.config.ConfigUtil.createLocalConfig(ConfigUtil.java:120)
[2019-04-19 15:38:38,468][INFO][main][] file:/D:/workspace/IDEA/yhs0092/JavaChassisFaultSimulator/fault-simulator-provider/target/classes/microservice.yaml. org.apache.servicecomb.config.ConfigUtil.createLocalConfig(ConfigUtil.java:120)
[2019-04-19 15:38:38,468][INFO][main][] file:/D:/workspace/IDEA/yhs0092/JavaChassisFaultSimulator/fault-simulator-common/target/classes/microservice.yaml. org.apache.servicecomb.config.ConfigUtil.createLocalConfig(ConfigUtil.java:120)
```
看看你搜到了几份配置文件呢？

**Comment by liubao68** [comment]
Maybe your project dependends on edge-core, remove it and try again. Or check following wujimin instructions.

**Comment by johnyannj** [comment]
I know the reason. 

I wanted to use different microservice.yaml in different  test case.
so I set the "servicecomb.configurationSource.defaultFileName" to different name in different test case.

so the microservice.yaml in java-chassis-core-1.xx.xx.jar is missed,  which contains "servicecomb.microserviceVersionFactory",  so it use the "DefaultMicroserviceVersionFactory".

我找到原因了， 我是想在不同的测试用例里使用不同的microservice.yaml ， 所以我想在每次测试用例之前改下"servicecomb.configurationSource.defaultFileName”  以达到目的。

但是因为修改"servicecomb.configurationSource.defaultFileName，导致 java-chassis-core-1.xx.xx.jar包里的 microservice.yaml没有加载。 而这个microservice.yaml包含servicecomb.microserviceVersionFactory=org.apache.servicecomb.core.definition.PrivateMicroserviceVersionMetaFactory的配置。

既然microservice.yaml的名字可以换，servicecomb包里又预置microservice.yaml好像，是不是有点不太合适？

此外我想在不同的单元测试用例里使用不同的微服务配置， 官方有什么好的建议呢？

**Comment by yhs0092** [comment]
不要用`servicecomb.configurationSource.defaultFileName`修改配置文件的名字，改为在System Property里设置`servicecomb.configurationSource.additionalUrls`，追加配置文件覆盖默认配置行不行呢？
相关逻辑的位置在`org.apache.servicecomb.config.archaius.sources.MicroserviceConfigLoader#loadAdditionalConfig`里

**Comment by liubao68** [comment]
If you are writing test cases, you can use this API https://github.com/apache/servicecomb-java-chassis/blob/master/foundations/foundation-test-scaffolding/src/main/java/org/apache/servicecomb/foundation/test/scaffolding/config/ArchaiusUtils.java  to change configurations in every test case.

**Comment by liubao68** [comment]
microservice.yaml supports override, using servicecomb-config-order in the first line to config it's order, this is another option. see https://docs.servicecomb.io/java-chassis/zh_CN/config/general-config.html

**Comment by liubao68** [comment]
Clear long time not updated issue. Please feel free to submit a new one if problem happended again.

**Comment by kissLife** [comment]
> microservice.yaml supports override, using servicecomb-config-order in the first line to config it's order, this is another option. see https://docs.servicecomb.io/java-chassis/zh_CN/config/general-config.html

link is refreshed:
http://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/config/general-config.html
