### ISSUE TITLE
servicecomb解析环境变量异常参数失败，导致无法启动

### ISSUE THREAD

**Issue by johnyannj** [apache/servicecomb-java-chassis#1219]
位置：
org.apache.servicecomb.config.ConfigurationSpringInitializer#setEnvironment

堆栈：
```
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:584)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:154)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:691)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:528)

Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'IFS+x' in value "() {  unset _mlre _mlIFS _mlshdbg;
 if [ "${MODULES_SILENT_SHELL_DEBUG:-0}" = '1' ]; then
.......
       at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:172)
        at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124)
        at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:237)
        at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:211)
        at org.springframework.core.env.AbstractPropertyResolver.resolveNestedPlaceholders(AbstractPropertyResolver.java:228)
        at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:88)
        at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:68)
        at org.springframework.core.env.AbstractEnvironment.getProperty(AbstractEnvironment.java:550)
        at org.apache.servicecomb.config.ConfigurationSpringInitializer.getProperties(ConfigurationSpringInitializer.java:199)
        at org.apache.servicecomb.config.ConfigurationSpringInitializer.getAllProperties(ConfigurationSpringInitializer.java:180)
        at org.apache.servicecomb.config.ConfigurationSpringInitializer.setEnvironment(ConfigurationSpringInitializer.java:82)
        at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:105)
        at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:96)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1737)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576)
        ... 12 more
```

如果系统环境变量value有错误格式，就会导致报错。

**Comment by yhs0092** [comment]
A task is created to track this issue [SCB-1297](https://issues.apache.org/jira/browse/SCB-1297)

**Comment by lyl8213** [comment]
这个问题要怎么解决啊，我也遇到了

**Comment by liubao68** [comment]
You can upgrade to lastest version(not released, need compile source), or try [CSE mirror](https://mirrors.huaweicloud.com/repository/maven/huaweicloudsdk/org/apache/servicecomb/common-rest/) for a lastest build, [maven repository notice](https://support.huaweicloud.com/qs-servicestage/cse_qs_0012.html)

**Comment by liubao68** [comment]
This issue have resovled in 1.3.0. Please test using this version. Please feel free to open an new issue if you find something goes wrong.
