### ISSUE TITLE
@RpcSchema注册失败而换成@RestSchema后正常

### ISSUE THREAD

**Issue by Arvinxiaoweihao** [apache/servicecomb-java-chassis#1237]
@RestController
//@RpcSchema(schemaId = "a")
@RestSchema(schemaId = "a")
@RequestMapping("a")
public class AController implements IARest {
//some method
}
代码修改后如上，这样才能启动正常，如果用的是@RpcSchema 则启动报错如下：

Caused by: org.apache.servicecomb.foundation.common.exceptions.ServiceCombException: operation with url /a/getAById/, method GET is duplicated.
	at org.apache.servicecomb.common.rest.locator.MicroservicePaths.addStaticPathResource(MicroservicePaths.java:81)
	at org.apache.servicecomb.common.rest.locator.MicroservicePaths.addResource(MicroservicePaths.java:57)
	at org.apache.servicecomb.common.rest.locator.ServicePathManager.addResource(ServicePathManager.java:121)
	at org.apache.servicecomb.common.rest.locator.ServicePathManager.addSchema(ServicePathManager.java:88)
	at org.apache.servicecomb.common.rest.RestEngineSchemaListener.onSchemaLoaded(RestEngineSchemaListener.java:54)
	at org.apache.servicecomb.core.definition.loader.SchemaListenerManager.notifySchemaListener(SchemaListenerManager.java:59)
	at org.apache.servicecomb.core.definition.loader.SchemaListenerManager.notifySchemaListener(SchemaListenerManager.java:48)
	at org.apache.servicecomb.core.definition.loader.SchemaListenerManager.notifySchemaListener(SchemaListenerManager.java:54)
	at org.apache.servicecomb.core.SCBEngine.doInit(SCBEngine.java:246)
	at org.apache.servicecomb.core.SCBEngine.init(SCBEngine.java:206)

发现在MicroservicePaths这个类中抛出了重复路径问题，如下是代码

protected void addStaticPathResource(RestOperationMeta operation) {
    String httpMethod = operation.getHttpMethod();
    String path = operation.getAbsolutePath();
    OperationGroup group = staticPathOperations.get(path);
    if (group == null) {
      group = new OperationGroup();
      group.register(httpMethod, operation);
      staticPathOperations.put(path, group);
      return;
    }

    if (group.findValue(httpMethod) == null) {
      group.register(httpMethod, operation);
      return;
    }

    throw new ServiceCombException(
        String.format("operation with url %s, method %s is duplicated.", path, httpMethod));
  }

**Comment by Arvinxiaoweihao** [comment]
使用的版本是1.2.0

**Comment by johnyannj** [comment]
https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/transparent-rpc.html

透明RPC开发模式是一种基于接口和接口实现的开发模式，服务的开发者不需要使用Spring MVC和JAX-RS注解。

不知道是不是你用了 RequestMapping的原因

**Comment by Arvinxiaoweihao** [comment]
测试中把改成@RequestMapping（“/”）用@RpcRpcSchema依旧会报错，只是少了“/a”路径而已。
Caused by: org.apache.servicecomb.foundation.common.exceptions.ServiceCombException: operation with url /getAById/, method GET is duplicated.
@RestSchema使用还是正常的

**Comment by johnyannj** [comment]
@Arvinxiaoweihao 
我觉得应该 去掉RequestMapping

**Comment by Arvinxiaoweihao** [comment]
有测试过跟RequestMapping无关

**Comment by liubao68** [comment]
能否看下some method的原型，有可能和这个有关。

**Comment by Arvinxiaoweihao** [comment]
method的方法如下：前几个版本的SC有着类似的写法，1.2.0这个版本运行直接出错，本地已经无法启动
    @Override
    @ApiOperation(value = "查看详情")
    @GetMapping(path = "getAById")
    public ObjectRestResponse<List<GetAByIdResponse>> getAById(){
   }

**Comment by Arvinxiaoweihao** [comment]
method的方法如下：前几个版本的SC有着类似的写法，1.2.0这个版本运行直接出错，本地已经无法启动
    @Override
    @ApiOperation(value = "查看回收站")
    @GetMapping(path = "getAInTrash")
    public ObjectRestResponse<List<GetAInTrashResponse>> getAInTrash() {
   //...
   }

**Comment by Arvinxiaoweihao** [comment]
method的方法如下：前几个版本的SC有着类似的写法，1.2.0这个版本运行直接出错，本地已经无法启动
@override
@ApiOperation(value = "查看回收站")
@GetMapping(path = "getAInTrash")
public ObjectRestResponse<List> getAInTrash() {
//...
}

**Comment by Arvinxiaoweihao** [comment]
页面显示时，泛型被隐藏了，ObjectRestResponse<List<GetAInTrashResponse>>

**Comment by liubao68** [comment]
Clean up old questions. Please feel free to create a new one if you met the problem again.
