### ISSUE TITLE
在servicecomb中使用ModelAndView报错，如何使用ModelAndView？？？？

### ISSUE THREAD

**Issue by zhangaijing** [apache/servicecomb-java-chassis#1273]
Caused by: java.lang.Error: generate operation swagger failed, com.controller.ViewController:view
	at org.apache.servicecomb.swagger.generator.core.SwaggerGenerator.scanMethods(SwaggerGenerator.java:280) ~[swagger-generator-core-1.1.0.B049.jar:1.1.0.B049]
	at org.apache.servicecomb.swagger.generator.core.SwaggerGenerator.generate(SwaggerGenerator.java:140) ~[swagger-generator-core-1.1.0.B049.jar:1.1.0.B049]
	at org.apache.servicecomb.core.definition.schema.AbstractSchemaFactory.generateSwagger(AbstractSchemaFactory.java:102) ~[java-chassis-core-1.1.0.B049.jar:1.1.0.B049]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.createSchema(ProducerSchemaFactory.java:115) ~[java-chassis-core-1.1.0.B049.jar:1.1.0.B049]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.createSchema(ProducerSchemaFactory.java:54) ~[java-chassis-core-1.1.0.B049.jar:1.1.0.B049]
	at org.apache.servicecomb.core.definition.schema.AbstractSchemaFactory.getOrCreateSchema(AbstractSchemaFactory.java:58) ~[java-chassis-core-1.1.0.B049.jar:1.1.0.B049]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.getOrCreateProducerSchema(ProducerSchemaFactory.java:76) ~[java-chassis-core-1.1.0.B049.jar:1.1.0.B049]
	at org.apache.servicecomb.provider.rest.common.RestProducerProvider.init(RestProducerProvider.java:45) ~[provider-rest-common-1.1.0.B049.jar:1.1.0.B049]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.init(ProducerProviderManager.java:54) ~[java-chassis-core-1.1.0.B049.jar:1.1.0.B049]
	at org.apache.servicecomb.core.SCBEngine.doInit(SCBEngine.java:235) ~[java-chassis-core-1.1.0.B049.jar:1.1.0.B049]
	at org.apache.servicecomb.core.SCBEngine.init(SCBEngine.java:206) ~[java-chassis-core-1.1.0.B049.jar:1.1.0.B049]
	... 15 common frames omitted
Caused by: java.lang.Error: HttpMethod must not both be empty in class and method
	at org.apache.servicecomb.swagger.generator.springmvc.processor.annotation.RequestMappingMethodAnnotationProcessor.process(RequestMappingMethodAnnotationProcessor.java:44) ~[swagger-generator-springmvc-1.1.0.B049.jar:1.1.0.B049]
	at org.apache.servicecomb.swagger.generator.core.OperationGenerator.scanMethodAnnotation(OperationGenerator.java:254) ~[swagger-generator-core-1.1.0.B049.jar:1.1.0.B049]
	at org.apache.servicecomb.swagger.generator.core.OperationGenerator.generate(OperationGenerator.java:180) ~[swagger-generator-core-1.1.0.B049.jar:1.1.0.B049]
	at org.apache.servicecomb.swagger.generator.core.SwaggerGenerator.scanMethods(SwaggerGenerator.java:276) ~[swagger-generator-core-1.1.0.B049.jar:1.1.0.B049]
	... 25 common frames omitted

**Comment by yhs0092** [comment]
ServiceComb-Java-Chassis 是一个RESTful微服务框架，它被设计出来主要是收发数据，做业务数据交互的，也就是它本来的设计目的是作为一个后端服务框架使用，所以不建议拿它作为前端页面的处理框架。

至于你碰到的这个错误，日志里已经把问题的直接原因打出来了
```
Caused by: java.lang.Error: HttpMethod must not both be empty in class and method
```
服务接口定义的时候没有指定HTTP method，比如像`@RequestMapping(path = "/sayhi", method = RequestMethod.POST)`这样的注解用法里，少了`method = RequestMethod.POST`这一段。

**Comment by liubao68** [comment]
ServiceComb不支持ModelAndView, 差异说明：https://docs.servicecomb.io/java-chassis/zh_CN/using-java-chassis-in-spring-boot/diff-spring-mvc.html 。 如果业务需要用spring boot MVC，也是可以并存的，可以参考说明： https://bbs.huaweicloud.com/blogs/b5dfdf9d51bf11e9bd5a7ca23e93a891

**Comment by liubao68** [comment]
Close old issues. Please feel free to create a new one when meet the problem again.
