### ISSUE TITLE
那位大佬赶紧给看看啊，在线等，挺急的！！！

### ISSUE THREAD

**Issue by luhuaitong** [apache/servicecomb-java-chassis#1291]
No schema defined for start.servicecomb.io:consumer.

**Comment by luhuaitong** [comment]
[ntloop-thread-4] o.a.s.c.rest.AbstractRestInvocation      : No schema defined for start.servicecomb.io:consumer.
2019-08-10 14:12:21.564  INFO 4740 --- [ntloop-thread-4] o.a.s.f.common.utils.SPIServiceUtils     : Found SPI service org.apache.servicecomb.swagger.invocation.exception.ExceptionToResponseConverter, count=2.
2019-08-10 14:12:21.564  INFO 4740 --- [ntloop-thread-4] o.a.s.f.common.utils.SPIServiceUtils     :   0. org.apache.servicecomb.swagger.invocation.exception.InvocationExceptionToResponseConverter.
2019-08-10 14:12:21.564  INFO 4740 --- [ntloop-thread-4] o.a.s.f.common.utils.SPIServiceUtils     :   1. org.apache.servicecomb.swagger.invocation.exception.DefaultExceptionToResponseConverter.
2019-08-10 14:12:21.592 ERROR 4740 --- [ntloop-thread-4] o.a.s.c.rest.AbstractRestInvocation      : No schema defined for start.servicecomb.io:consumer.
2019-08-10 14:12:33.144  WARN 4740 --- [ice Center Task] o.a.s.s.task.ServiceCenterTaskMonitor    : sc task interval changed from -1 to 30

**Comment by liubao68** [comment]
Need more information. Do you define any REST operations in consumer? Check service center frontend to find if any schema(swagger) found.

**Comment by liubao68** [comment]
Close old issue. Please feel free to create a new one.

**Comment by liubao68** [comment]
```
java.lang.Error: no schema defined for xxx.xxx
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.createRequestMeta(CseClientHttpRequest.java:164) ~[provider-springmvc-1.3.0.B007.jar:1.3.0.B007]
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.execute(CseClientHttpRequest.java:144) ~[provider-springmvc-1.3.0.B007.jar:1.3.0.B007]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:735) ~[spring-web-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:710) ~[spring-web-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:598) ~[spring-web-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at org.apache.servicecomb.provider.springmvc.reference.RestTemplateWrapper.exchange(RestTemplateWrapper.java:214) ~[provider-springmvc-1.3.0.B007.jar:1.3.0.B007]
```

如果发生这个错误， 很有可能是在 java-chassis 启动没有就绪的情况下，调用远程接口。 比如在 bean 的初始化过程中调用其他远程接口。 

发起对远程接口的调用， 需要在java-chassis启动就绪， 即 AFTER_REGISTRY 事件之后。 参考[服务启动事件](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/event-listener/)
