### ISSUE TITLE
内部接口调用报401

### ISSUE THREAD

**Issue by TCsteven** [apache/servicecomb-java-chassis#1320]
org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=401;msg={message=UNAUTHORIZED}
        at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.d**ate(ExceptionFactory.java:74) ~[swagger-invocation-core-1.1.0.B036.jar:1.1.0.B036]
        at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.create(ExceptionFactory.java:61) ~[swagger-invocation-core-1.1.0.B036.jar:1.1.0.B036]
        at org.apache.servicecomb.swagger.invocation.Response.create(Response.java:93) ~[swagger-invocation-core-1.1.0.B036.jar:1.1.0.B036]
        at org.apache.servicecomb.transport.rest.client.http.DefaultHttpClientFilter.extractResponse(DefaultHttpClientFilter.java:105) ~[transport-rest-client-1.1.0.B036.jar:1.1.0.B036]
        at org.apache.servicecomb.transport.rest.client.http.DefaultHttpClientFilter.afterReceiveResponse(DefaultHttpClientFilter.java:128) ~[transport-rest-client-1.1.0.B036.jar:1.1.0.B036]
        at org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.lambda$processResponseBody$7(RestClientInvocation.java:200) ~[transport-rest-client-1.1.0.B036.jar:1.1.0.B036]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**请问是什么问题，阻塞项目，急求**

**Comment by TCsteven** [comment]
内部接口调用，就只有这么多日志

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
