### ISSUE TITLE
如何使用Invocation传递多个参数？

### ISSUE THREAD

**Issue by ctlove0523** [apache/servicecomb-java-chassis#1363]
一个Provider提供一个下面类似的RPC接口：
`public List<String> queryApps(String appId, int count)`

请问如何通过Invocation传递appId和count两个参数进行调用？

**Comment by liubao68** [comment]
不太明白你的意思。 能给一下具体代码吗？ 一般RPC调用是:

```
@RpcReference(xxxx)
public Hello hello;

hello.queryApps(appId, count)
```

你是期望使用 InvokerUtils的方法调用？

**Comment by ctlove0523** [comment]
期望使用InvokerUtils的`Object syncInvoke(String microserviceName, String schemaId, String operationName, Object[] args)`方法进行调用，具体的代码如下：
```
       Object[] invokeArgs = new Object[2];
        invokeArgs[0] = "ServiceCOmb";
        invokeArgs[1] = 10;
        InvokerUtils.syncInvoke("hello","codeFirstCompute","queryApps",invokeArgs);
```

代码允许的错误如下：
```
Caused by: java.lang.Error: encode request failed. appid=pojo-sample, qualifiedName=hello.codeFirstCompute.queryApps
	at org.apache.servicecomb.transport.highway.HighwayClientPackage.createStream(HighwayClientPackage.java:43)
	at org.apache.servicecomb.foundation.vertx.client.tcp.TcpClientConnection.writeToBufferQueue(TcpClientConnection.java:133)
	at org.apache.servicecomb.foundation.vertx.client.tcp.TcpClientConnection.send(TcpClientConnection.java:109)
	at org.apache.servicecomb.transport.highway.HighwayClient.send(HighwayClient.java:103)
	at org.apache.servicecomb.transport.highway.HighwayTransport.send(HighwayTransport.java:55)
	at org.apache.servicecomb.core.handler.impl.TransportClientHandler.handle(TransportClientHandler.java:42)
	at org.apache.servicecomb.core.Invocation.next(Invocation.java:204)
	at org.apache.servicecomb.loadbalance.LoadbalanceHandler.send(LoadbalanceHandler.java:244)
	at org.apache.servicecomb.loadbalance.LoadbalanceHandler.handle(LoadbalanceHandler.java:205)
	at org.apache.servicecomb.core.Invocation.next(Invocation.java:204)
	at org.apache.servicecomb.bizkeeper.BizkeeperCommand.lambda$construct$2(BizkeeperCommand.java:79)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	... 43 more
Caused by: java.lang.ClassCastException: [C cannot be cast to java.lang.String
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$9$1.writeTo(RuntimeUnsafeFieldFactory.java:760)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:475)
	at org.apache.servicecomb.codec.protobuf.utils.schema.ArgsNotWrapSchema.writeObject(ArgsNotWrapSchema.java:51)
	at org.apache.servicecomb.transport.highway.HighwayOutputStream.write(HighwayOutputStream.java:54)
	at org.apache.servicecomb.transport.highway.HighwayOutputStream.write(HighwayOutputStream.java:33)
	at org.apache.servicecomb.transport.highway.HighwayCodec.encodeRequest(HighwayCodec.java:47)
	at org.apache.servicecomb.transport.highway.HighwayClientPackage.createStream(HighwayClientPackage.java:38)
	... 54 more
```

调用的参数是一个Object数组，Object[]是如何被解析的？无参数和只有一个参数的经过测试调用是可以的。多谢！

**Comment by liubao68** [comment]
目前不支持这种用法，估计得到2.0版本规划实现。 目前这里的args传递的是swagger类型（可以打开契约查看），类型是一个包装的类型，类型信息是运行时动态创建的。使用者无法自己构建这个类型的实例。 

如果你不使用highway协议， 使用REST的话，可以尝试下使用map传参。

**Comment by ctlove0523** [comment]
服务端使用REST协议（而且只能使用REST协议不能使用highway），客户端可以使用Map传递多个参数，样例：
```
       Object[] invokeArgs = new Object[1];
        Map<String,Object> map = new HashMap<>();
        map.put("appId","app1");
        map.put("count",10);
        invokeArgs[0] = map;
        Object result = InvokerUtils.syncInvoke("hello","codeFirstCompute","queryApps",invokeArgs);
        System.out.println(new Gson().toJson(result));
```
是否可以将这个使用样例提交到sample中？

**Comment by liubao68** [comment]
参考： https://github.com/apache/servicecomb-java-chassis/issues/1413
