### ISSUE TITLE
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'producerProviderManager':

### ISSUE THREAD

**Issue by kenzhaoyihui** [apache/servicecomb-java-chassis#1377]
Hello, I am the starter with  servicecomb 1.3.0.
When I use the sample `springmvc` to learn , I found the error .
```
Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'producerProviderManager': Unsatisfied dependency expressed through field 'producerProviderList'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'restProducerProvider': Unsatisfied dependency expressed through field 'producerSchemaFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'producerSchemaFactory': Unsatisfied dependency expressed through field 'compositeSwaggerGeneratorContext'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'compositeSwaggerGeneratorContext' defined in URL [jar:file:/D:/repository/org/apache/servicecomb/swagger-generator-core/1.3.0/swagger-generator-core-1.3.0.jar!/org/apache/servicecomb/swagger/generator/core/CompositeSwaggerGeneratorContext.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.servicecomb.swagger.generator.core.CompositeSwaggerGeneratorContext]: Constructor threw exception; nested exception is java.util.ServiceConfigurationError: org.apache.servicecomb.swagger.generator.core.SwaggerGeneratorContext: Provider org.apache.servicecomb.swagger.generator.jaxrs.JaxrsSwaggerGeneratorContext could not be instantiated
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:586)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:364)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1269)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
	at org.apache.servicecomb.foundation.common.utils.BeanUtils.init(BeanUtils.java:54)
	at org.apache.servicecomb.foundation.common.utils.BeanUtils.init(BeanUtils.java:47)

other errors:

Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V

Caused by: java.util.ServiceConfigurationError: org.apache.servicecomb.swagger.generator.core.SwaggerGeneratorContext: Provider org.apache.servicecomb.swagger.generator.jaxrs.JaxrsSwaggerGeneratorContext could not be instantiated


Error creating bean with name 'compositeSwaggerGeneratorContext' defined in URL [jar:file:/D:/repository/org/apache/servicecomb/swagger-generator-core/1.3..0.jar!/org/apache/servicecomb/swagger/generator/core/CompositeSwaggerGeneratorContext.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.servicecomb.swagger.generator.core.CompositeSwaggerGeneratorContext]: Constructor threw exception; nested exception is java.util.ServiceConfigurationError: org.apache.servicecomb.swagger.generator.core.SwaggerGeneratorContext: Provider org.apache.servicecomb.swagger.generator.jaxrs.JaxrsSwaggerGeneratorContext could not be instantiated
```

can you give me the help?

**Comment by liubao68** [comment]
You can use 
```
mvn dependency:tree 
```
to check the dependencies for guava. Maybe you used some old version of guava that is not compatible. 

Then fix it by adding dependency management to use the correct version.

**Comment by liubao68** [comment]
Close old issue, please feel free to create new one if you meet the problem again.
