### ISSUE TITLE
项目配置https后，可通过ip进行访问，无法通过cse上的服务名方式访问

### ISSUE THREAD

**Issue by Fang57** [apache/servicecomb-java-chassis#1395]
1.握手失败
2.Failed to create SSL connection

javax.net.ssl.SSLHandshakeException: Failed to create SSL connection
	at io.vertx.core.http.impl.HttpChannelConnector.handshakeFailure(HttpChannelConnector.java:229) ~[vertx-core-3.5.3.jar:3.5.3]
	at io.vertx.core.http.impl.HttpChannelConnector.lambda$null$0(HttpChannelConnector.java:165) ~[vertx-core-3.5.3.jar:3.5.3]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) [netty-common-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) [netty-common-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) [netty-common-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) [netty-common-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121) [netty-common-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.handler.ssl.SslHandler.handleUnwrapThrowable(SslHandler.java:1201) [netty-handler-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1183) [netty-handler-4.1.24.Final.jar:4.1.24.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1221) [netty-handler-4.1.24.Final.jar:4.1.24.Final]

**Comment by liubao68** [comment]
This trace lack of information needed to alalyse the problem. Can you try to provide more information?

**Comment by Fang57** [comment]
已解决
