### ISSUE TITLE
servicecomb有类似dubbo泛化调用的功能吗，如果有的话怎么使用呢

### ISSUE THREAD

**Issue by ruiwang04** [apache/servicecomb-java-chassis#1413]
我发现InvokerUtils.syncInvoke(String microserviceName, String schemaId, String operationName, Object[] args)方法好像是跟dubbo的泛化调用类似，使用了一下，发现一些问题
只能通过map传参，一个方法体内第一次调用没问题，后续调用会报下面这种错
InvocationException: code=400;msg={message=Parameters not valid or types not match.}
org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=400;msg={message=Parameters not valid or types not match.}
        at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.doCreate(ExceptionFactory.java:74)
        at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.create(ExceptionFactory.java:61)

InvokerUtils.syncInvoke(String microserviceName, String microserviceVersion, String transport, String schemaId, String operationName, Object[] args)这个方法该如何使用呢，目前为止我还没调通过，希望帮忙解答一下，谢谢了

**Comment by liubao68** [comment]
你服务端的接口是采用RPC方式定义的吗？并且接口包含大于等于2个参数？ RPC模式有点特殊，多个参数从契约上包装成了一个参数。

**Comment by liubao68** [comment]
类似问题参考： https://github.com/apache/servicecomb-java-chassis/issues/1363

**Comment by ruiwang04** [comment]
> 你服务端的接口是采用RPC方式定义的吗？并且接口包含大于等于2个参数？ RPC模式有点特殊，多个参数从契约上包装成了一个参数。

服务端是rpc方式定义的，一个参数，两个参数的方法都有定义, #1363这个问题我也看过，也是用map传的参，但是同一个方法体类多次用InvokerUtils.syncInvoke调用的话发现有个问题，有参数的方法第一次调用没问题，后续调用就会报错了，上面也把报错贴出来了，同一个方法体内无参数调用多次是没问题的

**Comment by liubao68** [comment]
第一次调用成功，第二次调用不成功， 这个感觉有点奇怪。 这个错误是SwaggerProducerOperation打印出来的，可以试试打一个断点调试下，看看服务端得到的类型是什么样的，是否能够转换为服务端的类型。

**Comment by ruiwang04** [comment]
> 第一次调用成功，第二次调用不成功， 这个感觉有点奇怪。 这个错误是SwaggerProducerOperation打印出来的，可以试试打一个断点调试下，看看服务端得到的类型是什么样的，是否能够转换为服务端的类型。

![图片](https://user-images.githubusercontent.com/26107888/69687957-9c1be480-10ff-11ea-92d0-d2b723e3da5e.png)
确实很奇怪，我只是把调用复制了一次

**Comment by ruiwang04** [comment]
> 第一次调用成功，第二次调用不成功， 这个感觉有点奇怪。 这个错误是SwaggerProducerOperation打印出来的，可以试试打一个断点调试下，看看服务端得到的类型是什么样的，是否能够转换为服务端的类型。
![Uploading 图片.png
![WX20191127-servicecomb](https://user-images.githubusercontent.com/26107888/69688224-6b887a80-1100-11ea-8075-a75fcf0fc127.png)
确实很奇怪，我只是复制了一遍
…]()

**Comment by ruiwang04** [comment]
> 第一次调用成功，第二次调用不成功， 这个感觉有点奇怪。 这个错误是SwaggerProducerOperation打印出来的，可以试试打一个断点调试下，看看服务端得到的类型是什么样的，是否能够转换为服务端的类型。

![图片](https://user-images.githubusercontent.com/26107888/69688310-a68aae00-1100-11ea-8b79-882cf4d9971a.png)

**Comment by ruiwang04** [comment]
![图片](https://user-images.githubusercontent.com/26107888/69688347-c4581300-1100-11ea-966d-2aa0e58d9b2b.png)

**Comment by ruiwang04** [comment]
> 第一次调用成功，第二次调用不成功， 这个感觉有点奇怪。 这个错误是SwaggerProducerOperation打印出来的，可以试试打一个断点调试下，看看服务端得到的类型是什么样的，是否能够转换为服务端的类型。

确实很奇怪，我只是复制了一次方法再次调用

 Map<String,Object> map = new HashMap<>();
            map.put("name","zhangsan22");
            map.put("age",31);

            Object result1 = InvokerUtils.syncInvoke("ServiceCombProviderDemo","providerController","sayHello2",new Object[]{map});
            System.out.println("泛化调用结果1："+result1);

            Object result11 = InvokerUtils.syncInvoke("ServiceCombProviderDemo","providerController","sayHello2",new Object[]{map});
            System.out.println("泛化调用结果11："+result11);

运行结果如下：
泛化调用结果1：姓名：zhangsan22,年龄：31
InvocationException: code=400;msg={message=Parameters not valid or types not match.}
	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.doCreate(ExceptionFactory.java:74)
	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.create(ExceptionFactory.java:61)
	at org.apache.servicecomb.swagger.invocation.Response.create(Response.java:93)
	at org.apache.servicecomb.swagger.invocation.Response.create(Response.java:87)
	at org.apache.servicecomb.transport.highway.HighwayCodec.decodeResponse(HighwayCodec.java:82)
	at org.apache.servicecomb.transport.highway.HighwayClient.lambda$null$0(HighwayClient.java:119)
	at org.apache.servicecomb.transport.highway.HighwayClient$$Lambda$367/484222006.run(Unknown Source)
	at org.apache.servicecomb.core.provider.consumer.SyncResponseExecutor.waitResponse(SyncResponseExecutor.java:56)
	at org.apache.servicecomb.core.provider.consumer.InvokerUtils.innerSyncInvoke(InvokerUtils.java:75)
	at org.apache.servicecomb.core.provider.consumer.InvokerUtils.syncInvoke(InvokerUtils.java:54)
	at org.apache.servicecomb.core.provider.consumer.InvokerUtils.syncInvoke(InvokerUtils.java:37)
	at com.wang.ServiceCombConsumerDemo.HelloController.hello(HelloController.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.doInvoke(SwaggerProducerOperation.java:180)
	at org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.syncInvoke(SwaggerProducerOperation.java:165)
	at org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.invoke(SwaggerProducerOperation.java:119)
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.handle(ProducerOperationHandler.java:40)
	at org.apache.servicecomb.core.Invocation.next(Invocation.java:204)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.doInvoke(AbstractRestInvocation.java:243)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke(AbstractRestInvocation.java:217)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor(AbstractRestInvocation.java:201)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(AbstractRestInvocation.java:160)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation$$Lambda$319/1296001042.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by liubao68** [comment]
哦。 你服务端配置了两个transport，应该是REST transport没问题， highway有问题。 可以删除highway。 highway是protobuffer编码（有类型信息要求），目前还支持不了这种处理方式。

**Comment by ruiwang04** [comment]
> 哦。 你服务端配置了两个transport，应该是REST transport没问题， highway有问题。 可以删除highway。 highway是protobuffer编码（有类型信息要求），目前还支持不了这种处理方式。

也就是说目前为止highway transport是无法实现类似dubbo的泛化调用吗

**Comment by liubao68** [comment]
目前RPC模式是不可以的， 我们记录一个需求考虑下后续支持计划。 服务端如果采用Spring MVC或者REST方式定义接口，应该是可以的，这个时候，有比较明确的契约，服务端生成契约的时候，不需要现在这样将多个参数包装为一个。

**Comment by ruiwang04** [comment]
> 目前RPC模式是不可以的， 我们记录一个需求考虑下后续支持计划。 服务端如果采用Spring MVC或者REST方式定义接口，应该是可以的，这个时候，有比较明确的契约，服务端生成契约的时候，不需要现在这样将多个参数包装为一个。

好的，非常感谢您的解答

**Comment by liubao68** [comment]
2.0.0支持了这种方式，例子[参考](https://github.com/apache/servicecomb-java-chassis/blob/master/demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/TestWeakPojo.java)

需要注意的是，泛化调用客户端指定的参数列表是“Swagger Arguments”，需要查看服务端的生成的swagger接口描述，然后通过map传递参数列表。对于RPC（POJO）和Spring MVC开发模式，契约会有所差异。上述例子展现了RPC模式:

```
    Map<String, Object> args = new HashMap<>();
    args.put("x", 2);
    args.put("y", 3);
    Map<String, Object> swaggerArgs = new HashMap<>();
    swaggerArgs.put("differentNameBody", args);
    TestMgr.check(7, InvokerUtils.syncInvoke("pojo", "WeakPojo", "differentName", swaggerArgs));
```

RPC模式会将所有参数包装为一个body参数，所有实际的参数是differentNameBody
