### ISSUE TITLE
微服务间接口调用失败

### ISSUE THREAD

**Issue by afan321** [apache/servicecomb-java-chassis#1436]
同一个应用下3个服务A B C. A 去调用C 的接口是好的.但当B 去调用C的接口时报错 Probably invoke a service before it is registered, or no instance found for it. 想问下消费者这边那些配置可能会影响到这种接口的调用. 报错的信息如下2019-12-03 18:59:17,647 [pool-8-thread-2] INFO  o.a.s.s.consumer.MicroserviceVersions:83 - create MicroserviceVersions, appId=CloudTest, microserviceName=userAuth.
2019-12-03 18:59:17,653 [pool-8-thread-2] INFO  o.a.s.s.registry.AbstractServiceRegistry:260 - find instances[1] from service center success. service=CloudTest/userAuth/0.0.0+, old revision=null, new revision=2726e0d04cc69c18cbf5689585a7baf56b90f175
2019-12-03 18:59:17,653 [pool-8-thread-2] INFO  o.a.s.s.registry.AbstractServiceRegistry:268 - service id=a55095d8049aa5fe2eea91d84f7b4ee454627221, instance id=960fc60415b911eab7bd286ed48991d4, endpoints=[rest://127.0.0.1:12582]
2019-12-03 18:59:17,655 [pool-8-thread-2] INFO  o.a.s.core.definition.MicroserviceVersionMeta:56 - get or create MicroserviceMeta from microserviceMetaManager for userAuth.
2019-12-03 18:59:17,655 [pool-8-thread-2] INFO  o.a.s.c.d.classloader.MicroserviceClassLoader:41 - create classloader for microservice CloudTest:userAuth:0.0.2.
2019-12-03 18:59:17,656 [pool-8-thread-2] INFO  o.a.s.core.definition.schema.ConsumerSchemaFactory:73 - load schema from service center, microservice=CloudTest:userAuth:0.0.2, schemaId=AuthencationController, result=true
2019-12-03 18:59:17,659 [pool-8-thread-2] ERROR o.a.s.s.consumer.MicroserviceVersions:166 - Failed to setInstances, appId=CloudTest, microserviceName=userAuth.
org.apache.servicecomb.foundation.common.exceptions.ServiceCombException: **Parse swagger from content failed,** 
	at org.apache.servicecomb.swagger.SwaggerUtils.parseSwagger(SwaggerUtils.java:75)
	at org.apache.servicecomb.core.definition.SchemaUtils.parseSwagger(SchemaUtils.java:48)
	at org.apache.servicecomb.core.definition.schema.ConsumerSchemaFactory.loadSwagger(ConsumerSchemaFactory.java:81)
	at org.apache.servicecomb.core.definition.schema.ConsumerSchemaFactory.createSchema(ConsumerSchemaFactory.java:58)
	at org.apache.servicecomb.core.definition.schema.ConsumerSchemaFactory.createSchema(ConsumerSchemaFactory.java:33)
	at org.apache.servicecomb.core.definition.schema.AbstractSchemaFactory.getOrCreateSchema(AbstractSchemaFactory.java:58)
	at org.apache.servicecomb.core.definition.schema.ConsumerSchemaFactory.createConsumerSchema(ConsumerSchemaFactory.java:48)
	at org.apache.servicecomb.core.definition.MicroserviceVersionMeta.<init>(MicroserviceVersionMeta.java:70)
	at org.apache.servicecomb.core.definition.MicroserviceVersionMetaFactory.create(MicroserviceVersionMetaFactory.java:38)
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceVersions.lambda$setInstances$0(MicroserviceVersions.java:184)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.apache.servicecomb.foundation.common.concurrent.ConcurrentHashMapEx.computeIfAbsent(ConcurrentHashMapEx.java:56)
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceVersions.setInstances(MicroserviceVersions.java:183)
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceVersions.safeSetInstances(MicroserviceVersions.java:163)
	at org.apache.servicecomb.serviceregistry.consumer.MicroserviceVersions.pullInstances(MicroserviceVersions.java:158)Caused by: **java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonStreamContext.<init>(II)V
	at com.fasterxml.jackson.databind.util.TokenBufferReadContext.<init>**(TokenBufferReadContext.java:59)
	at com.fasterxml.jackson.databind.util.TokenBufferReadContext.createRootContext(TokenBufferReadContext.java:89)
	at com.fasterxml.jackson.databind.util.TokenBuffer$Parser.<init>(TokenBuffer.java:1298)
	at com.fasterxml.jackson.databind.util.TokenBuffer.asParser(TokenBuffer.java:276)
	at com.fasterxml.jackson.databind.util.TokenBuffer.asParser(TokenBuffer.java:242)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3731)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3668)
	at io.swagger.util.PathDeserializer.deserialize(PathDeserializer.java:27)
	at io.swagger.util.PathDeserializer.deserialize(PathDeserializer.java:14)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at org.apache.servicecomb.swagger.SwaggerUtils.internalParseSwagger(SwaggerUtils.java:102)
	at org.apache.servicecomb.swagger.SwaggerUtils.parseSwagger(SwaggerUtils.java:73)
	... 105 common frames omitted
2019-12-03 18:59:17,659 [pool-8-thread-2] INFO  o.a.s.serviceregistry.consumer.MicroserviceManager:76 - remove microservice, appId=CloudTest, microserviceName=userAuth.
2019-12-03 18:59:17,660 [pool-8-thread-2] INFO  o.a.s.s.consumer.MicroserviceVersions:227 - create MicroserviceVersionRule, appId=CloudTest, microserviceName=userAuth, versionRule=0+.
2019-12-03 18:59:17,660 [pool-8-thread-2] INFO  o.a.s.s.consumer.MicroserviceVersionRule:113 - update instances to be empty caused by version rule, appId=CloudTest, microserviceName=userAuth, versionRule=0.0.0.0+, latestVersion=null, inputVersionCount=0, inputInstanceCount=1
2019-12-03 18:59:17,661 [pool-8-thread-2] ERROR o.a.s.s.i.e.DefaultExceptionToProducerResponseConverter:35 - invoke failed, invocation=PRODUCER rest commom.CaseSuitBatchesController.test
java.lang.IllegalStateException: **Probably invoke a service before it is registered, or no instance found for it, appId=CloudTest, name=userAuth**
	at org.apache.servicecomb.core.provider.consumer.ConsumerProviderManager.createReferenceConfig(ConsumerProviderManager.java:61)
	at org.apache.servicecomb.core.provider.consumer.ConsumerProviderManager.createReferenceConfig(ConsumerProviderManager.java:87)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.apache.servicecomb.foundation.common.concurrent.ConcurrentHashMapEx.computeIfAbsent(ConcurrentHashMapEx.java:56)
	at org.apache.servicecomb.core.provider.consumer.ConsumerProviderManager.getReferenceConfig(ConsumerProviderManager.java:91)
	at org.apache.servicecomb.core.SCBEngine.getReferenceConfigForInvoke(SCBEngine.java:332)
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.findReferenceConfig(CseClientHttpRequest.java:170)
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.createRequestMeta(CseClientHttpRequest.java:152)
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.execute(CseClientHttpRequest.java:138)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:735)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:579)

**Comment by yhs0092** [comment]
看日志的话不是B服务没找到C服务，而是B在加载C的服务契约的时候抛异常了。
你贴的日志里面有这么一行
```
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonStreamContext
```
一般这种错误是依赖问题，可能是依赖包有冲突，建议排查一下看看

**Comment by liubao68** [comment]
参考[文章](https://servicecomb.apache.org/cn/docs/maven_dependency_management/)排查依赖关系

**Comment by afan321** [comment]
十分感谢各位. 问题已经解决. 原因是CSE 中jackson 包版本为2.9.8  本项目中原先引用的jackson 版本为2.8.8   将版本改一致后问题得到解决.

**Comment by lw985** [comment]
> 看日志的话不是B服务没找到C服务，而是B在加载C的服务契约的时候抛异常了。 你贴的日志里面有这么一行
> 
> ```
> Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonStreamContext
> ```
> 
> 一般这种错误是依赖问题，可能是依赖包有冲突，建议排查一下看看

那我这种是啥问题呢
2024-07-01 09:09:42.254 ERROR 45396 --- [oup0-1-thread-2] o.a.s.r.consumer.MicroserviceVersions    : Failed to setInstances, appId=qwer, microserviceName=provider_qwer.

org.apache.servicecomb.foundation.common.exceptions.ServiceCombException: Parse swagger from content failed, 
	at org.apache.servicecomb.swagger.SwaggerUtils.parseSwagger(SwaggerUtils.java:110) ~[swagger-generator-core-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.swagger.SwaggerUtils.parseAndValidateSwagger(SwaggerUtils.java:115) ~[swagger-generator-core-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.registry.swagger.SwaggerLoader.lambda$loadFromRemote$4(SwaggerLoader.java:196) ~[foundation-registry-2.8.14.jar:2.8.14]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_252]
	at org.apache.servicecomb.foundation.common.concurrent.ConcurrentHashMapEx.computeIfAbsent(ConcurrentHashMapEx.java:56) ~[foundation-common-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.registry.swagger.SwaggerLoader.loadFromRemote(SwaggerLoader.java:185) ~[foundation-registry-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.registry.swagger.SwaggerLoader.loadSwagger(SwaggerLoader.java:138) ~[foundation-registry-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.core.definition.ServiceRegistryListener.onCreateMicroserviceVersion(ServiceRegistryListener.java:103) ~[java-chassis-core-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.foundation.common.event.SimpleSubscriber.syncDispatch(SimpleSubscriber.java:118) ~[foundation-common-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.foundation.common.event.SimpleSubscriber.dispatchEvent(SimpleSubscriber.java:107) ~[foundation-common-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.foundation.common.event.SimpleEventBus.post(SimpleEventBus.java:74) ~[foundation-common-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.registry.consumer.MicroserviceVersion.<init>(MicroserviceVersion.java:58) ~[foundation-registry-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.registry.consumer.MicroserviceVersions.createMicroserviceVersion(MicroserviceVersions.java:259) [foundation-registry-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.registry.consumer.MicroserviceVersions.lambda$setInstances$1(MicroserviceVersions.java:240) [foundation-registry-2.8.14.jar:2.8.14]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_252]
	at org.apache.servicecomb.foundation.common.concurrent.ConcurrentHashMapEx.computeIfAbsent(ConcurrentHashMapEx.java:56) ~[foundation-common-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.registry.consumer.MicroserviceVersions.setInstances(MicroserviceVersions.java:239) [foundation-registry-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.registry.consumer.MicroserviceVersions.safeSetInstances(MicroserviceVersions.java:207) [foundation-registry-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.registry.consumer.MicroserviceVersions.pullInstances(MicroserviceVersions.java:186) [foundation-registry-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.registry.consumer.MicroserviceManager.getOrCreateMicroserviceVersions(MicroserviceManager.java:66) [foundation-registry-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.registry.consumer.AppManager.getOrCreateMicroserviceVersions(AppManager.java:70) [foundation-registry-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.registry.DiscoveryManager.getOrCreateMicroserviceVersions(DiscoveryManager.java:141) [foundation-registry-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.core.SCBEngine.createMicroserviceReferenceConfig(SCBEngine.java:545) [java-chassis-core-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.core.SCBEngine.createMicroserviceReferenceConfig(SCBEngine.java:516) [java-chassis-core-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.provider.pojo.PojoConsumerMetaRefresher.refreshMeta(PojoConsumerMetaRefresher.java:93) [provider-pojo-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.provider.pojo.PojoConsumerMetaRefresher.ensureMetaAvailable(PojoConsumerMetaRefresher.java:81) [provider-pojo-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.provider.pojo.PojoConsumerMetaRefresher.getLatestMeta(PojoConsumerMetaRefresher.java:58) [provider-pojo-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.provider.pojo.PojoInvocationCreator.create(PojoInvocationCreator.java:26) [provider-pojo-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.provider.pojo.HandlerInvocationCaller.call(HandlerInvocationCaller.java:31) [provider-pojo-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.provider.pojo.Invoker.invoke(Invoker.java:71) [provider-pojo-2.8.14.jar:2.8.14]
	at com.sun.proxy.$Proxy63.sayHello(Unknown Source) [na:na]
	at com.example.consumer.controller.ConsumerController.sayHello(ConsumerController.java:43) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_252]
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.doInvoke(ProducerOperationHandler.java:125) [java-chassis-core-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.syncInvoke(ProducerOperationHandler.java:110) [java-chassis-core-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.invoke(ProducerOperationHandler.java:63) [java-chassis-core-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.handle(ProducerOperationHandler.java:54) [java-chassis-core-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.core.Invocation.next(Invocation.java:280) [java-chassis-core-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.qps.ConsumerQpsFlowControlHandler.handle(ConsumerQpsFlowControlHandler.java:57) [handler-flowcontrol-qps-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.core.Invocation.next(Invocation.java:280) [java-chassis-core-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.doInvoke(AbstractRestInvocation.java:293) [common-rest-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke(AbstractRestInvocation.java:264) [common-rest-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor(AbstractRestInvocation.java:248) [common-rest-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$2(AbstractRestInvocation.java:204) [common-rest-2.8.14.jar:2.8.14]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_252]
Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.parser.ParserImpl.<init>(Lorg/yaml/snakeyaml/reader/StreamReader;Lorg/yaml/snakeyaml/LoaderOptions;)V
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:204) ~[jackson-dataformat-yaml-2.15.0.jar:2.15.0]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:510) ~[jackson-dataformat-yaml-2.15.0.jar:2.15.0]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:414) ~[jackson-dataformat-yaml-2.15.0.jar:2.15.0]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:387) ~[jackson-dataformat-yaml-2.15.0.jar:2.15.0]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[jackson-dataformat-yaml-2.15.0.jar:2.15.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772) ~[jackson-databind-2.15.0.jar:2.15.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740) ~[jackson-databind-2.15.0.jar:2.15.0]
	at org.apache.servicecomb.swagger.SwaggerUtils.internalParseSwagger(SwaggerUtils.java:146) ~[swagger-generator-core-2.8.14.jar:2.8.14]
	at org.apache.servicecomb.swagger.SwaggerUtils.parseSwagger(SwaggerUtils.java:108) ~[swagger-generator-core-2.8.14.jar:2.8.14]
	... 49 common frames omitted

**Comment by liubao68** [comment]
> > 看日志的话不是B服务没找到C服务，而是B在加载C的服务契约的时候抛异常了。 你贴的日志里面有这么一行
> > ```
> > Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonStreamContext
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 一般这种错误是依赖问题，可能是依赖包有冲突，建议排查一下看看
> 
> 那我这种是啥问题 2024-07-01 09:09:42.254 ERROR 45396 --- [oup0-1-thread-2] o.a.s.r.consumer.MicroserviceVersions : **Failed to setInstances, appId=qwer, microserviceName=provider_qwer.**
> 
> org.apache.servicecomb.foundation.common.exceptions.ServiceCombException: Parse swagger from content failed, at 


你的问题类似，排查下三方件版本配套是否正确。 参考上面的依赖管理和你使用的2.8.14集成的三方件版本排查下: https://github.com/apache/servicecomb-java-chassis/blob/2.8.14/dependencies/default/pom.xml

**Comment by lw985** [comment]
> > > 看日志的话不是B服务没找到C服务，而是B在加载C的服务契约的时候抛异常了。 你贴的日志里面有这么一行
> > > ```
> > > Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonStreamContext
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 一般这种错误是依赖问题，可能是依赖包有冲突，建议排查一下看看
> > 
> > 
> > 那我这种是啥问题 2024-07-01 09:09:42.254 ERROR 45396 --- [oup0-1-thread-2] o.a.s.r.consumer.MicroserviceVersions : **Failed to setInstances, appId=qwer, microserviceName=provider_qwer.**
> > org.apache.servicecomb.foundation.common.exceptions.ServiceCombException: Parse swagger from content failed, at
> 
> 你的问题类似，排查下三方件版本配套是否正确。 参考上面的依赖管理和你使用的2.8.14集成的三方件版本排查下: https://github.com/apache/servicecomb-java-chassis/blob/2.8.14/dependencies/default/pom.xml

我把spring-boot-start去掉，不用父工程就行了
