### ISSUE TITLE
请求的URL中存在冒号报错490

### ISSUE THREAD

**Issue by willard-kali** [apache/servicecomb-java-chassis#1446]
Server发布的REST接口，URL定义为：/微服务/query/{name}
有EdgeService作为网关转发微服务的请求。浏览器发送请求：https://ip:port/rest/微服务/query/test:name。
请求经过EdgeService，会将URL提取出来：/query/test:name，并转发给微服务。
然后EdgeService日志中报错490，错误信息如下：

> [ERROR][Invoke all server failed. Operation CONSUMER rest 微服务名.Controller包路径.接口方法, e=cause:InvocationException,message:InvocationException: code=490;msg=CommonExceptionData [message=Cse Internal Bad Request];cause:NullPointerException,message:null][org.apache.servicecomb.loadbalance.LoadbalanceHandler][onExecutionFailed,323]
[ERROR][vertx rest transport send error.][org.apache.servicecomb.transport.rest.client.RestTransportClient][send,117]
java.lang.NullPointerException: null
        at org.apache.servicecomb.common.rest.definition.path.PathVarParamWriter.write(PathVarParamWriter.java:34) ~[common-rest-1.2.1.jar:1.2.1]
        at org.apache.servicecomb.common.rest.definition.path.URLPathBuilder.genPathString(URLPathBuilder.java:111) ~[common-rest-1.2.1.jar:1.2.1]
        at org.apache.servicecomb.common.rest.definition.path.URLPathBuilder.createRequestPath(URLPathBuilder.java:97) ~[common-rest-1.2.1.jar:1.2.1]
        at org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.createRequestPath(RestClientInvocation.java:275) ~[transport-rest-client-1.2.1.jar:1.2.1]
        at org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.invoke(RestClientInvocation.java:85) ~[transport-rest-client-1.2.1.jar:1.2.1]
        at org.apache.servicecomb.transport.rest.client.RestTransportClient.send(RestTransportClient.java:114) ~[transport-rest-client-1.2.1.jar:1.2.1]
        at org.apache.servicecomb.transport.rest.vertx.VertxRestTransport.send(VertxRestTransport.java:86) ~[transport-rest-vertx-1.2.1.jar:1.2.1]
        at org.apache.servicecomb.core.handler.impl.TransportClientHandler.handle(TransportClientHandler.java:42) ~[java-chassis-core-1.2.1.jar:1.2.1]
        at org.apache.servicecomb.core.Invocation.next(Invocation.java:204) ~[java-chassis-core-1.2.1.jar:1.2.1]
        at org.apache.servicecomb.loadbalance.LoadbalanceHandler$4.lambda$call$1(LoadbalanceHandler.java:368) ~[handler-loadbalance-1.2.1.jar:1.2.1]
        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:235) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:286) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.onNext(OnSubscribeConcatMap.java:144) ~[rxjava-1.3.8.jar:1.3.8]
        at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:185) ~[ribbon-loadbalancer-2.2.5.jar:2.2.5]
        at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180) ~[ribbon-loadbalancer-2.2.5.jar:2.2.5]
        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1.call(OperatorRetryWithPredicate.java:127) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:79) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:45) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.Subscriber.setProducer(Subscriber.java:209) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.Observable.subscribe(Observable.java:10423) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.Observable.subscribe(Observable.java:10390) ~[rxjava-1.3.8.jar:1.3.8]
        at rx.Observable.subscribe(Observable.java:10271) ~[rxjava-1.3.8.jar:1.3.8]
        at org.apache.servicecomb.loadbalance.LoadbalanceHandler.sendWithRetry(LoadbalanceHandler.java:394) ~[handler-loadbalance-1.2.1.jar:1.2.1]
        at org.apache.servicecomb.loadbalance.LoadbalanceHandler.handle(LoadbalanceHandler.java:207) ~[handler-loadbalance-1.2.1.jar:1.2.1]
        at org.apache.servicecomb.core.Invocation.next(Invocation.java:204) ~[java-chassis-core-1.2.1.jar:1.2.1]
......

根据实测分析，是因为URL路径中带有冒号，导致出现该错误。请问下当前这种使用场景，应该如何配置才能支持URL中有冒号？

**Comment by liubao68** [comment]
你尝试了： 
```
https://ip:port/rest/微服务/query/test%%3Aname
```
吗？

**Comment by willard-kali** [comment]
使用浏览器访问，尝试过这种写法，但是浏览器会自动将%3A转码为：。

**Comment by lovefu** [comment]
你好，这是我测试的例子，是支持url带冒号的，你看看：
demo地址：https://github.com/apache/servicecomb-java-chassis/tree/master/demo/demo-edge

1、修改url为带冒号格式
@RequestMapping(path = "/x:{x}/y:{y}/add", method = RequestMethod.GET)
  public ResultWithInstance add(@PathVariable("x") int x, @PathVariable("y") int y) {
    return ResultWithInstance.create(x + y);
  }

2、修改microservice.yaml微服务版本，接口有变更时，需要增加版本
APPLICATION_ID: edge
service_description:
  name: business
  version: 1.1.2

3、访问http://127.0.0.1:8090/business/v1/x:1/y:2/add，能正常返回
{
    "result":3,
    "serviceId":"xxx...",
    "instanceId:"xxx...",
    "version":"1.1.2"
}

**Comment by lovefu** [comment]
看了下你的问题，将url定义为/微服务/query/test:{name}
应该是可以调通的，url中冒号左边的关键字不能省略
----------------------------------------------------------------------------------
Server发布的REST接口，URL定义为：/微服务/query/{name}
有EdgeService作为网关转发微服务的请求。浏览器发送请求：https://ip:port/rest/微服务/query/test:name。

**Comment by willard-kali** [comment]
> ## 看了下你的问题，将url定义为/微服务/query/test:{name}
> 应该是可以调通的，url中冒号左边的关键字不能省略
> Server发布的REST接口，URL定义为：/微服务/query/{name}
> 有EdgeService作为网关转发微服务的请求。浏览器发送请求：[https://ip:port/rest/微服务/query/test:name。](https://ip:port/rest/%E5%BE%AE%E6%9C%8D%E5%8A%A1/query/test:name%E3%80%82)

非常感谢。
我的使用场景，无法确定url中冒号前边的关键字，/query/{name}中，name可能有冒号，可能没有冒号。

**Comment by lovefu** [comment]
你好，我这边测试，%3A是支持的，后台能正常获取到name参数，浏览器+postman都支持
接口代码：
  @RequestMapping(path = "/myadd/{name}/test", method = RequestMethod.GET)
  public ResultWithInstance myadd(@PathVariable String name) {
    System.out.println(name);
    return ResultWithInstance.create(1);
  }
请求接口：
http://127.0.0.1:8080/business/v1/myadd/uuuu%3A3433/test
控制台打印：
2019-12-17 09:04:56,522 [WARN] sc task postponed for 31196ms for some reason...
uuuu:3433

**Comment by willard-kali** [comment]
> 你好，我这边测试，%3A是支持的，后台能正常获取到name参数，浏览器+postman都支持
> 接口代码：
> @RequestMapping(path = "/myadd/{name}/test", method = RequestMethod.GET)
> public ResultWithInstance myadd(@PathVariable String name) {
> System.out.println(name);
> return ResultWithInstance.create(1);
> }
> 请求接口：
> http://127.0.0.1:8080/business/v1/myadd/uuuu%3A3433/test
> 控制台打印：
> 2019-12-17 09:04:56,522 [WARN] sc task postponed for 31196ms for some reason...
> uuuu:3433

你好，我使用的是EdgeService转发的，形如：
`
EdgeInvocation invoker = new EdgeInvocation();
invoker.init(serviceName, context, path, httpServerFilters);
`
代码中path尝试使用:或者%3A，到后台微服务都无法正确接收到请求参数name。
后又尝试再对%进行编码如%253A，到后台微服务能接收到参数name中为%3A，也不是：。
目前怀疑EdgeInvocation在转发微服务的时候又对URL做了一层解码。

**Comment by liubao68** [comment]
可以尝试一下 2.0.0， 这个 [issue](https://github.com/apache/servicecomb-java-chassis/pull/1561) 或许和问题有关。
