### ISSUE TITLE
serviceComb适配vertx-pac4j报错

### ISSUE THREAD

**Issue by zhuqing205** [apache/servicecomb-java-chassis#1447]
使用serviceComb适配vertx-pac4j完成cas功能，之前使用的是vertx-pac4j3.0.1版本的可以实现登录功能，但是升级到vertx-pac4j4.1.1版本登陆后报错：

> org.pac4j.core.exception.TechnicalException: java.lang.NullPointerException
	at org.pac4j.vertx.handler.impl.CallbackHandler.lambda$handle$1(CallbackHandler.java:78) ~[vertx-pac4j-4.1.1.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:284) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
	at org.pac4j.core.client.IndirectClient.computeFinalCallbackUrl(IndirectClient.java:157) ~[pac4j-core-3.4.0.jar:?]
	at org.pac4j.cas.config.CasConfiguration.buildCas30TicketValidator(CasConfiguration.java:172) ~[pac4j-cas-3.4.0.jar:?]
	at org.pac4j.cas.config.CasConfiguration.retrieveTicketValidator(CasConfiguration.java:135) ~[pac4j-cas-3.4.0.jar:?]
	at org.pac4j.cas.credentials.authenticator.CasAuthenticator.validate(CasAuthenticator.java:72) ~[pac4j-cas-3.4.0.jar:?]
	at org.pac4j.cas.credentials.authenticator.CasAuthenticator.validate(CasAuthenticator.java:31) ~[pac4j-cas-3.4.0.jar:?]
	at org.pac4j.core.client.BaseClient.retrieveCredentials(BaseClient.java:71) ~[pac4j-core-3.4.0.jar:?]
	at org.pac4j.core.client.IndirectClient.getCredentials(IndirectClient.java:140) ~[pac4j-core-3.4.0.jar:?]
	at org.pac4j.core.engine.DefaultCallbackLogic.perform(DefaultCallbackLogic.java:89) ~[pac4j-core-3.4.0.jar:?]
	at org.pac4j.vertx.handler.impl.CallbackHandler.lambda$handle$0(CallbackHandler.java:69) ~[vertx-pac4j-4.1.1.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272) ~[vertx-core-3.7.0.jar:3.7.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_222]
	... 2 more

**Comment by liubao68** [comment]
这个问题看起来和java-chassis没有什么关系。 vert.x升级经常出现不兼容的变更， 可能需要你自行分析下解决方案。
