### ISSUE TITLE
服务器性能余量充足，但是请求排队超时，报错InvocationException: code=500

### ISSUE THREAD

**Issue by Nongkahei1231** [apache/servicecomb-java-chassis#1470]
报错rest server onRequest error org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=500;msg=CommonExceptionData [message=Timeout when processing the request.] 以及Unhandled exceptionjava.lang.IllegalStateException: Response is closed以及CSE心跳丢失
服务器平时cpu使用率2%，内存20%，性能余量充足，发生问题时请求超时，同时伴随的cpu使用率飙升到60%，持续3秒，导致现网少量请求失败，这种情况根因是什么，有什么解决办法

**Comment by liubao68** [comment]
这个是请求处理超时了。可以抓取堆栈分析下具体哪个业务处理耗时。 超时后，就可能会打印上述的错误日志。 如果没法及时抓取堆栈，可以打开访问日志，看看是哪些请求，可以做一些较大规模的并发测试以发现问题。

**Comment by yhs0092** [comment]
Timeout when processing the request
这个是请求在等待进入业务线程池时超时了，有请求在排队等待线程去处理它。假设你的服务工作在[同步模式](https://docs.servicecomb.io/java-chassis/zh_CN/build-provider/thread-pool.html)，如果不是并发量太大线程池处理不过来的话，那就应该是前面有请求处理得太慢了，少量请求长时间占据大量的业务线程。
Java-Chassis 在处理请求超时错误时应该不至于消耗这么多的CPU计算量，建议先去排查一下到底是什么导致了请求超时。

**Comment by Nick-The-Uncharted** [comment]
@liubao68 @yhs0092 我正好在调试一个自己的小程序时出了类似的问题，是服务器自己给自己发请求时概率卡住，但是发送请求的线程超时异常之后，又能收到请求。之前定位过类似的netty问题，我猜测是因为服务器正好选择使用相同线程接收请求，但是这个线程任务还未执行完毕，造成死锁。 附超时堆栈。
```
2019-12-19 17:16:32.118 [vert.x-eventloop-thread-2] WARN  org.apache.servicecomb.bizkeeper.BizkeeperCommand [BizkeeperCommand.java : 82] - bizkeeper command CONSUMER rest vehicle-gw.oc.inc failed due to {}
org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=490;msg=CommonExceptionData [message=Cse Internal Bad Request]
	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.doCreate(ExceptionFactory.java:79)
	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.convertException(ExceptionFactory.java:124)
	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.convertConsumerException(ExceptionFactory.java:83)
	at org.apache.servicecomb.swagger.invocation.Response.createConsumerFail(Response.java:129)
	at org.apache.servicecomb.swagger.invocation.Response.createFail(Response.java:122)
	at org.apache.servicecomb.swagger.invocation.AsyncResponse.fail(AsyncResponse.java:42)
	at org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.fail(RestClientInvocation.java:278)
	at org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.lambda$invoke$0(RestClientInvocation.java:112)
	at io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:139)
	at io.vertx.core.http.impl.HttpClientRequestBase.timeout(HttpClientRequestBase.java:211)
	at io.vertx.core.http.impl.HttpClientRequestBase.handleTimeout(HttpClientRequestBase.java:194)
	at io.vertx.core.http.impl.HttpClientRequestBase.lambda$setTimeout$0(HttpClientRequestBase.java:124)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:906)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:865)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.vertx.core.http.impl.HttpClientRequestBase$1: The timeout period of 30000ms has been exceeded while executing GET /oc/v1/project_id/ociov/ociov_id/inc?x=1 for host 10.138.97.76
```

**Comment by liubao68** [comment]
可能你服务端并发调用出现死锁。 业务应该尽可能避免循环调用，比如 A -> B -> A，或者A->A。 当线程池足够或者并发数很小的时候，可能没问题。 并发数大了就会死锁。 

服务内部调用，建议直接调用service暴露出来的API。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
