### ISSUE TITLE
在ServiceComb下运行redis连接池出错

### ISSUE THREAD

**Issue by sunjinghan7331** [apache/servicecomb-java-chassis#1474]
在我调用JedisPool.getResource()方法时，报以下错误，该如何解决。

java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.doInvoke(SwaggerProducerOperation.java:188) ~[swagger-invocation-core-1.3.0.jar:1.3.0]
	at org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.syncInvoke(SwaggerProducerOperation.java:173) ~[swagger-invocation-core-1.3.0.jar:1.3.0]
	at org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.invoke(SwaggerProducerOperation.java:123) ~[swagger-invocation-core-1.3.0.jar:1.3.0]
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.handle(ProducerOperationHandler.java:40) ~[java-chassis-core-1.3.0.jar:1.3.0]
	at org.apache.servicecomb.core.Invocation.next(Invocation.java:204) ~[java-chassis-core-1.3.0.jar:1.3.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.doInvoke(AbstractRestInvocation.java:243) ~[common-rest-1.3.0.jar:1.3.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke(AbstractRestInvocation.java:217) ~[common-rest-1.3.0.jar:1.3.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor(AbstractRestInvocation.java:201) ~[common-rest-1.3.0.jar:1.3.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(AbstractRestInvocation.java:160) ~[common-rest-1.3.0.jar:1.3.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.NoClassDefFoundError: redis/clients/jedis/JedisPoolConfig
	at org.mec.houp.user.redis.RedisUtil.save(RedisUtil.java:24) ~[classes/:?]
	at org.mec.houp.user.service.UserMgmtService.login(UserMgmtService.java:177) ~[classes/:?]
	at org.mec.houp.user.controller.TestController.login(TestController.java:56) ~[classes/:?]
	... 16 more
Caused by: java.lang.ClassNotFoundException: redis.clients.jedis.JedisPoolConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_202]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_202]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_202]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202]
	at org.mec.houp.user.redis.RedisUtil.save(RedisUtil.java:24) ~[classes/:?]
	at org.mec.houp.user.service.UserMgmtService.login(UserMgmtService.java:177) ~[classes/:?]
	at org.mec.houp.user.controller.TestController.login(TestController.java:56) ~[classes/:?]
	... 16 more

**Comment by liubao68** [comment]
这个问题应该和java-chassis没有关系，你的依赖关系没处理好。 可以参考[文章](http://servicecomb.apache.org/cn/docs/maven_dependency_management/)

**Comment by sunjinghan7331** [comment]
请看一下我的pom文件，为了进一步验证问题，仅引入了极少的包，不存在复杂的依赖关系。下面会给出新的测试代码。

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>servicecomb</groupId>
  <artifactId>servicecombprovider</artifactId>
  <version>1.0-SNAPSHOT</version>

  <build>
    <finalName>mepagent</finalName>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.1</version>
          <configuration>
            <source>1.8</source>
            <target>1.8</target>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.apache.servicecomb</groupId>
        <artifactId>java-chassis-dependencies</artifactId>
        <version>1.3.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>

    <dependency>
      <groupId>org.glassfish.jersey.core</groupId>
      <artifactId>jersey-client</artifactId>
    </dependency>
    
    <dependency>
      <groupId>org.apache.servicecomb</groupId>
      <artifactId>handler-bizkeeper</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.servicecomb</groupId>
      <artifactId>handler-loadbalance</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.servicecomb</groupId>
      <artifactId>handler-flowcontrol-qps</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.servicecomb</groupId>
      <artifactId>transport-highway</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.servicecomb</groupId>
      <artifactId>transport-rest-vertx</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.servicecomb</groupId>
      <artifactId>provider-jaxrs</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-slf4j-impl</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
    </dependency>

    
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.10</version>
    </dependency>

    
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.8.2</version>
    </dependency>

    
    <dependency>
      <groupId>org.mec.cbb</groupId>
      <artifactId>commoncbb</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>

    
    <dependency>
      <groupId>redis.clients</groupId>
      <artifactId>jedis</artifactId>
      <version>2.9.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-pool2</artifactId>
      <version>2.5.0</version>
    </dependency>

  </dependencies>



</project>

**Comment by sunjinghan7331** [comment]
这里给出了精简后的测试代码，在new Jedis()对象后，出现了错误：Caused by: java.lang.NoClassDefFoundError: redis/clients/jedis/Jedis

public Response login(LoginRequest reqParam) {
        LoginRequest loginRequest = reqParam;

        TokenResponse token = new TokenResponse();
        token.setUserId(loginRequest.getUsername());
        token.setToken(loginRequest.getPassword());

        String key = token.getToken();
        String value = token.getUserId();
        Jedis jedis = new Jedis("*.*.*.*"); // 此处隐去真实可用host
        if (jedis.exists(key)) {
            jedis.expire(key, 1800);
        } else {
            jedis.set(key,value);
            jedis.expire(key, 1800);
        }

        return Response.ok().entity(token).build();
    }

**Comment by liubao68** [comment]
ClassNotFoundException 问题相对很好解决的，找一下这个类在哪个jar包，引入进来即可。

**Comment by sunjinghan7331** [comment]
<dependency>
  <groupId>redis.clients</groupId>
  <artifactId>jedis</artifactId>
  <version>2.9.0</version>
</dependency>
<dependency>
  <groupId>org.apache.commons</groupId>
  <artifactId>commons-pool2</artifactId>
  <version>2.5.0</version>
</dependency>

jar包已经引了，之前是基于Jersey开发的，微服务没有问题，切换到ServiceComb就无法找到了Jedis了

**Comment by sunjinghan7331** [comment]
在一个普通的HelloWorld工程中引入下面两个依赖就可以使用redis数据库，但是在ServiceComb的sample代码中加入如下依赖，却无法连接redis，提示Jedis类找不到，个人认为是ServiceComb提供的依赖中与Jedis冲突。
<dependency>
      <groupId>redis.clients</groupId>
      <artifactId>jedis</artifactId>
      <version>2.9.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-pool2</artifactId>
      <version>2.5.0</version>
    </dependency>

**Comment by liubao68** [comment]
You can follow the ways provided by my first answer and check out the differences of jedis dependency. First find out which library change caused by the problem. Maybe you can debug the code which error caused initializing Jeids class fail.

**Comment by WillemJiang** [comment]
@sunjinghan7331  Could you share the detail that how you resolve the issue?

**Comment by sunjinghan7331** [comment]
@WillemJiang I use the Lettuce instead of Jedis, the Jedis can not be started successfully, so I abandon it.

**Comment by AntonioDC-AAA** [comment]
ditto，I select Lettuce instead of Jedis
