### ISSUE TITLE
业务用户hicloud执行consolewebsite的start脚本 tomcat/logs/localhost.2019-12-24.log报如下错误，请问怎么解决

### ISSUE THREAD

**Issue by hongfeihuangseu** [apache/servicecomb-java-chassis#1486]
24-Dec-2019 11:01:25.620 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log Initializing Spring embedded WebApplicationContext
24-Dec-2019 11:01:30.334 SEVERE [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log StandardWrapper.Throwable
 java.lang.IllegalStateException: Failed to create cache dir
        at io.vertx.core.file.impl.FileResolver.setupCacheDir(FileResolver.java:333)
        at io.vertx.core.file.impl.FileResolver.<init>(FileResolver.java:88)
        at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:168)
        at io.vertx.core.impl.VertxImpl.vertx(VertxImpl.java:93)
        at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:38)
        at io.vertx.core.Vertx.vertx(Vertx.java:85)
        at cse.console.proxy.ServletProxy.init(ServletProxy.java:72)
        at javax.servlet.GenericServlet.init(GenericServlet.java:158)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4997)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5289)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by liubao68** [comment]
From the stack trace, this problem is not related to java-chassis. Please check your implementation of ServletProxy and find a solution.
