### ISSUE TITLE
基于ServiceComb和javax开发的微服务如何打包成可执行jar包？

### ISSUE THREAD

**Issue by sunjinghan7331** [apache/servicecomb-java-chassis#1508]
查询了网络上使用maven打包的说明，使用了maven-jar-plugin和maven-dependency-plugin联合打包，结果在生成的MANIFEST.MF文件中缺少foundation-commom的包，但是在lib目录下是有这个包的，但是由于MANIFEST.MF中的Class-Path中没有，所以打出来的包无法执行。

使用maven-assembly-plugin打包后执行会报错：
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.apache.servicecomb.bizkeeper.BeansHolder#0' defined in URL [jar:file:/E:/user/target/user-jar-with-dependencies.jar!/META-INF/spring/cse.bean.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1631)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
        at org.apache.servicecomb.foundation.common.utils.BeanUtils.init(BeanUtils.java:54)
        at org.apache.servicecomb.foundation.common.utils.BeanUtils.init(BeanUtils.java:47)
        at org.mec.houp.user.controller.MainServer.main(MainServer.java:8)
Caused by: java.lang.NullPointerException
        at org.apache.servicecomb.bizkeeper.BeansHolder.init(BeansHolder.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1760)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1697)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1627)
        ... 14 more

使用maven-shade-plugin打包依旧报此异常。

请问该如何解决？

**Comment by liubao68** [comment]
目前流行的maven打包一般有两种模式：
 * flat 模式： jar 包里面只有本模块的classes， 依赖的包放到独立的 lib 目录， 并且在jar包里面包含MANIFEST文件描述class path [示例](https://github.com/apache/servicecomb-java-chassis/blob/master/demo/pom.xml)
* spring boot模式： 将所有包和依赖的jar包打包到一个lib里面，详细情况可以看下内部格式。 [示例](https://github.com/apache/servicecomb-samples/blob/master/porter_lightweight/pom.xml)
