### ISSUE TITLE
HTTP切HTTPS报错： signed CRL fields invalid

### ISSUE THREAD

**Issue by alantaitai** [apache/servicecomb-java-chassis#1528]
org.apache.servicecomb.foundation.vertx.client.ClientVerticle.start(ClientVerticle.java:38) ->
io.vertx.core.VertxException: java.security.cert.CRLException: signed CRL fields invalid
        at io.vertx.core.net.impl.SSLHelper.getContext(SSLHelper.java:472) ~[vertx-core-3.6.3.jar!/:3.6.3]
        at io.vertx.core.net.impl.SSLHelper.validate(SSLHelper.java:499) ~[vertx-core-3.6.3.jar!/:3.6.3]
        at io.vertx.core.http.impl.HttpClientImpl.<init>(HttpClientImpl.java:131) ~[vertx-core-3.6.3.jar!/:3.6.3]
        at io.vertx.core.impl.VertxImpl.createHttpClient(VertxImpl.java:309) ~[foundation-vertx-1.2.0.B011.jar!/:3.6.3]
        at org.apache.servicecomb.foundation.vertx.client.http.HttpClientPoolFactory.createClientPool(HttpClientPoolFactory.java:36) ~[foundation-vertx-1.2.0.B011.jar!/:1.2.0.B011]
        at org.apache.servicecomb.foundation.vertx.client.http.HttpClientPoolFactory.createClientPool(HttpClientPoolFactory.java:27) ~[foundation-vertx-1.2.0.B011.jar!/:1.2.0.B011]
        at org.apache.servicecomb.foundation.vertx.client.ClientPoolManager.createClientPool(ClientPoolManager.java:60) ~[foundation-vertx-1.2.0.B011.jar!/:1.2.0.B011]
        at org.apache.servicecomb.foundation.vertx.client.ClientVerticle.start(ClientVerticle.java:35) ~[foundation-vertx-1.2.0.B011.jar!/:1.2.0.B011]
        at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106) ~[vertx-core-3.6.3.jar!/:3.6.3]
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:494) ~[vertx-core-3.6.3.jar!/:3.6.3]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) ~[vertx-core-3.6.3.jar!/:3.6.3]
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[vertx-core-3.6.3.jar!/:3.6.3]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.28.Final.jar!/:4.1.28.Final]
Caused by: java.security.cert.CRLException: signed CRL fields invalid
        at sun.security.x509.X509CRLImpl.parse(X509CRLImpl.java:1081) ~[?:1.8.0_222]
        at sun.security.x509.X509CRLImpl.<init>(X509CRLImpl.java:146) ~[?:1.8.0_222]
        at sun.security.provider.X509Factory.parseX509orPKCS7CRL(X509Factory.java:523) ~[?:1.8.0_222]
        at sun.security.provider.X509Factory.engineGenerateCRLs(X509Factory.java:420) ~[?:1.8.0_222]
        at java.security.cert.CertificateFactory.generateCRLs(CertificateFactory.java:535) ~[?:1.8.0_222]
        at io.vertx.core.net.impl.SSLHelper.getTrustMgrFactory(SSLHelper.java:342) ~[vertx-core-3.6.3.jar!/:3.6.3]
        at io.vertx.core.net.impl.SSLHelper.getContext(SSLHelper.java:470) ~[vertx-core-3.6.3.jar!/:3.6.3]

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
