### ISSUE TITLE
在RPC调用时报下面DuplicateMemberException: duplicate method

### ISSUE THREAD

**Issue by xuzhiweiand** [apache/servicecomb-java-chassis#1536]
public interface ICodecService {
  RpcResponse<String> decode(@NotNull DecodeReqDTO decodeInfo) throws Exception;

  RpcResponse<byte[]> encode(@NotNull EncodeReqDTO encodeInfo) throws Exception;
}

public class DecodeReqDTO {
  private String groupId;

  private String deviceId;

  private String bundleId;

  private byte[] binaryData;
}
在RPC接口中定义了一个ICodecService接口，参数是DecodeReqDTO ，在RPC调用时报下面的错误，请问是什么原因啊？
Caused by: javassist.bytecode.DuplicateMemberException: duplicate method: decode in com.****.api.rpc.ICodecService
        at javassist.bytecode.ClassFile.testExistingMethod(ClassFile.java:685) ~[?:?]
        at javassist.bytecode.ClassFile.addMethod(ClassFile.java:660) ~[?:?]
        at javassist.CtClassType.addMethod(CtClassType.java:1485) ~[?:?]

**Comment by liubao68** [comment]
需要确保每个方法有唯一的operation id。 

```
@ApiOperation(value="", nickname="decode2")
RpcResponse decode(@NotNull DecodeReqDTO decodeInfo) throws Exception;

RpcResponse<byte[]> encode(@NotNull EncodeReqDTO encodeInfo) throws Exception;
```

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
