### ISSUE TITLE
重写返回值序列化，工程启动报LinkageError

### ISSUE THREAD

**Issue by WellaceZ** [apache/servicecomb-java-chassis#1541]
业务需要REST返回值支持compactFormat和PrettyPrint两种输出格式，因此重写了ProduceJsonProcessor。但是工程启动却报LinkageError错误。如何解决？
（1）自定义的ProduceProcessor实现类如下：
public class MyProduceProcessor implements ProduceProcessor {

    @Override
    public String getName() {
        return String.valueOf(MediaType.APPLICATION_JSON);
    }

    @Override
    public int getOrder() {
        return -1;
    }

    @Override
    public void doEncodeResponse(OutputStream outputStream, Object o) throws Exception {
        RestObjectMapperFactory.getRestObjectMapper().writerWithDefaultPrettyPrinter().writeValue(outputStream, o);
    }

    @Override
    public Object doDecodeResponse(InputStream inputStream, JavaType javaType) throws Exception {
        return RestObjectMapperFactory.getRestObjectMapper().readValue(inputStream, javaType);
    }
}
（2）自定义的ProduceProcessor实现类如下：
![image](https://user-images.githubusercontent.com/53045286/72506750-78faef00-387d-11ea-969d-d765f1689e18.png)
resources下文件：META-INF/services/org.apache.servicecomb.common.rest.codec.produce.ProduceProcessor，内容com.**.**.utils.MyProduceProcessor（此处隐藏了具体报名）
（3）工程启动报错如下：
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.huawei.nuwa.boot.loader.MainMethodRunner.run(MainMethodRunner.java:31)
	at com.huawei.nuwa.boot.loader.AbstractLauncher.launch(AbstractLauncher.java:65)
	at com.huawei.nuwa.boot.loader.AbstractLauncher.launch(AbstractLauncher.java:58)
	at com.huawei.nuwa.boot.loader.AbstractLauncher.launch(AbstractLauncher.java:42)
	at com.huawei.nuwa.boot.loader.NuwaClassPathLauncher.main(NuwaClassPathLauncher.java:30)
Caused by: com.huawei.nuwa.boot.loader.exception.NuwaBootException: Failed to start nuwa. Cause:
	at com.huawei.nuwa.container.NuwaContainer.main(NuwaContainer.java:59)
	... 9 more
Caused by: com.huawei.nuwa.boot.loader.exception.NuwaBootException: ServiceComb init failed.
	at com.huawei.nuwa.container.model.PluginModel.start(PluginModel.java:382)
	at com.huawei.nuwa.container.service.plugin.PluginDeployServiceImpl.deploy(PluginDeployServiceImpl.java:22)
	at com.huawei.nuwa.container.pipeline.DeployPluginStage.process(DeployPluginStage.java:26)
	at com.huawei.nuwa.container.pipeline.StandardPipeline.process(StandardPipeline.java:39)
	at com.huawei.nuwa.container.NuwaContainer.start(NuwaContainer.java:76)
	at com.huawei.nuwa.container.NuwaContainer.main(NuwaContainer.java:53)
	... 9 more
Caused by: java.lang.IllegalStateException: ServiceComb init failed.
	at org.apache.servicecomb.core.SCBEngine.init(SCBEngine.java:225)
	at org.apache.servicecomb.core.CseApplicationListener.onApplicationEvent(CseApplicationListener.java:81)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:896)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at com.huawei.nuwa.SpringInitializer.init(SpringInitializer.java:33)
	at com.huawei.nuwa.NuwaBootstrap.start(NuwaBootstrap.java:42)
	at com.huawei.nuwa.container.model.PluginModel.start(PluginModel.java:380)
	... 14 more
Caused by: java.lang.ExceptionInInitializerError
	at org.apache.servicecomb.common.rest.definition.RestOperationMeta.createProduceProcessors(RestOperationMeta.java:199)
	at org.apache.servicecomb.common.rest.definition.RestOperationMeta.init(RestOperationMeta.java:94)
	at org.apache.servicecomb.common.rest.locator.ServicePathManager.addSchema(ServicePathManager.java:86)
	at org.apache.servicecomb.common.rest.RestEngineSchemaListener.onSchemaLoaded(RestEngineSchemaListener.java:54)
	at org.apache.servicecomb.core.definition.loader.SchemaListenerManager.notifySchemaListener(SchemaListenerManager.java:59)
	at org.apache.servicecomb.core.definition.loader.SchemaListenerManager.notifySchemaListener(SchemaListenerManager.java:48)
	at org.apache.servicecomb.core.definition.loader.SchemaListenerManager.notifySchemaListener(SchemaListenerManager.java:54)
	at org.apache.servicecomb.core.SCBEngine.doInit(SCBEngine.java:257)
	at org.apache.servicecomb.core.SCBEngine.init(SCBEngine.java:214)
	... 25 more
Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.huawei.minidemo.utils.MyProduceProcessor] from ClassLoader [com.huawei.nuwa.container.classloader.BizClassLoader@13b6aecc]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:686)
	at org.springframework.util.ReflectionUtils.findMethod(ReflectionUtils.java:207)
	at org.springframework.util.ReflectionUtils.findMethod(ReflectionUtils.java:188)
	at org.apache.servicecomb.foundation.common.utils.SPIServiceUtils.lambda$loadSortedService$0(SPIServiceUtils.java:65)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.servicecomb.foundation.common.utils.SPIServiceUtils.loadSortedService(SPIServiceUtils.java:63)
	at org.apache.servicecomb.foundation.common.utils.SPIServiceUtils.getOrLoadSortedService(SPIServiceUtils.java:95)
	at org.apache.servicecomb.foundation.common.utils.SPIServiceUtils.getSortedService(SPIServiceUtils.java:122)
	at org.apache.servicecomb.common.rest.codec.produce.ProduceProcessorManager.<clinit>(ProduceProcessorManager.java:31)
	... 34 more
Caused by: java.lang.LinkageError: loader constraint violation: loader (instance of com/huawei/nuwa/container/classloader/BizClassLoader) previously initiated loading for a different type with name "com/fasterxml/jackson/databind/JavaType"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at com.huawei.nuwa.container.classloader.AbstractClasspathClassLoader.resolveLocalClass(AbstractClasspathClassLoader.java:257)
	at com.huawei.nuwa.container.classloader.BizClassLoader.loadClassInternal(BizClassLoader.java:57)
	at com.huawei.nuwa.container.classloader.AbstractClasspathClassLoader.loadClass(AbstractClasspathClassLoader.java:61)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:668)
	... 42 more

**Comment by liubao68** [comment]
可能自定义的类使用BizClassLoader加载的，这个类依赖的JavaType在另外的class loader加载的，就出现了上面的错误。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
