### ISSUE TITLE
客户端调用服务端RPC接口时报错，方法重复，实际上方法未重复

### ISSUE THREAD

**Issue by xuzhiweiand** [apache/servicecomb-java-chassis#1579]
报错如下，请帮忙分析一下
2020-02-17 09:14:59,381Z | INFO  | CoAP-handler--16 | ConsumerSchemaFactory            |  | com.huawei.m2m.cig.rpcservice | load schema from service center, microservice=0:IoDM:20.2.6, schemaId=IoDMHealthCheckResource, result=true
2020-02-17 09:14:59,382Z | INFO  | CoAP-handler--16 | SchemaLoader                     |  | com.huawei.m2m.cig.rpcservice | register schema 0/IoDM/IoDMHealthCheckResource
2020-02-17 09:14:59,389Z | INFO  | CoAP-handler--16 | ConsumerSchemaFactory            |  | com.huawei.m2m.cig.rpcservice | load schema from service center, microservice=0:IoDM:20.2.6, schemaId=iodmStatRecord, result=true
2020-02-17 09:14:59,390Z | INFO  | CoAP-handler--16 | SchemaLoader                     |  | com.huawei.m2m.cig.rpcservice | register schema 0/IoDM/iodmStatRecord
2020-02-17 09:14:59,394Z | ERROR | CoAP-handler--16 | JavassistUtils                   |  | com.huawei.m2m.cig.rpcservice | Failed to create method, source:
public com.huawei.m2m.iodm.record.DTO.Record2IoOM statistics(java.lang.String marking,java.lang.String maxSize,java.lang.String beginTime,java.lang.String endTime);.
2020-02-17 09:14:59,394Z | ERROR | CoAP-handler--16 | SchemaMeta                       |  | com.huawei.m2m.cig.rpcservice | Unhandled exception to service IoDM schema iodmStatRecord
2020-02-17 09:14:59,394Z | ERROR | CoAP-handler--16 | MicroserviceVersions             |  | com.huawei.m2m.cig.rpcservice | Failed to setInstances, appId=0, microserviceName=IoDM.
java.lang.IllegalStateException: Failed to create CtClass com.huawei.m2m.iodm.record.IRecord in classLoader MicroserviceClassLoader 0:IoDM:20.2.6.
        at org.apache.servicecomb.common.javassist.JavassistUtils.createCtClass(JavassistUtils.java:189) ~[?:?]
        at org.apache.servicecomb.common.javassist.JavassistUtils.createClass(JavassistUtils.java:197) ~[?:?]
        at org.apache.servicecomb.swagger.converter.SwaggerToClassGenerator.convertToInterface(SwaggerToClassGenerator.java:237) ~[?:?]
        at org.apache.servicecomb.swagger.converter.SwaggerToClassGenerator.convert(SwaggerToClassGenerator.java:144) ~[?:?]
        at org.apache.servicecomb.core.definition.SchemaMeta.<init>(SchemaMeta.java:70) ~[?:?]
        at org.apache.servicecomb.core.definition.schema.ConsumerSchemaFactory.createSchema(ConsumerSchemaFactory.java:33) ~[?:?]
        at org.apache.servicecomb.core.definition.schema.AbstractSchemaFactory.getOrCreateSchema(AbstractSchemaFactory.java:58) ~[?:?]
        at org.apache.servicecomb.core.definition.schema.ConsumerSchemaFactory.createConsumerSchema(ConsumerSchemaFactory.java:48) ~[?:?]
        at org.apache.servicecomb.core.definition.MicroserviceVersionMeta.<init>(MicroserviceVersionMeta.java:45) ~[?:?]
        at org.apache.servicecomb.core.definition.MicroserviceVersionMetaFactory.create(MicroserviceVersionMetaFactory.java:38) ~[?:?]
        at org.apache.servicecomb.serviceregistry.consumer.MicroserviceVersions.lambda$setInstances$0(MicroserviceVersions.java:188) ~[?:?]
        at org.apache.servicecomb.swagger.converter.SwaggerToClassGenerator.convertToInterface(SwaggerToClassGenerator.java:237) ~[?:?]
        at org.apache.servicecomb.swagger.converter.SwaggerToClassGenerator.convert(SwaggerToClassGenerator.java:144) ~[?:?]
        at org.apache.servicecomb.core.definition.SchemaMeta.<init>(SchemaMeta.java:70) ~[?:?]
        at org.apache.servicecomb.core.definition.loader.SchemaLoader.registerSchema(SchemaLoader.java:86) ~[?:?]

Caused by: javassist.bytecode.DuplicateMemberException: duplicate method: statistics in com.huawei.m2m.iodm.record.IRecord
        at javassist.bytecode.ClassFile.testExistingMethod(ClassFile.java:685) ~[?:?]
        at javassist.bytecode.ClassFile.addMethod(ClassFile.java:660) ~[?:?]
        at javassist.CtClassType.addMethod(CtClassType.java:1485) ~[?:?]
        at org.apache.servicecomb.common.javassist.JavassistUtils.createCtClass(JavassistUtils.java:178) ~[?:?]

**Comment by xuzhiweiand** [comment]
当classload不一致时，会报此错误 Caused by: javassist.bytecode.DuplicateMemberException，需要在调用RPC时指定classloader。

**Comment by liubao68** [comment]
Thanks for sharing this.
