### ISSUE TITLE
java的服务（集成java cse的sdk)调用go的服务（集成go cse sdk）通信报错

### ISSUE THREAD

**Issue by h00379108** [apache/servicecomb-java-chassis#1607]
java--> go 报错截图：

go的契约情况：
为空

**Comment by h00379108** [comment]
图片上传不了

**Comment by heyile** [comment]
给一个demo 吧.

**Comment by h00379108** [comment]
2020-03-03 10:36:38.874|DAS|ERROR|http-nio-16951-exec-99|{X-request-id=280c56eee85b4d86adb3291c630dde0f-1583202998741-vc-dataanalysisservice-v34865-75947b9c7-xv9j7}|<generated>--1|LiveDomainService.java-72|Query domain error: id=5d483977c0ca46d9969f11ec326fe921
java.lang.Error: no schema defined for default:los
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.createRequestMeta(CseClientHttpRequest.java:163) ~[provider-springmvc-1.2.0.B011.jar!/:1.2.0.B011]
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.execute(CseClientHttpRequest.java:144) ~[provider-springmvc-1.2.0.B011.jar!/:1.2.0.B011]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:735) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:579) ~[spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.apache.servicecomb.provider.springmvc.reference.RestTemplateWrapper.exchange(RestTemplateWrapper.java:178) ~[provider-springmvc-1.2.0.B011.jar!/:1.2.0.B011]
	at com.huawei.vod.darklaunchclient.rest.process.AbstractCseRequestProcess.doCseSend(AbstractCseRequestProcess.java:77) ~[rest-darkLaunch-client-1.0.33.jar!/:?]
	at com.huawei.vod.darklaunchclient.rest.process.AbstractCseRequestProcess.doSendImpl(AbstractCseRequestProcess.java:53) ~[rest-darkLaunch-client-1.0.33.jar!/:?]

**Comment by h00379108** [comment]
是业务代码 还没有demo 你拿到java的demo和go的demo试下

**Comment by h00379108** [comment]
go cse版本 2020-03-03 10:36:38.867|DAS|INFO |http-nio-16951-exec-99|{X-request-id=280c56eee85b4d86adb3291c630dde0f-1583202998741-vc-dataanalysisservice-v34865-75947b9c7-xv9j7}|MicroserviceVersions.java-237|create MicroserviceVersionRule, appId=default, microserviceName=los, versionRule=0.0.0.0+.
2020-03-03 10:36:38.873|DAS|INFO |http-nio-16951-exec-99|{X-request-id=280c56eee85b4d86adb3291c630dde0f-1583202998741-vc-dataanalysisservice-v34865-75947b9c7-xv9j7}|MicroserviceVersionRule.java-145|update instances, appId=default, microserviceName=los, versionRule=0.0.0.0+, latestVersion=2020.302.1909.55, inputVersionCount=1, inputInstanceCount=2
  0.instanceId=7cb195e15c8011ea905a0255ac10507b, status=UP, version=2020.302.1909.55, endpoints=[rest://172.16.19.14:31005], environment=null, framework.name=Go-Chassis, framework.version=dev
  1.instanceId=983f9d125c8011ea905a0255ac10507b, status=UP, version=2020.302.1909.55, endpoints=[rest://172.16.6.219:31005], environment=null, framework.name=Go-Chassis, framework.version=dev

**Comment by heyile** [comment]
行,我自己试下.

**Comment by h00379108** [comment]
版本不限

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
