### ISSUE TITLE
servicecomb1.3+spingboo2，启用了ssl，但是实际https请求会报错

### ISSUE THREAD

**Issue by zouwenxmu** [apache/servicecomb-java-chassis#1608]
servicecomb1.2+spingboo1切换成servicecomb1.3+spingboo2之后，启用ssl的配置失效了
`rest:
    address: 0.0.0.0:8090?sslEnabled=true
########SSL options
ssl:
  protocols: TLSv1.2
  authPeer: false
  ciphers: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256
  checkCN:
    host: false
  trustStore: D:/tls/icetruststore.jks
  trustStoreType: JKS
  trustStoreValue: 123456
  keyStore: D:/tls/icekeystore.jks
  keyStoreType: JKS
  keyStoreValue: 123456`
报错日志
`2020-03-03 10:31:14.105  INFO 30000 --- [nio-8090-exec-7] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:415) ~[tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:260) ~[tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]`
这个配置在servicecomb1.2+spingboo1是可以正常启用https

**Comment by heyile** [comment]
可否给一个demo, 给一个连接到自己的githu 仓库. 最好有个readme.md

**Comment by zouwenxmu** [comment]
通过接口测试https://127.0.0.1:8080/test/hello，报错`java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens`，使用restTemplate.getForEntity("cse://demo2/test/hello", String.class)请求则要求create SSL connection，目前我使用springboot2的ssl配置可以正常发布https的rest服务

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
