### ISSUE TITLE
ServiceComb有access.log访问自身的日志，那有没有调用其他服务的outcall.log?如果有该怎么配置？

### ISSUE THREAD

**Issue by Bluselye** [apache/servicecomb-java-chassis#1611]
ServiceComb有access.log访问自身的日志，那有没有调用其他服务的outcall.log?如果有该怎么配置？

**Comment by heyile** [comment]
暂时没这个能力. 如果可以. 你可以给个 PR, 把能力补充一下.

**Comment by yhs0092** [comment]
经过Java-Chassis发出去的REST请求都会经过`HttpClientFilter`，做一个扩展实现来打印日志应该可以满足需求吧：

**Comment by Bluselye** [comment]
这个可以实现，但是我们目标要求能记录到异常信息，从HttpClientFilter中记录不到异常信息，异常会在产生后抛到业务层去。

**Comment by yhs0092** [comment]
想捕获异常的话也可以考虑使用`Handler`扩展来做，放在consumer端Handler链里面。不过Java-Chassis框架以抛出`InvocationException`的方式表达错误返回码，如果你们有自定义的错误返回，并且使用RPC方式调用的话，让框架把InvocationException抛出来可能更好一些。

**Comment by Bluselye** [comment]
使用Handler方式我试过了，请求异常时也会直接抛到业务层面，进不了handler. 一个异常日志如下：
[15:08:34.101][E][ool-16-thread-2][a.r.s.i.UserDownloadResultImpl.193] -Request AppGalleryUserCenterService error:InvocationException: code=490;msg=CommonExceptionData [message=Cse Internal Bad Request]
org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=490;msg=CommonExceptionData [message=Cse Internal Bad Request]
	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.doCreate(ExceptionFactory.java:79)
	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.convertException(ExceptionFactory.java:124)
	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.convertConsumerException(ExceptionFactory.java:83)
	at org.apache.servicecomb.swagger.invocation.Response.createConsumerFail(Response.java:129)
	at org.apache.servicecomb.swagger.invocation.Response.createFail(Response.java:122)
	at org.apache.servicecomb.swagger.invocation.Response.failResp(Response.java:165)
	at org.apache.servicecomb.bizkeeper.FallbackPolicyManager.getFallbackResponse(FallbackPolicyManager.java:44)
	at org.apache.servicecomb.bizkeeper.BizkeeperCommand.lambda$resumeWithFallback$0(BizkeeperCommand.java:65)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:8666)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:72)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:72)
	at rx.observers.Subscribers$5.onError(Subscribers.java:230)  ODS_HISPACE_OUTERCALL_LOG_DM
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnRunHookApplication$1.onError(AbstractCommand.java:1431)
	at com.netflix.hystrix.AbstractCommand$ExecutionHookApplication$1.onError(AbstractCommand.java:1362)
	at org.apache.servicecomb.bizkeeper.BizkeeperCommand.lambda$null$1(BizkeeperCommand.java:84)
	at org.apache.servicecomb.swagger.invocation.AsyncResponse.fail(AsyncResponse.java:42)
	at org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.fail(RestClientInvocation.java:278)
	at org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.lambda$invoke$0(RestClientInvocation.java:112)
	at io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:139)
	at io.vertx.core.http.impl.HttpClientRequestBase.timeout(HttpClientRequestBase.java:211)
	at io.vertx.core.http.impl.HttpClientRequestBase.handleTimeout(HttpClientRequestBase.java:194)
	at io.vertx.core.http.impl.HttpClientRequestBase.lambda$setTimeout$0(HttpClientRequestBase.java:124)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:906)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:865)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.servicecomb.core.exception.CseException: This is a fallback call from circuit breaker. 
 You can add fallback logic by catching this exception. 
 info: operation=AppGalleryUserCenterService:AppGalleryUserService.AppGalleryUserOrderInfoAPI.userOrder.
	at org.apache.servicecomb.bizkeeper.BizkeeperExceptionUtils.createBizkeeperException(BizkeeperExceptionUtils.java:34)
	at org.apache.servicecomb.bizkeeper.FallbackPolicyManager.getFallbackResponse(FallbackPolicyManager.java:46)
	... 43 common frames omitted
Caused by: org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=490;msg=CommonExceptionData [message=Cse Internal Bad Request]
	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.doCreate(ExceptionFactory.java:79)
	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.convertException(ExceptionFactory.java:124)
	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.convertConsumerException(ExceptionFactory.java:83)
	at org.apache.servicecomb.swagger.invocation.Response.createConsumerFail(Response.java:129)
	at org.apache.servicecomb.swagger.invocation.Response.createFail(Response.java:122)
	... 18 common frames omitted
Caused by: io.vertx.core.http.impl.HttpClientRequestBase$1: The timeout period of 50ms has been exceeded while executing POST /uc/rest/user-info-service/v1/user-order-info/order for host 10.24.0.244

**Comment by heyile** [comment]
已经有一个相关PR。 可以参考 #1628 https://github.com/apache/servicecomb-java-chassis/pull/1628

**Comment by Bluselye** [comment]
太感谢了，这个扩展功能做的挺好的。再问下，这个特性会在哪个版本开始支持。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
