### ISSUE TITLE
CSE java-chassis切ServiceComb java-chassis后项目无法启动

### ISSUE THREAD

**Issue by Fang57** [apache/servicecomb-java-chassis#1621]
[ ERROR] [2020-03-04 15:35:52.673] [main] [org.springframework.boot.SpringApplication.reportFailure(SpringApplication.java:821)] - Application run failed
java.lang.IllegalStateException: ServiceComb init failed.
	at org.apache.servicecomb.core.SCBEngine.init(SCBEngine.java:231) ~[java-chassis-core-1.3.0.B010RC1.jar:1.3.0.B010RC1]
	at org.apache.servicecomb.core.CseApplicationListener.onApplicationEvent(CseApplicationListener.java:81) ~[java-chassis-core-1.3.0.B010RC1.jar:1.3.0.B010RC1]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:102) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:77) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at com.huawei.rtc.rtcamservice.server.app.Application.main(Application.java:22) [classes/:?]
Caused by: java.lang.Error: can not find handler :perf-stats
	at org.apache.servicecomb.core.handler.AbstractHandlerManager.convertToChainClass(AbstractHandlerManager.java:72) ~[java-chassis-core-1.3.0.B010RC1.jar:1.3.0.B010RC1]
	at org.apache.servicecomb.core.handler.AbstractHandlerManager.createHandlerChain(AbstractHandlerManager.java:86) ~[java-chassis-core-1.3.0.B010RC1.jar:1.3.0.B010RC1]
	at org.apache.servicecomb.core.handler.AbstractHandlerManager.create(AbstractHandlerManager.java:112) ~[java-chassis-core-1.3.0.B010RC1.jar:1.3.0.B010RC1]
	at org.apache.servicecomb.core.handler.AbstractHandlerManager.create(AbstractHandlerManager.java:32) ~[java-chassis-core-1.3.0.B010RC1.jar:1.3.0.B010RC1]
	at org.apache.servicecomb.foundation.common.AbstractObjectManager.getOrCreate(AbstractObjectManager.java:37) ~[foundation-common-1.3.0.B010RC1.jar:1.3.0.B010RC1]
	at org.apache.servicecomb.core.definition.loader.SchemaLoader.registerSchema(SchemaLoader.java:88) ~[java-chassis-core-1.3.0.B010RC1.jar:1.3.0.B010RC1]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.createSchema(ProducerSchemaFactory.java:133) ~[java-chassis-core-1.3.0.B010RC1.jar:1.3.0.B010RC1]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.createSchema(ProducerSchemaFactory.java:54) ~[java-chassis-core-1.3.0.B010RC1.jar:1.3.0.B010RC1]
	at org.apache.servicecomb.core.definition.schema.AbstractSchemaFactory.getOrCreateSchema(AbstractSchemaFactory.java:58) ~[java-chassis-core-1.3.0.B010RC1.jar:1.3.0.B010RC1]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.getOrCreateProducerSchema(ProducerSchemaFactory.java:76) ~[java-chassis-core-1.3.0.B010RC1.jar:1.3.0.B010RC1]
	at org.apache.servicecomb.metrics.core.MetricsBootListener.registerSchemas(MetricsBootListener.java:69) ~[metrics-core-1.3.0.B010RC1.jar:1.3.0.B010RC1]
	at org.apache.servicecomb.metrics.core.MetricsBootListener.onBootEvent(MetricsBootListener.java:54) ~[metrics-core-1.3.0.B010RC1.jar:1.3.0.B010RC1]
	at org.apache.servicecomb.core.SCBEngine.triggerEvent(SCBEngine.java:157) ~[java-chassis-core-1.3.0.B010RC1.jar:1.3.0.B010RC1]
	at org.apache.servicecomb.core.SCBEngine.doInit(SCBEngine.java:263) ~[java-chassis-core-1.3.0.B010RC1.jar:1.3.0.B010RC1]
	at org.apache.servicecomb.core.SCBEngine.init(SCBEngine.java:219) ~[java-chassis-core-1.3.0.B010RC1.jar:1.3.0.B010RC1]
	... 12 more

**Comment by WillemJiang** [comment]
From the stack trace, it looks like you didn't change the java-chassis version from CSE to the community version.  Please check the java-chassis version in your pom.
从代码版本号来看，应该还是CSE版本，请检查pom配置里面的java-chassis版本替换是否替换完全。

**Comment by yhs0092** [comment]
报错原因这里已经打出来了
```
Caused by: java.lang.Error: can not find handler :perf-stats
```

你在这个服务的handler链里配置了一个不存在的handler，`perf-stats`。去检查一下handler链的配置吧

**Comment by Fang57** [comment]
thanks
