### ISSUE TITLE
通过docker镜像启动项目报错

### ISSUE THREAD

**Issue by sunjinghan7331** [apache/servicecomb-java-chassis#1625]
我将项目打包成可执行jar包，单独运行jar包时可以正确启动，但是在做成镜像时，启动jar包报以下错误。在项目中我有创建https访问的连接池，在linux和windows下单独启动jar包是没问题的，为什么打包成镜像后出现问题了呢？我依赖的基础镜像时centos 7.7.1908和 openjdk 8

Caused by: java.lang.IllegalArgumentException: no enabled cipher suits.
        at org.apache.servicecomb.foundation.ssl.SSLManager.getEnabledCiphers(SSLManager.java:184) ~[foundation-ssl-1.3.0.jar:1.3.0]
        at org.apache.servicecomb.foundation.ssl.SSLManager.createSSLSocket(SSLManager.java:161) ~[foundation-ssl-1.3.0.jar:1.3.0]
        at org.apache.servicecomb.foundation.ssl.SSLManager.getEnalbedCiphers(SSLManager.java:197) ~[foundation-ssl-1.3.0.jar:1.3.0]
        at org.apache.servicecomb.foundation.vertx.VertxTLSBuilder.buildTCPSSLOptions(VertxTLSBuilder.java:144) ~[foundation-vertx-1.3.0.jar:1.3.0]
        at org.apache.servicecomb.foundation.vertx.VertxTLSBuilder.buildClientOptionsBase(VertxTLSBuilder.java:83) ~[foundation-vertx-1.3.0.jar:1.3.0]
        at org.apache.servicecomb.foundation.vertx.VertxTLSBuilder.buildHttpClientOptions(VertxTLSBuilder.java:76) ~[foundation-vertx-1.3.0.jar:1.3.0]
        at org.apache.servicecomb.foundation.vertx.VertxTLSBuilder.buildHttpClientOptions(VertxTLSBuilder.java:71) ~[foundation-vertx-1.3.0.jar:1.3.0]
        at org.apache.servicecomb.transport.rest.client.RestTransportClient.createHttpClientOptions(RestTransportClient.java:85) ~[transport-rest-client-1.3.0.jar:1.3.0]
        at org.apache.servicecomb.transport.rest.client.RestTransportClient.init(RestTransportClient.java:60) ~[transport-rest-client-1.3.0.jar:1.3.0]
        at org.apache.servicecomb.transport.rest.client.RestTransportClientManager.<init>(RestTransportClientManager.java:35) ~[transport-rest-client-1.3.0.jar:1.3.0]
        at org.apache.servicecomb.transport.rest.client.RestTransportClientManager.<clinit>(RestTransportClientManager.java:25) ~[transport-rest-client-1.3.0.jar:1.3.0]
        at org.apache.servicecomb.transport.rest.vertx.VertxRestTransport.init(VertxRestTransport.java:73) ~[transport-rest-vertx-1.3.0.jar:1.3.0]
        at org.apache.servicecomb.core.transport.TransportManager.init(TransportManager.java:55) ~[java-chassis-core-1.3.0.jar:1.3.0]
        at org.apache.servicecomb.core.SCBEngine.doInit(SCBEngine.java:272) ~[java-chassis-core-1.3.0.jar:1.3.0]
        at org.apache.servicecomb.core.SCBEngine.init(SCBEngine.java:219) ~[java-chassis-core-1.3.0.jar:1.3.0]

**Comment by yhs0092** [comment]
>  Caused by: java.lang.IllegalArgumentException: no enabled cipher suits

看看是不是`ssl.ciphers`这个配置项配错了？参考Java-Chassis的[TLS资料](https://docs.servicecomb.io/java-chassis/zh_CN/security/tls/)
