### ISSUE TITLE
打成jar包形式的servicecomb，启动时找不到ssl认证文件

### ISSUE THREAD

**Issue by zhangbeiyuan-hw** [apache/servicecomb-java-chassis#1626]
认证文件放在resourecs中，并且一起打包在jar文件中，在启动的时候报错找不到认证文件。
难道不能引用jar内部的认证文件？

[2020-03-09 17:27:25,250][WARN][vert.x-eventloop-thread-15][VertxTLSBuilder.java][]keyStore **[file:/D:/code/github-zhangby/user-mgmt/target/user-mgmt-be.jar!/tls/openmep.p12] file not exist**, please check! org.apache.servicecomb.foundation.vertx.VertxTLSBuilder.buildTCPSSLOptions(VertxTLSBuilder.java:118)
[2020-03-09 17:27:25,271][WARN][vert.x-eventloop-thread-15][VertxTLSBuilder.java][]trustStore **[file:/D:/code/github-zhangby/user-mgmt/target/user-mgmt-be.jar!/tls/openmep.truststore]** file not exist, please check! org.apache.servicecomb.foundation.vertx.VertxTLSBuilder.buildTCPSSLOptions(VertxTLSBuilder.java:138)
[2020-03-09 17:27:25,270][ERROR][vert.x-eventloop-thread-5][RestServerVerticle.java][] org.apache.servicecomb.transport.rest.vertx.RestServerVerticle.start(RestServerVerticle.java:118)
io.vertx.core.VertxException: io.vertx.core.VertxException: Key/certificate is mandatory for SSL
        at io.vertx.core.net.impl.SSLHelper.createContext(SSLHelper.java:299) ~[vertx-core-3.6.3.jar:3.6.3]
        at io.vertx.core.net.impl.SSLHelper.getContext(SSLHelper.java:474) ~[vertx-core-3.6.3.jar:3.6.3]
        at io.vertx.core.net.impl.SSLHelper.validate(SSLHelper.java:499) ~[vertx-core-3.6.3.jar:3.6.3]
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:220) ~[vertx-core-3.6.3.jar:3.6.3]
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:191) ~[vertx-core-3.6.3.jar:3.6.3]
        at org.apache.servicecomb.transport.rest.vertx.RestServerVerticle.startListen(RestServerVerticle.java:216) ~[transport-rest-vertx-1.3.0.jar:1.3.0]
        at org.apache.servicecomb.transport.rest.vertx.RestServerVerticle.start(RestServerVerticle.java:115) ~[transport-rest-vertx-1.3.0.jar:1.3.0]
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:494) ~[vertx-core-3.6.3.jar:3.6.3]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) ~[vertx-core-3.6.3.jar:3.6.3]
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[vertx-core-3.6.3.jar:3.6.3]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.36.Final.jar:4.1.36.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405) [netty-common-4.1.36.Final.jar:4.1.36.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.36.Final.jar:4.1.36.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-common-4.1.36.Final.jar:4.1.36.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.36.Final.jar:4.1.36.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.36.Final.jar:4.1.36.Final]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: io.vertx.core.VertxException: Key/certificate is mandatory for SSL
        at io.vertx.core.net.impl.SSLHelper.createContext(SSLHelper.java:259) ~[vertx-core-3.6.3.jar:3.6.3]
        ... 16 more

**Comment by heyile** [comment]
证书确实无法打包在jar包内. 建议证书外挂

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
