### ISSUE TITLE
org.apache.servicecomb.foundation.common.exceptions.ServiceCombException: all transport named rest refused to init.

### ISSUE THREAD

**Issue by lizhiqian-hw** [apache/servicecomb-java-chassis#1629]
注册服务出现异常，多次更换端口号不起作用，java.lang.IllegalStateException: ServiceComb init failed.
	at org.apache.servicecomb.core.SCBEngine.init(SCBEngine.java:231) ~[java-chassis-core-1.3.0.jar:1.3.0]
	at org.apache.servicecomb.core.CseApplicationListener.onApplicationEvent(CseApplicationListener.java:81) ~[java-chassis-core-1.3.0.jar:1.3.0]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:102) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:77) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.appstore.mec.MainServer.main(MainServer.java:16) [classes/:na]
Caused by: org.apache.servicecomb.foundation.common.exceptions.ServiceCombException: all transport named rest refused to init.
	at org.apache.servicecomb.core.transport.TransportManager.chooseOneTransport(TransportManager.java:90) ~[java-chassis-core-1.3.0.jar:1.3.0]
	at org.apache.servicecomb.core.transport.TransportManager.buildTransportMap(TransportManager.java:74) ~[java-chassis-core-1.3.0.jar:1.3.0]

**Comment by heyile** [comment]
有没有其他报错? 换个端口也不行?

**Comment by lizhiqan** [comment]
<dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>transport-rest-vertx</artifactId>
        </dependency>

**Comment by lizhiqan** [comment]
> 有没有其他报错? 换个端口也不行?

这个问题就是多次更换端口，依然报错，需要在pom中增加依赖transport-rest-vertx，但是原理为何

**Comment by liubao68** [comment]
可以参考 [transports](https://docs.servicecomb.io/java-chassis/zh_CN/transports/rest-over-servlet/)，  java-chassis支持多种不同的transport， 如果所有的transport初始化失败，则会报告上面的错误。 加了transport-rest-vertx，相当于引入了REST over vert.x

**Comment by sun-weihan** [comment]
详细解释：https://bbs.huaweicloud.com/forum/thread-14695-1-1.html

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
