### ISSUE TITLE
 Cannot deserialize instance of `java.lang.String` out of START_OBJECT token

### ISSUE THREAD

**Issue by lizhiqian-hw** [apache/servicecomb-java-chassis#1630]
接口测试提示内容
CommonExceptionData [message=Parameters not valid or types not match.]

异常堆栈
java.lang.IllegalArgumentException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3750) ~[jackson-databind-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3688) ~[jackson-databind-2.9.9.jar:2.9.9]
	at org.apache.servicecomb.swagger.invocation.converter.impl.ConverterCommon.convert(ConverterCommon.java:36) ~[swagger-invocation-core-1.3.0.jar:1.3.0]

**Comment by yhs0092** [comment]
这个一般是body参数的格式不对，你贴的堆栈已经把问题位置打出来了
`org.apache.servicecomb.swagger.invocation.converter.impl.ConverterCommon.convert(ConverterCommon.java:36) ~[swagger-invocation-core-1.3.0.jar:1.3.0]`
建议在这里打断点看看转换的参数原文是什么样的吧？

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
