### ISSUE TITLE
edge由于某个后端服务响应慢导致整体故障，影响了其他后端服务的转发

### ISSUE THREAD

**Issue by h00379108** [apache/servicecomb-java-chassis#1647]
现网edge出现大量block，整体故障处于无法服务状态。定位到某个后端服务影响慢，导致edge也转发不了请求给其他的后端服务，这种情况是否说明使用reactive模式存在很大的风险？

2020-03-19 13:34:16.654|SR|WARN |vertx-blocked-thread-checker|{}|io.vertx.core.impl.BlockedThreadChecker$1.run(BlockedThreadChecker.java:55)|Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 228655 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
	at io.vertx.core.http.impl.HttpServerResponseImpl.setChunked(HttpServerResponseImpl.java:138) ~[vertx-core-3.6.3.jar!/:3.6.3]
	at io.vertx.core.http.impl.HttpServerResponseImpl.setChunked(HttpServerResponseImpl.java:55) ~[vertx-core-3.6.3.jar!/:3.6.3]
	at com.huawei.common.util.UrlRedirectUtil.lambda$urlRequest$3(UrlRedirectUtil.java:87) ~[classes!/:?]
	at com.huawei.common.util.UrlRedirectUtil$$Lambda$282/1597685093.handle(Unknown Source) ~[?:?]
	at io.vertx.core.http.impl.HttpClientRequestImpl.doHandleResponse(HttpClientRequestImpl.java:430) ~[vertx-core-3.6.3.jar!/:3.6.3]
	at io.vertx.core.http.impl.HttpClientRequestBase.doHandleResponse(HttpClientRequestBase.java:175) ~[vertx-core-3.6.3.jar!/:3.6.3]
	at io.vertx.core.http.impl.HttpClientRequestBase.checkHandleResponse(HttpClientRequestBase.java:162) ~[vertx-core-3.6.3.jar!/:3.6.3]
	at io.vertx.core.http.impl.HttpClientRequestBase.handleResponse(HttpClientRequestBase.java:146) ~[vertx-core-3.6.3.jar!/:3.6.3]
	at io.vertx.core.http.impl.Http1xClientConnection.handleResponseBegin(Http1xClientConnection.java:624) ~[vertx-core-3.6.3.jar!/:3.6.3]
	at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:594) ~[vertx-core-3.6.3.jar!/:3.6.3]
	at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:560) ~[vertx-core-3.6.3.jar!/:3.6.3]
	at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:397) ~[vertx-core-3.6.3.jar!/:3.6.3]
	at io.vertx.core.net.impl.VertxHandler$$Lambda$71/499332961.handle(Unknown Source) ~[?:?]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) ~[vertx-core-3.6.3.jar!/:3.6.3]
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43) ~[vertx-core-3.6.3.jar!/:3.6.3]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188) ~[vertx-core-3.6.3.jar!/:3.6.3]
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:174) ~[vertx-core-3.6.3.jar!/:3.6.3]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[netty-codec-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[netty-codec-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[netty-codec-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1407) ~[netty-handler-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1177) ~[netty-handler-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1221) ~[netty-handler-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460) ~[netty-transport-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-common-4.1.28.Final.jar!/:4.1.28.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.28.Final.jar!/:4.1.28.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_222]

**Comment by liubao68** [comment]
这个堆栈显示的是自定义 Disptacher 阻塞， 不是Edge本身的实现阻塞了。需要分析下自定义代码。

**Comment by h00379108** [comment]
package com.huawei.common.util;

import com.huawei.common.config.ConfigUtil;
import com.huawei.common.config.KeyConfigUtil;
import com.huawei.common.log.LogUtil;
import com.huawei.servicerouting.filter.HttpEventServletFilter;
import io.vertx.core.Vertx;
import io.vertx.core.http.HttpClient;
import io.vertx.core.http.HttpClientOptions;
import io.vertx.core.http.HttpClientRequest;
import io.vertx.ext.web.RoutingContext;
import org.apache.servicecomb.transport.rest.client.TransportClientConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.net.URI;

import static com.huawei.common.util.SrUtil.CLIENT_RESPONSE;

public class UrlRedirectUtil {

    private static final Logger LOG = LoggerFactory.getLogger(UrlRedirectUtil.class);


    private static Vertx vertx = Vertx.vertx();
    private static HttpClient httpsClient = null;
    private static HttpClient httpClient = null;

    static
    {
        HttpClientOptions options = new HttpClientOptions();
        options.setSsl(true)
        .setTrustAll(true)
        .setVerifyHost(false)
        .setIdleTimeout(TransportClientConfig.getConnectionIdleTimeoutInSeconds())
        .setKeepAlive(TransportClientConfig.getConnectionKeepAlive())
        .setConnectTimeout(KeyConfigUtil.getConnectTimeOut())
        .setMaxPoolSize(TransportClientConfig.getConnectionMaxPoolSize())
        .setMaxHeaderSize(ConfigUtil.getIntConfig("MaxHeaderSize", 32000))
        .setMaxInitialLineLength(ConfigUtil.getIntConfig("MaxInitialLineLength", HttpClientOptions.DEFAULT_MAX_INITIAL_LINE_LENGTH));
        httpsClient = vertx.createHttpClient(options);

        HttpClientOptions option = new HttpClientOptions();
        //option.setMaxPoolSize() 目前没有限制，设置了会导致新请求拒绝。
        option.setVerifyHost(false)
                .setIdleTimeout(TransportClientConfig.getConnectionIdleTimeoutInSeconds())
                .setKeepAlive(TransportClientConfig.getConnectionKeepAlive())
                .setConnectTimeout(KeyConfigUtil.getConnectTimeOut())
                .setMaxPoolSize(TransportClientConfig.getConnectionMaxPoolSize())
                .setMaxHeaderSize(ConfigUtil.getIntConfig("MaxHeaderSize", 32000))
                .setMaxInitialLineLength(ConfigUtil.getIntConfig("MaxInitialLineLength", HttpClientOptions.DEFAULT_MAX_INITIAL_LINE_LENGTH));
        httpClient = vertx.createHttpClient(option);
    }

    private static URI getUri(String url) throws Exception
    {
        return new URI(url);
    }

    @SuppressWarnings("deprecation")
    public static void urlRequest(RoutingContext context, String url)
    {
        try {
            LOG.info("Start to deliver by IP={}", url);

            URI uri = getUri(url);
            HttpClient tempClient = null;
            if (url.startsWith("https://")) {
                tempClient = httpsClient;
            }
            else {
                tempClient = httpClient;
            }

            String requestId = LogUtil.getRequestId();

            long startTime = System.currentTimeMillis();
            context.put(HttpEventServletFilter.HTTP_START_TIME, startTime);

            // 使用HttpClient转发请求
            HttpClientRequest clietRequest =
                    tempClient.request(context.request().method(),
                            uri.getPort(),
                            uri.getHost(),
                            context.request().uri(),
                            clientResponse -> {

                                context.request().response().setChunked(true);
                                context.request().response().setStatusCode(clientResponse.statusCode());
                                context.request().response().headers().setAll(clientResponse.headers());
                                context.request().response().headers().set(LogUtil.SRREQUESTID, requestId);

                                clientResponse.handler(data -> {
                                    context.request().response().write(data);
                                    context.put(CLIENT_RESPONSE, data.toString("UTF-8"));
                                });

                                clientResponse.exceptionHandler(e -> {
                                    LogUtil.putContext(LogUtil.SRREQUESTID, requestId);
                                    SrUtil.handleException(context, e);
                                    LogUtil.clearContext();
                                });

                                clientResponse.endHandler((v) -> {
                                    LogUtil.putContext(LogUtil.SRREQUESTID, requestId);
                                    SrUtil.endResponse(context);
                                    LogUtil.clearContext();
                                });

                            });

            clietRequest.setChunked(true);
            clietRequest.headers().setAll(context.request().headers().remove("Content-Length").remove("Host").remove("Connection").remove("Cache-Control"));
            clietRequest.setTimeout(KeyConfigUtil.getTotalTimeOut());
            // 吧请求ServiceRoutign的消息体写到clietRequest
            context.request().handler(clietRequest::write);

            clietRequest.exceptionHandler(v->{
                LogUtil.putContext(LogUtil.SRREQUESTID, requestId);
                SrUtil.handleException(context, v);
                LogUtil.clearContext();
            });


            // 异步发送请求
            context.request().endHandler((v) -> clietRequest.end());
        }
        catch (Exception e) {
            SrUtil.handleException(context, e);
        } finally {
            LogUtil.clearContext();
        }
    }
}

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
