### ISSUE TITLE
servicecomb启动报空指针异常

### ISSUE THREAD

**Issue by w00189670** [apache/servicecomb-java-chassis#1662]
2020-03-25T11:49:29.948+0800 || http-nio-8080-exec-3 || [.[.[.[ServicecombRestServlet].175  || ERROR || Servlet.service() for servlet [ServicecombRestServlet] in context with path [] threw exception
java.lang.NullPointerException: null
	at org.apache.servicecomb.common.rest.locator.ServicePathManager.getServicePathManager(ServicePathManager.java:59)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.findRestOperation(AbstractRestInvocation.java:80)
	at org.apache.servicecomb.common.rest.RestProducerInvocation.findRestOperation(RestProducerInvocation.java:57)
	at org.apache.servicecomb.transport.rest.servlet.RestServletProducerInvocation.findRestOperation(RestServletProducerInvocation.java:28)
	at org.apache.servicecomb.common.rest.RestProducerInvocation.invoke(RestProducerInvocation.java:46)
	at org.apache.servicecomb.transport.rest.servlet.ServletRestDispatcher.service(ServletRestDispatcher.java:57)
	at org.apache.servicecomb.transport.rest.servlet.RestServlet.service(RestServlet.java:47)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.huawei.appgallery.quickapp.portal.component.xss.XssFilter.doFilter(XssFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2020-03-25T11:49:29.953+0800 || http-nio-8080-exec-3 || [.[.[.[ServicecombRestServlet].175  || ERROR || Servlet.service() for servlet [ServicecombRestServlet] threw exception
java.lang.IllegalStateException: Calling [asyncStart()] is not valid for a request with Async state [STARTING]
	at org.apache.coyote.AsyncStateMachine.asyncStart(AsyncStateMachine.java:242)
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:497)
	at org.apache.coyote.Request.action(Request.java:432)
	at org.apache.catalina.core.AsyncContextImpl.setStarted(AsyncContextImpl.java:323)
	at org.apache.catalina.connector.Request.startAsync(Request.java:1700)
	at org.apache.catalina.connector.Request.startAsync(Request.java:1682)
	at org.apache.catalina.connector.RequestFacade.startAsync(RequestFacade.java:1043)
	at javax.servlet.ServletRequestWrapper.startAsync(ServletRequestWrapper.java:383)
	at org.apache.servicecomb.transport.rest.servlet.ServletRestDispatcher.service(ServletRestDispatcher.java:49)
	at org.apache.servicecomb.transport.rest.servlet.RestServlet.service(RestServlet.java:47)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:461)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:394)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:253)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:348)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:173)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2020-03-25T11:49:29.954+0800 || http-nio-8080-exec-3 ||        o.a.c.c.C.[.[localhost].175  || ERROR || Exception Processing ErrorPage[errorCode=0, location=/error]
java.lang.IllegalStateException: Calling [asyncStart()] is not valid for a request with Async state [STARTING]
	at org.apache.coyote.AsyncStateMachine.asyncStart(AsyncStateMachine.java:242)
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:497)
	at org.apache.coyote.Request.action(Request.java:432)
	at org.apache.catalina.core.AsyncContextImpl.setStarted(AsyncContextImpl.java:323)
	at org.apache.catalina.connector.Request.startAsync(Request.java:1700)
	at org.apache.catalina.connector.Request.startAsync(Request.java:1682)
	at org.apache.catalina.connector.RequestFacade.startAsync(RequestFacade.java:1043)
	at javax.servlet.ServletRequestWrapper.startAsync(ServletRequestWrapper.java:383)
	at org.apache.servicecomb.transport.rest.servlet.ServletRestDispatcher.service(ServletRestDispatcher.java:49)
	at org.apache.servicecomb.transport.rest.servlet.RestServlet.service(RestServlet.java:47)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:461)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:394)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:253)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:348)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:173)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2020-03-25T11:49:29.954+0800 || http-nio-8080-exec-3 ||      o.a.c.h.Http11NioProtocol.175  || ERROR || Error reading request, ignored
java.lang.IllegalStateException: Calling [asyncPostProcess()] is not valid for a request with Async state [MUST_ERROR]
	at org.apache.coyote.AsyncStateMachine.asyncPostProcess(AsyncStateMachine.java:290)
	at org.apache.coyote.AbstractProcessor.asyncPostProcess(AbstractProcessor.java:191)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:81)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by liubao68** [comment]
你用的哪个版本？ 可以对着代码看看失败代码上下文， 也可以看看更前面的日志，可能是启动过程中其他异常导致的。

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.
