### ISSUE TITLE
Caused by: javassist.NotFoundException: Static Internal Class

### ISSUE THREAD

**Issue by houjibo** [apache/servicecomb-java-chassis#1691]
There has no problem when i debug with `classPool.get(javaType.getRawClass().getTypeName())` !

https://github.com/apache/servicecomb-java-chassis/blob/be097f43a9711b1669977c6cda1fc43983f96590/common/common-javassist/src/main/java/org/apache/servicecomb/common/javassist/CtType.java#L55

```text
Caused by: javassist.NotFoundException: test.Person.StaticInternalPerson
	at javassist.ClassPool.get(ClassPool.java:422) ~[javassist-3.24.0-GA.jar:?]
	at org.apache.servicecomb.common.javassist.CtType.<init>(CtType.java:55) ~[common-javassist-1.0.0.B003.H98.jar:1.0.0.B003.H98]
	at org.apache.servicecomb.common.javassist.MethodConfig.addParameter(MethodConfig.java:72) ~[common-javassist-1.0.0.B003.H98.jar:1.0.0.B003.H98]
	at org.apache.servicecomb.swagger.converter.SwaggerToClassGenerator.convertToInterface(SwaggerToClassGenerator.java:229) ~[swagger-generator-core-1.0.0.B003.H98.jar:1.0.0.B003.H98]
	at org.apache.servicecomb.swagger.converter.SwaggerToClassGenerator.convert(SwaggerToClassGenerator.java:144) ~[swagger-generator-core-1.0.0.B003.H98.jar:1.0.0.B003.H98]
	at org.apache.servicecomb.core.definition.SchemaMeta.<init>(SchemaMeta.java:70) ~[java-chassis-core-1.0.0.B003.H98.jar:1.0.0.B003.H98]
	at org.apache.servicecomb.core.definition.loader.SchemaLoader.registerSchema(SchemaLoader.java:85) ~[java-chassis-core-1.0.0.B003.H98.jar:1.0.0.B003.H98]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.createSchema(ProducerSchemaFactory.java:133) ~[java-chassis-core-1.0.0.B003.H98.jar:1.0.0.B003.H98]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.createSchema(ProducerSchemaFactory.java:54) ~[java-chassis-core-1.0.0.B003.H98.jar:1.0.0.B003.H98]
	at org.apache.servicecomb.core.definition.schema.AbstractSchemaFactory.getOrCreateSchema(AbstractSchemaFactory.java:58) ~[java-chassis-core-1.0.0.B003.H98.jar:1.0.0.B003.H98]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.getOrCreateProducerSchema(ProducerSchemaFactory.java:76) ~[java-chassis-core-1.0.0.B003.H98.jar:1.0.0.B003.H98]
	at org.apache.servicecomb.provider.rest.common.RestProducerProvider.init(RestProducerProvider.java:45) ~[provider-rest-common-1.0.0.B003.H98.jar:1.0.0.B003.H98]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.init(ProducerProviderManager.java:54) ~[java-chassis-core-1.0.0.B003.H98.jar:1.0.0.B003.H98]
	at org.apache.servicecomb.core.SCBEngine.doInit(SCBEngine.java:239) ~[java-chassis-core-1.0.0.B003.H98.jar:1.0.0.B003.H98]
	at org.apache.servicecomb.core.SCBEngine.init(SCBEngine.java:207) ~[java-chassis-core-1.0.0.B003.H98.jar:1.0.0.B003.H98]
```

```java
@Data
public class Person {
    private String name;

    private int age;

    @Data
    static class StaticInternalPerson {
        private String name;

        private int age;
    }

    public static void main(String[] args) {
        System.out.println("CanonicalName: " + Person.class.getCanonicalName());
        System.out.println("     TypeName: " + Person.class.getTypeName());
        System.out.println("CanonicalName: " + StaticInternalPerson.class.getCanonicalName());
        System.out.println("     TypeName: " + StaticInternalPerson.class.getTypeName());
        System.out.println("CanonicalName: " + InternalPerson.class.getCanonicalName());
        System.out.println("     TypeName: " + InternalPerson.class.getTypeName());
    }
}

@Data
class InternalPerson {
    private String name;

    private int age;
}
```
The main result as:
```text
CanonicalName: test.Person
     TypeName: test.Person
CanonicalName: test.Person.StaticInternalPerson
     TypeName: test.Person$StaticInternalPerson
CanonicalName: test.InternalPerson
     TypeName: test.InternalPerson
```

**Comment by liubao68** [comment]
This mechanism has been deleted in java-chassis 2.0.* . If you are using older versions, suggestion not using inner class type.  Even in new versions, inner class type is not recommended. Although they may work, but some unexpected problems may happen in newer JDK .

**Comment by houjibo** [comment]
I've already changed it as the test.InternalPerson.
