### ISSUE TITLE
Using POJO as query parameters dont support List<Long> property

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [apache/servicecomb-java-chassis#1709]
I just refactored our code to use pojo instead of a bunch of query parameters because there are simply too many parameters. But when I moved something like `List<Long> ids` into pojo, servicecomb failed to start.
```
Caused by: java.lang.IllegalStateException: not allow complex type for query parameter, type=java.util.List.
	at org.apache.servicecomb.swagger.SwaggerUtils.setParameterType(SwaggerUtils.java:229) ~[swagger-generator-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.swagger.generator.springmvc.SpringmvcOperationGenerator.lambda$initMethodParameterGenerators$1(SpringmvcOperationGenerator.java:47) ~[swagger-generator-springmvc-2.0.1.jar:2.0.1]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_231]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_231]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_231]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_231]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_231]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_231]
	at org.apache.servicecomb.swagger.generator.springmvc.SpringmvcOperationGenerator.initMethodParameterGenerators(SpringmvcOperationGenerator.java:44) ~[swagger-generator-springmvc-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.initParameterGenerators(AbstractOperationGenerator.java:213) ~[classes/:2.0.1]
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.scanMethodParameters(AbstractOperationGenerator.java:193) ~[classes/:2.0.1]
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.generate(AbstractOperationGenerator.java:154) ~[classes/:2.0.1]
	at org.apache.servicecomb.swagger.generator.core.AbstractSwaggerGenerator.scanMethods(AbstractSwaggerGenerator.java:297) ~[swagger-generator-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.swagger.generator.core.AbstractSwaggerGenerator.generate(AbstractSwaggerGenerator.java:119) ~[swagger-generator-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.swagger.generator.SwaggerGenerator.generate(SwaggerGenerator.java:32) ~[swagger-generator-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.swagger.engine.SwaggerEnvironment.createProducer(SwaggerEnvironment.java:105) ~[swagger-invocation-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.registerSchema(ProducerProviderManager.java:97) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.regsiterProducerMetas(ProducerProviderManager.java:86) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.init(ProducerProviderManager.java:72) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.SCBEngine.doRun(SCBEngine.java:341) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.SCBEngine.run(SCBEngine.java:297) ~[java-chassis-core-2.0.1.jar:2.0.1]
	... 12 more
```
I looked into source code and find when calling `propertyDefinition.getPrimaryType().getRawClass()` in `org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator#extractAggregatedParameterGenerators` generic info was omitted, we should call something like `propertyDefinition.getPrimaryMember().getGenericType()` instead.

PS: `com.fasterxml.jackson.databind.introspect.Annotated#getGenericType` is deprecated, but its seems easy to implement on our own.

**Comment by liubao68** [comment]
Close old issues. Please feel free to open a new one.

**Comment by liubao68** [comment]
This issues seems fixed in latest version. 

Close old issues. Please feel free to open a new one.
