### ISSUE TITLE
Springboot工程集成ServiceComb，无法读取方案文档

### ISSUE THREAD

**Issue by GuiSong01** [apache/servicecomb-java-chassis#1711]
Springboot集成ServiceComb。启动报如下错误：
2020-04-15 10:24:01,065Z(26835):WARN [main]org.springframework.util.xml.SimpleSaxErrorHandler.warning(SimpleSaxErrorHandler.java:48)-->Ignored XML validation warning
org.xml.sax.SAXParseException: schema_reference.4: 无法读取方案文档 'https://www.springframework.org/schema/tool/spring-tool.xsd', 原因为 1) 无法找到文档; 2) 无法读取文档; 3) 文档的根元素不是 <xsd:schema>。
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203) ~[?:1.8.0_45]
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.warning(ErrorHandlerWrapper.java:99) ~[?:1.8.0_45]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:433) ~[?:1.8.0_45]
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4162) ~[?:1.8.0_45]
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaWarning(XSDHandler.java:4157) ~[?:1.8.0_45]
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument1(XSDHandler.java:2490) ~[?:1.8.0_45]
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2187) ~[?:1.8.0_45]
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.resolveSchema(XSDHandler.java:2078) ~[?:1.8.0_45]
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.constructTrees(XSDHandler.java:1008) ~[?:1.8.0_45]
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:620) ~[?:1.8.0_45]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:617) ~[?:1.8.0_45]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2453) ~[?:1.8.0_45]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1773) ~[?:1.8.0_45]
..........
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_45]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_45]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345) ~[?:1.8.0_45]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_45]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_45]
调测了一下，应该是如下xml文件解析出现问题：
/org/apache/servicecomb/java-chassis-core/1.3.0.B006/java-chassis-core-1.3.0.B006.jar!/META-INF/spring/cse.bean.xml

请问有遇到过吗？怎么解决的？

**Comment by liubao68** [comment]
cse.bean.xml 并没有 spring-tool 的引用。 看起来不是这个文件。 这类错误有可能是 pom 配置不恰当， 导致 spring/spring boot 的不同版本并存引起的。 建议参考下[这里的说明和例子](http://localhost:8000/using-java-chassis-in-spring-boot/components-for-spring-boot/)

**Comment by GuiSong01** [comment]
多谢，问题已经解决，确实是依赖导致的问题。我在pom里面引入了，spring-beans（5.1.5.RELEASE），spring-core（5.1.5.RELEASE），也引入spring-data-commons（2.1.6.RELEASE），spring-data-commons已经引入spring-core（5.1.6.RELEASE），spring-beans（5.1.6.RELEASE），我把自己在pom里面引入的spring-beans（5.1.5.RELEASE），spring-core（5.1.5.RELEASE）干掉就好使了
