### ISSUE TITLE
升级servicecomb 2.0.1版本，Application run failed

### ISSUE THREAD

**Issue by Fang57** [apache/servicecomb-java-chassis#1723]
[ WARN ] [2020-04-20 09:58:58.280] [main] [org.apache.servicecomb.serviceregistry.client.http.ServiceRegistryClientImpl.updateMicroserviceInstanceStatus(ServiceRegistryClientImpl.java:939)] - Bad Request
[ ERROR] [2020-04-20 09:58:58.307] [main] [org.springframework.boot.SpringApplication.reportFailure(SpringApplication.java:821)] - Application run failed
java.lang.IllegalStateException: ServiceComb init failed.
	at org.apache.servicecomb.core.SCBEngine.run(SCBEngine.java:309) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.CseApplicationListener.onApplicationEvent(CseApplicationListener.java:77) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:102) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:77) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at com.huawei.rtc.rtcamservice.server.app.Application.main(Application.java:20) [classes/:?]
Caused by: java.lang.IllegalStateException: generate swagger operation failed, method=com.huawei.rtc.rtcamservice.server.controller.APPInfoProvider:subscribeAPPInfo.
	at org.apache.servicecomb.swagger.generator.core.AbstractSwaggerGenerator.scanMethods(AbstractSwaggerGenerator.java:301) ~[swagger-generator-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.swagger.generator.core.AbstractSwaggerGenerator.generate(AbstractSwaggerGenerator.java:119) ~[swagger-generator-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.swagger.generator.SwaggerGenerator.generate(SwaggerGenerator.java:32) ~[swagger-generator-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.swagger.engine.SwaggerEnvironment.createProducer(SwaggerEnvironment.java:105) ~[swagger-invocation-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.registerSchema(ProducerProviderManager.java:97) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.regsiterProducerMetas(ProducerProviderManager.java:86) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.init(ProducerProviderManager.java:72) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.SCBEngine.doRun(SCBEngine.java:341) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.SCBEngine.run(SCBEngine.java:297) ~[java-chassis-core-2.0.1.jar:2.0.1]
	... 12 more
Caused by: java.lang.IllegalStateException: parameter name is not present, method=com.huawei.rtc.rtcamservice.server.controller.APPInfoProvider:subscribeAPPInfo
solution:
  change pom.xml, add compiler argument: -parameters, for example:
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-compiler-plugin</artifactId>
      <configuration>
        <compilerArgument>-parameters</compilerArgument>
      </configuration>
    </plugin>
	at org.apache.servicecomb.swagger.generator.SwaggerGeneratorUtils.collectParameterName(SwaggerGeneratorUtils.java:192) ~[swagger-generator-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.swagger.generator.ParameterGenerator.<init>(ParameterGenerator.java:55) ~[swagger-generator-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.swagger.generator.ParameterGenerator.<init>(ParameterGenerator.java:66) ~[swagger-generator-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.initMethodParameterGenerators(AbstractOperationGenerator.java:230) ~[swagger-generator-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.swagger.generator.springmvc.SpringmvcOperationGenerator.initMethodParameterGenerators(SpringmvcOperationGenerator.java:40) ~[swagger-generator-springmvc-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.initParameterGenerators(AbstractOperationGenerator.java:213) ~[swagger-generator-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.scanMethodParameters(AbstractOperationGenerator.java:193) ~[swagger-generator-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.generate(AbstractOperationGenerator.java:154) ~[swagger-generator-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.swagger.generator.core.AbstractSwaggerGenerator.scanMethods(AbstractSwaggerGenerator.java:297) ~[swagger-generator-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.swagger.generator.core.AbstractSwaggerGenerator.generate(AbstractSwaggerGenerator.java:119) ~[swagger-generator-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.swagger.generator.SwaggerGenerator.generate(SwaggerGenerator.java:32) ~[swagger-generator-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.swagger.engine.SwaggerEnvironment.createProducer(SwaggerEnvironment.java:105) ~[swagger-invocation-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.registerSchema(ProducerProviderManager.java:97) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.regsiterProducerMetas(ProducerProviderManager.java:86) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.init(ProducerProviderManager.java:72) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.SCBEngine.doRun(SCBEngine.java:341) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.SCBEngine.run(SCBEngine.java:297) ~[java-chassis-core-2.0.1.jar:2.0.1]
	... 12 more

**Comment by Fang57** [comment]
java-chassis-spring-boot-starter-servlet 引入的spring依赖为5.1.5版本，使用5.1.8版本覆盖spring组件后问题已修复

**Comment by liubao68** [comment]
```
Caused by: java.lang.IllegalStateException: parameter name is not present, method=com.huawei.rtc.rtcamservice.server.controller.APPInfoProvider:subscribeAPPInfo
solution:
change pom.xml, add compiler argument: -parameters, for example:

org.apache.maven.plugins
maven-compiler-plugin

-parameters
```
这个错误是编译选型设置的错误， java-chassis 2.0.0 以上的版本要求加上， 这个应该是spring 版本无关。 升级指导描述了这个问题： https://docs.servicecomb.io/java-chassis/zh_CN/featured-topics/upgrading/1_3_0T2_0_0/
