### ISSUE TITLE
请求接口失败，框架自行打印异常日志，能否关闭

### ISSUE THREAD

**Issue by Fang57** [apache/servicecomb-java-chassis#1730]
[ ERROR] [2020-04-28 18:26:05.778] [group0-1-thread-3] [org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.doInvoke(ProducerOperationHandler.java:146)] - unexpected error PRODUCER rest RTCAMService.openapi_rtcamservice_appservicedatamanager.createAPPServiceData,
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor254.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.doInvoke(ProducerOperationHandler.java:130) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.syncInvoke(ProducerOperationHandler.java:115) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.invoke(ProducerOperationHandler.java:63) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.handle(ProducerOperationHandler.java:54) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.Invocation.next(Invocation.java:293) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.bizkeeper.BizkeeperCommand.lambda$construct$2(BizkeeperCommand.java:79) ~[handler-bizkeeper-2.0.1.jar:2.0.1]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.Observable.unsafeSubscribe(Observable.java:8666) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:52) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:36) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.Observable.unsafeSubscribe(Observable.java:8666) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:52) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:36) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.Observable.unsafeSubscribe(Observable.java:8666) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:52) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:36) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.Observable.subscribe(Observable.java:8759) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.Observable.subscribe(Observable.java:8726) ~[rxjava-1.1.6.jar:1.1.6]
	at rx.Observable.subscribe(Observable.java:8619) ~[rxjava-1.1.6.jar:1.1.6]
	at org.apache.servicecomb.bizkeeper.BizkeeperHandler.handle(BizkeeperHandler.java:78) ~[handler-bizkeeper-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.Invocation.next(Invocation.java:293) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.qps.ProviderQpsFlowControlHandler.handle(ProviderQpsFlowControlHandler.java:38) ~[handler-flowcontrol-qps-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.core.Invocation.next(Invocation.java:293) ~[java-chassis-core-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.doInvoke(AbstractRestInvocation.java:245) ~[common-rest-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke(AbstractRestInvocation.java:219) ~[common-rest-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor(AbstractRestInvocation.java:203) ~[common-rest-2.0.1.jar:2.0.1]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(AbstractRestInvocation.java:162) ~[common-rest-2.0.1.jar:2.0.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

版本：servicecomb 2.0.1

**Comment by liubao68** [comment]
可以打开 ProducerOperationHandler 看下对应的代码行，有个开关。

**Comment by Fang57** [comment]
目前支持设置ProducerOperationHandler类的shouldPrintErrorLog方法，并被框架读取吗

**Comment by liubao68** [comment]
shouldPrintErrorLog读取了一个配置项，加上配置项即可。

**Comment by Fang57** [comment]
protected boolean shouldPrintErrorLog(Throwable throwable) {
    if (!(throwable instanceof InvocationTargetException)) {
      return true;
    }
    Throwable targetException = ((InvocationTargetException) throwable).getTargetException();
    return !(targetException instanceof InvocationException);
  }
这里没有可配置的地方啊，请问要怎么配置

**Comment by liubao68** [comment]
看了下代码，确实不支持配置关闭。 我记错代码了。 唯一能规避下的就是配置下 logger。 不输出ProducerOperationHandler的日志。
