### ISSUE TITLE
依赖了com.huawei.paas.cse：cse-handler-cloud-extension包之后，疯狂打印如下错误日志。要怎么屏蔽？

### ISSUE THREAD

**Issue by zhongyi-tim** [apache/servicecomb-java-chassis#1796]
config-center-vert.x-eventloop-thread-0|||||||get url https://xx.xxx.x.x:443/api/v1/namespaces/default/secrets/default-secret with status: 403

**Comment by liubao68** [comment]
This is not a modul in java-chassis, you can try to remove the module.  Maybe 'foundation-auth*jar'

**Comment by zhongyi-tim** [comment]
> This is not a modul in java-chassis, you can try to remove the module. Maybe 'foundation-auth*jar'

exclude掉'foundation-auth*jar后，日志报错如下：

2020-05-30 08:55:06,587Z(71143):ERROR{}[monitor-center-vert.x-eventloop-thread-0#15]-->Unhandled exception
java.lang.NoClassDefFoundError: com/huawei/paas/foundation/auth/AuthHeaderProviderImpl
        at com.huawei.paas.monitor.DefaultMonitorDataPublisher.lambda$doSend$4(DefaultMonitorDataPublisher.java:245) ~[cse-handler-cloud-extension-2.4.5RC25.jar:2.4.5RC25]
        at org.apache.servicecomb.foundation.vertx.client.http.HttpClientWithContext.lambda$runOnContext$0(HttpClientWithContext.java:43) ~[foundation-vertx-1.2.0.B011.jar:1.2.0.B011]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) ~[vertx-core-3.6.3.jar:3.6.3]
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[vertx-core-3.6.3.jar:3.6.3]

**Comment by liubao68** [comment]
Close old issues.
