### ISSUE TITLE
升级serviceComb2.0.0，定义RPC调用方式所使用的代理接口调不通

### ISSUE THREAD

**Issue by zhuqing205** [apache/servicecomb-java-chassis#1813]
1、之前使用的是1.2.1版本的，使用spring-boot-starter-provider启动，
2、现在2.0.0版本修改为java-chassis-spring-boot-starter后
启动报错，提示在maven-compiler-plugin中添加<compilerArgument>-parameters</compilerArgument>
3、完成后，微服务启动，但是cse接口一直提示如下错误

[2020/06/03 19:14:57.041][WARN][new consumer invoke old version producer, parameter(xxxxx) is not exist in contract, method=xxxxx.][org.apache.servicecomb.swagger.invocation.arguments.consumer.ConsumerArgumentsMapperCreator][processUnknownParameter,80][ForkJoinPool.commonPool-worker-1]
[2020/06/03 19:14:57.041][WARN][new consumer invoke old version producer, parameter(xxx) is not exist in contract, method=xxxx.][org.apache.servicecomb.swagger.invocation.arguments.consumer.ConsumerArgumentsMapperCreator][processUnknownParameter,80][ForkJoinPool.commonPool-worker-1]
[2020/06/03 19:14:57.045][INFO][select [org.apache.servicecomb.swagger.generator.pojo.PojoSwaggerGeneratorFactory] for [xxxxxx] to generate schema.][org.apache.servicecomb.swagger.generator.SwaggerGenerator][create,39][ForkJoinPool.commonPool-worker-1]
[2020/06/03 19:14:57.092][ERROR][Parameter is not valid for operation [xxxxxx]. Parameter is [xxxxx]. Processor is [query]. Add servicecomb.codec.printErrorMessage=true to print the details.][org.apache.servicecomb.common.rest.codec.RestCodec][restToArgs,75][group1-2-thread-2]
[2020/06/03 19:14:57.092][ERROR][unknown rest exception.][org.apache.servicecomb.common.rest.AbstractRestInvocation][invoke,221][group1-2-thread-2]
org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=400;msg=CommonExceptionData [message=Parameter is not valid for operation [xxxxx]. Parameter is [xxxx]. Processor is [query].]
	at org.apache.servicecomb.common.rest.codec.RestCodec.restToArgs(RestCodec.java:77) ~[common-rest-2.0.0.jar:2.0.0]
	at org.apache.servicecomb.common.rest.filter.inner.ServerRestArgsFilter.afterReceiveRequest(ServerRestArgsFilter.java:62) ~[common-rest-2.0.0.jar:2.0.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.prepareInvoke(AbstractRestInvocation.java:233) ~[common-rest-2.0.0.jar:2.0.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke(AbstractRestInvocation.java:213) ~[common-rest-2.0.0.jar:2.0.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor(AbstractRestInvocation.java:203) ~[common-rest-2.0.0.jar:2.0.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(AbstractRestInvocation.java:162) ~[common-rest-2.0.0.jar:2.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by liubao68** [comment]
建议按照错误提示先看下是否存在对应的问题。 
1. 警告：`new consumer invoke old version producer, parameter(xxx) is not exist in contract`, 客户端请求的时候，比服务端定义的接口多了参数。 这个通常可以忽略， 如果确实这样， 多余的参数没用，建议修改下；
2. 错误：`Parameter is not valid for operation`， 根据错误提示加上 ` servicecomb.codec.printErrorMessage`把详细错误打印出来，看看具体错误。 或者调试一下 RestCodec 77 行代码，看看具体错误。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
