### ISSUE TITLE
请求服务端接口报 Invoke all server failed

### ISSUE THREAD

**Issue by Fang57** [apache/servicecomb-java-chassis#1849]
Invoke all server failed. Operation CONSUMER rest SLService.SLService.ReceiveNotify, e=cause:InvocationException,message:InvocationException: code=490;msg=CommonExceptionData [message=Cse Internal Bad Request];cause:CseException,message:This is a fallback call from circuit breaker. 
 You can add fallback logic by catching this exception. 
 info: operation=SLService.SLService.ReceiveNotify.;cause:ArithmeticException,message:/ by zero

service CONSUMER rest SLService.SLService.ReceiveNotify, call error, msg is cause:InvocationException,message:InvocationException: code=490;msg=CommonExceptionData [message=Cse Internal Bad Request];cause:CseException,message:This is a fallback call from circuit breaker. 
 You can add fallback logic by catching this exception. 
 info: operation=SLService.SLService.ReceiveNotify.;cause:ArithmeticException,message:/ by zero, server is rest://172.17.14.0:37001

**Comment by liubao68** [comment]
异常是由于 `cause:ArithmeticException,message:/ by zero` 导致的。但是java-chassis没打印完整的堆栈，你能稍微调试下，看看这个异常是什么情况下抛出的吗？

你可以试着临时去掉 handler chain 配置里面的bizkeeper，这个增加了Hystrix的处理，有时候会隐藏原始异常，给定位带来一定麻烦， [说明参考](http://localhost:8000/references-handlers/bizkeeper/)。

**Comment by Fang57** [comment]
handler:
    chain:
      Provider:
        default: qps-flowcontrol-provider
      Consumer:
        default: qps-flowcontrol-consumer,loadbalance
去除bizkeeper-provider与bizkeeper-consumer后，仍然报错490 Cse Internal Bad Request

execution error, msg is cause:ArithmeticException,message:/ by zero

Invoke server failed. Operation CONSUMER rest RTCSLBService.RTCSLBService.ReceiveAmNotify; server rest://172.17.203.4:35001; 0-0 msg cause:ArithmeticException,message:/ by zero

**Comment by yhs0092** [comment]
单看这一点日志无法确认问题原因啊。不过490错误码是Java-Chassis将无法识别的异常包装成490的，Java-Chassis捕获这种异常的时候会在日志里面把原始异常信息打出来的。你在日志文件里面搜一下看看能不能找到原始的错误信息呢？
另外建议你先确认一下490错误码是哪个微服务实例返回的，比如A-》B-》C这样的调用链，C报了一个错，被Java-Chassis包装成490 状态码的`InvocationException`抛出，这个490会沿着调用链返回给B，再返回给A的（不考虑B服务实例有你们自己定义的catch处理逻辑）。所以得先确认最原始的490错误是谁返回的，再去看它的日志。

**Comment by jlynet** [comment]
我也遇到这样的错误了，突然服务就有问题了！调用服务就异常！

**Comment by liubao68** [comment]
估计是做了某些软件包升级，导致服务启动的过程中出现异常了，建议从启动日志看看过程中是不是有什么加载错误，特别是做了netty等三方件升级的情况。

**Comment by jlynet** [comment]
@liubao68 
```
org.apache.servicecomb.core.exception.CseException: This is a fallback call from circuit breaker. 
 You can add fallback logic by catching this exception. 
 info: operation=base.QueryService.getSys.
	at org.apache.servicecomb.bizkeeper.BizkeeperExceptionUtils.createBizkeeperException(BizkeeperExceptionUtils.java:34) ~[handler-bizkeeper-1.2.1.jar:1.2.1]
	at org.apache.servicecomb.bizkeeper.FallbackPolicyManager.getFallbackResponse(FallbackPolicyManager.java:46) ~[handler-bizkeeper-1.2.1.jar:1.2.1]
Caused by: org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=490;msg=CommonExceptionData [message=Cse Internal Bad Request]
	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.doCreate(ExceptionFactory.java:79) ~[swagger-invocation-core-1.2.1.jar:1.2.1]
	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.convertException(ExceptionFactory.java:124) ~[swagger-invocation-core-1.2.1.jar:1.2.1]
	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.convertConsumerException(ExceptionFactory.java:83) ~[swagger-invocation-core-1.2.1.jar:1.2.1]
	at org.apache.servicecomb.swagger.invocation.Response.createConsumerFail(Response.java:129) ~[swagger-invocation-core-1.2.1.jar:1.2.1]
	at org.apache.servicecomb.swagger.invocation.Response.createFail(Response.java:122) ~[swagger-invocation-core-1.2.1.jar:1.2.1]
	... 22 more
Caused by: io.vertx.core.http.impl.HttpClientRequestBase$1: The timeout period of 30000ms has been exceeded while executing POST /QueryService/getSys for host 172.2.2.3
```
大神，这种异常是注册中心引起的还是服务本身引起的啊？

**Comment by jlynet** [comment]
没有做什么升级啊！
我抓了线程包帮看看呗！为什么调用服务还会出现大量的线程阻塞情况啊？
```
Thread 75005: (state = BLOCKED)
 - sun.misc.Unsafe.park(boolean, long) @bci=0 (Compiled frame; information may be imprecise)
 - java.util.concurrent.locks.LockSupport.park(java.lang.Object) @bci=14, line=175 (Compiled frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt() @bci=1, line=836 (Compiled frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(int) @bci=72, line=997 (Compiled frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(int) @bci=24, line=1304 (Compiled frame)
 - java.util.concurrent.CountDownLatch.await() @bci=5, line=231 (Compiled frame)
 - org.apache.servicecomb.core.provider.consumer.SyncResponseExecutor.waitResponse() @bci=4, line=53 (Compiled frame)
 - org.apache.servicecomb.core.provider.consumer.InvokerUtils.innerSyncInvoke(org.apache.servicecomb.core.Invocation) @bci=44, line=75 (Compiled frame)
 - org.apache.servicecomb.provider.pojo.Invoker.syncInvoke(org.apache.servicecomb.core.Invocation, org.apache.servicecomb.swagger.engine.SwaggerConsumerOperation) @bci=1, line=162 (Compiled frame)
 - org.apache.servicecomb.provider.pojo.Invoker.invoke(java.lang.Object, java.lang.reflect.Method, java.lang.Object[]) @bci=189, line=158 (Compiled frame)
 - com.sun.proxy.$Proxy146.getSysDictElementByDictKeyAndEleKey(java.lang.String, java.lang.String) @bci=20 (Compiled frame)
 - com.xxx.xx.support.config.dict.SysDictConfigCache.getSysDictElementValue(java.lang.String, java.lang.String, java.lang.String) @bci=6, line=37 (Compiled frame)
 - com.xxx.xx.support.config.utils.SysConfigHelper.valueOfSysDictEleStaic(java.lang.String, java.lang.String, java.lang.String, java.lang.String) @bci=6, line=181 (Compiled frame)
 - com.xxx.xx.support.config.utils.SysConfigHelper.valueOfSysDictEleStaic(java.lang.String, java.lang.String, java.lang.String) @bci=4, line=210 (Compiled frame)
 - com.xxx.oi.kk.crm.atom.AbstractCRMOI.isSendOiCrmLogToKafKaSwitch(java.lang.String, java.lang.String, java.lang.String) @bci=6, line=162 (Compiled frame)
 - com.xxx.oi.kk.crm.atom.AbstractCRMOI.sendMessageByPost(com.sinovatech.oiclient.model.TOiRequestHead, java.lang.Class) @bci=1527, line=657 (Compiled frame)
 - com.xxx.oi.kk.crm.atom.CRMOIInfoQueryApp.OI_GetUserAllInfo(com.xxx.oiclient.kk.crm.model.infoquery.OIGetUserAllInfoIn) @bci=4, line=38 (Compiled frame)
 - com.xxx.oi.kk.crm.atom.CRMOIInfoQueryApp$$FastClassBySpringCGLIB$$9530b17d.invoke(int, java.lang.Object, java.lang.Object[]) @bci=382 (Compiled frame)
 - org.springframework.cglib.proxy.MethodProxy.invoke(java.lang.Object, java.lang.Object[]) @bci=19, line=218 (Compiled frame)
 - org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint() @bci=19, line=749 (Compiled frame)
 - org.springframework.aop.framework.ReflectiveMethodInvocation.proceed() @bci=19, line=163 (Compiled frame)
 - org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed() @bci=9, line=88 (Compiled frame)
 - com.xxx.oi.kk.ws.interceptorcrm.AsiWsCRMInterceptor.invoke(org.aspectj.lang.ProceedingJoinPoint) @bci=362, line=100 (Compiled frame)
 - sun.reflect.GeneratedMethodAccessor404.invoke(java.lang.Object, java.lang.Object[]) @bci=40 (Compiled frame)
 - sun.reflect.DelegatingMethodAccessorImpl.invoke(java.lang.Object, java.lang.Object[]) @bci=6, line=43 (Compiled frame)
 - java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) @bci=56, line=498 (Compiled frame)
 - org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(java.lang.Object[]) @bci=35, line=644 (Compiled frame)
 - org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(org.aspectj.lang.JoinPoint, org.aspectj.weaver.tools.JoinPointMatch, java.lang.Object, java.lang.Throwable) @bci=10, line=633 (Compiled frame)
 - org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(org.aopalliance.intercept.MethodInvocation) @bci=58, line=70 (Compiled frame)
 - org.springframework.aop.framework.ReflectiveMethodInvocation.proceed() @bci=120, line=186 (Compiled frame)
 - org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(org.aopalliance.intercept.MethodInvocation) @bci=18, line=93 (Compiled frame)
 - org.springframework.aop.framework.ReflectiveMethodInvocation.proceed() @bci=120, line=186 (Compiled frame)
 - org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(java.lang.Object, java.lang.reflect.Method, java.lang.Object[], org.springframework.cglib.proxy.MethodProxy) @bci=133, line=688 (Compiled frame)
 - com.xxx.oi.kk.crm.atom.CRMOIInfoQueryApp$$EnhancerBySpringCGLIB$$8f72ba9d.OI_GetUserAllInfo(com.xxx.oiclient.kk.crm.model.infoquery.OIGetUserAllInfoIn) @bci=36 (Compiled frame)
 - com.xxx.oi.kk.ws.intercrm.CoreCRMInter.query_uacInfo(com.xxx.oiclient.kk.ws.model.infoquery.request.SQueryCond) @bci=41, line=274 (Compiled frame)
 - com.xxx.oi.kk.ws.service.InfoqueryService.queryUacInfo(com.xxx.oiclient.kk.ws.model.infoquery.request.SQueryCond) @bci=5, line=59 (Compiled frame)
 - com.xxx.oi.kk.ws.service.InfoqueryService$$FastClassBySpringCGLIB$$aae96b5b.invoke(int, java.lang.Object, java.lang.Object[]) @bci=144 (Compiled frame)
 - org.springframework.cglib.proxy.MethodProxy.invoke(java.lang.Object, java.lang.Object[]) @bci=19, line=218 (Compiled frame)
 - org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint() @bci=19, line=749 (Compiled frame)
 - org.springframework.aop.framework.ReflectiveMethodInvocation.proceed() @bci=19, line=163 (Compiled frame)
 - org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed() @bci=9, line=88 (Compiled frame)
 - com.xxx.oi.kk.ws.interceptor.ServiceInterceptor.handleInfCache(java.lang.reflect.Method, com.xxxx.oiclient.model.TOiRequestHead, org.aspectj.lang.ProceedingJoinPoint) @bci=145, line=239 (Compiled frame)
 - com.xxx.oi.kk.ws.interceptor.ServiceInterceptor.invoke(org.aspectj.lang.ProceedingJoinPoint) @bci=429, line=185 (Compiled frame)
 - sun.reflect.GeneratedMethodAccessor385.invoke(java.lang.Object, java.lang.Object[]) @bci=40 (Compiled frame)
 - sun.reflect.DelegatingMethodAccessorImpl.invoke(java.lang.Object, java.lang.Object[]) @bci=6, line=43 (Compiled frame)
 - java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) @bci=56, line=498 (Compiled frame)
 - org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(java.lang.Object[]) @bci=35, line=644 (Compiled frame)
 - org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(org.aspectj.lang.JoinPoint, org.aspectj.weaver.tools.JoinPointMatch, java.lang.Object, java.lang.Throwable) @bci=10, line=633 (Compiled frame)
 - org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(org.aopalliance.intercept.MethodInvocation) @bci=58, line=70 (Compiled frame)
 - org.springframework.aop.framework.ReflectiveMethodInvocation.proceed() @bci=120, line=186 (Compiled frame)
 - org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(org.aopalliance.intercept.MethodInvocation) @bci=18, line=93 (Compiled frame)
 - org.springframework.aop.framework.ReflectiveMethodInvocation.proceed() @bci=120, line=186 (Compiled frame)
 - org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(java.lang.Object, java.lang.reflect.Method, java.lang.Object[], org.springframework.cglib.proxy.MethodProxy) @bci=133, line=688 (Compiled frame)
 - com.xxx.oi.kk.ws.service.InfoqueryService$$EnhancerBySpringCGLIB$$8a3902f7.queryUacInfo(com.xxx.oiclient.kk.ws.model.infoquery.request.SQueryCond) @bci=36 (Compiled frame)
 - sun.reflect.GeneratedMethodAccessor1907.invoke(java.lang.Object, java.lang.Object[]) @bci=40 (Interpreted frame)
 - sun.reflect.DelegatingMethodAccessorImpl.invoke(java.lang.Object, java.lang.Object[]) @bci=6, line=43 (Compiled frame)
 - java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) @bci=56, line=498 (Compiled frame)
 - org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.doInvoke(org.apache.servicecomb.swagger.invocation.SwaggerInvocation) @bci=70, line=180 (Compiled frame)
 - org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.syncInvoke(org.apache.servicecomb.swagger.invocation.SwaggerInvocation, org.apache.servicecomb.swagger.invocation.AsyncResponse) @bci=6, line=165 (Compiled frame)
 - org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.invoke(org.apache.servicecomb.swagger.invocation.SwaggerInvocation, org.apache.servicecomb.swagger.invocation.AsyncResponse) @bci=25, line=119 (Compiled frame)
 - org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.handle$original$3ZFkI8Vi(org.apache.servicecomb.core.Invocation, org.apache.servicecomb.swagger.invocation.AsyncResponse) @bci=38, line=40 (Compiled frame)
 - org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.handle$original$3ZFkI8Vi$accessor$fasVilUD(org.apache.servicecomb.core.Invocation, org.apache.servicecomb.swagger.invocation.AsyncResponse) @bci=3 (Compiled frame)
 - org.apache.servicecomb.core.handler.impl.ProducerOperationHandler$auxiliary$mV9cyocE.call() @bci=12 (Compiled frame)
 - org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(java.lang.Object, java.lang.Object[], java.util.concurrent.Callable, java.lang.reflect.Method) @bci=94, line=86 (Compiled frame)
 - org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.handle(org.apache.servicecomb.core.Invocation, org.apache.servicecomb.swagger.invocation.AsyncResponse) @bci=29 (Compiled frame)
 - org.apache.servicecomb.core.Invocation.next(org.apache.servicecomb.swagger.invocation.AsyncResponse) @bci=30, line=204 (Compiled frame)
 - org.apache.servicecomb.common.rest.AbstractRestInvocation.doInvoke() @bci=20, line=243 (Compiled frame)
 - org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke() @bci=16, line=217 (Compiled frame)
 - org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor() @bci=8, line=201 (Compiled frame)
 - org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(org.apache.servicecomb.core.definition.OperationMeta) @bci=67, line=160 (Compiled frame)
 - org.apache.servicecomb.common.rest.AbstractRestInvocation$$Lambda$3621.run() @bci=8 (Compiled frame)
 - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=95, line=1149 (Compiled frame)
 - java.util.concurrent.ThreadPoolExecutor$Worker.run() @bci=5, line=624 (Compiled frame)
 - java.lang.Thread.run() @bci=11, line=748 (Compiled frame)


Thread 75003: (state = BLOCKED)
 - java.util.AbstractCollection.isEmpty() @bci=1, line=86 (Compiled frame)
 - java.util.Collections$UnmodifiableCollection.isEmpty() @bci=4, line=1031 (Compiled frame)
 - java.util.ResourceBundle.checkList(java.util.List) @bci=5, line=1409 (Compiled frame)
 - java.util.ResourceBundle.getBundleImpl(java.lang.String, java.util.Locale, java.lang.ClassLoader, java.util.ResourceBundle$Control) @bci=118, line=1357 (Compiled frame)
 - java.util.ResourceBundle.getBundle(java.lang.String, java.util.Locale, java.util.ResourceBundle$Control) @bci=9, line=899 (Compiled frame)
 - sun.util.resources.LocaleData$1.run() @bci=11, line=167 (Compiled frame)
 - sun.util.resources.LocaleData$1.run() @bci=1, line=163 (Compiled frame)
 - java.security.AccessController.doPrivileged(java.security.PrivilegedAction) @bci=0 (Compiled frame)
 - sun.util.resources.LocaleData.getBundle(java.lang.String, java.util.Locale) @bci=9, line=163 (Compiled frame)
 - sun.util.resources.LocaleData.getDateFormatData(java.util.Locale) @bci=26, line=127 (Compiled frame)
 - java.text.DateFormatSymbols.initializeData(java.util.Locale) @bci=85, line=710 (Compiled frame)
 - java.text.DateFormatSymbols.<init>(java.util.Locale) @bci=69, line=145 (Compiled frame)
 - sun.util.locale.provider.DateFormatSymbolsProviderImpl.getInstance(java.util.Locale) @bci=17, line=85 (Compiled frame)
 - java.text.DateFormatSymbols.getProviderInstance(java.util.Locale) @bci=14, line=364 (Compiled frame)
 - java.text.DateFormatSymbols.getInstanceRef(java.util.Locale) @bci=1, line=354 (Compiled frame)
 - java.text.SimpleDateFormat.<init>(java.lang.String, java.util.Locale) @bci=53, line=603 (Compiled frame)
 - java.text.SimpleDateFormat.<init>(java.lang.String) @bci=8, line=580 (Compiled frame)
 - org.apache.logging.log4j.core.lookup.DateLookup.formatDate(long, java.lang.String) @bci=12, line=64 (Compiled frame)
 - org.apache.logging.log4j.core.lookup.DateLookup.lookup(org.apache.logging.log4j.core.LogEvent, java.lang.String) @bci=20, line=57 (Compiled frame)
 - org.apache.logging.log4j.core.lookup.Interpolator.lookup(org.apache.logging.log4j.core.LogEvent, java.lang.String) @bci=107, line=226 (Compiled frame)
 - org.apache.logging.log4j.core.lookup.StrSubstitutor.resolveVariable(org.apache.logging.log4j.core.LogEvent, java.lang.String, java.lang.StringBuilder, int, int) @bci=17, line=1185 (Compiled frame)
 - org.apache.logging.log4j.core.lookup.StrSubstitutor.substitute(org.apache.logging.log4j.core.LogEvent, java.lang.StringBuilder, int, int, java.util.List) @bci=703, line=1101 (Compiled frame)
 - org.apache.logging.log4j.core.lookup.StrSubstitutor.substitute(org.apache.logging.log4j.core.LogEvent, java.lang.StringBuilder, int, int) @bci=7, line=977 (Compiled frame)
 - org.apache.logging.log4j.core.lookup.StrSubstitutor.replace(org.apache.logging.log4j.core.LogEvent, java.lang.String) @bci=23, line=491 (Compiled frame)
 - org.apache.logging.log4j.core.layout.AbstractJacksonLayout.resolveAdditionalFields(org.apache.logging.log4j.core.LogEvent) @bci=72, line=332 (Compiled frame)
 - org.apache.logging.log4j.core.layout.AbstractJacksonLayout.wrapLogEvent(org.apache.logging.log4j.core.LogEvent) @bci=10, line=311 (Compiled frame)
 - org.apache.logging.log4j.core.layout.AbstractJacksonLayout.toSerializable(org.apache.logging.log4j.core.LogEvent, java.io.Writer) @bci=10, line=344 (Compiled frame)
 - org.apache.logging.log4j.core.layout.JsonLayout.toSerializable(org.apache.logging.log4j.core.LogEvent, java.io.Writer) @bci=26, line=292 (Compiled frame)
 - org.apache.logging.log4j.core.layout.AbstractJacksonLayout.toSerializable(org.apache.logging.log4j.core.LogEvent) @bci=11, line=292 (Compiled frame)
 - org.apache.logging.log4j.core.layout.JsonLayout.toSerializable(org.apache.logging.log4j.core.LogEvent) @bci=2, line=70 (Compiled frame)
 - org.apache.logging.log4j.core.layout.AbstractJacksonLayout.toSerializable(org.apache.logging.log4j.core.LogEvent) @bci=2, line=52 (Compiled frame)
 - org.apache.logging.log4j.core.layout.AbstractStringLayout.toByteArray(org.apache.logging.log4j.core.LogEvent) @bci=3, line=282 (Compiled frame)
 - org.apache.logging.log4j.core.layout.AbstractLayout.encode(org.apache.logging.log4j.core.LogEvent, org.apache.logging.log4j.core.layout.ByteBufferDestination) @bci=2, line=209 (Compiled frame)
 - org.apache.logging.log4j.core.layout.AbstractLayout.encode(java.lang.Object, org.apache.logging.log4j.core.layout.ByteBufferDestination) @bci=6, line=37 (Compiled frame)
 - org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(org.apache.logging.log4j.core.LogEvent) @bci=9, line=197 (Compiled frame)
 - org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(org.apache.logging.log4j.core.LogEvent) @bci=8, line=190 (Compiled frame)
 - org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(org.apache.logging.log4j.core.LogEvent) @bci=2, line=181 (Compiled frame)
 - org.apache.logging.log4j.core.appender.RollingFileAppender.append(org.apache.logging.log4j.core.LogEvent) @bci=13, line=312 (Compiled frame)
 - org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(org.apache.logging.log4j.core.LogEvent) @bci=5, line=161 (Compiled frame)
 - org.apache.logging.log4j.core.config.AppenderControl.callAppender0(org.apache.logging.log4j.core.LogEvent) @bci=14, line=134 (Compiled frame)
 - org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(org.apache.logging.log4j.core.LogEvent) @bci=10, line=125 (Compiled frame)
 - org.apache.logging.log4j.core.config.AppenderControl.callAppender(org.apache.logging.log4j.core.LogEvent) @bci=11, line=89 (Compiled frame)
 - org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(org.apache.logging.log4j.core.LogEvent) @bci=20, line=542 (Compiled frame)
 - org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(org.apache.logging.log4j.core.LogEvent, org.apache.logging.log4j.core.config.LoggerConfig$LoggerConfigPredicate) @bci=20, line=500 (Compiled frame)
 - org.apache.logging.log4j.core.config.LoggerConfig.log(org.apache.logging.log4j.core.LogEvent, org.apache.logging.log4j.core.config.LoggerConfig$LoggerConfigPredicate) @bci=11, line=483 (Compiled frame)
 - org.apache.logging.log4j.core.config.LoggerConfig.log(java.lang.String, java.lang.String, java.lang.StackTraceElement, org.apache.logging.log4j.Marker, org.apache.logging.log4j.Level, org.apache.logging.log4j.message.Message, java.lang.Throwable) @bci=46, line=417 (Compiled frame)
 - org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(org.apache.logging.log4j.util.Supplier, java.lang.String, java.lang.String, java.lang.StackTraceElement, org.apache.logging.log4j.Marker, org.apache.logging.log4j.Level, org.apache.logging.log4j.message.Message, java.lang.Throwable) @bci=21, line=82 (Compiled frame)
 - org.apache.logging.log4j.core.Logger.log(org.apache.logging.log4j.Level, org.apache.logging.log4j.Marker, java.lang.String, java.lang.StackTraceElement, org.apache.logging.log4j.message.Message, java.lang.Throwable) @bci=39, line=161 (Compiled frame)
 - org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(java.lang.String, java.lang.StackTraceElement, org.apache.logging.log4j.Level, org.apache.logging.log4j.Marker, org.apache.logging.log4j.message.Message, java.lang.Throwable) @bci=10, line=2205 (Compiled frame)
 - org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(java.lang.String, org.apache.logging.log4j.Level, org.apache.logging.log4j.Marker, org.apache.logging.log4j.message.Message, java.lang.Throwable) @bci=16, line=2159 (Compiled frame)
 - org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(java.lang.String, org.apache.logging.log4j.Level, org.apache.logging.log4j.Marker, org.apache.logging.log4j.message.Message, java.lang.Throwable) @bci=8, line=2142 (Compiled frame)
 - org.apache.logging.log4j.spi.AbstractLogger.logMessage(java.lang.String, org.apache.logging.log4j.Level, org.apache.logging.log4j.Marker, java.lang.String, java.lang.Object[]) @bci=28, line=2028 (Compiled frame)
 - org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(java.lang.String, org.apache.logging.log4j.Level, org.apache.logging.log4j.Marker, java.lang.String, java.lang.Object[]) @bci=21, line=1891 (Compiled frame)
 - org.apache.logging.log4j.spi.AbstractLogger.info(java.lang.String, java.lang.Object[]) @bci=10, line=1325 (Compiled frame)
 - com.xxx.oi.kk.ws.interceptor.ServiceInterceptor.invoke(org.aspectj.lang.ProceedingJoinPoint) @bci=592, line=208 (Compiled frame)
 - sun.reflect.GeneratedMethodAccessor385.invoke(java.lang.Object, java.lang.Object[]) @bci=40 (Compiled frame)
 - sun.reflect.DelegatingMethodAccessorImpl.invoke(java.lang.Object, java.lang.Object[]) @bci=6, line=43 (Compiled frame)
 - java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) @bci=56, line=498 (Compiled frame)
 - org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(java.lang.Object[]) @bci=35, line=644 (Compiled frame)
 - org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(org.aspectj.lang.JoinPoint, org.aspectj.weaver.tools.JoinPointMatch, java.lang.Object, java.lang.Throwable) @bci=10, line=633 (Compiled frame)
 - org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(org.aopalliance.intercept.MethodInvocation) @bci=58, line=70 (Compiled frame)
 - org.springframework.aop.framework.ReflectiveMethodInvocation.proceed() @bci=120, line=186 (Compiled frame)
 - org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(org.aopalliance.intercept.MethodInvocation) @bci=18, line=93 (Compiled frame)
 - org.springframework.aop.framework.ReflectiveMethodInvocation.proceed() @bci=120, line=186 (Compiled frame)
 - org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(java.lang.Object, java.lang.reflect.Method, java.lang.Object[], org.springframework.cglib.proxy.MethodProxy) @bci=133, line=688 (Compiled frame)
 - com.xxx.oi.kk.ws.service.InfoqueryService$$EnhancerBySpringCGLIB$$8a3902f7.queryUserInfo(com.xxx.oiclient.kk.ws.model.QueryParamIn) @bci=36 (Compiled frame)
 - sun.reflect.GeneratedMethodAccessor726.invoke(java.lang.Object, java.lang.Object[]) @bci=40 (Compiled frame)
 - sun.reflect.DelegatingMethodAccessorImpl.invoke(java.lang.Object, java.lang.Object[]) @bci=6, line=43 (Compiled frame)
 - java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) @bci=56, line=498 (Compiled frame)
 - org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.doInvoke(org.apache.servicecomb.swagger.invocation.SwaggerInvocation) @bci=70, line=180 (Compiled frame)
 - org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.syncInvoke(org.apache.servicecomb.swagger.invocation.SwaggerInvocation, org.apache.servicecomb.swagger.invocation.AsyncResponse) @bci=6, line=165 (Compiled frame)
 - org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.invoke(org.apache.servicecomb.swagger.invocation.SwaggerInvocation, org.apache.servicecomb.swagger.invocation.AsyncResponse) @bci=25, line=119 (Compiled frame)
 - org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.handle$original$3ZFkI8Vi(org.apache.servicecomb.core.Invocation, org.apache.servicecomb.swagger.invocation.AsyncResponse) @bci=38, line=40 (Compiled frame)
 - org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.handle$original$3ZFkI8Vi$accessor$fasVilUD(org.apache.servicecomb.core.Invocation, org.apache.servicecomb.swagger.invocation.AsyncResponse) @bci=3 (Compiled frame)
 - org.apache.servicecomb.core.handler.impl.ProducerOperationHandler$auxiliary$mV9cyocE.call() @bci=12 (Compiled frame)
 - org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(java.lang.Object, java.lang.Object[], java.util.concurrent.Callable, java.lang.reflect.Method) @bci=94, line=86 (Compiled frame)
 - org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.handle(org.apache.servicecomb.core.Invocation, org.apache.servicecomb.swagger.invocation.AsyncResponse) @bci=29 (Compiled frame)
 - org.apache.servicecomb.core.Invocation.next(org.apache.servicecomb.swagger.invocation.AsyncResponse) @bci=30, line=204 (Compiled frame)
 - org.apache.servicecomb.common.rest.AbstractRestInvocation.doInvoke() @bci=20, line=243 (Compiled frame)
 - org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke() @bci=16, line=217 (Compiled frame)
 - org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor() @bci=8, line=201 (Compiled frame)
 - org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(org.apache.servicecomb.core.definition.OperationMeta) @bci=67, line=160 (Compiled frame)
 - org.apache.servicecomb.common.rest.AbstractRestInvocation$$Lambda$3621.run() @bci=8 (Compiled frame)
 - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=95, line=1149 (Compiled frame)
 - java.util.concurrent.ThreadPoolExecutor$Worker.run() @bci=5, line=624 (Compiled frame)
 - java.lang.Thread.run() @bci=11, line=748 (Compiled frame)
```

**Comment by liubao68** [comment]
@jlynet  你的问题看起来是请求超时。 即服务端处理时间太长， 建议按照  https://servicecomb.apache.org/references/java-chassis/zh_CN/featured-topics/performance.html  打开每个服务的metrics日志先分析下。 

如果你发现有什么问题或者疑问，可以创建一个新的issue. 你的问题看起来和这个issue没有直接关系。

**Comment by liubao68** [comment]
Close too old issue.

**Comment by jlynet** [comment]
我看了服务端日志，没有到服务端内部方法。追踪平台提示已经调用了。可是没见有日志

**Comment by jlynet** [comment]
启动新服务的时候，旧服务所在的主机cpu 突然拉的特别高
