### ISSUE TITLE
edgeService 2.0.2 增加允许公共请求头后 鉴权功能 报空指针错误

### ISSUE THREAD

**Issue by andrelive** [apache/servicecomb-java-chassis#1871]
追踪了一下源代码，问题出在 EdgeAddHeaderClientFilter 第63行，再追踪进去是 Invocation 这个类的 initTraceId 方法，被迭代调用最后一次时，this.requestEx 变成了 null ……
求解答到底是咋回事……我看了一下，第二次的requestEx 好像是 
CompletableFuture<String> completableFuture = auth.auth("info"); // 示例代码
导致的。
鉴权通信信道采用的是rest on vert.x。如果采用highway就没问题。
求解为什么在handler中requestEx回成为null导致空指针异常？是否是handler和EdgeAddHeaderClientFilter 之间存在冲突？

另外，似乎edge的一些逻辑是有问题的，从edge handler发出去的请求如果是配置了需要经过某个handler，似乎会导致死循环？

**Comment by andrelive** [comment]
另外，我看到华为论坛上说在2.x之后的版本edge 配置 servicecomb.references.[microserviceName].transport: highway 是能够正常生效的。
但是，经过实测，并不能生效，还是只能通过
servicecomb:
  operation:
    [serviceName]:
      [schema]:
        [method]:
          transport: highway
来进行配置。
但各文档都没找到对应的描述

**Comment by liubao68** [comment]
可以看下 `OperationConfig` 类， 配置规则如下：

```
  @InjectProperty(keys = {
      "operation${op-priority}.transport", // Deprecated
      "references.transport${op-priority}"
  })
  private String transport;
```

即：

```
servicecomb:
  references:
    transport: 
      [serviceName].[schemaId].[operationId]: rest
```

**Comment by liubao68** [comment]
`从edge handler发出去的请求如果是配置了需要经过某个handler，似乎会导致死循环` 应该不会的。但是需要注意，如果在 handler 中调用其他服务， 这个调用会继续走 handler， 看起来会循环调用的样子。 不知道你是不是这种情况， 以前开发的时候，总是碰到类似情况，调试的时候感觉很困惑，实际是某些代码写错了。

**Comment by andrelive** [comment]
> `从edge handler发出去的请求如果是配置了需要经过某个handler，似乎会导致死循环` 应该不会的。但是需要注意，如果在 handler 中调用其他服务， 这个调用会继续走 handler， 看起来会循环调用的样子。 不知道你是不是这种情况， 以前开发的时候，总是碰到类似情况，调试的时候感觉很困惑，实际是某些代码写错了。补充说明下，看你的代码，和 java-chassis的 demo-edge 很像， 你也可以参考下这个demo代码。

没错，就是这种现象，所以我想，中间鉴权的handler调用某个请求，能否不再经过handler？因为这不是在转发请求。
一直经过handler感觉逻辑上很奇怪。

另外，这没办法解决第一个问题，就是在允许保留请求头的情况下，edge handler如果依赖调用走rest通信的话，会报空指针错误。除非我换成highway去调用。
这个问题能否有解？感觉edge在这些地方的处理逻辑都……嗯，就像错用了单例模式一样（只是比喻）。
如果跟本身的设计理念冲突，是否可以在开发文档上标明？

**Comment by liubao68** [comment]
"edge本身发起的调用我们认为是可信的，不需要经过鉴权等一系列处理。一直经过handler感觉逻辑上很奇怪。", 不完全是鉴权，所有的client调用server,都会经过Handler， 因为负载均衡， 服务治理等都是在Handler处理的，现在恰好鉴权的逻辑在Handler上实现而已。 如果信任edge转发的请求， 可以在发起前给InvocationContext写入一个header， 告诉鉴权的handler，跳过鉴权即可。 

"这没办法解决第一个问题，就是在允许保留请求头的情况下，edge handler如果依赖调用走rest通信的话，会报空指针错误。除非我换成highway去调用。"  正常情况不应该有这个问题， 不知道会不是哪里配置错误了，或者由于前面的问题影响的。 如果方便的话，帮忙提供下错误堆栈，或者共享下demo， 我们测试下，看看是什么问题。

**Comment by andrelive** [comment]
> 2020-07-10 16:25:48.132 ERROR [vert.x-eventloop-thread-4] o.a.s.t.r.client.RestTransportClient:54 - vertx rest transport send error.
java.lang.NullPointerException: null
	at org.apache.servicecomb.edge.core.EdgeAddHeaderClientFilter.lambda$beforeSendRequest$1(EdgeAddHeaderClientFilter.java:80)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at org.apache.servicecomb.edge.core.EdgeAddHeaderClientFilter.beforeSendRequest(EdgeAddHeaderClientFilter.java:79)
	at org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.invoke(RestClientInvocation.java:112)
	at org.apache.servicecomb.transport.rest.client.RestTransportClient.send(RestTransportClient.java:51)
	at org.apache.servicecomb.transport.rest.vertx.VertxRestTransport.send(VertxRestTransport.java:84)
	at org.apache.servicecomb.core.handler.impl.TransportClientHandler.handle(TransportClientHandler.java:42)
	at org.apache.servicecomb.core.Invocation.next(Invocation.java:292)
	at org.apache.servicecomb.loadbalance.LoadbalanceHandler.send(LoadbalanceHandler.java:269)
	at org.apache.servicecomb.loadbalance.LoadbalanceHandler.handle(LoadbalanceHandler.java:222)
	at org.apache.servicecomb.core.Invocation.next(Invocation.java:292)
	at org.apache.servicecomb.core.provider.consumer.InvokerUtils.reactiveInvoke(InvokerUtils.java:171)
	at org.apache.servicecomb.provider.pojo.Invoker.completableFutureInvoke(Invoker.java:213)
	at org.apache.servicecomb.provider.pojo.Invoker.invoke(Invoker.java:182)
	at com.sun.proxy.$Proxy83.authTest(Unknown Source)
	at com.ikaiyong.lawes.handler.AuthHandler.handle(AuthHandler.java:49)
	at org.apache.servicecomb.core.Invocation.next(Invocation.java:292)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.doInvoke(AbstractRestInvocation.java:247)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke(AbstractRestInvocation.java:221)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor(AbstractRestInvocation.java:205)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(AbstractRestInvocation.java:164)
	at org.apache.servicecomb.core.executor.ReactiveExecutor.execute(ReactiveExecutor.java:30)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.scheduleInvocation(AbstractRestInvocation.java:149)
	at org.apache.servicecomb.edge.core.EdgeInvocation.edgeInvoke(EdgeInvocation.java:65)
	at org.apache.servicecomb.edge.core.URLMappedEdgeDispatcher.onRequest(URLMappedEdgeDispatcher.java:121)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:986)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:95)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
	at org.apache.servicecomb.transport.rest.vertx.RestBodyHandler$BHandler.doEnd(RestBodyHandler.java:343)
	at org.apache.servicecomb.transport.rest.vertx.RestBodyHandler$BHandler.end(RestBodyHandler.java:324)
	at org.apache.servicecomb.transport.rest.vertx.RestBodyHandler.lambda$handle$0(RestBodyHandler.java:115)
	at io.vertx.core.http.impl.HttpServerRequestImpl.onEnd(HttpServerRequestImpl.java:530)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:516)
	at io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServerConnection.java:176)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:138)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by liubao68** [comment]
初步看了下代码， 像是 bug, 我联系功能开发者看看。感觉使用 httpclientfilter 的方式实现增加请求头，是不正确的。

**Comment by heyile** [comment]
@andrelive  有没有直接复现问题的用例。可以给一个 github url 地址。 我去测试一把。

**Comment by heyile** [comment]
可以参考这个，在本地试下问题还有没有  #1881  @andrelive

**Comment by liubao68** [comment]
fixed in 2.1.1
