### ISSUE TITLE
基于tomact的微服务集成CSE报servicecomb的子类未实例化bean

### ISSUE THREAD

**Issue by dbwdbw1** [apache/servicecomb-java-chassis#1886]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.apache.servicecomb.bizkeeper.BeansHolder#0': Unsatisfied dependency expressed through field 'policies'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.List<org.apache.servicecomb.bizkeeper.FallbackPolicy>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@javax.inject.Inject()}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)

**Comment by yhs0092** [comment]
看日志是`FallbackPolicy`类型的Spring Bean没有被加载。Java-Chassis提供了`ReturnNullFallbackPolicy`、`ThrowExceptionFallbackPolicy`、`FromCacheFallbackPolicy`，都打上了`Component`注解，得检查一下为啥它们没有加载。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
