### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.servicecomb.foundation.common.utils.ReflectUtils.getClassByName(Ljava/lang/String;)Ljava/lang/Class;

### ISSUE THREAD

**Issue by richard1230** [apache/servicecomb-java-chassis#1931]
Hello, I am the starter with servicecomb 2.0.0.
When I use the sample(https://docs.servicecomb.io/java-chassis/zh_CN/start/first-sample/) to learn , I found an error .
the steps to reproduce the error:
https://github.com/richard1230/helloService/blob/master/src/main/java/com/github/AppMain.java
when run the AppMain.java，the error is as follows:
```
10:32:10.707 [main] INFO  org.apache.servicecomb.foundation.common.utils.JvmUtils[94] - Found main class "com.github.AppMain".
10:32:10.717 [main] INFO  org.apache.servicecomb.foundation.common.utils.JvmUtils[63] - Found main class "com.github.AppMain" by stackTrace.
10:32:10.722 [main] INFO  org.apache.servicecomb.foundation.common.utils.BeanUtils[93] - Scb scan package list: org.apache.servicecomb,com.github
10:32:11.778 [main] INFO  org.apache.servicecomb.config.ConfigurationSpringInitializer[80] - Environment received, will get configurations from [org.springframework.core.env.StandardEnvironment@405950359].
10:32:11.810 [main] WARN  com.netflix.config.sources.URLConfigurationSource[121] - No URLs will be polled as dynamic configuration sources.
10:32:11.810 [main] INFO  com.netflix.config.sources.URLConfigurationSource[122] - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
10:32:11.885 [main] INFO  org.apache.servicecomb.config.ConfigUtil[118] - create local config:
10:32:11.885 [main] INFO  org.apache.servicecomb.config.ConfigUtil[120] -  jar:file:/Users/mac/.m2/repository/org/apache/servicecomb/java-chassis-core/2.0.0/java-chassis-core-2.0.0.jar!/microservice.yaml.
10:32:11.885 [main] INFO  org.apache.servicecomb.config.ConfigUtil[120] -  jar:file:/Users/mac/.m2/repository/org/apache/servicecomb/solution-basic/2.0.0/solution-basic-2.0.0.jar!/microservice.yaml.
10:32:11.885 [main] INFO  org.apache.servicecomb.config.ConfigUtil[120] -  file:/Users/mac/IdeaProjects/HelloWorldService/target/classes/microservice.yaml.
10:32:11.910 [main] INFO  org.apache.servicecomb.foundation.common.utils.SPIServiceUtils[79] - Found SPI service org.apache.servicecomb.config.spi.ConfigCenterConfigurationSource, count=0.
10:32:11.910 [main] INFO  org.apache.servicecomb.foundation.common.utils.SPIServiceUtils[110] - Can not find SPI service for org.apache.servicecomb.config.spi.ConfigCenterConfigurationSource
10:32:11.911 [main] INFO  org.apache.servicecomb.config.ConfigUtil[211] - config center SPI service can not find, skip to load configuration from config center
10:32:11.922 [main] INFO  org.apache.servicecomb.foundation.common.utils.SPIServiceUtils[110] - Can not find SPI service for org.apache.servicecomb.config.spi.ConfigCenterConfigurationSource
10:32:11.926 [main] INFO  org.apache.servicecomb.config.ConfigUtil[118] - create local config:
10:32:11.926 [main] INFO  org.apache.servicecomb.config.ConfigUtil[120] -  jar:file:/Users/mac/.m2/repository/org/apache/servicecomb/java-chassis-core/2.0.0/java-chassis-core-2.0.0.jar!/microservice.yaml.
10:32:11.926 [main] INFO  org.apache.servicecomb.config.ConfigUtil[120] -  jar:file:/Users/mac/.m2/repository/org/apache/servicecomb/solution-basic/2.0.0/solution-basic-2.0.0.jar!/microservice.yaml.
10:32:11.927 [main] INFO  org.apache.servicecomb.config.ConfigUtil[120] -  file:/Users/mac/IdeaProjects/HelloWorldService/target/classes/microservice.yaml.
10:32:11.940 [main] WARN  org.springframework.context.support.ClassPathXmlApplicationContext[557] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'restProducers' defined in URL [jar:file:/Users/mac/.m2/repository/org/apache/servicecomb/provider-rest-common/2.0.0/provider-rest-common-2.0.0.jar!/org/apache/servicecomb/provider/rest/common/RestProducers.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.servicecomb.provider.rest.common.RestProducers]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: org.apache.servicecomb.foundation.common.utils.ReflectUtils.getClassByName(Ljava/lang/String;)Ljava/lang/Class;
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'restProducers' defined in URL [jar:file:/Users/mac/.m2/repository/org/apache/servicecomb/provider-rest-common/2.0.0/provider-rest-common-2.0.0.jar!/org/apache/servicecomb/provider/rest/common/RestProducers.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.servicecomb.provider.rest.common.RestProducers]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: org.apache.servicecomb.foundation.common.utils.ReflectUtils.getClassByName(Ljava/lang/String;)Ljava/lang/Class;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1181)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:240)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:721)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:534)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:95)
	at org.apache.servicecomb.foundation.common.utils.BeanUtils.init(BeanUtils.java:54)
	at org.apache.servicecomb.foundation.common.utils.BeanUtils.init(BeanUtils.java:47)
	at com.github.AppMain.main(AppMain.java:7)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.servicecomb.provider.rest.common.RestProducers]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: org.apache.servicecomb.foundation.common.utils.ReflectUtils.getClassByName(Ljava/lang/String;)Ljava/lang/Class;
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:184)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1279)
	... 15 more
Caused by: java.lang.NoSuchMethodError: org.apache.servicecomb.foundation.common.utils.ReflectUtils.getClassByName(Ljava/lang/String;)Ljava/lang/Class;
	at org.apache.servicecomb.provider.rest.common.RestProducers.<init>(RestProducers.java:39)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)
	... 17 more
```

**Comment by liubao68** [comment]
After execute `mvn dependency:tree` , you can find some dependencies error:

```
[INFO] |  \- com.huawei.paas.cse:foundation-auth:jar:2.5.0:compile
[INFO] |     +- org.apache.servicecomb:foundation-common:jar:1.3.0:compile
[INFO] |     |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.9.8:compile
[INFO] |     |  |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.9.8:compile
[INFO] |     |  |  +- org.codehaus.woodstox:stax2-api:jar:3.1.4:compile
[INFO] |     |  |  \- com.fasterxml.woodstox:woodstox-core:jar:5.0.3:compile
[INFO] |     |  +- log4j:log4j:jar:1.2.17:compile
[INFO] |     |  +- org.apache.httpcomponents:httpclient:jar:4.5.7:compile
[INFO] |     |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.11:compile
[INFO] |     |  +- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[INFO] |     |  \- javax.servlet:javax.servlet-api:jar:4.0.1:compile
[INFO] |     +- org.apache.servicecomb:foundation-ssl:jar:1.3.0:compile
[INFO] |     |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.22.Final:compile
[INFO] |     +- commons-io:commons-io:jar:2.6:compile
[INFO] |     \- org.apache.servicecomb:foundation-config:jar:1.3.0:compile
[INFO] |        +- io.netty:netty-codec:jar:4.1.31.Final:compile
[INFO] |        +- io.netty:netty-codec-http:jar:4.1.31.Final:compile
[INFO] |        +- io.netty:netty-codec-http2:jar:4.1.31.Final:compile
[INFO] |        +- io.netty:netty-common:jar:4.1.31.Final:compile
[INFO] |        +- io.netty:netty-handler:jar:4.1.31.Final:compile
[INFO] |        +- io.netty:netty-buffer:jar:4.1.31.Final:compile
[INFO] |        +- io.netty:netty-codec-socks:jar:4.1.31.Final:compile
[INFO] |        +- io.netty:netty-handler-proxy:jar:4.1.31.Final:compile
[INFO] |        +- io.netty:netty-resolver:jar:4.1.31.Final:compile
[INFO] |        \- io.netty:netty-transport:jar:4.1.31.Final:compile
[INFO] \- org.apache.servicecomb:java-chassis-dependencies:pom:2.0.0:compile
```

old versions of servicecomb included. 


This is because solution-basic include foundation-auth and which dependencies old version of servicecomb and cause error. 


It is recommened you use dependency management to manage dependency and this will not heppen. The servicecomb-samplse is correct and changed it .

For more informanction, please read [使用maven管理复杂依赖关系的技巧](http://servicecomb.apache.org/cn/docs/maven_dependency_management/)


BTW, foudnation-auth is removed from solutioin-basic, you can also try 2.0.1 or higher version.

**Comment by richard1230** [comment]
@liubao68
There is a [dead link](https://github.com/apache/servicecomb-java-chassis/blob/master/java-chassis-dependencies/pom.xml) in http://servicecomb.apache.org/cn/docs/maven_dependency_management/;
Now I use dependency management to manage dependency; now the pom.xml is as follows:
```

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>HelloWorldService</artifactId>
    <version>1.0-SNAPSHOT</version>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <compilerArgument>-parameters</compilerArgument>
                    <encoding>UTF-8</encoding>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.servicecomb</groupId>
                <artifactId>java-chassis-dependencies</artifactId>
                <version>${java-chassis-dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <!-- https://mvnrepository.com/artifact/org.apache.servicecomb/solution-basic -->
        <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>solution-basic</artifactId>
<!--            <version>2.0.0</version>-->
        </dependency>
    </dependencies>

</project>
```
But build is failing, the error is:
```
Cannot resolve org.apache.servicecomb:solution-basic:unknown
```
the steps to reproduce the error:
https://github.com/richard1230/helloService

**Comment by liubao68** [comment]
missed to specify value of `${java-chassis-dependencies.version}`

I checked the link is working. Maybe you met some network problems.

**Comment by richard1230** [comment]
@liubao68
the question above is resoved，but a new issue is coming:
after I using the command `docker run -d -p 30100:30100 servicecomb/service-center`; I  run Appmain class；I can't see the instance record of the helloworld service，my page is as follows:
![image](https://user-images.githubusercontent.com/20439699/91272913-12449900-e7af-11ea-812c-bb9676c58d2d.png)

![image](https://user-images.githubusercontent.com/20439699/91272993-2a1c1d00-e7af-11ea-9538-008426be0e93.png)
the steps to reproduce the error:
https://github.com/richard1230/helloService

**Comment by liubao68** [comment]
I guess servicecomb/service-center do not provide a front end. service center provide a front end that listens 30103.

**Comment by richard1230** [comment]
I am afraid that the result may not be what you think: 30103 is invalid
![image](https://user-images.githubusercontent.com/20439699/91780806-2e22c180-ec2b-11ea-9584-f67955e4210f.png)

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
