### ISSUE TITLE
边缘服务上传文件偶尔490，报错：inputStream is closed

### ISSUE THREAD

**Issue by xhanthow** [apache/servicecomb-java-chassis#1950]
```
Caused by: java.lang.IllegalStateException: inputStream is closed
	at org.apache.servicecomb.foundation.vertx.stream.InputStreamToReadStream.check(InputStreamToReadStream.java:75)
	at org.apache.servicecomb.foundation.vertx.stream.InputStreamToReadStream.resume(InputStreamToReadStream.java:167)
	at org.apache.servicecomb.foundation.vertx.stream.InputStreamToReadStream.resume(InputStreamToReadStream.java:35)
	at io.vertx.core.streams.impl.PumpImpl.lambda$new$0(PumpImpl.java:42)
	at io.vertx.core.http.impl.HttpClientRequestImpl.handleDrained(HttpClientRequestImpl.java:336)
	... 104 common frames omitted
```
之前参考过这个[issue](https://github.com/eclipse-vertx/vert.x/issues/3062)改过，但是现在还是偶现这个问题，请问下可能是哪方面的问题了？

**Comment by xhanthow** [comment]
完整日志：
```
2020-09-11 16:19:21.505 [vert.x-eventloop-thread-7] WARN  - [BizkeeperCommand.java:lambda$null$1:82] - [654e1332-f5f7-4318-9e48-f05fcd3bedb5] - bizkeeper command CONSUMER rest xxxxx.file-upload.uploadFile failed due to {}
org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=490;msg=CommonExceptionData [message=Cse Internal Bad Request]
        at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.doCreate(ExceptionFactory.java:79)
        at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.convertException(ExceptionFactory.java:124)
        at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.convertConsumerException(ExceptionFactory.java:83)
        at org.apache.servicecomb.swagger.invocation.Response.createConsumerFail(Response.java:129)
        at org.apache.servicecomb.swagger.invocation.Response.createFail(Response.java:122)
        at org.apache.servicecomb.swagger.invocation.AsyncResponse.fail(AsyncResponse.java:42)
        at org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.fail(RestClientInvocation.java:281)
        at org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.lambda$new$0(RestClientInvocation.java:80)
        at org.apache.servicecomb.foundation.vertx.stream.PumpCommon.lambda$pump$0(PumpCommon.java:60)
        at io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:132)
        at io.vertx.core.http.impl.HttpClientRequestImpl.handleException(HttpClientRequestImpl.java:369)
        at io.vertx.core.http.impl.HttpClientRequestImpl.handleDrained(HttpClientRequestImpl.java:338)
        at io.vertx.core.http.impl.Http1xClientConnection.handleInterestedOpsChanged(Http1xClientConnection.java:767)
        at io.vertx.core.net.impl.VertxHandler.lambda$channelWritabilityChanged$2(VertxHandler.java:134)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:224)
        at io.vertx.core.net.impl.VertxHandler.channelWritabilityChanged(VertxHandler.java:134)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:441)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:428)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:421)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelWritabilityChanged(CombinedChannelDuplexHandler.java:448)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:129)
        at io.netty.channel.CombinedChannelDuplexHandler.channelWritabilityChanged(CombinedChannelDuplexHandler.java:271)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:441)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:428)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:421)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelWritabilityChanged(DefaultChannelPipeline.java:1433)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:441)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:428)
        at io.netty.channel.DefaultChannelPipeline.fireChannelWritabilityChanged(DefaultChannelPipeline.java:931)
        at io.netty.channel.ChannelOutboundBuffer.fireChannelWritabilityChanged(ChannelOutboundBuffer.java:628)
        at io.netty.channel.ChannelOutboundBuffer.setWritable(ChannelOutboundBuffer.java:594)
        at io.netty.channel.ChannelOutboundBuffer.decrementPendingOutboundBytes(ChannelOutboundBuffer.java:196)
        at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:273)
        at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:352)
        at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:431)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:930)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:897)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
        at io.netty.handler.ssl.SslHandler.forceFlush(SslHandler.java:2040)
        at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:796)
        at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:773)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:531)
        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125)
        at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
        at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:119)
        at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:161)
        at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.sendRequest(Http1xClientConnection.java:308)
        at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.writeHead(Http1xClientConnection.java:255)
        at io.vertx.core.http.impl.HttpClientRequestImpl.connected(HttpClientRequestImpl.java:502)
        at io.vertx.core.http.impl.HttpClientRequestImpl.lambda$null$5(HttpClientRequestImpl.java:465)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:224)
        at io.vertx.core.http.impl.HttpClientRequestImpl.lambda$connect$7(HttpClientRequestImpl.java:464)
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:126)
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:87)
        at io.vertx.core.http.impl.Http1xClientConnection.createStream(Http1xClientConnection.java:833)
        at io.vertx.core.http.impl.HttpClientImpl.lambda$getConnectionForRequest$4(HttpClientImpl.java:1041)
        at io.vertx.core.http.impl.ConnectionManager.lambda$getConnection$7(ConnectionManager.java:154)
        at io.vertx.core.http.impl.pool.Pool.connectSucceeded(Pool.java:366)
        at io.vertx.core.http.impl.pool.Pool.access$500(Pool.java:88)
        at io.vertx.core.http.impl.pool.Pool$Holder.lambda$connect$0(Pool.java:128)
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:126)
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:87)
        at io.vertx.core.http.impl.HttpChannelConnector.lambda$http1xConnected$3(HttpChannelConnector.java:222)
        at io.vertx.core.net.impl.VertxHandler.setConnection(VertxHandler.java:85)
        at io.vertx.core.net.impl.VertxHandler.handlerAdded(VertxHandler.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:971)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:223)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:195)
        at io.vertx.core.http.impl.HttpChannelConnector.http1xConnected(HttpChannelConnector.java:228)
        at io.vertx.core.http.impl.HttpChannelConnector.lambda$doConnect$0(HttpChannelConnector.java:144)
        at io.vertx.core.net.impl.ChannelProvider.lambda$connect$1(ChannelProvider.java:78)
        at io.vertx.core.net.impl.ChannelProvider$1.userEventTriggered(ChannelProvider.java:107)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
        at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
        at io.netty.handler.ssl.SslHandler.setHandshakeSuccess(SslHandler.java:1761)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1420)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1282)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: inputStream is closed
        at org.apache.servicecomb.foundation.vertx.stream.InputStreamToReadStream.check(InputStreamToReadStream.java:75)
        at org.apache.servicecomb.foundation.vertx.stream.InputStreamToReadStream.resume(InputStreamToReadStream.java:167)
        at org.apache.servicecomb.foundation.vertx.stream.InputStreamToReadStream.resume(InputStreamToReadStream.java:35)
        at io.vertx.core.streams.impl.PumpImpl.lambda$new$0(PumpImpl.java:42)
        at io.vertx.core.http.impl.HttpClientRequestImpl.handleDrained(HttpClientRequestImpl.java:336)
        ... 104 common frames omitted
```

**Comment by liubao68** [comment]
你能提供一个简单重现 DEMO 吗？

**Comment by xhanthow** [comment]
把自定的`PumpImpl`去掉就好了。。
