### ISSUE TITLE
ServiceComb 2.1版本走highWay协议，报解码错误io.protostuff.ProtobufException: CodedInput encountered an embedded string or bytes that misreported its size

### ISSUE THREAD

**Issue by zhoutianli518** [apache/servicecomb-java-chassis#1973]
用的CSE 3.1.1版本，集成ServiceComb版本为2.1.1。走rest协议没问题，开启highWay后，连续请求的话，会成功一次，失败一次
。成功失败交替出现。失败的情况下，报如下异常。

2020-09-25 11:13:42.159|ERROR|eop|13|172.16.1.43|6876257328093873291|Failed to mergeFrom, field=org.apache.servicecomb.transport.highway.message.RequestHeader.context_entry:context, type=context_entry|org.apache.servicecomb.foundation.protobuf.internal.schema.deserializer.MessageReadSchema
2020-09-25 11:13:42.160|ERROR|eop|13|172.16.1.43|6876257328093873291|decode request header error, msgId=0|org.apache.servicecomb.transport.highway.HighwayServerConnection
io.protostuff.ProtobufException: CodedInput encountered an embedded string or bytes that misreported its size.
	at io.protostuff.ProtobufException.misreportedSize(ProtobufException.java:86)
	at io.protostuff.ByteArrayInputEx.readString(ByteArrayInputEx.java:329)
	at org.apache.servicecomb.foundation.protobuf.internal.schema.deserializer.scalar.StringReadSchemas$StringSchema.mergeFrom(StringReadSchemas.java:59)
	at org.apache.servicecomb.foundation.protobuf.internal.schema.map.MapEntrySchema.mergeFrom(MapEntrySchema.java:55)
	at org.apache.servicecomb.foundation.protobuf.internal.schema.map.MapEntrySchema.mergeFrom(MapEntrySchema.java:30)
	at io.protostuff.ByteArrayInputEx.mergeObject(ByteArrayInputEx.java:378)
	at org.apache.servicecomb.foundation.protobuf.internal.schema.map.MapSchema.mergeFrom(MapSchema.java:59)
	at org.apache.servicecomb.foundation.protobuf.internal.schema.deserializer.MessageReadSchema.mergeFrom(MessageReadSchema.java:159)
	at org.apache.servicecomb.foundation.protobuf.RootDeserializer.deserialize(RootDeserializer.java:44)
	at org.apache.servicecomb.transport.highway.message.RequestHeader.readObject(RequestHeader.java:43)
	at org.apache.servicecomb.transport.highway.HighwayCodec.readRequestHeader(HighwayCodec.java:88)
	at org.apache.servicecomb.transport.highway.HighwayServerConnection.decodeRequestHeader(HighwayServerConnection.java:81)
	at org.apache.servicecomb.transport.highway.HighwayServerConnection.handle(HighwayServerConnection.java:61)
	at org.apache.servicecomb.foundation.vertx.server.TcpParser.onReadOnePackage(TcpParser.java:130)
	at org.apache.servicecomb.foundation.vertx.server.TcpParser.onParse(TcpParser.java:121)
	at io.vertx.core.parsetools.impl.RecordParserImpl.handleParsing(RecordParserImpl.java:214)
	at io.vertx.core.parsetools.impl.RecordParserImpl.handle(RecordParserImpl.java:285)
	at org.apache.servicecomb.foundation.vertx.server.TcpParser.handle(TcpParser.java:137)
	at org.apache.servicecomb.foundation.vertx.server.TcpParser.handle(TcpParser.java:32)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:378)
	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$2(NetSocketImpl.java:100)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:356)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by liubao68** [comment]
能够提供一个重现的简单 DEMO 吗？ 另外， 需要分析下是不是多实例部署（provider/consumer）， 每个实例的版本是否一致。 是不是每个 provider 实例只监听了一个 highway 地址。

**Comment by liuxinpeister** [comment]
我遇到的现象是Response中有List<Long>，然后返回前的赋值是Collections.emptyList()，换成null就好了，Collections.emptyList()会报以上错误

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
