### ISSUE TITLE
支持配置 socks 代理吗?

### ISSUE THREAD

**Issue by huanghezhen** [apache/servicecomb-java-chassis#2001]
### 已经开启了代理 使用 RestTemplate 时是可以正常访问k8s集群内部ip的

```
11:34:42.517 [main] DEBUG org.springframework.web.client.RestTemplate - HTTP GET http://10.100.219.86:8003/healthExamination
11:34:42.526 [main] DEBUG org.springframework.web.client.RestTemplate - Accept=[text/plain, application/xml, text/xml, application/json, application/*+xml, application/*+json, */*]
11:34:42.584 [main] DEBUG org.springframework.web.client.RestTemplate - Response 200 OK
11:34:42.586 [main] DEBUG org.springframework.web.client.RestTemplate - Reading to [java.lang.String] as "application/json;charset=utf-8"
{"status":true,"resultCode":"0000000","logicCode":"000000000","resultMsg":"成功"}
```

### 但是当rpc调用的时候 就报错了

VM:
-DsocksProxyHost=127.0.0.1
-DsocksProxyPort=2223

error:
```
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /10.100.219.86:8003
Caused by: java.net.ConnectException: Connection timed out: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by huanghezhen** [comment]
使用的是 kt connect

**Comment by liubao68** [comment]
目前不支持 socks 代理。 java-chassis的HttpClient是一个简单的 request-response 实现， 不是通常的 WebClient （即能够处理常见的HTTP状态，比如重定向等）

**Comment by huanghezhen** [comment]
对于 想打通到 k8s内部网络 有好的建议吗

**Comment by huanghezhen** [comment]
使用vpn解决啦!
