### ISSUE TITLE
controller中定义一个接口提示java.lang.NoSuchMethodError: io.swagger.annotations.ApiParam.type()Ljava/lang/String

### ISSUE THREAD

**Issue by liushuai-monster** [apache/servicecomb-java-chassis#2114]
Caused by: java.lang.IllegalStateException: generate swagger operation failed, method=com.huawei.activiti.controller.ProcessDefinitionController:upload.
	at org.apache.servicecomb.swagger.generator.core.AbstractSwaggerGenerator.scanMethods(AbstractSwaggerGenerator.java:301)
	at org.apache.servicecomb.swagger.generator.core.AbstractSwaggerGenerator.generate(AbstractSwaggerGenerator.java:119)
	at org.apache.servicecomb.swagger.generator.SwaggerGenerator.generate(SwaggerGenerator.java:32)
	at org.apache.servicecomb.swagger.engine.SwaggerEnvironment.createProducer(SwaggerEnvironment.java:105)
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.registerSchema(ProducerProviderManager.java:98)
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.regsiterProducerMetas(ProducerProviderManager.java:87)
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.init(ProducerProviderManager.java:73)
	at org.apache.servicecomb.core.SCBEngine.doRun(SCBEngine.java:357)
	at org.apache.servicecomb.core.SCBEngine.run(SCBEngine.java:308)
	... 13 more
Caused by: java.lang.IllegalStateException: failed to fill parameter, parameterName=filePath.
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.scanMethodParameter(AbstractOperationGenerator.java:328)
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.scanMethodParameters(AbstractOperationGenerator.java:197)
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.generate(AbstractOperationGenerator.java:154)
	at org.apache.servicecomb.swagger.generator.core.AbstractSwaggerGenerator.scanMethods(AbstractSwaggerGenerator.java:297)
	... 21 more
Caused by: java.lang.NoSuchMethodError: io.swagger.annotations.ApiParam.type()Ljava/lang/String;
	at io.swagger.util.ParameterProcessor$ApiParamWrapper.getType(ParameterProcessor.java:632)
	at io.swagger.util.ParameterProcessor$AnnotationsHelper.<init>(ParameterProcessor.java:439)
	at io.swagger.util.ParameterProcessor.applyAnnotations(ParameterProcessor.java:43)
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.fillParameter(AbstractOperationGenerator.java:381)
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.scanMethodParameter(AbstractOperationGenerator.java:321)
	... 24 more

**Comment by wujimin** [comment]
`Caused by: java.lang.NoSuchMethodError: io.swagger.annotations.ApiParam.type()Ljava/lang/String;`  
应该是swagger依赖版本，被你们的工程修改了  
  
另外，`activiti`这是`activity`的手误不？

**Comment by liushuai-monster** [comment]
activiti是工作流的组件名

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
