### ISSUE TITLE
serviceComb版本是1.3.0，vertx-core版本从3.6.3升级到3.9.4 微服务间调用异常 NoSuchMethodError: io.vertx.core.http.RequestOptions.setSsl(Z)Lio/vertx/core/http/RequestOptions

### ISSUE THREAD

**Issue by tangfan916** [apache/servicecomb-java-chassis#2156]
serviceComb版本是1.3.0，vertx-core版本从3.6.3升级到3.9.4 微服务间调用异常，报错如下：
01:28:04,599Z(474047):ERROR{}[org.springframework.kafka.KafkaListenerEndpointContainer#1-0-C-1]org.apache.servicecomb.loadbalance.LoadbalanceHandler$4.lambda$null$0(LoadbalanceHandler.java:384)-->service CONSUMER rest V2XCSU.com.huawei.m2m.rest.api.v2xcsu.service.APIG_SN_RSUController.batchShowInnerRsus, call error, msg is cause:InvocationException,message:InvocationException: code=490;msg=CommonExceptionData [message=Cse Internal Bad Request];cause:NoSuchMethodError,message:io.vertx.core.http.RequestOptions.setSsl(Z)Lio/vertx/core/http/RequestOptions;, server is rest://192.168.0.158:20989?sslEnabled=true 
2020-12-22 01:28:04,600Z(474048):ERROR{}[org.springframework.kafka.KafkaListenerEndpointContainer#1-0-C-1]org.apache.servicecomb.loadbalance.LoadbalanceHandler$3.onExceptionWithServer(LoadbalanceHandler.java:309)-->Invoke server failed. Operation CONSUMER rest V2XCSU.com.huawei.m2m.rest.api.v2xcsu.service.APIG_SN_RSUController.batchShowInnerRsus; server rest://192.168.0.158:20989?sslEnabled=true; 0-0 msg cause:InvocationException,message:InvocationException: code=490;msg=CommonExceptionData [message=Cse Internal Bad Request];cause:NoSuchMethodError,message:io.vertx.core.http.RequestOptions.setSsl(Z)Lio/vertx/core/http/RequestOptions;
2020-12-22 01:28:04,605Z(474053):ERROR{}[org.springframework.kafka.KafkaListenerEndpointContainer#1-0-C-1]org.apache.servicecomb.loadbalance.LoadbalanceHandler$3.onExecutionFailed(LoadbalanceHandler.java:337)-->Invoke all server failed. Operation CONSUMER rest V2XCSU.com.huawei.m2m.rest.api.v2xcsu.service.APIG_SN_RSUController.batchShowInnerRsus, e=cause:InvocationException,message:InvocationException: code=490;msg=CommonExceptionData [message=Cse Internal Bad Request];cause:NoSuchMethodError,message:io.vertx.core.http.RequestOptions.setSsl(Z)Lio/vertx/core/http/RequestOptions;
2020-12-22 01:28:04,608Z(474056):ERROR{}[org.springframework.kafka.KafkaListenerEndpointContainer#1-0-C-1]org.apache.servicecomb.transport.rest.client.RestTransportClient.send(RestTransportClient.java:119)-->vertx rest transport send error.
java.lang.NoSuchMethodError: io.vertx.core.http.RequestOptions.setSsl(Z)Lio/vertx/core/http/RequestOptions;
        at org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.createRequest(RestClientInvocation.java:182) ~[transport-rest-client-1.3.0.jar!/:1.3.0]
        at org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.invoke(RestClientInvocation.java:94) ~[transport-rest-client-1.3.0.jar!/:1.3.0]
        at org.apache.servicecomb.transport.rest.client.RestTransportClient.send(RestTransportClient.java:116) ~[transport-rest-client-1.3.0.jar!/:1.3.0]
        at org.apache.servicecomb.transport.rest.vertx.VertxRestTransport.send(VertxRestTransport.java:86) ~[transport-rest-vertx-1.3.0.jar!/:1.3.0]
        at org.apache.servicecomb.core.handler.impl.TransportClientHandler.handle(TransportClientHandler.java:42) ~[java-chassis-core-1.3.0.jar!/:1.3.0]
        at org.apache.servicecomb.core.Invocation.next(Invocation.java:204) ~[java-chassis-core-1.3.0.jar!/:1.3.0]
        at org.apache.servicecomb.authentication.consumer.ConsumerAuthHandler.handle(ConsumerAuthHandler.java:46) ~[handler-publickey-auth-1.3.0.jar!/:1.3.0]
        at org.apache.servicecomb.core.Invocation.next(Invocation.java:204) ~[java-chassis-core-1.3.0.jar!/:1.3.0]
        at org.apache.servicecomb.loadbalance.LoadbalanceHandler$4.lambda$call$1(LoadbalanceHandler.java:382) ~[handler-loadbalance-1.3.0.jar!/:1.3.0]
        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:235) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:286) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.onNext(OnSubscribeConcatMap.java:144) ~[rxjava-1.3.8.jar!/:1.3.8]
        at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:185) ~[ribbon-loadbalancer-2.3.0.jar!/:2.3.0]
        at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180) ~[ribbon-loadbalancer-2.3.0.jar!/:2.3.0]
        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1.call(OperatorRetryWithPredicate.java:127) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:79) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:45) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.Subscriber.setProducer(Subscriber.java:209) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.Observable.subscribe(Observable.java:10423) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.Observable.subscribe(Observable.java:10390) ~[rxjava-1.3.8.jar!/:1.3.8]
        at rx.Observable.subscribe(Observable.java:10271) ~[rxjava-1.3.8.jar!/:1.3.8]
        at org.apache.servicecomb.loadbalance.LoadbalanceHandler.sendWithRetry(LoadbalanceHandler.java:408) ~[handler-loadbalance-1.3.0.jar!/:1.3.0]
        at org.apache.servicecomb.loadbalance.LoadbalanceHandler.handle(LoadbalanceHandler.java:221) ~[handler-loadbalance-1.3.0.jar!/:1.3.0]
        at org.apache.servicecomb.core.Invocation.next(Invocation.java:204) ~[java-chassis-core-1.3.0.jar!/:1.3.0]
        at org.apache.servicecomb.core.provider.consumer.InvokerUtils.innerSyncInvoke(InvokerUtils.java:73) ~[java-chassis-core-1.3.0.jar!/:1.3.0]
        at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.doInvoke(CseClientHttpRequest.java:211) ~[provider-springmvc-1.3.0.jar!/:1.3.0]

**Comment by liubao68** [comment]
vert.x 存在很多接口不兼容。有可能是升级的目标版本和1.3.0不兼容， 无法独立升级。 只能servicecomb自己升级。 1.3.2 预计本月底发布， 会升级 vert.x。

**Comment by tangfan916** [comment]
io.vertx.core.http.RequestOptions.setSsl() 新版本是存在的，变化只是把参数类型从boolean变为Boolean
