### ISSUE TITLE
调用微服务偶发性失败

### ISSUE THREAD

**Issue by Moca-git** [apache/servicecomb-java-chassis#2187]
java.lang.IllegalStateException: can not find response mapper for com.abc.aa.cc.core.model.ServiceResponse<com.abc.aa.cc.core.model.PageDTO<com.abc.aa.cc.core.model.DictVersionParams>>, this should never happened.
	at org.apache.servicecomb.swagger.invocation.response.ResponseMapperFactorys.createResponseMapper(ResponseMapperFactorys.java:42)
	at org.apache.servicecomb.swagger.engine.SwaggerEnvironment.createConsumer(SwaggerEnvironment.java:83)
	at org.apache.servicecomb.provider.pojo.PojoConsumerMetaRefresher.refreshMeta(PojoConsumerMetaRefresher.java:107)
	at org.apache.servicecomb.provider.pojo.PojoConsumerMetaRefresher.ensureMetaAvailable(PojoConsumerMetaRefresher.java:80)
	at org.apache.servicecomb.provider.pojo.PojoConsumerMetaRefresher.getLatestMeta(PojoConsumerMetaRefresher.java:57)
	at org.apache.servicecomb.provider.pojo.Invoker.invoke(Invoker.java:68)
	at com.sun.proxy.$Proxy52.getParameter(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor373.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.abc.aa.cse.proxy.RpcFactoryBean.invokeToCSE(RpcFactoryBean.java:123)
	at com.abc.aa.cse.proxy.RpcFactoryBean.invoke(RpcFactoryBean.java:98)
	at com.sun.proxy.$Proxy52.getParameter(Unknown Source)
	at com.abc.aa.bb.service.impl.PriceTemplateDssThread.getTemplateConfigFromBbd(PriceTemplateDssThread.java:649)
	at com.abc.aa.bb.service.impl.PriceTemplateDssThread.setProductLinkFromApollo(PriceTemplateDssThread.java:453)
	at com.abc.aa.bb.service.impl.PriceTemplateDssThread.queryProductFeedInfo(PriceTemplateDssThread.java:235)
	at com.abc.aa.bb.service.impl.PriceTemplateDssThread.compute(PriceTemplateDssThread.java:180)
	at com.abc.aa.bb.service.impl.PriceTemplateDssThread.compute(PriceTemplateDssThread.java:55)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:759)
	at com.abc.aa.bb.service.impl.PriceTemplateDssThread.compute(PriceTemplateDssThread.java:190)
	at com.abc.aa.bb.service.impl.PriceTemplateDssThread.compute(PriceTemplateDssThread.java:55)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:759)
	at com.abc.aa.bb.service.impl.PriceTemplateDssThread.compute(PriceTemplateDssThread.java:190)
	at com.abc.aa.bb.service.impl.PriceTemplateDssThread.compute(PriceTemplateDssThread.java:55)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:326)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:391)
	at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:761)
	at com.abc.aa.bb.service.impl.PriceTemplateDssThread.compute(PriceTemplateDssThread.java:190)
	at com.abc.aa.bb.service.impl.PriceTemplateDssThread.compute(PriceTemplateDssThread.java:55)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:326)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:391)
	at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:761)
	at com.abc.aa.bb.service.impl.PriceTemplateDssThread.compute(PriceTemplateDssThread.java:190)
	at com.abc.aa.bb.service.impl.PriceTemplateDssThread.compute(PriceTemplateDssThread.java:55)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:759)
	at com.abc.aa.bb.service.impl.PriceTemplateDssThread.compute(PriceTemplateDssThread.java:190)
	at com.abc.aa.bb.service.impl.PriceTemplateDssServiceImpl.executeGeneratePriceModel(PriceTemplateDssServiceImpl.java:191)
	at com.abc.aa.bb.service.impl.PriceTemplateDssServiceImpl$$FastClassBySpringCGLIB$$3ca81365.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.abc.aa.bb.service.impl.PriceTemplateDssServiceImpl$$EnhancerBySpringCGLIB$$538c67c5.executeGeneratePriceModel(<generated>)
	at com.abc.aa.bb.service.impl.ProductFeedServiceImpl.generatePriceTemplate(ProductFeedServiceImpl.java:909)
	at com.abc.aa.bb.service.impl.ProductFeedServiceImpl$$FastClassBySpringCGLIB$$1cbd8d7.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.abc.aa.bb.service.impl.ProductFeedServiceImpl$$EnhancerBySpringCGLIB$$dc3daf5b.generatePriceTemplate(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.doInvoke(ProducerOperationHandler.java:121)
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.syncInvoke(ProducerOperationHandler.java:106)
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.invoke(ProducerOperationHandler.java:60)
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.handle(ProducerOperationHandler.java:51)
	at org.apache.servicecomb.core.Invocation.next(Invocation.java:304)
	at org.apache.servicecomb.qps.ProviderQpsFlowControlHandler.handle(ProviderQpsFlowControlHandler.java:39)
	at org.apache.servicecomb.core.Invocation.next(Invocation.java:304)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.doInvoke(AbstractRestInvocation.java:245)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke(AbstractRestInvocation.java:219)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor(AbstractRestInvocation.java:203)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(AbstractRestInvocation.java:162)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by liubao68** [comment]
这个异常结合代码不应该抛出，你可以看下 ResponseMapperFactorys 代码：

```
  public MAPPER createResponseMapper(Type providerType) {
    for (ResponseMapperFactory<MAPPER> factory : factorys) {
      if (!factory.isMatch(providerType)) {
        continue;
      }

      return factory.createResponseMapper(this, providerType);
    }

    throw new IllegalStateException(
        String.format("can not find response mapper for %s, this should never happened.",
            providerType.getTypeName()));
  }
```

`DefaultProducerResponseMapperFactory` 可以保证永远不会走到异常分支。 你可以调试下代码，看看实际情况。

**Comment by Moca-git** [comment]
> 
> 
> 这个异常结合代码不应该抛出，你可以看下 ResponseMapperFactorys 代码：
> 
> ```
>   public MAPPER createResponseMapper(Type providerType) {
>     for (ResponseMapperFactory<MAPPER> factory : factorys) {
>       if (!factory.isMatch(providerType)) {
>         continue;
>       }
> 
>       return factory.createResponseMapper(this, providerType);
>     }
> 
>     throw new IllegalStateException(
>         String.format("can not find response mapper for %s, this should never happened.",
>             providerType.getTypeName()));
>   }
> ```
> 
> `DefaultProducerResponseMapperFactory` 可以保证永远不会走到异常分支。 你可以调试下代码，看看实际情况。

现在抛出这个异常是不是说明provider没有提供服务啊？

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
