### ISSUE TITLE
微服务迁移到arm机器，cse报错，显示证书找不到，Key/certificate is mandatory for SSL

### ISSUE THREAD

**Issue by G-Jay-R** [apache/servicecomb-java-chassis#2230]
2021-02-07 01:06:48,611 ERROR [][vert.x-eventloop-thread-8][org.apache.servicecomb.transport.rest.vertx.RestServerVerticle 118]
io.vertx.core.VertxException: io.vertx.core.VertxException: Key/certificate is mandatory for SSL
        at io.vertx.core.net.impl.SSLHelper.createContext(SSLHelper.java:299) ~[vertx-core-3.6.3.jar:3.6.3]
        at io.vertx.core.net.impl.SSLHelper.getContext(SSLHelper.java:474) ~[vertx-core-3.6.3.jar:3.6.3]
        at io.vertx.core.net.impl.SSLHelper.validate(SSLHelper.java:499) ~[vertx-core-3.6.3.jar:3.6.3]
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:220) ~[vertx-core-3.6.3.jar:3.6.3]
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:191) ~[vertx-core-3.6.3.jar:3.6.3]
        at org.apache.servicecomb.transport.rest.vertx.RestServerVerticle.startListen(RestServerVerticle.java:216) ~[transport-rest-vertx-1.3.0.B012.jar:1.3.0.B012]
        at org.apache.servicecomb.transport.rest.vertx.RestServerVerticle.start(RestServerVerticle.java:115) ~[transport-rest-vertx-1.3.0.B012.jar:1.3.0.B012]
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:494) ~[vertx-core-3.6.3.jar:3.6.3]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) ~[vertx-core-3.6.3.jar:3.6.3]
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[vertx-core-3.6.3.jar:3.6.3]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-transport-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.49.Final.jar:4.1.49.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: io.vertx.core.VertxException: Key/certificate is mandatory for SSL
        at io.vertx.core.net.impl.SSLHelper.createContext(SSLHelper.java:259) ~[vertx-core-3.6.3.jar:3.6.3]
        ... 16 more

这样的配置在X86是行得通的，到arm上就报错了，能给解答一下么？

**Comment by liubao68** [comment]
这个错误的原因，是找不到SSL相关的配置文件，你可以现在有问题的环境上确认下配置文件中指定的SSL相关证书文件是否存在。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
