### ISSUE TITLE
java sdk由2.4降到2.3以后遇到的问题

### ISSUE THREAD

**Issue by G-Jay-R** [apache/servicecomb-java-chassis#2237]
2021-02-08 13:42:34,664 ERROR [][main][catalina.core.StandardService 564] Failed to initialize connector [Connector[com.huawei.wcc.secas.Http11NioProtocol-8443]]
org.apache.catalina.LifecycleException: Protocol handler initialization failed
        at org.apache.catalina.connector.Connector.initInternal(Connector.java:953) ~[catalina.jar:7.0.99]
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136) ~[catalina.jar:7.0.99]
        at org.apache.catalina.core.StandardService.initInternal(StandardService.java:560) [catalina.jar:7.0.99]
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136) [catalina.jar:7.0.99]
        at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:826) [catalina.jar:7.0.99]
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136) [catalina.jar:7.0.99]
        at org.apache.catalina.startup.Catalina.load(Catalina.java:660) [catalina.jar:7.0.99]
        at org.apache.catalina.startup.Catalina.load(Catalina.java:685) [catalina.jar:7.0.99]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
        at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:244) [bootstrap.jar:7.0.99]
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414) [bootstrap.jar:7.0.99]
Caused by: org.wcc.framework.AppRuntimeException: org.wcc.framework.AppRuntimeException: getOldRKCS error: getRKCPaths returns null/empty
        at org.wcc.crypt.CrypterProxy.decryptByRootKey(CrypterProxy.java:237) ~[wcc_crypt-1.2.22.jar:?]
        at org.wcc.crypt.Crypter.decryptByRootKey(Crypter.java:301) ~[wcc_crypt-1.2.22.jar:?]
        at com.huawei.wcc.secas.KSPass.decrypt(KSPass.java:121) ~[SecAs-1.2.33.jar:?]
        at com.huawei.wcc.secas.Http11NioProtocol.init(Http11NioProtocol.java:42) ~[SecAs-1.2.33.jar:?]
        at org.apache.catalina.connector.Connector.initInternal(Connector.java:951) ~[catalina.jar:7.0.99]
        ... 13 more
Caused by: org.wcc.framework.AppRuntimeException: getOldRKCS error: getRKCPaths returns null/empty
        at org.wcc.crypt.RootKeyUpdater.getOldRKCS(RootKeyUpdater.java:303) ~[wcc_crypt-1.2.22.jar:?]
        at org.wcc.crypt.CrypterProxy.decryptByRootKey(CrypterProxy.java:212) ~[wcc_crypt-1.2.22.jar:?]
        at org.wcc.crypt.Crypter.decryptByRootKey(Crypter.java:301) ~[wcc_crypt-1.2.22.jar:?]
        at com.huawei.wcc.secas.KSPass.decrypt(KSPass.java:121) ~[SecAs-1.2.33.jar:?]
        at com.huawei.wcc.secas.Http11NioProtocol.init(Http11NioProtocol.java:42) ~[SecAs-1.2.33.jar:?]
        at org.apache.catalina.connector.Connector.initInternal(Connector.java:951) ~[catalina.jar:7.0.99]
        ... 13 more

**Comment by liubao68** [comment]
这个错误和java-chassis提供的组件没有关联

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
