### ISSUE TITLE
空指针问题，请指导

### ISSUE THREAD

**Issue by houjianbo** [apache/servicecomb-java-chassis#2238]
用的版本号是 cse-solution-service-engine-2.4.6.4.jar

2021-01-13 02:43:22,903 INFO  [][][Edge-Register-All][common.utils.SPIServiceUtils 82]   0. com.huawei.paas.darklaunch.DarklaunchServerListFilter.
2021-01-13 02:43:22,905 INFO  [][][ForkJoinPool.commonPool-worker-9][common.utils.SPIServiceUtils 79] Found SPI service org.apache.servicecomb.loadbalance.ServerListFilterExt, count=1.
2021-01-13 02:43:22,906 INFO  [][][ForkJoinPool.commonPool-worker-9][common.utils.SPIServiceUtils 82]   0. com.huawei.paas.darklaunch.DarklaunchServerListFilter.
2021-01-13 02:43:23,255 ERROR [][][registry-vert.x-eventloop-thread-0][client.http.RestUtils 95] GET /v4/default/registry/instances?appId=cbc&global=true&serviceName=cronservice&env=production&version=0.0.0.0%2B fail, endpoint is 172.16.146.108:30100, message: Connection was closed
2021-01-13 02:43:23,256 WARN  [][][registry-vert.x-eventloop-thread-0][client.http.ServiceRegistryClientImpl 105] invoke service [/v4/default/registry/instances] failed, retry.
2021-01-13 02:43:23,256 INFO  [][][registry-vert.x-eventloop-thread-0][serviceregistry.client.IpPortManager 99] Change service center address from 172.16.146.108:30100 to 172.16.146.183:30100
2021-01-13 02:43:23,370 INFO  [][][registry-vert.x-eventloop-thread-4][foundation.vertx.VertxUtils 204] Success to close vertx registry.
2021-01-13 02:43:23,810 ERROR [][d19e24215d424a609976fd2a9f8fe0cf][group0-1-thread-2][common.rest.AbstractRestInvocation 221] unknown rest exception.
java.lang.ExceptionInInitializerError: null
        at org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.processException(SwaggerProducerOperation.java:214) ~[swagger-invocation-core-1.3.0.B012.jar:1.3.0.B012]
        at org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.doInvoke(SwaggerProducerOperation.java:204) ~[swagger-invocation-core-1.3.0.B012.jar:1.3.0.B012]
        at org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.syncInvoke(SwaggerProducerOperation.java:174) ~[swagger-invocation-core-1.3.0.B012.jar:1.3.0.B012]
        at org.apache.servicecomb.swagger.engine.SwaggerProducerOperation.invoke(SwaggerProducerOperation.java:128) ~[swagger-invocation-core-1.3.0.B012.jar:1.3.0.B012]
        at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.handle(ProducerOperationHandler.java:39) ~[java-chassis-core-1.3.0.B012.jar:1.3.0.B012]
        at org.apache.servicecomb.core.Invocation.next(Invocation.java:211) ~[java-chassis-core-1.3.0.B012.jar:1.3.0.B012]
        at com.huawei.olc.cse.plugin.OLCHandler.processOlcResult(OLCHandler.java:166) ~[olc-cse-adapter-4.1.5.jar:?]
        at com.huawei.olc.cse.plugin.OLCHandler.handle(OLCHandler.java:79) ~[olc-cse-adapter-4.1.5.jar:?]
        at com.huawei.olc.cse.plugin.ProviderGreatwallHandler.handle(ProviderGreatwallHandler.java:24) ~[olc-cse-adapter-4.1.5.jar:?]
        at org.apache.servicecomb.core.Invocation.next(Invocation.java:211) ~[java-chassis-core-1.3.0.B012.jar:1.3.0.B012]
        at org.apache.servicecomb.common.rest.AbstractRestInvocation.doInvoke(AbstractRestInvocation.java:245) ~[common-rest-1.3.0.B012.jar:1.3.0.B012]
        at org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke(AbstractRestInvocation.java:219) ~[common-rest-1.3.0.B012.jar:1.3.0.B012]
        at org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor(AbstractRestInvocation.java:203) ~[common-rest-1.3.0.B012.jar:1.3.0.B012]
        at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(AbstractRestInvocation.java:162) ~[common-rest-1.3.0.B012.jar:1.3.0.B012]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_262]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_262]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NullPointerException
        at org.apache.catalina.loader.WebappClassLoaderBase.findResources(WebappClassLoaderBase.java:1513) ~[catalina.jar:7.0.85]
        at java.lang.ClassLoader.getResources(ClassLoader.java:1135) ~[?:1.8.0_262]
        at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:348) ~[?:1.8.0_262]
        at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393) ~[?:1.8.0_262]
        at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474) ~[?:1.8.0_262]
        at java.lang.Iterable.forEach(Iterable.java:74) ~[?:1.8.0_262]
        at org.apache.servicecomb.foundation.common.utils.SPIServiceUtils.loadSortedService(SPIServiceUtils.java:63) ~[foundation-common-1.3.0.B012.jar:1.3.0.B012]
        at org.apache.servicecomb.foundation.common.utils.SPIServiceUtils.getOrLoadSortedService(SPIServiceUtils.java:95) ~[foundation-common-1.3.0.B012.jar:1.3.0.B012]
        at org.apache.servicecomb.foundation.common.utils.SPIServiceUtils.getSortedService(SPIServiceUtils.java:122) ~[foundation-common-1.3.0.B012.jar:1.3.0.B012]
        at org.apache.servicecomb.swagger.invocation.exception.ExceptionToProducerResponseConverters.<init>(ExceptionToProducerResponseConverters.java:42) ~[swagger-invocation-core-1.3.0.B012.jar:1.3.0.B012]
        at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.<clinit>(ExceptionFactory.java:47) ~[swagger-invocation-core-1.3.0.B012.jar:1.3.0.B012]
        ... 17 more

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
