### ISSUE TITLE
servicecomb不能使用HttpServletResponse？那么我想将一个二进制图片输出到页面应该怎么做呢？

### ISSUE THREAD

**Issue by liuguangrong** [apache/servicecomb-java-chassis#2258]
需要做一个页面访问后台，后台将二进制图片返回到页面展示，发现不能使用response，那么请问有什么办法能将图片写出去呢？
Caused by: org.apache.servicecomb.foundation.common.exceptions.ServiceCombException: [simple type, class java.util.function.Supplier] is interface. Must be a concrete type.
	at org.apache.servicecomb.swagger.extend.ModelResolverExt.checkType(ModelResolverExt.java:128)
	at org.apache.servicecomb.swagger.extend.ModelResolverExt.resolve(ModelResolverExt.java:148)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:203)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:103)
	at io.swagger.converter.ModelConverters.readAll(ModelConverters.java:98)
	at io.swagger.converter.ModelConverters.readAll(ModelConverters.java:88)
	at org.apache.servicecomb.swagger.SwaggerUtils.addDefinitions(SwaggerUtils.java:208)
	at org.apache.servicecomb.swagger.SwaggerUtils.setParameterType(SwaggerUtils.java:222)
	at org.apache.servicecomb.swagger.generator.springmvc.SpringmvcOperationGenerator.lambda$initMethodParameterGenerators$1(SpringmvcOperationGenerator.java:47)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at org.apache.servicecomb.swagger.generator.springmvc.SpringmvcOperationGenerator.initMethodParameterGenerators(SpringmvcOperationGenerator.java:44)
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.initParameterGenerators(AbstractOperationGenerator.java:213)
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.scanMethodParameters(AbstractOperationGenerator.java:193)
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.generate(AbstractOperationGenerator.java:154)
	at org.apache.servicecomb.swagger.generator.core.AbstractSwaggerGenerator.scanMethods(AbstractSwaggerGenerator.java:297)
	... 18 more

**Comment by liubao68** [comment]
可以考虑下文件下载功能： https://docs.servicecomb.io/java-chassis/zh_CN/general-development/upload-download/

**Comment by liuguangrong** [comment]
> 可以考虑下文件下载功能：[https](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/upload-download/) : [//docs.servicecomb.io/java-chassis/zh_CN/general-development/upload-download/](https://docs.servicecomb.io/java-chassis/zh_CN/general-development/upload-download/)
