### ISSUE TITLE
当服务端停止服务时，客户端已经刷新了微服务列表，但是客户端重启和不重启，访问报错的异常不同

### ISSUE THREAD

**Issue by IcyZhang** [apache/servicecomb-java-chassis#2326]
场景一： 服务端停止服务，客户端不重启
异常为：InvocationException
堆栈信息如下：
Line 21004: 2021-03-25 14:46:12.055|INFO |[vert.x-eventloop-thread-6]|605c31af61a4a750|[KnowledgeGraphSearcher:96]|This request supports knowledge graph search
	Line 21005: 2021-03-25 14:46:12.056|WARN |[vert.x-eventloop-thread-6]|605c31af61a4a750|[AbstractDiscoveryFilter:42]|discovery filter org.apache.servicecomb.serviceregistry.discovery.InstanceStatusDiscoveryFilter return null.
	Line 21006: 2021-03-25 14:46:12.056|ERROR|[vert.x-eventloop-thread-6]|605c31af61a4a750|[KnowledgeGraphServiceClient:72]|failed to recommend song from knowledge graph service org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=500;msg=CommonExceptionData [message=No available address found.]
	    at org.apache.servicecomb.loadbalance.LoadbalanceHandler.send(LoadbalanceHandler.java:264) ~[handler-loadbalance-2.0.2.jar:2.0.2]
        at org.apache.servicecomb.loadbalance.LoadbalanceHandler.handle(LoadbalanceHandler.java:222) ~[handler-loadbalance-2.0.2.jar:2.0.2]
        at org.apache.servicecomb.core.Invocation.next(Invocation.java:292) ~[java-chassis-core-2.0.2.jar:2.0.2]
        at org.apache.servicecomb.core.provider.consumer.InvokerUtils.reactiveInvoke(InvokerUtils.java:171) ~[java-chassis-core-2.0.2.jar:2.0.2]
        at org.apache.servicecomb.provider.pojo.Invoker.completableFutureInvoke(Invoker.java:213) ~[provider-pojo-2.0.2.jar:2.0.2]
        at org.apache.servicecomb.provider.pojo.Invoker.invoke(Invoker.java:182) ~[provider-pojo-2.0.2.jar:2.0.2]
        at com.sun.proxy.$Proxy62.recommendSongByEvent(Unknown Source) ~[?:?]
        at com.huawei.myna.thirdskillmusic.client.acesssknowledge.KnowledgeGraphServiceClient.recommendSongByEventProcess(KnowledgeGraphServiceClient.java:69) ~[thirdskill-music-service-5.8.0.1.jar:?]
        at com.huawei.myna.thirdskillmusic.client.acesssknowledge.KnowledgeGraphServiceClient.recommendSongByEvent(KnowledgeGraphServiceClient.java:61) ~[thirdskill-music-service-5.8.0.1.jar:?]

场景二：服务端停止服务后，客户端重启
异常为：IllegalStateException
堆栈信息为：
2021-03-25 14:53:25.370|INFO |[vert.x-eventloop-thread-0]|605c335fc029bd39|[KnowledgeGraphSearcher:96]|This request supports knowledge graph search
2021-03-25 14:53:25.376|INFO |[vert.x-eventloop-thread-0]|605c335fc029bd39|[MicroserviceVersions:96]|create MicroserviceVersions, appId=PipelineB, microserviceName=speaker-kg-service.
2021-03-25 14:53:25.385|INFO |[vert.x-eventloop-thread-0]|605c335fc029bd39|[SPIServiceUtils:79]|Found SPI service org.apache.servicecomb.serviceregistry.consumer.MicroserviceInstancePing, count=1.
2021-03-25 14:53:25.385|INFO |[vert.x-eventloop-thread-0]|605c335fc029bd39|[SPIServiceUtils:82]|  0. org.apache.servicecomb.serviceregistry.consumer.SimpleMicroserviceInstancePing.
2021-03-25 14:53:25.387|INFO |[nlu-work-pool-10]|605c3364946cc6bc|[SkillResultService:141]|after intent request handler, device:******ead-1-5 user:******9919242 cost:503 intent: timeCost:501 context:null
2021-03-25 14:53:25.395|INFO |[vert.x-eventloop-thread-0]|605c335fc029bd39|[RefreshableMicroserviceCache:113]|find instances[0] from service center success. service=PipelineB/speaker-kg-service/0.0.0.0+, old revision=null, new revision=97784746be9a2d00f08bc72fe1ce5ff8c7d07ffe
2021-03-25 14:53:25.399|INFO |[vert.x-eventloop-thread-0]|605c335fc029bd39|[MicroserviceVersions:281]|create MicroserviceVersionRule, appId=PipelineB, microserviceName=speaker-kg-service, versionRule=0.0.0.0+.
2021-03-25 14:53:25.402|INFO |[vert.x-eventloop-thread-0]|605c335fc029bd39|[MicroserviceVersionRule:113]|update instances to be empty caused by version rule, appId=PipelineB, microserviceName=speaker-kg-service, versionRule=0.0.0.0+, latestVersion=null, inputVersionCount=0, inputInstanceCount=0
2021-03-25 14:53:25.402|ERROR|[vert.x-eventloop-thread-0]|605c335fc029bd39|[KnowledgeGraphServiceClient:86]|get song by event failed java.lang.IllegalStateException: Probably invoke a service before it is registered, or no instance found for it, appId=PipelineB, name=speaker-kg-service, versionRule=0.0.0.0+.
        at org.apache.servicecomb.core.provider.consumer.MicroserviceReferenceConfig.getLatestMicroserviceMeta(MicroserviceReferenceConfig.java:79) ~[java-chassis-core-2.0.2.jar:2.0.2]
        at org.apache.servicecomb.provider.pojo.Invoker.refreshMeta(Invoker.java:122) ~[provider-pojo-2.0.2.jar:2.0.2]
        at org.apache.servicecomb.provider.pojo.Invoker.invoke(Invoker.java:146) ~[provider-pojo-2.0.2.jar:2.0.2]
        at com.sun.proxy.$Proxy62.recommendSongByEvent(Unknown Source) ~[?:?]
        at com.huawei.myna.thirdskillmusic.client.acesssknowledge.KnowledgeGraphServiceClient.recommendSongByEventProcess(KnowledgeGraphServiceClient.java:69) ~[thirdskill-music-service-5.8.0.1.jar:?]
        at com.huawei.myna.thirdskillmusic.client.acesssknowledge.KnowledgeGraphServiceClient.recommendSongByEvent(KnowledgeGraphServiceClient.java:61) ~[thirdskill-music-service-5.8.0.1.jar:?]

**Comment by liubao68** [comment]
第一个异常是因为客户端已经有过服务端的元数据信息了，只是没实例；第二个异常由于是重启， 获取元数据信息就失败了。 两个场景的信息（服务内部状态）不一样，所以异常也不一样。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
