### ISSUE TITLE
边缘服务多文件上传报490

### ISSUE THREAD

**Issue by x00384074** [apache/servicecomb-java-chassis#2417]
边缘服务多个文件上传报490，inputstream is closed

2021-06-16 14:44:17.259 [vert.x-eventloop-thread-11] WARN  - [BizkeeperCommand.java:lambda$null$1:82] - [5e515d9e-d7bc-4382-97c2-bc6bc74942b1] - bizkeeper command CONSUMER rest WeLinkLiteService:WeLinkLiteUserService.user.scanId failed due to {}
org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=490;msg=CommonExceptionData [message=Cse Internal Bad Request]
        at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.doCreate(ExceptionFactory.java:79)
        at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.convertException(ExceptionFactory.java:124)
        at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.convertConsumerException(ExceptionFactory.java:83)
        at org.apache.servicecomb.swagger.invocation.Response.createConsumerFail(Response.java:129)
        at org.apache.servicecomb.swagger.invocation.AsyncResponse.consumerFail(AsyncResponse.java:34)
        at org.apache.servicecomb.common.rest.codec.param.RestClientRequestImpl.lambda$attachFile$0(RestClientRequestImpl.java:201)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
        at org.apache.servicecomb.foundation.vertx.stream.InputStreamToReadStream.handleException(InputStreamToReadStream.java:136)
        at org.apache.servicecomb.foundation.vertx.stream.PumpCommon.lambda$pump$0(PumpCommon.java:53)
        at io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:133)
        at io.vertx.core.http.impl.HttpClientRequestImpl.handleException(HttpClientRequestImpl.java:370)
        at io.vertx.core.http.impl.HttpClientRequestImpl.handleDrained(HttpClientRequestImpl.java:339)
        at io.vertx.core.http.impl.Http1xClientConnection.handleInterestedOpsChanged(Http1xClientConnection.java:778)
        at io.vertx.core.net.impl.VertxHandler.lambda$channelWritabilityChanged$2(VertxHandler.java:124)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:221)
        at io.vertx.core.net.impl.VertxHandler.channelWritabilityChanged(VertxHandler.java:124)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:441)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:428)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:421)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelWritabilityChanged(CombinedChannelDuplexHandler.java:448)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:129)
        at io.netty.channel.CombinedChannelDuplexHandler.channelWritabilityChanged(CombinedChannelDuplexHandler.java:271)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:441)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:428)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:421)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelWritabilityChanged(DefaultChannelPipeline.java:1433)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:441)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:428)
        at io.netty.channel.DefaultChannelPipeline.fireChannelWritabilityChanged(DefaultChannelPipeline.java:931)
        at io.netty.channel.ChannelOutboundBuffer.fireChannelWritabilityChanged(ChannelOutboundBuffer.java:628)
        at io.netty.channel.ChannelOutboundBuffer.setWritable(ChannelOutboundBuffer.java:594)
        at io.netty.channel.ChannelOutboundBuffer.decrementPendingOutboundBytes(ChannelOutboundBuffer.java:196)
        at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:273)
        at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:352)
        at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:431)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:930)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:897)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:531)
        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125)
        at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
        at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:124)
        at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:205)
        at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.writeBuffer(Http1xClientConnection.java:340)
        at io.vertx.core.http.impl.HttpClientRequestImpl.write(HttpClientRequestImpl.java:656)
        at io.vertx.core.http.impl.HttpClientRequestImpl.write(HttpClientRequestImpl.java:581)
        at io.vertx.core.http.impl.HttpClientRequestImpl.write(HttpClientRequestImpl.java:575)
        at io.vertx.core.http.impl.HttpClientRequestImpl.write(HttpClientRequestImpl.java:52)
        at io.vertx.core.streams.impl.PumpImpl.lambda$new$1(PumpImpl.java:59)
        at org.apache.servicecomb.foundation.vertx.stream.InputStreamToReadStream.handleData(InputStreamToReadStream.java:179)
        at org.apache.servicecomb.foundation.vertx.stream.InputStreamToReadStream.afterReadInEventloop(InputStreamToReadStream.java:152)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.CompletionException: java.lang.IllegalStateException: inputStream is closed
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
        at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
        at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:925)
        at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:913)
        ... 67 common frames omitted
Caused by: java.lang.IllegalStateException: inputStream is closed
        at org.apache.servicecomb.foundation.vertx.stream.InputStreamToReadStream.check(InputStreamToReadStream.java:75)
        at org.apache.servicecomb.foundation.vertx.stream.InputStreamToReadStream.resume(InputStreamToReadStream.java:167)
        at org.apache.servicecomb.foundation.vertx.stream.InputStreamToReadStream.resume(InputStreamToReadStream.java:35)
        at io.vertx.core.streams.impl.PumpImpl.lambda$new$0(PumpImpl.java:57)
        at io.vertx.core.http.impl.HttpClientRequestImpl.handleDrained(HttpClientRequestImpl.java:337)
        ... 60 common frames omitted
2021-06-16 14:44:17.259 [vert.x-eventloop-thread-11] WARN  - [BizkeeperHandler.java:onExecutionError:55] - [5e515d9e-d7bc-4382-97c2-bc6bc74942b1] - bizkeeper execution error, info=cause:InvocationException,message:InvocationException: code=490;msg=CommonExceptionData [message=Cse Internal Bad Request];cause:CompletionException,message:java.lang.IllegalStateException: inputStream is closed;cause:IllegalStateException,message:inputStream is closed

**Comment by liubao68** [comment]
用的哪个版本？ 可以试试 [新版本](https://github.com/apache/servicecomb-java-chassis/releases/tag/2.2.0)

**Comment by x00384074** [comment]
实现这个会影响吗 
public class PumpImpl<T> implements Pump {

    private final ReadStream<T> readStream;

    private final WriteStream<T> writeStream;

    private final Handler<T> dataHandler;

    private final Handler<Void> drainHandler;

    private int pumped;

    /**
     * Create a new {@code Pump} with the given {@code ReadStream} and {@code WriteStream}. Set the write queue max size
     * of the write stream to {@code maxWriteQueueSize}
     */
    public PumpImpl(ReadStream<T> rs, WriteStream<T> ws, int maxWriteQueueSize) {
        this(rs, ws);
        writeStream.setWriteQueueMaxSize(maxWriteQueueSize);
    }

    public PumpImpl(ReadStream<T> rs, WriteStream<T> ws) {
        readStream = rs;
        writeStream = ws;
        drainHandler = v -> readStream.resume();
        writeStream.drainHandler(drainHandler);
        dataHandler = data -> {
            writeStream.write(data);
            incPumped();
            if (writeStream.writeQueueFull()) {
                readStream.pause();
            }
        };
    }

    /**
     * 设置写队列最大长度
     *
     * @param maxSize 队列最大长度
     * @return PumpImpl
     */
    @Override
    public PumpImpl setWriteQueueMaxSize(int maxSize) {
        writeStream.setWriteQueueMaxSize(maxSize);
        return this;
    }

    /**
     * 开始处理
     *
     * @return PumpImpl
     */
    @Override
    public PumpImpl start() {
        readStream.handler(dataHandler);
        return this;
    }

    /**
     * 停止
     *
     * @return PumpImpl
     */
    @Override
    public PumpImpl stop() {
        writeStream.drainHandler(null);
        readStream.handler(null);
        return this;
    }

    /**
     * numberPumped
     *
     * @return int
     */
    @Override
    public synchronized int numberPumped() {
        return pumped;
    }

    // Note we synchronize as numberPumped can be called from a different thread however incPumped will always
    // be called from the same thread so we benefit from bias locked optimisation which should give a very low
    // overhead
    private synchronized void incPumped() {
        pumped++;
    }
}

**Comment by liubao68** [comment]
这个实现的是vert.x的接口， 我不是很清楚你们实现这个的目的和用途。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
