### ISSUE TITLE
InvocationException: code=590;msg=CommonExceptionData

### ISSUE THREAD

**Issue by lujiango** [apache/servicecomb-java-chassis#2440]
能否帮忙看一下问题。场景就是A通过cse调用B，之前调用都是正常的，从某个点突然出现调不通报错就是上面的日志，然后一直调不通，必须重启B节点才能恢复。
日志如下：
cseRequest failed:InvocationException: code=590;msg=CommonExceptionData [message=Cse Internal Server Error] -exception-org.apache.servicecomb.swagger.invocation.exception.InvocationException: 
org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.doCreate(ExceptionFactory.java:76) 
org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.create(ExceptionFactory.java:63) 
org.apache.servicecomb.swagger.invocation.Response.create(Response.java:142) 
org.apache.servicecomb.transport.rest.client.http.DefaultHttpClientFilter.extractResponse(DefaultHttpClientFilter.java:105) 
org.apache.servicecomb.transport.rest.client.http.DefaultHttpClientFilter.afterReceiveResponse(DefaultHttpClientFilter.java:128) 
org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.lambda$processResponseBody$4(RestClientInvocation.java:237) 
org.apache.servicecomb.core.provider.consumer.SyncResponseExecutor.waitResponse(SyncResponseExecutor.java:56) 
org.apache.servicecomb.core.provider.consumer.InvokerUtils.innerSyncInvoke(InvokerUtils.java:160) 
org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.doInvoke(CseClientHttpRequest.java:244) 
org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.invoke(CseClientHttpRequest.java:234) 
org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.execute(CseClientHttpRequest.java:177) 
org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:739) 
org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674) 
org.apache.servicecomb.provider.springmvc.reference.CseRestTemplate.postForObject(CseRestTemplate.java:82) 
org.apache.servicecomb.provider.springmvc.reference.RestTemplateWrapper.postForObject(RestTemplateWrapper.java:113)
com.huawei.intelligence.transfer.handler.impl.HwDialogueSpeechHandlerImp.cseRequest(HwDialogueSpeechHandlerImp.java:181) 
com.huawei.intelligence.transfer.handler.impl.HwDialogueSpeechHandlerImp.sendDialogSpeechData(HwDialogueSpeechHandlerImp.java:149) 
com.huawei.intelligence.transfer.thread.impl.DialogueSpeechRequestTaskRunnable.run(DialogueSpeechRequestTaskRunnable.java:43) 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
java.lang.Thread.run(Thread.java:748) 

--------------------------------------------------------------------------------------------------------------
2021-06-29 17:47:41.121 | INFO  | taskThreadPool-692 | 10.31.25.235 | CseRouteRule.java:53 | 54c47d92873f40aca230249ad9807fa745 | 1 | 485**30252 | 247819011389468 | 48558******30252 choose server [null] rest://10.33.204.101:8080?sslEnabled=false servers:[rest://10.33.204.101:8080?sslEnabled=false, rest://10.33.204.48:8080?sslEnabled=false]
2021-06-29 17:47:41.130 | ERROR | taskThreadPool-692 | 10.31.25.235 | GeneralDispatcher.java:68 | 54c47d92873f40aca230249ad9807fa745 | 1 | 485**30252 | 247819011389468 | dispatch exception. InvocationException: code=590;msg=CommonExceptionData [message=Unexpected producer error, please check logs for details]
org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=590;msg=CommonExceptionData [message=Unexpected producer error, please check logs for details]
        at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.doCreate(ExceptionFactory.java:76) ~[swagger-invocation-core-2.1.5.jar:2.1.5]
        at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.create(ExceptionFactory.java:63) ~[swagger-invocation-core-2.1.5.jar:2.1.5]
        at org.apache.servicecomb.swagger.invocation.Response.create(Response.java:142) ~[swagger-invocation-core-2.1.5.jar:2.1.5]
        at org.apache.servicecomb.transport.rest.client.http.DefaultHttpClientFilter.extractResponse(DefaultHttpClientFilter.java:105) ~[transport-rest-client-2.1.5.jar:2.1.5]
        at org.apache.servicecomb.transport.rest.client.http.DefaultHttpClientFilter.afterReceiveResponse(DefaultHttpClientFilter.java:128) ~[transport-rest-client-2.1.5.jar:2.1.5]
        at org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.lambda$processResponseBody$4(RestClientInvocation.java:237) ~[transport-rest-client-2.1.5.jar:2.1.5]
        at org.apache.servicecomb.core.provider.consumer.SyncResponseExecutor.waitResponse(SyncResponseExecutor.java:56) ~[java-chassis-core-2.1.5.jar:2.1.5]
        at org.apache.servicecomb.core.provider.consumer.InvokerUtils.innerSyncInvoke(InvokerUtils.java:160) ~[java-chassis-core-2.1.5.jar:2.1.5]
        at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.doInvoke(CseClientHttpRequest.java:244) ~[provider-springmvc-2.1.5.jar:2.1.5]
        at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.invoke(CseClientHttpRequest.java:234) ~[provider-springmvc-2.1.5.jar:2.1.5]
        at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.execute(CseClientHttpRequest.java:177) ~[provider-springmvc-2.1.5.jar:2.1.5]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:737) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:672) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.apache.servicecomb.provider.springmvc.reference.CseRestTemplate.postForObject(CseRestTemplate.java:82) ~[provider-springmvc-2.1.5.jar:2.1.5]
        at org.apache.servicecomb.provider.springmvc.reference.RestTemplateWrapper.postForObject(RestTemplateWrapper.java:113) ~[provider-springmvc-2.1.5.jar:2.1.5]
        at com.huawei.intelligence.client.CseClient.post(CseClient.java:47) ~[api-gateway-1.0.0.jar:1.0.0]
        at com.huawei.intelligence.client.HttpClient.post(HttpClient.java:60) ~[api-gateway-1.0.0.jar:1.0.0]
        at com.huawei.intelligence.handler.impl.GeneralDispatcher.dispatch(GeneralDispatcher.java:63) ~[api-gateway-1.0.0.jar:1.0.0]
        at com.huawei.intelligence.api.ProxyController.lambda$text$0(ProxyController.java:71) ~[api-gateway-1.0.0.jar:1.0.0]
        at com.huawei.intelligence.model.MultipartWebAsyncTask.lambda$new$0(MultipartWebAsyncTask.java:36) ~[api-gateway-1.0.0.jar:1.0.0]
        at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:337) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_232]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_232]
        at com.huawei.intelligence.configuration.TaskConfiguration$ThreadTaskDecorator.lambda$decorate$0(TaskConfiguration.java:94) ~[api-gateway-1.0.0.jar:1.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by yhs0092** [comment]
`org.apache.servicecomb.transport.rest.client.http.DefaultHttpClientFilter.extractResponse(DefaultHttpClientFilter.java:105)`

你的两段日志的异常栈里面都有上面这一行, 说明都是从服务端的response里获取到了590状态码的响应. 这说明错误发生在下游微服务, 还需要继续向下排查. 光看这两段日志是看不出问题在哪里的.

**Comment by lujiango** [comment]
> `org.apache.servicecomb.transport.rest.client.http.DefaultHttpClientFilter.extractResponse(DefaultHttpClientFilter.java:105)`
> 
> 你的两段日志的异常栈里面都有上面这一行, 说明都是从服务端的response里获取到了590状态码的响应. 这说明错误发生在下游微服务, 还需要继续向下排查. 光看这两段日志是看不出问题在哪里的.

--对cse框架不是特别了解，请问是看cse具体什么日志呢？

**Comment by yhs0092** [comment]
> 
> 
> > `org.apache.servicecomb.transport.rest.client.http.DefaultHttpClientFilter.extractResponse(DefaultHttpClientFilter.java:105)`
> > 你的两段日志的异常栈里面都有上面这一行, 说明都是从服务端的response里获取到了590状态码的响应. 这说明错误发生在下游微服务, 还需要继续向下排查. 光看这两段日志是看不出问题在哪里的.
> 
> --对cse框架不是特别了解，请问是看cse具体什么日志呢？

如果你没有定制过Java-Chassis的异常转换机制的话, 那么下游服务的原始异常信息应该是在`org.apache.servicecomb.swagger.invocation.exception.DefaultExceptionToProducerResponseConverter` 类中打印出来的. 该类型是Java-Chassis提供的默认异常转换类, 业务代码抛出的异常会被Java-Chassis框架捕获并交给`DefaultExceptionToProducerResponseConverter`转换成490或590异常.

至于具体是什么日志, 这得看你怎么配置你的日志打印框架了.

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
