### ISSUE TITLE
业务运行过程中，线程一直处于僵死状态

### ISSUE THREAD

**Issue by chenchanglong1997** [apache/servicecomb-java-chassis#2441]
"scheduling-3" #81 prio=5 os_prio=0 tid=0x00007f2a8c488800 nid=0x2e87 waiting on condition [0x00007f2a265f0000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000af614cb8> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:838)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:999)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1306)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at org.apache.servicecomb.core.provider.consumer.SyncResponseExecutor.waitResponse(SyncResponseExecutor.java:53)
	at org.apache.servicecomb.core.provider.consumer.InvokerUtils.innerSyncInvoke(InvokerUtils.java:160)
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.doInvoke(CseClientHttpRequest.java:244)
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.invoke(CseClientHttpRequest.java:234)
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.execute(CseClientHttpRequest.java:177)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:737)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:672)
	at org.apache.servicecomb.provider.springmvc.reference.CseRestTemplate.postForObject(CseRestTemplate.java:82)
	at org.apache.servicecomb.provider.springmvc.reference.RestTemplateWrapper.postForObject(RestTemplateWrapper.java:113)
	at com.huawei.ryoma.ude.service.core.service.MicroServiceInfoReportService.sendAgentInfo2Ude(MicroServiceInfoReportService.java:132)
	at com.huawei.ryoma.ude.service.core.service.MicroServiceInfoReportService.reportHeartBeat(MicroServiceInfoReportService.java:97)
	at sun.reflect.GeneratedMethodAccessor395.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by DongJigong** [comment]
It seems waiting for  response data

**Comment by chenchanglong1997** [comment]
> It seems waiting for response data

这个线程卡在这好几天了，这一块有什么超时机制吗？不应该存在线程僵死的事情

**Comment by DongJigong** [comment]
> > It seems waiting for response data
> 
> 这个线程卡在这好几天了，这一块有什么超时机制吗？不应该存在线程僵死的事情

It should have timeout config. But I am not sure about that.

**Comment by chenchanglong1997** [comment]
> > > It seems waiting for response data
> > 
> > 
> > 这个线程卡在这好几天了，这一块有什么超时机制吗？不应该存在线程僵死的事情
> 
> It should have timeout config. But I am not sure about that.

如果我没理解，cse有默认的超时时间

**Comment by DongJigong** [comment]
> > > > It seems waiting for response data
> > > 
> > > 
> > > 这个线程卡在这好几天了，这一块有什么超时机制吗？不应该存在线程僵死的事情
> > 
> > 
> > It should have timeout config. But I am not sure about that.
> 
> 如果我没理解，cse有默认的超时时间

https://github.com/apache/servicecomb-java-chassis/issues/2441#issuecomment-871873078
I think this  doc would help you. You can try this. Every transport has a timeout config

**Comment by chenchanglong1997** [comment]
已修复的bug
