### ISSUE TITLE
线程阻塞

### ISSUE THREAD

**Issue by five111** [apache/servicecomb-java-chassis#2445]
servicecomb-java-chassis版本2.1.5 
业务突然中断 无法进行 分析后发现线程处于阻塞休眠状态
部分日志如下
"temp_event_thread" #209640 prio=5 os_prio=0 tid=0x00007f2a58006800 nid=0xc385 waiting on condition [0x00007f2ab4af7000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.huawei.smartcare.netview.pms.hprestate.appmanage.AppProcessThread$ReportAppStatusEvent.doEvent(AppProcessThread.java:343)
	at com.huawei.smartcare.netview.pms.hprestate.comm.timer.BaseEvent$InternalThd.run(BaseEvent.java:143)
	at java.lang.Thread.run(Thread.java:748)

"IPC Parameter Sending Thread #7925" #209635 daemon prio=5 os_prio=0 tid=0x00007f29e4134000 nid=0xc31e waiting on condition [0x00007f2ab43f4000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000adbc1348> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"dynamic timer" #34448 prio=5 os_prio=0 tid=0x00007f2984037000 nid=0xf47c waiting on condition [0x00007f2a896f7000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at com.huawei.smartcare.netview.pms.hprestate.comm.thread.ThreadUtil.sleep(ThreadUtil.java:36)
	at com.huawei.smartcare.netview.pms.hprestate.comm.timer.DynamicTimerThread.execute(DynamicTimerThread.java:56)
	at com.huawei.smartcare.netview.pms.hprestate.comm.thread.LoopThread.run(LoopThread.java:27)
	at java.lang.Thread.run(Thread.java:748)

跟踪源码发现以下代码
![源码截图](https://user-images.githubusercontent.com/19482564/124124062-92f8b380-daaa-11eb-8f18-b40d9bf989cd.png)
第33行是否会造成此现象？
另外 41行的excute方法出现特殊状况时，如阻塞 会导致countDown一直执行不到从而一直休眠吗

**Comment by liubao68** [comment]
你截取的堆栈和代码没有关联性。 需要先结合全量 stack （可以每隔2~3秒抓取多个，分析变化）， 来判断阻塞的点。
