### ISSUE TITLE
org.apache.servicecomb.registry.RegistrationManager.AfterServiceInstanceRegistryHandler#afterRegistryInstance是否需要@EnableExceptionPropagation

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [apache/servicecomb-java-chassis#2458]
如果没有的话会导致如果BootListener#onAfterRegistry报错 依旧能正常启动

**Comment by liubao68** [comment]
AfterServiceInstanceRegistryHandler只是发送一个事件， 实际的业务场景是什么？ AfterServiceInstanceRegistryHandler什么情况下失败？

**Comment by Nick-The-Uncharted** [comment]
@liubao68 我们在onAfterRegistry里注册了第三方接口，因为接口定义错误导致失败。但是我们有n个第三方接口，中间的一个注册失败就导致后面的所有BootListener都不跑了

**Comment by liubao68** [comment]
感觉这种场景的最好处理测试是业务自己捕获异常。因为预期就是注册失败，不影响加载流程，继续注册其他接口。

**Comment by Nick-The-Uncharted** [comment]
@liubao68 好的 那最好在文档里说明一下，因为 servicecomb的早期版本以及 spring的各种listener都是如果异常就启动失败的。忽然不失败了有点不适应。

而且个人认为如果启动过程中有异常最好直接启动失败，或者可以配置。现在很多人都用k8s，带问题启动反而会把原先健康的老版本给替代了，关键是如果没有经验还不好定位原因。

**Comment by liubao68** [comment]
明白了，看到SCBEngine了。 这样看是一个bug。

**Comment by Nick-The-Uncharted** [comment]
附上堆栈~
```
java.lang.IllegalStateException: Only allowed one default path. method=xxxxx.
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.addOperationToSwagger(AbstractOperationGenerator.java:443) ~[swagger-generator-core-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.swagger.generator.core.AbstractSwaggerGenerator.addOperationsToSwagger(AbstractSwaggerGenerator.java:319) ~[swagger-generator-core-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.swagger.generator.core.AbstractSwaggerGenerator.generate(AbstractSwaggerGenerator.java:120) ~[swagger-generator-core-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.swagger.generator.SwaggerGenerator.generate(SwaggerGenerator.java:32) ~[swagger-generator-core-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.registry.swagger.SwaggerLoader.registerSwagger(SwaggerLoader.java:119) ~[foundation-registry-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.registry.consumer.StaticMicroserviceVersions.addSchema(StaticMicroserviceVersions.java:82) ~[foundation-registry-2.1.3.jar:2.1.3]
	at com.google.common.collect.SingletonImmutableBiMap.forEach(SingletonImmutableBiMap.java:66) ~[guava-30.0-jre.jar:?]
	at org.apache.servicecomb.registry.consumer.StaticMicroserviceVersions.addSchemas(StaticMicroserviceVersions.java:77) ~[foundation-registry-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.registry.consumer.StaticMicroserviceVersions.init(StaticMicroserviceVersions.java:56) ~[foundation-registry-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.registry.consumer.StaticMicroserviceVersions.init(StaticMicroserviceVersions.java:50) ~[foundation-registry-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.registry.RegistrationManager.lambda$registerMicroserviceMapping$8(RegistrationManager.java:175) ~[foundation-registry-2.1.3.jar:2.1.3]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688) ~[?:1.8.0_252]
	at org.apache.servicecomb.foundation.common.concurrent.ConcurrentHashMapEx.computeIfAbsent(ConcurrentHashMapEx.java:56) ~[foundation-common-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.registry.RegistrationManager.registerMicroserviceMapping(RegistrationManager.java:172) ~[foundation-registry-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.registry.RegistrationManager.registerMicroserviceMappingByEndpoints(RegistrationManager.java:194) ~[foundation-registry-2.1.3.jar:2.1.3]
	at com.huawei.ivcs.common.registrar.AbstractServiceRegistrar.onAfterRegistry(AbstractServiceRegistrar.java:49) ~[commons-convention-0.2.0-20210624.024018-20.jar:?]
	at org.apache.servicecomb.core.BootListener.onBootEvent(BootListener.java:100) ~[java-chassis-core-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.core.SCBEngine.triggerEvent(SCBEngine.java:270) ~[java-chassis-core-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.core.SCBEngine$AfterRegistryEventHanlder.afterRegistryInstance(SCBEngine.java:618) ~[java-chassis-core-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.foundation.common.event.SimpleSubscriber.syncDispatch(SimpleSubscriber.java:118) ~[foundation-common-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.foundation.common.event.SimpleSubscriber.dispatchEvent(SimpleSubscriber.java:107) ~[foundation-common-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.foundation.common.event.SimpleEventBus.post(SimpleEventBus.java:73) ~[foundation-common-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.registry.RegistrationManager$AfterServiceInstanceRegistryHandler.afterRegistryInstance(RegistrationManager.java:341) ~[foundation-registry-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.foundation.common.event.SimpleSubscriber.syncDispatch(SimpleSubscriber.java:118) ~[foundation-common-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.foundation.common.event.SimpleSubscriber.dispatchEvent(SimpleSubscriber.java:107) ~[foundation-common-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.foundation.common.event.SimpleEventBus.post(SimpleEventBus.java:73) ~[foundation-common-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.serviceregistry.RegistryUtils$AfterServiceInstanceRegistryHandler.afterRegistryInstance(RegistryUtils.java:307) ~[registry-service-center-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.foundation.common.event.SimpleSubscriber.syncDispatch(SimpleSubscriber.java:118) ~[foundation-common-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.foundation.common.event.SimpleSubscriber.dispatchEvent(SimpleSubscriber.java:107) ~[foundation-common-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.foundation.common.event.SimpleEventBus.post(SimpleEventBus.java:73) ~[foundation-common-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.serviceregistry.task.AbstractTask.run(AbstractTask.java:54) ~[registry-service-center-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.serviceregistry.task.CompositeTask.run(CompositeTask.java:35) ~[registry-service-center-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.serviceregistry.task.ServiceCenterTask.init(ServiceCenterTask.java:108) ~[registry-service-center-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.serviceregistry.registry.AbstractServiceRegistry.run(AbstractServiceRegistry.java:137) ~[registry-service-center-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.serviceregistry.registry.RemoteServiceRegistry.run(RemoteServiceRegistry.java:75) ~[registry-service-center-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.serviceregistry.RegistryUtils.executeOnEachServiceRegistry(RegistryUtils.java:246) ~[registry-service-center-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.serviceregistry.RegistryUtils.run(RegistryUtils.java:112) ~[registry-service-center-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.serviceregistry.ServiceCenterRegistration.run(ServiceCenterRegistration.java:42) ~[registry-service-center-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.registry.RegistrationManager.lambda$run$6(RegistrationManager.java:136) ~[foundation-registry-2.1.3.jar:2.1.3]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_252]
	at org.apache.servicecomb.registry.RegistrationManager.run(RegistrationManager.java:136) ~[foundation-registry-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.core.SCBEngine.doRun(SCBEngine.java:383) ~[java-chassis-core-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.core.SCBEngine.run(SCBEngine.java:319) ~[java-chassis-core-2.1.3.jar:2.1.3]
	at org.apache.servicecomb.core.CseApplicationListener.onApplicationEvent(CseApplicationListener.java:87) ~[java-chassis-core-2.1.3.jar:2.1.3]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:108) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:77) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
```

**Comment by liubao68** [comment]
fixed in https://github.com/apache/servicecomb-java-chassis/pull/2460
