### ISSUE TITLE
CSE：报错parameter name is not present

### ISSUE THREAD

**Issue by csy1030** [apache/servicecomb-java-chassis#2463]
环境： ServiceComb：2.1.5    Spring：5.3.4    SpringBoot： 2.4.3    Gradle：6.8.3

在controller入参中使用@RequestBody @Valid AddBean addBean
**导致在本地起服务的时候报错：Failed to start ServiceComb** 

2021-07-13 11:37:49,129|ERROR|Failed to start ServiceComb due to errors and close|main|org.apache.servicecomb.core.SCBEngine.run(SCBEngine.java:324)
java.lang.IllegalStateException: generate swagger operation failed, method=com.huawei.orch.controller.AxRelationNumberController:createBindInfo.
	at org.apache.servicecomb.swagger.generator.core.AbstractSwaggerGenerator.scanMethods(AbstractSwaggerGenerator.java:301) ~[swagger-generator-core-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.swagger.generator.core.AbstractSwaggerGenerator.generate(AbstractSwaggerGenerator.java:119) ~[swagger-generator-core-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.swagger.generator.SwaggerGenerator.generate(SwaggerGenerator.java:32) ~[swagger-generator-core-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.swagger.engine.SwaggerEnvironment.checkAndGenerateSwagger(SwaggerEnvironment.java:165) ~[swagger-invocation-core-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.swagger.engine.SwaggerEnvironment.createProducer(SwaggerEnvironment.java:109) ~[swagger-invocation-core-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.registerSchema(ProducerProviderManager.java:102) ~[java-chassis-core-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.registerProducerMetas(ProducerProviderManager.java:87) ~[java-chassis-core-2.1.5.jar:2.1.5]

**报错原因：**
Caused by: java.lang.IllegalStateException: **parameter name is not present**, method=com.huawei.orch.controller.AxRelationNumberController:createBindInfo
solution:
  change pom.xml, add compiler argument: -parameters, for example:
 ```
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-compiler-plugin</artifactId>
      <configuration>
        <compilerArgument>-parameters</compilerArgument>
      </configuration>
   </plugin>
```
	at org.apache.servicecomb.swagger.generator.SwaggerGeneratorUtils.collectParameterName(SwaggerGeneratorUtils.java:212) ~[swagger-generator-core-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.swagger.generator.ParameterGenerator.<init>(ParameterGenerator.java:58) ~[swagger-generator-core-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.swagger.generator.ParameterGenerator.<init>(ParameterGenerator.java:70) ~[swagger-generator-core-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.initMethodParameterGenerators(AbstractOperationGenerator.java:234

按照提示在build.gradle中加入：
```
tasks.withType(JavaCompile) {
    options.compilerArgs << '-parameters'
}
```
但是并没有生效，重试本地起服务还是会报错，在流水线上跑会注册不上ServiceComb

**Comment by csy1030** [comment]
build.gradle
```
        implementation ('org.apache.servicecomb:solution-basic:' + SERVICE_COMB_VERSION) {
            exclude(group: 'org.springframework.boot')
        }
        implementation ('org.apache.servicecomb:java-chassis-spring-boot-starter-servlet:' + SERVICE_COMB_VERSION) {
            exclude group: 'org.apache.logging.log4j', module: 'log4j-to-slf4j'
            exclude(group: 'org.springframework.boot')
        }
        implementation 'org.apache.servicecomb:config-cc:' + SERVICE_COMB_VERSION
        implementation 'org.apache.servicecomb:servicestage-environment:' + SERVICE_COMB_VERSION
        implementation 'org.apache.servicecomb:registry-service-center:' + SERVICE_COMB_VERSION
        implementation 'org.apache.servicecomb:metrics-core:' + SERVICE_COMB_VERSION
```

**Comment by csy1030** [comment]
**按照这个文档中的指示操作了，也不生效**

常见问题
java-chassis运行时依赖于接口定义里面的名字
为了更好的基于swagger对服务进行治理，以及提高客户端代码书写的灵活性，java-chassis要求书写的接口定义代码在编译的时候，带上参数名称信息，否则会报告如下错误：

Caused by: java.lang.IllegalStateException: parameter name is not present, method=org.apache.servicecomb.samples.porter.file.api.InternalAccessEndpoint:localAccess
solution:
  change pom.xml, add compiler argument: -parameters, for example:
```
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-compiler-plugin</artifactId>
      <configuration>
        <compilerArgument>-parameters</compilerArgument>
      </configuration>
    </plugin>
```
解决该问题可以通过配置maven compiler plugin， 加上-parameters参数。如果在IDE下面运行，需要设置 build -> java compilers 在编译参数里面增加-parameters。
