### ISSUE TITLE
Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens

### ISSUE THREAD

**Issue by dafeng19** [apache/servicecomb-java-chassis#2499]
微服务之间调用，A微服务用以下几种方式向B微服务发起请求，均报错
 restTemplate.postForEntity(fullUrl, requestHttp, JSONObject.class);
 restTemplate.postForEntity(fullUrl, requestHttp, String.class);
 restTemplate.postForEntity(fullUrl, requestHttp, Object.class);

Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: (org.apache.servicecomb.foundation.vertx.stream.BufferInputStream); line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:710)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._throwInvalidSpace(ParserMinimalBase.java:688)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:3012)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:724)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4684)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4586)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3601)
        at org.apache.servicecomb.common.rest.codec.produce.ProduceJsonProcessor.doDecodeResponse(ProduceJsonProcessor.java:64)
        at org.apache.servicecomb.common.rest.codec.produce.ProduceProcessor.decodeResponse(ProduceProcessor.java:76)
        at org.apache.servicecomb.transport.rest.client.http.DefaultHttpClientFilter.extractResponse(DefaultHttpClientFilter.java:104)

**Comment by liubao68** [comment]
能够基于 https://github.com/apache/servicecomb-samples 提供一个简单的服务端定义和客户端请求数据的代码吗？ 
我们无法根据你提供的信息重现和分析问题。

**Comment by dafeng19** [comment]
不好提供。B微服务一侧没有报错，debug 微服务B的时候，断点处能看到响应。debug 微服务A的时候，org.springframework.web.client.RestTemplate#doExecute     			response = request.execute(); 
![image](https://user-images.githubusercontent.com/42594818/128807197-dc845cc7-2d40-4567-824a-6e10329d60a4.png)
response 是null，且抛出异常。

**Comment by WillemJiang** [comment]
这个有点像是服务端的回复有问题，你最好是检查一下服务端的回复消息。
