### ISSUE TITLE
jar包冲突

### ISSUE THREAD

**Issue by johnyannj** [apache/servicecomb-java-chassis#2504]
![image](https://user-images.githubusercontent.com/8110450/129432665-d2c4a43f-7632-4f40-a57b-0c5272f638ea.png)

Caused by: java.lang.NoSuchMethodError: javax.validation.BootstrapConfiguration.getClockProviderClassName()Ljava/lang/String;
	at org.hibernate.validator.internal.xml.config.ValidationBootstrapParameters.<init>(ValidationBootstrapParameters.java:65)
	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.parseValidationXml(AbstractConfigurationImpl.java:664)
	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.buildValidatorFactory(AbstractConfigurationImpl.java:421)
	at org.apache.servicecomb.core.filter.impl.ParameterValidatorFilter.createValidatorFactory(ParameterValidatorFilter.java:75)
	at org.apache.servicecomb.core.filter.impl.ParameterValidatorFilter.afterPropertiesSet(ParameterValidatorFilter.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
	... 14 more

**Comment by johnyannj** [comment]
java-chassis-bom is not right
please use  java-chassis-dependencies
