### ISSUE TITLE
服务启动过程中，偶现报错

### ISSUE THREAD

**Issue by helloworldhelloworld** [apache/servicecomb-java-chassis#2573]
o.a.s.s.r.cache.RefreshableMicroserviceCache | unknown error occurs while pulling instances
java.lang.NullPointerException: null
	at org.apache.servicecomb.serviceregistry.client.http.RestClientUtil.httpDo(RestClientUtil.java:76)
	at org.apache.servicecomb.serviceregistry.client.http.RestClientUtil.httpDo(RestClientUtil.java:71)
	at org.apache.servicecomb.serviceregistry.client.http.RestClientUtil.get(RestClientUtil.java:206)
	at org.apache.servicecomb.serviceregistry.client.http.ServiceRegistryClientImpl.findServiceInstances(ServiceRegistryClientImpl.java:767)
	at org.apache.servicecomb.serviceregistry.registry.cache.RefreshableMicroserviceCache.pullInstanceFromServiceCenter(RefreshableMicroserviceCache.java:130)
	at org.apache.servicecomb.serviceregistry.registry.cache.RefreshableMicroserviceCache.pullInstance(RefreshableMicroserviceCache.java:89)
	at org.apache.servicecomb.serviceregistry.registry.cache.RefreshableMicroserviceCache.safePullInstance(RefreshableMicroserviceCache.java:81)
	at org.apache.servicecomb.serviceregistry.registry.cache.RefreshableMicroserviceCache.refresh(RefreshableMicroserviceCache.java:71)
	at org.apache.servicecomb.serviceregistry.registry.cache.RefreshableServiceRegistryCache.lambda$findServiceCache$1(RefreshableServiceRegistryCache.java:120)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.apache.servicecomb.foundation.common.concurrent.ConcurrentHashMapEx.computeIfAbsent(ConcurrentHashMapEx.java:56)
	at org.apache.servicecomb.serviceregistry.registry.cache.RefreshableServiceRegistryCache.findServiceCache(RefreshableServiceRegistryCache.java:118)
	at org.apache.servicecomb.serviceregistry.registry.AbstractServiceRegistry.findMicroserviceCache(AbstractServiceRegistry.java:209)
	at org.apache.servicecomb.serviceregistry.registry.cache.AggregateMicroserviceCache.fillInMicroserviceCaches(AggregateMicroserviceCache.java:80)
	at org.apache.servicecomb.serviceregistry.registry.cache.AggregateMicroserviceCache.refreshInnerState(AggregateMicroserviceCache.java:65)
	at org.apache.servicecomb.serviceregistry.registry.cache.AggregateMicroserviceCache.refresh(AggregateMicroserviceCache.java:60)
	at org.apache.servicecomb.serviceregistry.registry.cache.AggregateMicroserviceCache.<init>(AggregateMicroserviceCache.java:55)
	at org.apache.servicecomb.serviceregistry.registry.cache.AggregateServiceRegistryCache.lambda$findServiceCache$0(AggregateServiceRegistryCache.java:53)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688)
	at org.apache.servicecomb.foundation.common.concurrent.ConcurrentHashMapEx.computeIfAbsent(ConcurrentHashMapEx.java:56)
	at org.apache.servicecomb.serviceregistry.registry.cache.AggregateServiceRegistryCache.findServiceCache(AggregateServiceRegistryCache.java:52)
	at org.apache.servicecomb.serviceregistry.RegistryUtils.findServiceInstance(RegistryUtils.java:152)
	at com.huawei.paas.monitor.AddressManager.updateServersFromSC(AddressManager.java:123)
	at com.huawei.paas.monitor.AddressManager.nextServer(AddressManager.java:107)
	at com.huawei.paas.monitor.DefaultMonitorDataPublisher.publish(DefaultMonitorDataPublisher.java:68)
	at com.huawei.paas.monitor.DataFactory.sendData(DataFactory.java:81)
	at com.huawei.paas.monitor.DataFactory.lambda$start$0(DataFactory.java:66)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

**Comment by liubao68** [comment]
你使用的那个版本? 另外， 这类错误可能需要全量的日志， 通过加载上下文看可能的错误。 可以从前面的日志看下是否有其他加载异常。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
