### ISSUE TITLE
vert.x-worker-thread处理PipedInputStream，连续8次取消response后，服务端无法正常返回响应消息

### ISSUE THREAD

**Issue by xxdwpl** [apache/servicecomb-java-chassis#2601]
**版本：**
1.3.2

**背景：**
服务端需要流式返回音频数据，采用http chunk方式传输。
客户端接收音频数据后播放，播放存在取消操作，也就是数据接收一部分之后，客户端会存在`response.close()`操作。
服务端在catch到Pipe closed异常后，会取消后续的业务操作，节省资源。
发现在客户端连续取消8次后，第9次请求客户端无法接收到response数据，等待约50s后，服务恢复正常，可以继续请求。

代码如下
```
// 服务端接口代码
public ResponseEntity<InputStream> serviceIntf(@RequestBody ...) {
    PipedInputStream inputStream = service.executBusiness(...);
    return ResponseEntity.ok().header(HttpHeaders.CONTENT_TYPE, "application/octet-stream").body(inputStream);
}

// 服务端启动异步线程做业务处理，并写入数据到outputStream，最后关闭流
public InputStream executBusiness(...) {
    PipedOutputStream outputStream = new PipedOutputStream();
    PipedInputStream  inputStream = new PipedInputStream(outputStream, 64 * 1024);
    threadPoolTaskExecutor.execute(() -> {
        try {
            ...
            outputStream.write(audioData);
            outputStream.flush();
        } catch (IOException e) {
            // 客户端主动关闭连接，取消后续业务处理
            if ("Pipe closed".equals(e.getMessage())) {
                cancelBusinessProcess();
            }
        } finally {
            outputStream.close();
        }
    });

}
```

**Comment by xxdwpl** [comment]
**在第9次请求等待期间打印线程堆栈：**
```

```

**Comment by xxdwpl** [comment]
1)查询官方文档，发现verticle-count默认值为CPU个数，业务使用的8C虚拟机，verticle-count=8，与问题现象能对应起来。
https://servicecomb.apache.org/references/java-chassis/zh_CN/transports/verticle-count.html

2)调整verticle-count=16，重新测试后问题有所优化，大约25次请求后会重现问题。

3)猜测可能是由于第17次请求时，第一个verticle实例释放了所以服务正常，到第25次之后verticle实现重新占满eventloop线程池。

请帮忙解答下，在http chunk场景下，客户端主动关闭response，verticle实例回收的逻辑是什么？是否跟`servicecomb.rest.server.connection.idleTimeoutInSeconds`配置有关？

**Comment by xxdwpl** [comment]
补充下，客户端主动关闭response时，cse错误日志：
```
2021-09-28 18:04:27.903 [vert.x-eventloop-thread-7] ERROR - [AbstractRestInvocation.java:onExecuteHttpServerFiltersFinish:301] - [] - Failed to execute HttpServerFilters, operation:XXXService.xx.xxx, request uri:/xx/xxx/xxx
java.util.concurrent.CompletionException: io.vertx.core.VertxException: Connection was closed
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326) ~[?:1.8.0_272]
        at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338) ~[?:1.8.0_272]
        at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:925) ~[?:1.8.0_272]
        at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:913) ~[?:1.8.0_272]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_272]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[?:1.8.0_272]
        at org.apache.servicecomb.foundation.vertx.stream.InputStreamToReadStream.handleException(InputStreamToReadStream.java:136) ~[foundation-vertx-1.3.2.jar!/:1.3.2]
        at org.apache.servicecomb.foundation.vertx.stream.PumpCommon.lambda$pump$0(PumpCommon.java:53) ~[foundation-vertx-1.3.2.jar!/:1.3.2]
        at io.vertx.core.http.impl.HttpServerResponseImpl.handleClosed(HttpServerResponseImpl.java:620) ~[vertx-core-3.9.4.jar!/:3.9.4]
        at io.vertx.core.http.impl.HttpServerResponseImpl.handleException(HttpServerResponseImpl.java:594) ~[vertx-core-3.9.4.jar!/:3.9.4]
        at io.vertx.core.http.impl.HttpServerRequestImpl.handleException(HttpServerRequestImpl.java:570) ~[vertx-core-3.9.4.jar!/:3.9.4]
        at io.vertx.core.http.impl.Http1xServerConnection.handleClosed(Http1xServerConnection.java:413) ~[vertx-core-3.9.4.jar!/:3.9.4]
        at io.vertx.core.net.impl.VertxHandler.lambda$channelInactive$4(VertxHandler.java:152) ~[vertx-core-3.9.4.jar!/:3.9.4]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) [vertx-core-3.9.4.jar!/:3.9.4]
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43) [vertx-core-3.9.4.jar!/:3.9.4]
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229) [vertx-core-3.9.4.jar!/:3.9.4]
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:221) [vertx-core-3.9.4.jar!/:3.9.4]
        at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:152) [vertx-core-3.9.4.jar!/:3.9.4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) [netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) [netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) [netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) [netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) [netty-handler-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) [netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) [netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) [netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) [netty-codec-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) [netty-codec-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) [netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) [netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) [netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) [netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) [netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) [netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) [netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:819) [netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-common-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-common-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.59.Final.jar!/:4.1.59.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.59.Final.jar!/:4.1.59.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: io.vertx.core.VertxException: Connection was closed
```

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
