### ISSUE TITLE
CseRestTemplate调用postForObject报错"Can not execute sync logic in event loop."

### ISSUE THREAD

**Issue by Snowfish1994** [apache/servicecomb-java-chassis#2607]
版本：2.1.5
jdk:1.8
场景：CSE网元间请求，请求url为cse://CCOPMService/rest/operation/queryappkey/v1.0

debug报错位置：
![image](https://user-images.githubusercontent.com/16447839/136903021-fb948c49-a88d-4634-bee7-8e4b13109dc5.png)

其中：所使用的cseRestTemplate：
![image](https://user-images.githubusercontent.com/16447839/136903495-23a5def5-bbed-4458-8895-f9df2945eff9.png)

线程调用堆栈：
innerSyncInvoke:151, InvokerUtils (org.apache.servicecomb.core.provider.consumer)
doInvoke:244, CseClientHttpRequest (org.apache.servicecomb.provider.springmvc.reference)
invoke:234, CseClientHttpRequest (org.apache.servicecomb.provider.springmvc.reference)
execute:177, CseClientHttpRequest (org.apache.servicecomb.provider.springmvc.reference)
doExecute:776, RestTemplate (org.springframework.web.client)
execute:711, RestTemplate (org.springframework.web.client)
**postForObject:82, CseRestTemplate (org.apache.servicecomb.provider.springmvc.reference)**
queryFilePathInfo:117, OpmClient (com.huawei.orch.http.opm)
getAppKeyByIMSIOrCallee:181, AppData (com.huawei.orch.data.redis)
queryFilePathInfoForMixCso:143, AppData (com.huawei.orch.data.redis)
sendToCCF:1043, XModeNotifyUtil (com.huawei.orch.notify.resale)
sendCdr:1026, XModeNotifyUtil (com.huawei.orch.notify.resale)
updateNumMsg:509, XModeNotifyUtil (com.huawei.orch.notify.resale)
executeReceiveSmsScript:463, XModeNotifyUtil (com.huawei.orch.notify.resale)
doEventAfterResp:42, XModeReceiveSmsStrategy (com.huawei.orch.notify.resale)
accept:-1, 436079316 (com.huawei.orch.notify.resale.XModeReceiveSmsStrategy$$Lambda$3520)
onSuccess:54, XModeMicroCallback (com.huawei.orch.http.cse)
onSuccess:25, XModeMicroCallback (com.huawei.orch.http.cse)
onSuccess:72, ListenableFutureAdapter$1 (org.springframework.util.concurrent)
notifySuccess:76, ListenableFutureCallbackRegistry (org.springframework.util.concurrent)
success:142, ListenableFutureCallbackRegistry (org.springframework.util.concurrent)
lambda$new$0:59, CompletableToListenableFutureAdapter (org.springframework.util.concurrent)
accept:-1, 1889428700 (org.springframework.util.concurrent.CompletableToListenableFutureAdapter$$Lambda$4092)
uniWhenComplete:774, CompletableFuture (java.util.concurrent)
tryFire:750, CompletableFuture$UniWhenComplete (java.util.concurrent)
postComplete:488, CompletableFuture (java.util.concurrent)
complete:1975, CompletableFuture (java.util.concurrent)
lambda$doAsyncInvoke$0:67, CseAsyncClientHttpRequest (org.apache.servicecomb.provider.springmvc.reference.async)
handle:-1, 705070259 (org.apache.servicecomb.provider.springmvc.reference.async.CseAsyncClientHttpRequest$$Lambda$4090)
lambda$reactiveInvoke$0:196, InvokerUtils (org.apache.servicecomb.core.provider.consumer)
handle:-1, 351352310 (org.apache.servicecomb.core.provider.consumer.InvokerUtils$$Lambda$4091)
lambda$handle$0:199, LoadbalanceHandler (org.apache.servicecomb.loadbalance)
handle:-1, 1664606749 (org.apache.servicecomb.loadbalance.LoadbalanceHandler$$Lambda$3472)
complete:46, AsyncResponse (org.apache.servicecomb.swagger.invocation)
onExecutionSuccess:354, LoadbalanceHandler$3 (org.apache.servicecomb.loadbalance)
onExecutionSuccess:319, LoadbalanceHandler$3 (org.apache.servicecomb.loadbalance)
onExecutionSuccess:143, ExecutionContextListenerInvoker (com.netflix.loadbalancer.reactive)
onExecutionSuccess:131, ExecutionContextListenerInvoker (com.netflix.loadbalancer.reactive)
onNext:324, LoadBalancerCommand$3$1$1 (com.netflix.loadbalancer.reactive)
onNext:96, OnSubscribeDoOnEach$DoOnEachSubscriber (rx.internal.operators)
lambda$null$0:420, LoadbalanceHandler$4 (org.apache.servicecomb.loadbalance)
handle:-1, 265977596 (org.apache.servicecomb.loadbalance.LoadbalanceHandler$4$$Lambda$3496)
complete:46, AsyncResponse (org.apache.servicecomb.swagger.invocation)
complete:255, RestClientInvocation (org.apache.servicecomb.transport.rest.client.http)
lambda$processResponseBody$4:239, RestClientInvocation (org.apache.servicecomb.transport.rest.client.http)
run:-1, 1078965787 (org.apache.servicecomb.transport.rest.client.http.RestClientInvocation$$Lambda$3506)
execute:28, ReactiveResponseExecutor (org.apache.servicecomb.core.provider.consumer)
processResponseBody:230, RestClientInvocation (org.apache.servicecomb.transport.rest.client.http)
handle:-1, 1238004075 (org.apache.servicecomb.transport.rest.client.http.RestClientInvocation$$Lambda$3505)
notifyHandler:292, HttpClientResponseImpl$BodyHandler (io.vertx.core.http.impl)
lambda$bodyHandler$0:193, HttpClientResponseImpl (io.vertx.core.http.impl)
handle:-1, 1873713345 (io.vertx.core.http.impl.HttpClientResponseImpl$$Lambda$492)
handleEnd:248, HttpClientResponseImpl (io.vertx.core.http.impl)
lambda$beginResponse$0:484, Http1xClientConnection$StreamImpl (io.vertx.core.http.impl)
handle:-1, 1737615027 (io.vertx.core.http.impl.Http1xClientConnection$StreamImpl$$Lambda$489)
handleEvent:237, InboundBuffer (io.vertx.core.streams.impl)
write:127, InboundBuffer (io.vertx.core.streams.impl)
endResponse:503, Http1xClientConnection$StreamImpl (io.vertx.core.http.impl)
access$000:242, Http1xClientConnection$StreamImpl (io.vertx.core.http.impl)
handleResponseEnd:644, Http1xClientConnection (io.vertx.core.http.impl)
handleHttpMessage:604, Http1xClientConnection (io.vertx.core.http.impl)
handleMessage:577, Http1xClientConnection (io.vertx.core.http.impl)
handle:-1, 1345436 (io.vertx.core.net.impl.VertxHandler$$Lambda$484)
executeTask:366, ContextImpl (io.vertx.core.impl)
execute:43, EventLoopContext (io.vertx.core.impl)
executeFromIO:229, ContextImpl (io.vertx.core.impl)
channelRead:164, VertxHandler (io.vertx.core.net.impl)
invokeChannelRead:379, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelRead:365, AbstractChannelHandlerContext (io.netty.channel)
fireChannelRead:357, AbstractChannelHandlerContext (io.netty.channel)
fireChannelRead:436, CombinedChannelDuplexHandler$DelegatingChannelHandlerContext (io.netty.channel)
fireChannelRead:324, ByteToMessageDecoder (io.netty.handler.codec)
channelRead:296, ByteToMessageDecoder (io.netty.handler.codec)
channelRead:251, CombinedChannelDuplexHandler (io.netty.channel)
invokeChannelRead:379, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelRead:365, AbstractChannelHandlerContext (io.netty.channel)
fireChannelRead:357, AbstractChannelHandlerContext (io.netty.channel)
channelRead:286, IdleStateHandler (io.netty.handler.timeout)
invokeChannelRead:379, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelRead:365, AbstractChannelHandlerContext (io.netty.channel)
fireChannelRead:357, AbstractChannelHandlerContext (io.netty.channel)
channelRead:1410, DefaultChannelPipeline$HeadContext (io.netty.channel)
invokeChannelRead:379, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelRead:365, AbstractChannelHandlerContext (io.netty.channel)
fireChannelRead:919, DefaultChannelPipeline (io.netty.channel)
read:166, AbstractNioByteChannel$NioByteUnsafe (io.netty.channel.nio)
processSelectedKey:719, NioEventLoop (io.netty.channel.nio)
processSelectedKeysOptimized:655, NioEventLoop (io.netty.channel.nio)
processSelectedKeys:581, NioEventLoop (io.netty.channel.nio)
run:493, NioEventLoop (io.netty.channel.nio)
run:989, SingleThreadEventExecutor$4 (io.netty.util.concurrent)
run:74, ThreadExecutorMap$2 (io.netty.util.internal)
run:30, FastThreadLocalRunnable (io.netty.util.concurrent)
run:748, Thread (java.lang)

**Comment by Snowfish1994** [comment]
错误日志
2021-10-12 15:19:58,846|ERROR|invoke failed, CCOPMService.AppControl.getApp|vert.x-eventloop-thread-3|org.apache.servicecomb.core.provider.consumer.InvokerUtils.innerSyncInvoke(InvokerUtils.java:167)
java.lang.IllegalStateException: Can not execute sync logic in event loop. 
	at org.apache.servicecomb.core.provider.consumer.InvokerUtils.innerSyncInvoke(InvokerUtils.java:151) ~[java-chassis-core-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.doInvoke(CseClientHttpRequest.java:244) ~[provider-springmvc-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.invoke(CseClientHttpRequest.java:234) ~[provider-springmvc-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.execute(CseClientHttpRequest.java:177) ~[provider-springmvc-2.1.5.jar:2.1.5]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:776) ~[spring-web-5.3.4.jar:5.3.4]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711) ~[spring-web-5.3.4.jar:5.3.4]
	at org.apache.servicecomb.provider.springmvc.reference.CseRestTemplate.postForObject(CseRestTemplate.java:82) ~[provider-springmvc-2.1.5.jar:2.1.5]
	at com.huawei.orch.http.opm.OpmClient.queryFilePathInfo(OpmClient.java:117) ~[main/:?]
	at com.huawei.orch.data.redis.AppData.getAppKeyByIMSIOrCallee(AppData.java:181) ~[main/:?]
	at com.huawei.orch.data.redis.AppData.queryFilePathInfoForMixCso(AppData.java:143) ~[main/:?]
	at com.huawei.orch.notify.resale.XModeNotifyUtil.sendToCCF(XModeNotifyUtil.java:1043) ~[main/:?]
	at com.huawei.orch.notify.resale.XModeNotifyUtil.sendCdr(XModeNotifyUtil.java:1026) ~[main/:?]
	at com.huawei.orch.notify.resale.XModeNotifyUtil.updateNumMsg(XModeNotifyUtil.java:509) ~[main/:?]
	at com.huawei.orch.notify.resale.XModeNotifyUtil.executeReceiveSmsScript(XModeNotifyUtil.java:463) ~[main/:?]
	at com.huawei.orch.notify.resale.XModeReceiveSmsStrategy.doEventAfterResp(XModeReceiveSmsStrategy.java:42) ~[main/:?]
	at com.huawei.orch.http.cse.XModeMicroCallback.onSuccess(XModeMicroCallback.java:54) ~[main/:?]
	at com.huawei.orch.http.cse.XModeMicroCallback.onSuccess(XModeMicroCallback.java:25) ~[main/:?]
	at org.springframework.util.concurrent.ListenableFutureAdapter$1.onSuccess(ListenableFutureAdapter.java:72) ~[spring-core-5.3.4.jar:5.3.4]
	at org.springframework.util.concurrent.ListenableFutureCallbackRegistry.notifySuccess(ListenableFutureCallbackRegistry.java:76) ~[spring-core-5.3.4.jar:5.3.4]
	at org.springframework.util.concurrent.ListenableFutureCallbackRegistry.success(ListenableFutureCallbackRegistry.java:142) ~[spring-core-5.3.4.jar:5.3.4]
	at org.springframework.util.concurrent.CompletableToListenableFutureAdapter.lambda$new$0(CompletableToListenableFutureAdapter.java:59) ~[spring-core-5.3.4.jar:5.3.4]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) ~[?:1.8.0_252]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) ~[?:1.8.0_252]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_252]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) ~[?:1.8.0_252]
	at org.apache.servicecomb.provider.springmvc.reference.async.CseAsyncClientHttpRequest.lambda$doAsyncInvoke$0(CseAsyncClientHttpRequest.java:67) ~[provider-springmvc-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.core.provider.consumer.InvokerUtils.lambda$reactiveInvoke$0(InvokerUtils.java:196) ~[java-chassis-core-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.loadbalance.LoadbalanceHandler.lambda$handle$0(LoadbalanceHandler.java:199) ~[handler-loadbalance-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.swagger.invocation.AsyncResponse.complete(AsyncResponse.java:46) ~[swagger-invocation-core-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.loadbalance.LoadbalanceHandler$3.onExecutionSuccess(LoadbalanceHandler.java:354) ~[handler-loadbalance-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.loadbalance.LoadbalanceHandler$3.onExecutionSuccess(LoadbalanceHandler.java:319) ~[handler-loadbalance-2.1.5.jar:2.1.5]
	at com.netflix.loadbalancer.reactive.ExecutionContextListenerInvoker.onExecutionSuccess(ExecutionContextListenerInvoker.java:143) ~[ribbon-loadbalancer-2.3.0.jar:2.3.0]
	at com.netflix.loadbalancer.reactive.ExecutionContextListenerInvoker.onExecutionSuccess(ExecutionContextListenerInvoker.java:131) ~[ribbon-loadbalancer-2.3.0.jar:2.3.0]
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1$1.onNext(LoadBalancerCommand.java:324) ~[ribbon-loadbalancer-2.3.0.jar:2.3.0]
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:96) ~[rxjava-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.loadbalance.LoadbalanceHandler$4.lambda$null$0(LoadbalanceHandler.java:420) ~[handler-loadbalance-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.swagger.invocation.AsyncResponse.complete(AsyncResponse.java:46) ~[swagger-invocation-core-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.complete(RestClientInvocation.java:255) ~[transport-rest-client-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.lambda$processResponseBody$4(RestClientInvocation.java:239) ~[transport-rest-client-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.core.provider.consumer.ReactiveResponseExecutor.execute(ReactiveResponseExecutor.java:28) ~[java-chassis-core-2.1.5.jar:2.1.5]
	at org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.processResponseBody(RestClientInvocation.java:230) ~[transport-rest-client-2.1.5.jar:2.1.5]
	at io.vertx.core.http.impl.HttpClientResponseImpl$BodyHandler.notifyHandler(HttpClientResponseImpl.java:292) ~[vertx-core-3.9.8.jar:3.9.8]
	at io.vertx.core.http.impl.HttpClientResponseImpl.lambda$bodyHandler$0(HttpClientResponseImpl.java:193) ~[vertx-core-3.9.8.jar:3.9.8]
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:248) ~[vertx-core-3.9.8.jar:3.9.8]
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$beginResponse$0(Http1xClientConnection.java:484) ~[vertx-core-3.9.8.jar:3.9.8]
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237) ~[vertx-core-3.9.8.jar:3.9.8]
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127) ~[vertx-core-3.9.8.jar:3.9.8]
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.endResponse(Http1xClientConnection.java:503) ~[vertx-core-3.9.8.jar:3.9.8]
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.access$000(Http1xClientConnection.java:242) ~[vertx-core-3.9.8.jar:3.9.8]
	at io.vertx.core.http.impl.Http1xClientConnection.handleResponseEnd(Http1xClientConnection.java:644) ~[vertx-core-3.9.8.jar:3.9.8]
	at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:604) ~[vertx-core-3.9.8.jar:3.9.8]
	at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:577) ~[vertx-core-3.9.8.jar:3.9.8]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) [vertx-core-3.9.8.jar:3.9.8]
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43) [vertx-core-3.9.8.jar:3.9.8]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229) [vertx-core-3.9.8.jar:3.9.8]
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:164) [vertx-core-3.9.8.jar:3.9.8]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.59.Final.jar:4.1.59.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
2021-10-12 15:19:58,852|ERROR|invocation type: CONSUMER, handler chain: [org.apache.servicecomb.qps.ConsumerQpsFlowControlHandler@f1b5295, org.apache.servicecomb.loadbalance.LoadbalanceHandler@49ec5b1b, org.apache.servicecomb.core.handler.impl.TransportClientHandler@433d796a]|vert.x-eventloop-thread-3|org.apache.servicecomb.core.provider.consumer.InvokerUtils.innerSyncInvoke(InvokerUtils.java:168)
2021-10-12 15:19:58,861|WARN |slow(1000 ms) invocation, CONSUMER  CCOPMService.AppControl.getApp:
  http method: POST
  url        : /rest/operation/queryappkey/v1.0/
  server     : unknown
  status code: 490
  total      : 0.0 ms
    prepare                : 0.0 ms
    handlers request       : 0.0 ms
    client filters request : 0.0 ms
    send request           : 0.0 ms
    get connection         : 0.0 ms
    write to buf           : 0.0 ms
    wait response          : 0.0 ms
    wake consumer          : 0.0 ms
    client filters response: 0.0 ms
    handlers response      : 0.0 ms|vert.x-eventloop-thread-3|org.apache.servicecomb.core.tracing.TraceIdLogger.warn(TraceIdLogger.java:56)
2021-10-12 15:19:58,862|ERROR|Something wrong happens during getting the AudioFilePathResponse! InvocationException: code=490;msg=CommonExceptionData [message=Unexpected consumer error, please check logs for details]
	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.doCreate(ExceptionFactory.java:81)
	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.convertException(ExceptionFactory.java:124)
	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.convertConsumerException(ExceptionFactory.java:85)
	at org.apache.servicecomb.swagger.invocation.Response.createConsumerFail(Response.java:178)
	at org.apache.servicecomb.core.provider.consumer.InvokerUtils.innerSyncInvoke(InvokerUtils.java:171)
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.doInvoke(CseClientHttpRequest.java:244)
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.invoke(CseClientHttpRequest.java:234)
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.execute(CseClientHttpRequest.java:177)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:776)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)|vert.x-eventloop-thread-3|com.huawei.orch.http.opm.OpmClient.queryFilePathInfo(OpmClient.java:128)

**Comment by Snowfish1994** [comment]
> 可以查一下依赖 是不是引用了edge-core jar包 你这个问题和 #2286 很类似

查了一下依赖树，并不包含这个包
