### ISSUE TITLE
消费方偶现某节点调用某服务报 new producer not running or not deployed错误

### ISSUE THREAD

**Issue by zhoutianli518** [apache/servicecomb-java-chassis#2633]
消费方某个节点调用某个服务方一直报如下错误。
此消费方是集群节点，有几十个节点，调用的下游微服务有十几个。
现象是只有某个消费方节点调用某下游服务接口一直报此错。此消费节点的其它兄弟节点没有这个问题。此报错的节点调用其它服务接口没有这个问题。重启此消费方节点故障恢复。 servicecomb-java-chassis版本为2.3.5

java.lang.IllegalStateException: Schema not exist, microserviceName=vmall-rushBuy2-server, schemaId=IRushBuyQualif, consumer interface=com.huawei.vmall.rushbuy.api.rpc.IRushBuyQualif; new producer not running or not deployed.
	at org.apache.servicecomb.provider.pojo.PojoConsumerMetaRefresher.refreshMeta(PojoConsumerMetaRefresher.java:99)
	at org.apache.servicecomb.provider.pojo.PojoConsumerMetaRefresher.ensureMetaAvailable(PojoConsumerMetaRefresher.java:81)
	at org.apache.servicecomb.provider.pojo.PojoConsumerMetaRefresher.getLatestMeta(PojoConsumerMetaRefresher.java:58)
	at org.apache.servicecomb.provider.pojo.PojoInvocationCreator.create(PojoInvocationCreator.java:26)

**Comment by liubao68** [comment]
这个现象看起来不合乎预期，但是这些信息无法支持问题分析。 需要补充下问题出现的过程，能够重现问题就好了。

**Comment by liubao68** [comment]
close old issues, please feel free to submit a new one if the problem still exists.
