### ISSUE TITLE
使用@path@post注解时，请求参数中存在Boolean类型时会把Boolean类型识别为Body

### ISSUE THREAD

**Issue by lengshanwudi** [apache/servicecomb-java-chassis#2735]
bool值isSync、isGray定义在IntentRequestHeaders 实体类中
```
    public CompletableFuture<xxxx> executeSkill(
        @BeanParam @NotNull IntentRequestHeaders intentRequestHeaders,
        @RequestBody @NotNull IntentRequest intentRequest) {}
```
```
@HeaderParam("x-is-sync")
  private Boolean isSync;
  @HeaderParam("x-is-gray")
  private Boolean isGray;
```

报错信息：
_java.lang.IllegalStateException: defined 3 body parameter.
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.initParameterGenerators(AbstractOperationGenerator.java:222)
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.scanMethodParameters(AbstractOperationGenerator.java:192)
	at org.apache.servicecomb.swagger.generator.core.AbstractOperationGenerator.generate(AbstractOperationGenerator.java:152)
	at org.apache.servicecomb.swagger.generator.core.AbstractSwaggerGenerator.scanMethods(AbstractSwaggerGenerator.java:297)_

**Comment by liubao68** [comment]
```
@HeaderParam("x-is-sync")
  private Boolean isSync;
  @HeaderParam("x-is-gray")
  private Boolean isGray;
```

是 IntentRequest  的属性吗？

**Comment by zhaozw** [comment]
Boolean 类型的名字不要加is，直接sync和gray，否则会有问题，通过反射找不到对应的变量
