### ISSUE TITLE
Duplicate schemaId validation can be more strict

### ISSUE THREAD

**Issue by yhs0092** [apache/servicecomb-java-chassis#2821]
Hi, we're using Java-Chassis 1.3.7 and find that if some controllers are using the same `schemaId`(carried by annotation `@RestSchema`), Java-Chassis does not throw any Exception at the boot up stage. And there may be some strange and obscure problem caused by this problem at the runtime stage.

I guess we can put certain validation logic in the boot up stage, to point out such problem explicitly.

**Comment by liubao68** [comment]
I tested 2.8.x and 3.0.0, will throw exception

```
Exception in thread "main" java.lang.IllegalStateException: ServiceComb init failed.
	at org.apache.servicecomb.core.SCBEngine.run(SCBEngine.java:335)
	at org.apache.servicecomb.core.SCBApplicationListener.onApplicationEvent(SCBApplicationListener.java:89)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:941)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:95)
	at org.apache.servicecomb.foundation.common.utils.BeanUtils.init(BeanUtils.java:65)
	at org.apache.servicecomb.foundation.common.utils.BeanUtils.init(BeanUtils.java:56)
	at org.apache.servicecomb.demo.springmvc.SpringmvcServer.main(SpringmvcServer.java:26)
Caused by: java.lang.IllegalStateException: failed to register SchemaMeta caused by duplicated schemaId, appId=springmvctest, microserviceName=springmvc, schemaId=RetrySchema.
	at org.apache.servicecomb.core.definition.MicroserviceMeta.registerSchemaMeta(MicroserviceMeta.java:125)
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.registerSchema(ProducerProviderManager.java:106)
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.registerProducerMetas(ProducerProviderManager.java:87)
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.init(ProducerProviderManager.java:73)
	at org.apache.servicecomb.core.SCBEngine.doRun(SCBEngine.java:375)
	at org.apache.servicecomb.core.SCBEngine.run(SCBEngine.java:322)
	... 13 more
```

Will not fix in 1.3.x any more, please upgrade.
