### ISSUE TITLE
开发edge-service,服务已正常启动，可以进行路由转发，但是在服务内部调用其他微服务出现了问题

### ISSUE THREAD

**Issue by Zhuwanshun** [apache/servicecomb-java-chassis#2937]
问题和https://github.com/apache/servicecomb-java-chassis/issues/2286的报错一致，我尝试去除了edge-core的jar确实可以了，但是此时路由转发的功能丢失了，请问下edge-service服务中调用第三方服务有什么限制吗？
java.lang.IllegalStateException: Can not execute sync logic in event loop. 
	at org.apache.servicecomb.core.provider.consumer.InvokerUtils.innerSyncInvoke(InvokerUtils.java:152) ~[java-chassis-core-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.doInvoke(CseClientHttpRequest.java:244) ~[provider-springmvc-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.invoke(CseClientHttpRequest.java:234) ~[provider-springmvc-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.provider.springmvc.reference.CseClientHttpRequest.execute(CseClientHttpRequest.java:177) ~[provider-springmvc-2.6.0.jar:2.6.0]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:776) ~[spring-web-5.3.14.jar:5.3.14]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:751) ~[spring-web-5.3.14.jar:5.3.14]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:621) ~[spring-web-5.3.14.jar:5.3.14]
	at org.apache.servicecomb.provider.springmvc.reference.RestTemplateWrapper.exchange(RestTemplateWrapper.java:214) ~[provider-springmvc-2.6.0.jar:2.6.0]
	at com.huawei.intelligent.common.rest.RestClientWrapper.sendGetCSERequest(RestClientWrapper.java:147) ~[common-cse-2.0.0.jar:?]
	at com.huawei.intelligent.user.service.provider.UserProvider.getUserDetail(UserProvider.java:49) ~[classes/:?]
	at com.huawei.intelligent.user.service.W3TokenGranter.grant(W3TokenGranter.java:48) ~[classes/:?]
	at com.huawei.intelligent.user.controller.TokenEndpoint.grantToken(TokenEndpoint.java:33) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.doInvoke(ProducerOperationHandler.java:125) ~[java-chassis-core-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.syncInvoke(ProducerOperationHandler.java:110) ~[java-chassis-core-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.invoke(ProducerOperationHandler.java:63) ~[java-chassis-core-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.core.handler.impl.ProducerOperationHandler.handle(ProducerOperationHandler.java:54) ~[java-chassis-core-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.core.Invocation.next(Invocation.java:274) ~[java-chassis-core-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.qps.ProviderQpsFlowControlHandler.handle(ProviderQpsFlowControlHandler.java:35) ~[handler-flowcontrol-qps-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.core.Invocation.next(Invocation.java:274) ~[java-chassis-core-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.doInvoke(AbstractRestInvocation.java:251) ~[common-rest-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke(AbstractRestInvocation.java:222) ~[common-rest-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor(AbstractRestInvocation.java:206) ~[common-rest-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(AbstractRestInvocation.java:162) ~[common-rest-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.core.executor.ReactiveExecutor.execute(ReactiveExecutor.java:30) ~[java-chassis-core-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.scheduleInvocation(AbstractRestInvocation.java:147) ~[common-rest-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.common.rest.RestProducerInvocation.invoke(RestProducerInvocation.java:52) ~[common-rest-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.transport.rest.vertx.VertxRestDispatcher.onRequest(VertxRestDispatcher.java:219) ~[transport-rest-vertx-2.6.0.jar:2.6.0]
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1127) ~[vertx-web-4.1.5.jar:4.1.5]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:151) ~[vertx-web-4.1.5.jar:4.1.5]
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133) ~[vertx-web-4.1.5.jar:4.1.5]
	at org.apache.servicecomb.transport.rest.vertx.RestBodyHandler$BHandler.doEnd(RestBodyHandler.java:362) ~[transport-rest-vertx-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.transport.rest.vertx.RestBodyHandler$BHandler.end(RestBodyHandler.java:339) ~[transport-rest-vertx-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.transport.rest.vertx.RestBodyHandler.lambda$handle$0(RestBodyHandler.java:112) ~[transport-rest-vertx-2.6.0.jar:2.6.0]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.http.impl.Http1xServerRequest.onEnd(Http1xServerRequest.java:565) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.http.impl.Http1xServerRequest.handleEnd(Http1xServerRequest.java:548) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:71) [vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:163) [vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.http.impl.Http1xServerConnection.onEnd(Http1xServerConnection.java:189) [vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.http.impl.Http1xServerConnection.onContent(Http1xServerConnection.java:179) [vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.http.impl.Http1xServerConnection.handleOther(Http1xServerConnection.java:159) [vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:147) [vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155) [vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:154) [vertx-core-4.1.5.jar:4.1.5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:99) [netty-codec-http-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372) [netty-handler-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235) [netty-handler-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284) [netty-handler-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [netty-codec-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) [netty-codec-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
2022-05-18 15:59:05.313[UTC:20220518T075905]|     || slow(1000 ms) invocation, CONSUMER  user-mgmt.user.innerQueryUser:
  http method: GET
  url        : /user-mgmt/inner/user/
  server     : unknown
  status code: 490
  total      : 0.0 ms
    prepare                : 0.0 ms
    handlers request       : 0.0 ms
    client filters request : 0.0 ms
    send request           : 0.0 ms
    get connection         : 0.0 ms
    write to buf           : 0.0 ms
    wait response          : 0.0 ms
    wake consumer          : 0.0 ms
    client filters response: 0.0 ms
    handlers response      : 0.0 ms org.apache.servicecomb.core.tracing.TraceIdLogger.warn(TraceIdLogger.java:56)

**Comment by zhaozw** [comment]
可否贴一下pom文件

**Comment by Zhuwanshun** [comment]
开发的edge-service开启了TSL通信，pom文件加了以下依赖 servicecomb.version 2.6.0
        <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>edge-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>handler-loadbalance</artifactId>
        </dependency>

        <dependency>
            <groupId>xxxxxxx</groupId>
            <artifactId>common-cse</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>solution-basic</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>transport-highway</artifactId>
                    <groupId>org.apache.servicecomb</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>netty-tcnative-boringssl-static</artifactId>
                    <groupId>io.netty</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>java-chassis-spring-boot-starter-standalone</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>spring-boot-starter-logging</artifactId>
                    <groupId>org.springframework.boot</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>tomcat-embed-logging-juli</artifactId>
                    <groupId>org.apache.tomcat.embed</groupId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
common-cse里主要有这些依赖
<dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>swagger-invocation-validator</artifactId>
            <version>${servicecomb.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>foundation-ssl</artifactId>
            <version>${servicecomb.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-tcnative-boringssl-static</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>provider-springmvc</artifactId>
            <version>${servicecomb.version}</version>
        </dependency>

**Comment by zhaozw** [comment]
但是在服务内部调用其他微服务出现了问题,这个服务里面是否有edge-core依赖？edge-service和这个服务不是一个项目吧？

**Comment by Zhuwanshun** [comment]
没有，不是一个服务。在edge-service使用RestClientWrapper调用其他微服务出现的问题

**Comment by liubao68** [comment]
edge service 工作在 reactive 模式， 需要使用异步处理， 参考 [reactive](https://servicecomb.apache.org/references/java-chassis/zh_CN/build-provider/reactive.html)

**Comment by Zhuwanshun** [comment]
已解决

**Comment by guoyangming123** [comment]
@Zhuwanshun 你好，请问下你是怎么解决的呢？我也遇到了一样的问题。
