### ISSUE TITLE
Error calling api's through Edge gateway <java.lang.IllegalArgumentException: Invalid character found in method name>

### ISSUE THREAD

**Issue by shri-arunraj** [apache/servicecomb-java-chassis#3302]
Hi ,
I have spring boot based servlet java chassis service. When calling the API's through gateway, the API requests one in every 3 hits failing with the below. Its so weird given all the requests are not failing.

`
2022-08-26 22:26:27.627  INFO 10936 --- [Center Task [0]] o.a.s.s.task.ServiceCenterTaskMonitor    : sc task interval changed from -1 to 30
2022-08-26 22:26:36.716  INFO 10936 --- [nio-9095-exec-3] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in method name [.10x0d0x0ax-cse-target-microservice: ]. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:419) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:271) ~[tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.coyote.AbstractProcessorLight.checkForPipelinedData(AbstractProcessorLight.java:108) [tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:60) [tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) [tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) [tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.62.jar:9.0.62]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.62.jar:9.0.62]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_241]
`
Looking forward for insights. Thanks!

**Comment by shri-arunraj** [comment]
@liubao68 

 On the internet, it was said to add 
`server:
  maxHttpHeaderSize: 1MB ` 

to the to Spring boot config to resolve this error on the tomcat side. But it didn't worked.

Later on the Internet to see a paste, said it was originally HTTP request error using HTTPS way request will be reported that the wrong.


The weird thing is only  3 out of 10 requests are failing with this error. And not all requests. And also direct requests to the service won't fail. Only the requests routed via edge is failing. So i presume the error is with the requests posted by edge service. 

Is it possible that edge sever is making `https` request instead of `http`?. 

Digging this error for a long time. Looking forward for some pointers ~
Thanks,
Meenakshi

**Comment by liubao68** [comment]
Do you add some user define context to InvocationContext in edge service? From your logs, seem some special characters which may not properly encoded before adding to InvocationContext（ which is sent using http header and http header can only have ISO-8859-1 character set）

**Comment by liubao68** [comment]
BTW, The lastest version add a fix https://github.com/apache/servicecomb-java-chassis/pull/3045 to support this.

**Comment by shri-arunraj** [comment]
@liubao68  Thanks for your response! Yeah I have written a custom HttpClientFilter which has messed up with headers. It worked after fix up. Thanks for your time!

Cheers,
Meenakshi

**Comment by jinadu4oyeniyi** [comment]
Hello people,
I am currently having exactly same issue. I am a support engineer and not a developer. 
What suggestions should I give my developer?

**Comment by shri-arunraj** [comment]
@jinadu4oyeniyi 

THe problem was that I have register 2 instances of third party API service and one of them was down. Since dynamic routing is not enabled for the third party Services, it ended up in this error.
