### ISSUE TITLE
Recover service instance from isolation 接口仍然不通

### ISSUE THREAD

**Issue by xuhailangHW** [apache/servicecomb-java-chassis#3334]
org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=490;msg=CommonExceptionData [message=Unexpected consumer error, please check logs for details]
        at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.doCreate(ExceptionFactory.java:81)
        at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.convertException(ExceptionFactory.java:124)
        at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.convertConsumerException(ExceptionFactory.java:85)
        at org.apache.servicecomb.swagger.invocation.Response.createConsumerFail(Response.java:178)
        at org.apache.servicecomb.swagger.invocation.Response.createFail(Response.java:171)
        at org.apache.servicecomb.swagger.invocation.Response.failResp(Response.java:219)
        at org.apache.servicecomb.bizkeeper.FallbackPolicyManager.getFallbackResponse(FallbackPolicyManager.java:44)

**Comment by yanghao605** [comment]
![image](https://user-images.githubusercontent.com/73453250/191159967-b850af7d-01ab-4f06-b4b6-afee62104fa1.png)
或许可以看看Fallback的配置
