### ISSUE TITLE
 Application run failed  系统运行着突然失败了。。。，版本：<java-chassis.version>1.2.0</java-chassis.version>

### ISSUE THREAD

**Issue by ferrymo** [apache/servicecomb-java-chassis#3398]
2022-10-14 17:14:16.265 [registry-vert.x-eventloop-thread-0] ERROR o.a.s.serviceregistry.client.http.RestUtils - GET /v4/default/registry/instances?rev=c8e8916b2447f7ec663f4ba7411d6c0c9881e824&appId=paas-prd&global=true&serviceName=paas-prd%3Apaas-api&env=production&version=0.0.0%2B fail, endpoint is servicecenter:30100, message: Connection was closed
2022-10-14 17:15:14.033 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: ServiceComb init failed.
	at org.apache.servicecomb.core.SCBEngine.init(SCBEngine.java:217)
	at org.apache.servicecomb.core.CseApplicationListener.onApplicationEvent(CseApplicationListener.java:81)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:105)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:78)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:332)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinderInstance(DefaultBinderFactory.java:250)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.doGetBinder(DefaultBinderFactory.java:174)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinder(DefaultBinderFactory.java:120)
	at org.springframework.cloud.stream.binding.BindingService.getBinder(BindingService.java:313)
	at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:214)
	at org.springframework.cloud.stream.binding.BindableProxyFactory.createAndBindOutputs(BindableProxyFactory.java:262)
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.doStartWithBindable(OutputBindingLifecycle.java:55)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:47)
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:34)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:879)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:163)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at cn.medsci.collect.MainApplication.main(MainApplication.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.IllegalStateException: The schema(id=[project]) content held by this instance and the service center is different. You need to increment microservice version before deploying. Or you can configure service_description.environment=development to work in development environment and ignore this error
	at org.apache.servicecomb.serviceregistry.task.MicroserviceRegisterTask.compareAndReRegisterSchema(MicroserviceRegisterTask.java:277)
	at org.apache.servicecomb.serviceregistry.task.MicroserviceRegisterTask.registerSchema(MicroserviceRegisterTask.java:206)
	at org.apache.servicecomb.serviceregistry.task.MicroserviceRegisterTask.registerSchemas(MicroserviceRegisterTask.java:170)
	at org.apache.servicecomb.serviceregistry.task.MicroserviceRegisterTask.doRegister(MicroserviceRegisterTask.java:122)
	at org.apache.servicecomb.serviceregistry.task.AbstractRegisterTask.doRun(AbstractRegisterTask.java:41)
	at org.apache.servicecomb.serviceregistry.task.AbstractTask.run(AbstractTask.java:53)
	at org.apache.servicecomb.serviceregistry.task.CompositeTask.run(CompositeTask.java:35)
	at org.apache.servicecomb.serviceregistry.task.ServiceCenterTask.init(ServiceCenterTask.java:82)
	at org.apache.servicecomb.serviceregistry.registry.AbstractServiceRegistry.run(AbstractServiceRegistry.java:178)
	at org.apache.servicecomb.serviceregistry.registry.RemoteServiceRegistry.run(RemoteServiceRegistry.java:86)
	at org.apache.servicecomb.serviceregistry.RegistryUtils.run(RegistryUtils.java:70)
	at org.apache.servicecomb.core.SCBEngine.doInit(SCBEngine.java:252)
	at org.apache.servicecomb.core.SCBEngine.init(SCBEngine.java:206)
	... 44 common frames omitted

**Comment by liubao68** [comment]
这个错误应该是服务重启失败了。 重启的时候，检测到版本的swagger变化。 记得很早的一些版本存在代码没变化， swagger的结果可能不同的情况。

**Comment by ferrymo** [comment]
> 这个错误应该是服务重启失败了。 重启的时候，检测到版本的swagger变化。 记得很早的一些版本存在代码没变化， swagger的结果可能不同的情况。

是放在k8s中运行的，不知道为什么重启了，k8s只能看最近的一次错误，每次重启都会进行几次（会因serviceCenter中有相同版本导致也无法启动），然后k8s会把该pod再进行重启，导致我也无法直接看到第一次重启的原因，能有办法让一次启动成功嘛

**Comment by yanghao605** [comment]
是否可以手动去注册微服务，在注册微服务之前先将之前存在于注册中心的微服务信息删除

**Comment by liubao68** [comment]
可以先看下启动失败的日志，具体是什么原因

**Comment by ferrymo** [comment]
disappointed

**Comment by ferrymo** [comment]
disappointed
