### ISSUE TITLE
客户端请求服务端报错431

### ISSUE THREAD

**Issue by bambi2016** [apache/servicecomb-java-chassis#3400]
请求参数内容过多时，报错431，有没有什么地方可以配置一下，允许这么大的参数或去除参数大小限制。正常http的post请求都没有限制的。
2022-10-14 11:09:19,564Z+0000|ERROR|group0-1-thread-46|||||TID: N/A|com.huawei.m2m.cmp.global.adapter.interceptor.aspect.NotifyControllerLogAspect.doInterceptor(NotifyControllerLogAspect.java:112)|InvocationException:
org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=431;msg=null
	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.doCreate(ExceptionFactory.java:76) ~[swagger-invocation-core-2.7.4.jar:2.7.4]
	at org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory.create(ExceptionFactory.java:63) ~[swagger-invocation-core-2.7.4.jar:2.7.4]
	at org.apache.servicecomb.swagger.invocation.Response.create(Response.java:142) ~[swagger-invocation-core-2.7.4.jar:2.7.4]
	at org.apache.servicecomb.transport.rest.client.http.DefaultHttpClientFilter.extractResponse(DefaultHttpClientFilter.java:105) ~[transport-rest-client-2.7.4.jar:2.7.4]
	at org.apache.servicecomb.transport.rest.client.http.DefaultHttpClientFilter.afterReceiveResponse(DefaultHttpClientFilter.java:133) ~[transport-rest-client-2.7.4.jar:2.7.4]
	at org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.lambda$processResponseBody$6(RestClientInvocation.java:240) ~[transport-rest-client-2.7.4.jar:2.7.4]
	at org.apache.servicecomb.core.provider.consumer.SyncResponseExecutor.waitResponse(SyncResponseExecutor.java:62) ~[java-chassis-core-2.7.4.jar:2.7.4]
	at org.apache.servicecomb.core.provider.consumer.InvokerUtils.innerSyncInvokeImpl(InvokerUtils.java:216) ~[java-chassis-core-2.7.4.jar:2.7.4]
	at org.apache.servicecomb.core.provider.consumer.InvokerUtils.lambda$decorateSyncRetry$cf34ec48$2(InvokerUtils.java:269) ~[java-chassis-core-2.7.4.jar:2.7.4]
	at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$3f69f149$1(Retry.java:137) ~[resilience4j-retry-1.7.0.jar:1.7.0]
	at io.vavr.control.Try.of(Try.java:75) ~[vavr-0.9.1.jar:?]
	at org.apache.servicecomb.core.provider.consumer.InvokerUtils.decorateSyncRetry(InvokerUtils.java:270) ~[java-chassis-core-2.7.4.jar:2.7.4]
	at org.apache.servicecomb.core.provider.consumer.InvokerUtils.innerSyncInvoke(InvokerUtils.java:198) ~[java-chassis-core-2.7.4.jar:2.7.4]
	at org.apache.servicecomb.provider.pojo.HandlerInvocationCaller.syncInvoke(HandlerInvocationCaller.java:40) ~[provider-pojo-2.7.4.jar:2.7.4]
	at org.apache.servicecomb.provider.pojo.HandlerInvocationCaller.call(HandlerInvocationCaller.java:34) ~[provider-pojo-2.7.4.jar:2.7.4]
	at org.apache.servicecomb.provider.pojo.Invoker.invoke(Invoker.java:71) ~[provider-pojo-2.7.4.jar:2.7.4]
	at com.sun.proxy.$Proxy122.simCardsDetailNotify(Unknown Source) ~[?:?]
	at com.huawei.m2m.cmp.global.adapter.controller.NotifyControllerImpl.simCardsDetailNotify(NotifyControllerImpl.java:171) ~[cmadapter-impl-2.0.1-SNAPSHOT.jar:?]

**Comment by liubao68** [comment]
需要看下是什么参数，以及服务端的运行模式（vert.x还是servlet， 一般容器都会限制最大body大小，或者header大小的）

**Comment by bambi2016** [comment]
> 

原来是我们的代码把请求参数又加到请求头中，造成请求头太大造成的。body应该没限制大小。
