### ISSUE TITLE
微服务配置TLS通信，调用失败

### ISSUE THREAD

**Issue by pengye1207** [apache/servicecomb-java-chassis#3466]
项目使用servicecomb+springboot
servicecomb：2.6.0
springboot：2.6.7

证书使用的openssl自签名证书，edge和业务使用了同一个ca证书签名的证书。

edge网关的TLS配置

```yaml
ssl.protocols: TLSv1.2
ssl.authPeer: false
ssl.checkCN.host: false
ssl.keyStore: client.p12
ssl.keyStoreType: PKCS12
ssl.keyStoreValue: aaaa
ssl.sslCustomClass: xxx.SslCustomConfiguration
```

业务微服务的TLS配置

```yaml
ssl.protocols: TLSv1.2
ssl.authPeer: false
ssl.checkCN.host: false
ssl.keyStore: server.p12
ssl.keyStoreType: PKCS12
ssl.keyStoreValue: aaaa
ssl.sslCustomClass: xxx.SslCustomConfiguration
```

使用postman，发起对网关的调用时，网关和业务微服务分别报错如下：

edge报错

```shell
2022-11-08 12:25:52.256+0000|transport-vert.x-eventloop-thread-19||ERROR|org.apache.servicecomb.transport.rest.vertx.RestServerVerticle.lambda$start$2:116|Unexpected error in server.cause:SSLException,message:Received fatal alert: certificate_unknown
2022-11-08 12:26:00.583+0000|transport-vert.x-eventloop-thread-20|636a4ad87b644e52-0|ERROR|org.apache.servicecomb.core.tracing.TraceIdLogger.error:50|Failed to send request, alreadyFailed:false, local:not connected, remote:/10.136.77.243:31531, message=cause:SSLHandshakeException,message:Failed to create SSL connection;cause:NotSslRecordException,message:not an SSL/TLS record: 485454502f312e3120343030200d0a436f6e74656e742d547970653a20746578742f68746d6c3b636861727365743d7574662d380d0a436f6e74656e742d4c616e67756167653a20656e0d0a436f6e74656e742d4c656e6774683a203433350d0a446174653a205475652c203038204e6f7620323032322031323a32363a303020474d540d0a436f6e6e656374696f6e3a20636c6f73650d0a0d0a3c21646f63747970652068746d6c3e3c68746d6c206c616e673d22656e223e3c686561643e3c7469746c653e48545450205374617475732034303020e280932042616420526571756573743c2f7469746c653e3c7374796c6520747970653d22746578742f637373223e626f6479207b666f6e742d66616d696c793a5461686f6d612c417269616c2c73616e732d73657269663b7d2068312c2068322c2068332c2062207b636f6c6f723a77686974653b6261636b67726f756e642d636f6c6f723a233532354437363b7d206831207b666f6e742d73697a653a323270783b7d206832207b666f6e742d73697a653a313670783b7d206833207b666f6e742d73697a653a313470783b7d2070207b666f6e742d73697a653a313270783b7d2061207b636f6c6f723a626c61636b3b7d202e6c696e65207b6865696768743a3170783b6261636b67726f756e642d636f6c6f723a233532354437363b626f726465723a6e6f6e653b7d3c2f7374796c653e3c2f686561643e3c626f64793e3c68313e48545450205374617475732034303020e280932042616420526571756573743c2f68313e3c2f626f64793e3c2f68746d6c3e.
2022-11-08 12:26:00.593+0000|transport-vert.x-eventloop-thread-20|636a4ad87b644e52-0|ERROR|org.apache.servicecomb.core.tracing.TraceIdLogger.error:50|service CONSUMER rest UserFeedbackService.ticketOpsController.pageQueryTicketList, call error, msg is cause:InvocationException,message:InvocationException: code=490;msg=CommonExceptionData [message=Unexpected consumer error, please check logs for details];cause:SSLHandshakeException,message:Failed to create SSL connection;cause:NotSslRecordException,message:not an SSL/TLS record: 485454502f312e3120343030200d0a436f6e74656e742d547970653a20746578742f68746d6c3b636861727365743d7574662d380d0a436f6e74656e742d4c616e67756167653a20656e0d0a436f6e74656e742d4c656e6774683a203433350d0a446174653a205475652c203038204e6f7620323032322031323a32363a303020474d540d0a436f6e6e656374696f6e3a20636c6f73650d0a0d0a3c21646f63747970652068746d6c3e3c68746d6c206c616e673d22656e223e3c686561643e3c7469746c653e48545450205374617475732034303020e280932042616420526571756573743c2f7469746c653e3c7374796c6520747970653d22746578742f637373223e626f6479207b666f6e742d66616d696c793a5461686f6d612c417269616c2c73616e732d73657269663b7d2068312c2068322c2068332c2062207b636f6c6f723a77686974653b6261636b67726f756e642d636f6c6f723a233532354437363b7d206831207b666f6e742d73697a653a323270783b7d206832207b666f6e742d73697a653a313670783b7d206833207b666f6e742d73697a653a313470783b7d2070207b666f6e742d73697a653a313270783b7d2061207b636f6c6f723a626c61636b3b7d202e6c696e65207b6865696768743a3170783b6261636b67726f756e642d636f6c6f723a233532354437363b626f726465723a6e6f6e653b7d3c2f7374796c653e3c2f686561643e3c626f64793e3c68313e48545450205374617475732034303020e280932042616420526571756573743c2f68313e3c2f626f64793e3c2f68746d6c3e, server is rest://10.136.77.243:31531?sslEnabled=true 
2022-11-08 12:26:00.594+0000|transport-vert.x-eventloop-thread-20|636a4ad87b644e52-0|ERROR|org.apache.servicecomb.core.tracing.TraceIdLogger.error:50|Invoke server failed. Operation CONSUMER rest UserFeedbackService.ticketOpsController.pageQueryTicketList; server rest://10.136.77.243:31531?sslEnabled=true; 0-0 msg cause:InvocationException,message:InvocationException: code=490;msg=CommonExceptionData [message=Unexpected consumer error, please check logs for details];cause:SSLHandshakeException,message:Failed to create SSL connection;cause:NotSslRecordException,message:not an SSL/TLS record: 485454502f312e3120343030200d0a436f6e74656e742d547970653a20746578742f68746d6c3b636861727365743d7574662d380d0a436f6e74656e742d4c616e67756167653a20656e0d0a436f6e74656e742d4c656e6774683a203433350d0a446174653a205475652c203038204e6f7620323032322031323a32363a303020474d540d0a436f6e6e656374696f6e3a20636c6f73650d0a0d0a3c21646f63747970652068746d6c3e3c68746d6c206c616e673d22656e223e3c686561643e3c7469746c653e48545450205374617475732034303020e280932042616420526571756573743c2f7469746c653e3c7374796c6520747970653d22746578742f637373223e626f6479207b666f6e742d66616d696c793a5461686f6d612c417269616c2c73616e732d73657269663b7d2068312c2068322c2068332c2062207b636f6c6f723a77686974653b6261636b67726f756e642d636f6c6f723a233532354437363b7d206831207b666f6e742d73697a653a323270783b7d206832207b666f6e742d73697a653a313670783b7d206833207b666f6e742d73697a653a313470783b7d2070207b666f6e742d73697a653a313270783b7d2061207b636f6c6f723a626c61636b3b7d202e6c696e65207b6865696768743a3170783b6261636b67726f756e642d636f6c6f723a233532354437363b626f726465723a6e6f6e653b7d3c2f7374796c653e3c2f686561643e3c626f64793e3c68313e48545450205374617475732034303020e280932042616420526571756573743c2f68313e3c2f626f64793e3c2f68746d6c3e
2022-11-08 12:26:00.595+0000|transport-vert.x-eventloop-thread-20|636a4ad87b644e52-0|ERROR|org.apache.servicecomb.core.tracing.TraceIdLogger.error:50|Invoke all server failed. Operation CONSUMER rest UserFeedbackService.ticketOpsController.pageQueryTicketList, e=cause:InvocationException,message:InvocationException: code=490;msg=CommonExceptionData [message=Unexpected consumer error, please check logs for details];cause:SSLHandshakeException,message:Failed to create SSL connection;cause:NotSslRecordException,message:not an SSL/TLS record: 485454502f312e3120343030200d0a436f6e74656e742d547970653a20746578742f68746d6c3b636861727365743d7574662d380d0a436f6e74656e742d4c616e67756167653a20656e0d0a436f6e74656e742d4c656e6774683a203433350d0a446174653a205475652c203038204e6f7620323032322031323a32363a303020474d540d0a436f6e6e656374696f6e3a20636c6f73650d0a0d0a3c21646f63747970652068746d6c3e3c68746d6c206c616e673d22656e223e3c686561643e3c7469746c653e48545450205374617475732034303020e280932042616420526571756573743c2f7469746c653e3c7374796c6520747970653d22746578742f637373223e626f6479207b666f6e742d66616d696c793a5461686f6d612c417269616c2c73616e732d73657269663b7d2068312c2068322c2068332c2062207b636f6c6f723a77686974653b6261636b67726f756e642d636f6c6f723a233532354437363b7d206831207b666f6e742d73697a653a323270783b7d206832207b666f6e742d73697a653a313670783b7d206833207b666f6e742d73697a653a313470783b7d2070207b666f6e742d73697a653a313270783b7d2061207b636f6c6f723a626c61636b3b7d202e6c696e65207b6865696768743a3170783b6261636b67726f756e642d636f6c6f723a233532354437363b626f726465723a6e6f6e653b7d3c2f7374796c653e3c2f686561643e3c626f64793e3c68313e48545450205374617475732034303020e280932042616420526571756573743c2f68313e3c2f626f64793e3c2f68746d6c3e
2022-11-08 12:26:00.609+0000|transport-vert.x-eventloop-thread-20||ERROR|org.apache.servicecomb.common.rest.AbstractRestInvocation.onExecuteHttpServerFiltersFinish:308|Failed to flush rest response, operation:UserFeedbackService.ticketOpsController.pageQueryTicketList, request uri:/ufs/v1/devops/ticket
java.lang.IllegalStateException: Response has already been written
	at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:394) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:382) ~[vertx-core-4.1.5.jar:4.1.5]
	at org.apache.servicecomb.foundation.vertx.http.VertxServerResponseToHttpServletResponse.internalFlushBuffer(VertxServerResponseToHttpServletResponse.java:125) ~[foundation-vertx-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.foundation.vertx.http.VertxServerResponseToHttpServletResponse.flushBuffer(VertxServerResponseToHttpServletResponse.java:112) ~[foundation-vertx-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.onExecuteHttpServerFiltersFinish(AbstractRestInvocation.java:306) ~[common-rest-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$executeHttpServerFilters$3(AbstractRestInvocation.java:295) ~[common-rest-2.6.0.jar:2.6.0]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140) ~[?:1.8.0_212]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.executeHttpServerFilters(AbstractRestInvocation.java:290) ~[common-rest-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.sendResponse(AbstractRestInvocation.java:283) ~[common-rest-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.sendResponseQuietly(AbstractRestInvocation.java:268) ~[common-rest-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$doInvoke$2(AbstractRestInvocation.java:251) ~[common-rest-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.loadbalance.LoadbalanceHandler.lambda$handle$0(LoadbalanceHandler.java:199) ~[handler-loadbalance-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.swagger.invocation.AsyncResponse.consumerFail(AsyncResponse.java:34) ~[swagger-invocation-core-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.loadbalance.LoadbalanceHandler$3.fail(LoadbalanceHandler.java:379) ~[handler-loadbalance-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.loadbalance.LoadbalanceHandler$3.onExecutionFailed(LoadbalanceHandler.java:370) ~[handler-loadbalance-2.6.0.jar:2.6.0]
	at com.netflix.loadbalancer.reactive.ExecutionContextListenerInvoker.onExecutionFailed(ExecutionContextListenerInvoker.java:164) ~[ribbon-loadbalancer-2.3.0.jar:2.3.0]
	at com.netflix.loadbalancer.reactive.ExecutionContextListenerInvoker.onExecutionFailed(ExecutionContextListenerInvoker.java:152) ~[ribbon-loadbalancer-2.3.0.jar:2.3.0]
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$4.call(LoadBalancerCommand.java:361) ~[ribbon-loadbalancer-2.3.0.jar:2.3.0]
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$4.call(LoadBalancerCommand.java:345) ~[ribbon-loadbalancer-2.3.0.jar:2.3.0]
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1$1.onError(OperatorRetryWithPredicate.java:107) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.observers.SerializedObserver.onError(SerializedObserver.java:152) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:78) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerError(OnSubscribeConcatMap.java:192) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.onError(OnSubscribeConcatMap.java:340) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.observers.Subscribers$5.onError(Subscribers.java:230) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87) ~[rxjava-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.loadbalance.LoadbalanceHandler$4.lambda$null$0(LoadbalanceHandler.java:415) ~[handler-loadbalance-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.swagger.invocation.AsyncResponse.fail(AsyncResponse.java:42) ~[swagger-invocation-core-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.fail(RestClientInvocation.java:292) ~[transport-rest-client-2.6.0.jar:2.6.0]
	at org.apache.servicecomb.transport.rest.client.http.RestClientInvocation.lambda$invoke$4(RestClientInvocation.java:151) ~[transport-rest-client-2.6.0.jar:2.6.0]
	at io.vertx.core.impl.future.FutureImpl$2.onFailure(FutureImpl.java:117) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FailedFuture.addListener(FailedFuture.java:98) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.Composition.onFailure(Composition.java:55) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:81) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:173) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:66) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.http.impl.HttpClientImpl.lambda$doRequest$7(HttpClientImpl.java:626) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.net.impl.pool.Endpoint.lambda$getConnection$0(Endpoint.java:52) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.http.impl.ClientHttpEndpointBase.lambda$requestConnection$0(ClientHttpEndpointBase.java:46) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint$Request.handle(SharedClientHttpStreamEndpoint.java:159) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint$Request.handle(SharedClientHttpStreamEndpoint.java:120) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:274) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.net.impl.pool.SimpleConnectionPool$ConnectFailed$2.run(SimpleConnectionPool.java:390) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.net.impl.pool.CombinerExecutor.submit(CombinerExecutor.java:50) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.net.impl.pool.SimpleConnectionPool.execute(SimpleConnectionPool.java:254) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.net.impl.pool.SimpleConnectionPool.lambda$connect$3(SimpleConnectionPool.java:268) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint.lambda$connect$2(SharedClientHttpStreamEndpoint.java:101) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FailedFuture.addListener(FailedFuture.java:98) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.Composition.onFailure(Composition.java:55) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:274) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.net.impl.NetClientImpl.failed(NetClientImpl.java:283) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.net.impl.NetClientImpl.lambda$connectInternal$4(NetClientImpl.java:251) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:109) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.vertx.core.net.impl.ChannelProvider$1.userEventTriggered(ChannelProvider.java:131) [vertx-core-4.1.5.jar:4.1.5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.ssl.SslUtils.handleHandshakeFailure(SslUtils.java:443) [netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1883) [netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1852) [netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1219) [netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284) [netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

```

业务报错

```shell
2022-11-08 12:26:00.544+0000|http-nio-31531-exec-2||INFO |org.apache.juli.logging.DirectJDKLog.log:175|Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x030x00t0x010x000x00p0x030x03cjJ0xd80xca0x190xf90xba0xa3H0xca0xee0xf40xca0xd5#8W0xee0xcd0xe3PZ0xb0<z0xd1'}0xb10x1f0xb10x000x000x040xc000xc0/0x010x000x00C0x000x0a0x000x160x000x140x000x170x000x180x000x190x000x090x000x0a0x000x0b0x000x0c0x000x0d0x000x0e0x000x160x000x0b0x000x020x010x000x000x0d0x000x160x000x140x060x030x060x010x050x030x050x010x040x030x040x010x040x020x020x030x020x010x020x020x000x170x000x000xff0x010x000x010x00...]. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:419) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:271) [tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) [tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735) [tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.58.jar:9.0.58]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

```

**Comment by liubao68** [comment]
业务微服务使用的是TOMCAT，需要按照TOMCAT配置SSL，上述配置项不适用于TOMCAT场景。

**Comment by yanghao605** [comment]
> ssl.protocols: TLSv1.2
ssl.authPeer: false
ssl.checkCN.host: false
ssl.keyStore: server.p12
ssl.keyStoreType: PKCS12
ssl.keyStoreValue: aaaa
ssl.sslCustomClass: xxx.SslCustomConfiguration

上述SSL的配置不适用于使用tomcat的微服务吗？
就是说基于tomcat微服务在使用servicecomb-java-chassis的时候，想要使用TLS通信，除了要配置chassis的tls通信配置，还要设置tomcat的ssl配置？
我们这边也有服务遇到过这个问题，不过是偶现的
