### ISSUE TITLE
客户端调用服务器在一定压力下（非常小的并发）报错，且 get connection 非常长

### ISSUE THREAD

**Issue by edgar1170** [apache/servicecomb-java-chassis#3475]
2022-11-11 17:24:04.180  WARN 2267 --- [service-tomcat-1163] o.a.s.m.c.publish.SlowInvocationLogger   : 56 slow(1000 ms) invocation, CONSUMER rest crmadapter.crmAdapterService.queryProdInstIot:
  http method: POST
  url        : /ICRMAdapterService/queryProdInstIot/
  server     : rest://10.0.3.138:8081
  status code: 408
  total      : 40004.524 ms
    prepare                : 0.22 ms
    handlers request       : 32122.667 ms
    client filters request : 0.78 ms
    send request           : 0.355 ms
    get connection         : 32122.307 ms
    write to buf           : 0.448 ms
    wait response          : 0.0 ms
    wake consumer          : 0.0 ms
    client filters response: 0.0 ms
    handlers response      : 0.0 ms
2022-11-11 17:24:04.181 ERROR 2267 --- [service-tomcat-1163] c.h.m.p.e.GlobalExceptionHandler         : 118 RuntimeException: 

org.apache.servicecomb.swagger.invocation.exception.InvocationException: InvocationException: code=408;msg=CommonExceptionData{code='SCB.00000004', message='Invocation Timeout.', dynamic={}}
	at org.apache.servicecomb.core.provider.consumer.SyncResponseExecutor.guardedWait(SyncResponseExecutor.java:90)
	at org.apache.servicecomb.core.provider.consumer.SyncResponseExecutor.waitResponse(SyncResponseExecutor.java:58)
	at org.apache.servicecomb.core.provider.consumer.InvokerUtils.innerSyncInvokeImpl(InvokerUtils.java:210)
	at org.apache.servicecomb.core.provider.consumer.InvokerUtils.lambda$decorateSyncRetry$cf34ec48$2(InvokerUtils.java:263)

**Comment by edgar1170** [comment]
通过检查调用链，发现服务器处理业务耗时仅在200ms以内

**Comment by edgar1170** [comment]
@liubao68

**Comment by liubao68** [comment]
可以看下客户端和服务端对应时间的完整的metrics。 根据你的描述， 可能是服务端大量请求排队了， 业务处理200ms其实是非常长的时间了。

**Comment by edgar1170** [comment]
> 可以看下客户端和服务端对应时间的完整的metrics。 根据你的描述， 可能是服务端大量请求排队了， 业务处理200ms其实是非常长的时间了。

@liubao68 因为业务处理方需要调用外部第三方的接口，因此压力下耗时会比较长，2s,3s的也很常见，请问这种情况可以如何调整参数使得不会返回408呢？哪怕是慢一点，因为以前1.3版本的时候是不会撑破的

**Comment by yanghao605** [comment]
> servicecomb.request.timeout: 20000

把这个参数调大呗
