### ISSUE TITLE
如何只使用cse的consumerProvider功能调用别的模块，不使用 producerProvider向别的模块提供服务？

### ISSUE THREAD

**Issue by rongdafeng** [apache/servicecomb-java-chassis#3505]
如何只使用cse的consumerProvider功能调用别的模块，不使用 producerProvider向别的模块提供服务？

cse能不能支持这样的使用方法呢？我们只想集成消费者调用别的模块。我们的模块只给自己的前端通过springboot的标准方法提供接口，不能接入producerProvider（否则的话，整改工作量非常大）

能不能这么搞呢？请官方给个明确的答案，谢谢

**Comment by yanghao605** [comment]
如果不希望自身服务被消费端通过注册中心发现自身服务，可以不填写rest的监听地址
如果是不希望自身微服务在启动时，不生成相应的接口的契约信息，可以在microservice.yaml中加入下述配置
servicecomb:
provider:
    rest:
      scanRestController: false

**Comment by liubao68** [comment]
@yanghao605 的方案是可以的。 不过我记得如果不填写REST的监听地址，或者所有的transport都未初始化，无法启动， 这个得验证下。

**Comment by rongdafeng** [comment]
按照@yanghao605 的方案，还是启动不了，报如下的错误

2022-11-28 10:01:33[INFO][REQ-][vert.x-eventloop-thread-12][VertxUtils.java-204]-Success to close vertx transport.
2022-11-28 10:01:33[INFO][REQ-][main][SCBEngine.java-175]-BootListener org.apache.servicecomb.edge.core.EdgeBootListener succeed to process AFTER_CLOSE.
2022-11-28 10:01:33[INFO][REQ-][main][SCBEngine.java-175]-BootListener org.apache.servicecomb.common.rest.RestEngineSchemaListener succeed to process AFTER_CLOSE.
2022-11-28 10:01:33[INFO][REQ-][main][SCBEngine.java-175]-BootListener org.apache.servicecomb.core.provider.producer.ProducerProviderManager succeed to process AFTER_CLOSE.
2022-11-28 10:01:33[INFO][REQ-][main][SCBEngine.java-175]-BootListener org.apache.servicecomb.AuthHandlerBoot succeed to process AFTER_CLOSE.
2022-11-28 10:01:33[INFO][REQ-][main][SCBEngine.java-175]-BootListener com.huawei.nuwa.map.support.servicecomb.MapBootListener succeed to process AFTER_CLOSE.
2022-11-28 10:01:33[INFO][REQ-][main][SCBEngine.java-301]-ServiceComb had closed
2022-11-28 10:01:33[INFO][REQ-][main][SCBEngine.java-250]-Service information is shown below:\nService Center: [[https://127.0.0.1:30100]\nConfig](https://127.0.0.1:30100]/nConfig) Center: not exist\nApp ID: default\nService Name: defaultMicroservice\nVersion: 1.0.0\nEnvironment: \nService ID: null\nInstance ID: null\n
2022-11-28 10:01:33[ERROR][REQ-][main][SpringApplication.java-830]-Application run failed
java.lang.IllegalStateException: ServiceComb init failed.
	at org.apache.servicecomb.core.SCBEngine.init(SCBEngine.java:237) ~[java-chassis-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.core.CseApplicationListener.onApplicationEvent(CseApplicationListener.java:81) ~[java-chassis-core-1.3.8.jar:1.3.8]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:114) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:82) ~[spring-boot-2.6.6.jar:2.6.6]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:82) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.6.jar:2.6.6]
	at com.huawei.mycloud.OMSystemApplication.main(OMSystemApplication.java:29) ~[classes/:?]
Caused by: java.lang.Error: generate operation swagger failed, com.huawei.mycloud.om.business.activitygiftconfig.controller.ActiveGiftConfigController:delete
	at org.apache.servicecomb.swagger.generator.core.SwaggerGenerator.scanMethods(SwaggerGenerator.java:252) ~[swagger-generator-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.swagger.generator.core.SwaggerGenerator.generate(SwaggerGenerator.java:141) ~[swagger-generator-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.core.definition.schema.AbstractSchemaFactory.generateSwagger(AbstractSchemaFactory.java:102) ~[java-chassis-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.createSchema(ProducerSchemaFactory.java:115) ~[java-chassis-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.createSchema(ProducerSchemaFactory.java:54) ~[java-chassis-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.core.definition.schema.AbstractSchemaFactory.getOrCreateSchema(AbstractSchemaFactory.java:58) ~[java-chassis-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.getOrCreateProducerSchema(ProducerSchemaFactory.java:76) ~[java-chassis-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.provider.rest.common.RestProducerProvider.init(RestProducerProvider.java:45) ~[provider-rest-common-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.init(ProducerProviderManager.java:54) ~[java-chassis-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.core.SCBEngine.doInit(SCBEngine.java:270) ~[java-chassis-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.core.SCBEngine.init(SCBEngine.java:225) ~[java-chassis-core-1.3.8.jar:1.3.8]
	... 16 more
Caused by: org.apache.servicecomb.foundation.common.exceptions.ServiceCombException: [simple type, class org.springframework.validation.BindingResult] is interface. Must be a concrete type.
	at org.apache.servicecomb.swagger.extend.ModelResolverExt.checkType(ModelResolverExt.java:119) ~[swagger-generator-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.swagger.extend.ModelResolverExt.resolveProperty(ModelResolverExt.java:151) ~[swagger-generator-core-1.3.8.jar:1.3.8]
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:128) ~[swagger-core-1.6.6.jar:1.6.6]
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:83) ~[swagger-core-1.6.6.jar:1.6.6]
	at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:63) ~[swagger-core-1.6.6.jar:1.6.6]
	at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:57) ~[swagger-core-1.6.6.jar:1.6.6]
	at org.apache.servicecomb.swagger.generator.springmvc.processor.parameter.SpringmvcDefaultParameterProcessor.process(SpringmvcDefaultParameterProcessor.java:39) ~[swagger-generator-springmvc-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.swagger.generator.core.OperationGenerator.scanMethodParameters(OperationGenerator.java:298) ~[swagger-generator-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.swagger.generator.core.OperationGenerator.generate(OperationGenerator.java:181) ~[swagger-generator-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.swagger.generator.core.SwaggerGenerator.scanMethods(SwaggerGenerator.java:248) ~[swagger-generator-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.swagger.generator.core.SwaggerGenerator.generate(SwaggerGenerator.java:141) ~[swagger-generator-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.core.definition.schema.AbstractSchemaFactory.generateSwagger(AbstractSchemaFactory.java:102) ~[java-chassis-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.createSchema(ProducerSchemaFactory.java:115) ~[java-chassis-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.createSchema(ProducerSchemaFactory.java:54) ~[java-chassis-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.core.definition.schema.AbstractSchemaFactory.getOrCreateSchema(AbstractSchemaFactory.java:58) ~[java-chassis-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.core.definition.schema.ProducerSchemaFactory.getOrCreateProducerSchema(ProducerSchemaFactory.java:76) ~[java-chassis-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.provider.rest.common.RestProducerProvider.init(RestProducerProvider.java:45) ~[provider-rest-common-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.init(ProducerProviderManager.java:54) ~[java-chassis-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.core.SCBEngine.doInit(SCBEngine.java:270) ~[java-chassis-core-1.3.8.jar:1.3.8]
	at org.apache.servicecomb.core.SCBEngine.init(SCBEngine.java:225) ~[java-chassis-core-1.3.8.jar:1.3.8]
	... 16 more

**Comment by yanghao605** [comment]
参考文档 [用 Spring MVC 开发微服务](https://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/build-provider/springmvc.html)

**Comment by rongdafeng** [comment]
> 参考文档 [用 Spring MVC 开发微服务](https://servicecomb.gitee.io/servicecomb-java-chassis-doc/java-chassis/zh_CN/build-provider/springmvc.html)
> 
> ![image](https://user-images.githubusercontent.com/73453250/204221896-9efc0033-d0e4-4579-a0ac-b4264636339a.png)

我已经使用了配置：
servicecomb:
  provider:
    rest:
      scanRestController: false
但还是报上面日志中的错误：Caused by: org.apache.servicecomb.foundation.common.exceptions.ServiceCombException: [simple type, class org.springframework.validation.BindingResult] is interface. Must be a concrete type.

**Comment by lbc97** [comment]
org.springframework.validation.BindingResult 你们是否用这个类做了接口的返回值 这是一个接口不是一个实体类在servicecomb中不能用来做返回值 但是这个接口你加了配置之后应该不会被扫描 所以请检查你们的配置是否正确并生效。

**Comment by lbc97** [comment]
org.springframework.validation.BindingResult 你们是否有接口使用这个做返回值 这是个接口不能用来做servicecomb的返回值 但是如果你们开了上述说的配置校验时应该不会校验这个接口 所以请检查该配置是否正确配置并生效。

**Comment by rongdafeng** [comment]
> org.springframework.validation.BindingResult 你们是否有接口使用这个做返回值 这是个接口不能用来做servicecomb的返回值 但是如果你们开了上述说的配置校验时应该不会校验这个接口 所以请检查该配置是否正确配置并生效。

感谢，
servicecomb:
provider:
rest:
scanRestController: false

写在microservice.yaml不生效，把这个变量移到application.yml里可以了，谢谢
