### ISSUE TITLE
servicecomb服务注册不上

### ISSUE THREAD

**Issue by zhangaijing** [apache/servicecomb-java-chassis#3516]
本机上起着servicecomb.
启动服务时无法注册,报错信息如下:
2022-12-08 16:55:18:018 [registry-vert.x-eventloop-thread-0] [INFO ] org.apache.servicecomb.serviceregistry.client.IpPortManager >> Change service center address from 127.0.0.1:30100 to 127.0.0.1:30100
2022-12-08 16:55:18:018 [registry-vert.x-eventloop-thread-0] [ERROR] org.apache.servicecomb.serviceregistry.client.http.RestUtils >> POST /v4/default/registry/microservices fail, endpoint is 127.0.0.1:30100, message: Failed to create SSL connection

前段时间还能正常使用,今天无法注册了
请问怎么处理?

**Comment by liubao68** [comment]
是不是改配置文件了？ e.g.  `http://127.0.0.1:30100` -> `https://127.0.0.1:30100`

**Comment by zhangaijing** [comment]
我们现在有个项目是要基于原来的一个项目上做开发的,现在测试下来使用原来的微服务名是能够在注册中心注册上去的.但换另一个微服务名就不行.....备注: 两个配置一模一样.

我们现在先用原来的微服务名注册中心是有服务了,但出现微服务之间无法调用:  报错信息如下:
2022-12-12 09:48:44:044 [vert.x-eventloop-thread-7] [INFO ] com.hoolink.manage.gateway.dispatcher.ApiDispatcher >> [txId]: 3A10053E13E54C338A69444D1A611382 microservice is: manage-crm-rpc, method is: /web/seeyon/getTest, params is: 
2022-12-12 09:48:44:044 [pool-2-thread-5] [ERROR] org.apache.servicecomb.common.rest.AbstractRestInvocation >> unknown rest exception.
java.lang.NoClassDefFoundError: Could not initialize class org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory
	at org.apache.servicecomb.swagger.invocation.Response.createConsumerFail(Response.java:129)
	at org.apache.servicecomb.core.provider.consumer.InvokerUtils.reactiveInvoke(InvokerUtils.java:117)
	at org.apache.servicecomb.provider.pojo.Invoker.completableFutureInvoke(Invoker.java:185)
	at org.apache.servicecomb.provider.pojo.Invoker.invoke(Invoker.java:158)
	at com.sun.proxy.$Proxy111.getSessionUser(Unknown Source)
	at com.hoolink.manage.gateway.handler.AuthHandler.handle(AuthHandler.java:74)
	at org.apache.servicecomb.core.Invocation.next(Invocation.java:204)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.doInvoke(AbstractRestInvocation.java:243)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke(AbstractRestInvocation.java:217)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor(AbstractRestInvocation.java:201)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(AbstractRestInvocation.java:160)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
2022-12-12 09:48:44:044 [pool-2-thread-5] [ERROR] org.apache.servicecomb.common.rest.AbstractRestInvocation >> rest server onRequest error
java.lang.NoClassDefFoundError: Could not initialize class org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory
	at org.apache.servicecomb.swagger.invocation.Response.createProducerFail(Response.java:134)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.sendFailResponse(AbstractRestInvocation.java:251)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.invoke(AbstractRestInvocation.java:220)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.runOnExecutor(AbstractRestInvocation.java:201)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(AbstractRestInvocation.java:160)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Exception in thread "pool-2-thread-5" java.lang.NoClassDefFoundError: Could not initialize class org.apache.servicecomb.swagger.invocation.exception.ExceptionFactory
	at org.apache.servicecomb.swagger.invocation.Response.createProducerFail(Response.java:134)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.sendFailResponse(AbstractRestInvocation.java:251)
	at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(AbstractRestInvocation.java:163)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
2022-12-12 09:49:06:006 [pool-1-thread-1] [WARN ] com.hoolink.sdk.cloud.CloudConfigurationSourceImpl >> Config value cache changed: action:SET; item:[service_description.version]

**Comment by zhangaijing** [comment]
我们的POM是没有修改的,,现有的POM配置如下: 麻烦帮我们看下哪个依赖没有引入的.
    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>spring-boot2-starter</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.apache.servicecomb</groupId>
            <artifactId>inspector</artifactId>
        </dependency>
        
        <dependency>
            <groupId>com.huawei.paas.cse</groupId>
            <artifactId>cse-solution-service-engine</artifactId>
            <version>${cse.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>${google.gson.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>${spring.boot.mybatis.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper</artifactId>
            <version>${pagehelper.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper-spring-boot-starter</artifactId>
            <version>${spring.boot.pagehelper.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-net</groupId>
            <artifactId>commons-net</artifactId>
            <version>${commons.net.version}</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>${mySql.vsersion}</version>
        </dependency>
        
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>${apache.poi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>${apache.poi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-test</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
    </dependencies>

**Comment by zhangaijing** [comment]
在serviceComb注册中心的服务契约中是能找到对应的接口.

**Comment by lbc97** [comment]
> 在serviceComb注册中心的服务契约中是能找到对应的接口.

不是说注册不上吗，为啥又能找到对应接口了

**Comment by lbc97** [comment]
直接引入这个依赖试一下<groupId>org.apache.servicecomb</groupId><artifactId>solution-basic</artifactId>

**Comment by lbc97** [comment]
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>solution-basic</artifactId>
        </dependency>

**Comment by lbc97** [comment]
solution-basic 直接引入这个依赖试试
