### ISSUE TITLE
RPC接口调用出现类无法找到：Could not initialize class rx.Observable

### ISSUE THREAD

**Issue by enotsgib** [apache/servicecomb-java-chassis#3722]
我尝试通过rpc调用时出现如下异常，不知道rx.Observable是什么，请问这是哪里缺少了东西么？重启微服务可规避，目前已出现两次，均出现在补丁升级后。
2023-03-16 13:26:18,953Z | ERROR | pcs-182          | InvokerUtils                     | 46 - ioei-rpcservice - 2023.315.941.44 | |||protocol:null||org.apache.servicecomb.core.provider.consumer.InvokerUtils.innerSyncInvoke(InvokerUtils.java:80) | Msg: invoke failed, IoVehicle.apiAuthQueryService.queryApiCertCNameAuthStatus
java.lang.NoClassDefFoundError: Could not initialize class rx.Observable
        at com.netflix.loadbalancer.reactive.LoadBalancerCommand.selectServer(LoadBalancerCommand.java:180) ~[46:ioei-rpcservice:2023.315.941.44]
        at com.netflix.loadbalancer.reactive.LoadBalancerCommand.submit(LoadBalancerCommand.java:276) ~[46:ioei-rpcservice:2023.315.941.44]
        at org.apache.servicecomb.loadbalance.LoadbalanceHandler.sendWithRetry(LoadbalanceHandler.java:303) ~[46:ioei-rpcservice:2023.315.941.44]
        at org.apache.servicecomb.loadbalance.LoadbalanceHandler.handle(LoadbalanceHandler.java:184) ~[46:ioei-rpcservice:2023.315.941.44]
        at org.apache.servicecomb.core.Invocation.next(Invocation.java:151) ~[46:ioei-rpcservice:2023.315.941.44]
        at org.apache.servicecomb.core.provider.consumer.InvokerUtils.innerSyncInvoke(InvokerUtils.java:72) ~[46:ioei-rpcservice:2023.315.941.44]
        at org.apache.servicecomb.provider.pojo.Invoker.syncInvoke(Invoker.java:161) ~[46:ioei-rpcservice:2023.315.941.44]
        at org.apache.servicecomb.provider.pojo.Invoker.invoke(Invoker.java:157) ~[46:ioei-rpcservice:2023.315.941.44]
        at com.xxx.jsf.invocation.PaaSInvoker.invoke(PaaSInvoker.java:21) ~[46:ioei-rpcservice:2023.315.941.44]
        at com.sun.proxy.$Proxy311.queryApiCertCNameAuthStatus(Unknown Source) ~[46:ioei-rpcservice:2023.315.941.44]
        at com.xxx.rpcservice.iovehicle.VehicleApiAuthQueryService.queryApiCertCNameAuthStatus(VehicleApiAuthQueryService.java:34) ~[46:ioei-rpcservice:2023.315.941.44]
        at com.xxxx.vehicle.service.rpc.VehicleAuthService.isValidCertCname(VehicleAuthService.java:28) ~[?:?]
        at com.xxxx.plugin.service.activation.process.ChoiceProcessor.process(ChoiceProcessor.java:92) ~[?:?]
        at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63) ~[?:?]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) ~[?:?]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[?:?]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[?:?]
        at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:113) ~[?:?]
        at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:84) ~[?:?]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) ~[?:?]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) ~[?:?]
        at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:76) ~[?:?]
        at org.apache.camel.processor.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:186) ~[?:?]
        at org.apache.camel.processor.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:86) ~[?:?]
        at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:541) ~[?:?]
        at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:506) ~[?:?]
        at org.apache.camel.impl.ProducerCache.doInProducer(ProducerCache.java:369) ~[?:?]
        at org.apache.camel.impl.ProducerCache.sendExchange(ProducerCache.java:506) ~[?:?]
        at org.apache.camel.impl.ProducerCache.send(ProducerCache.java:213) ~[?:?]
        at org.apache.camel.impl.DefaultProducerTemplate.send(DefaultProducerTemplate.java:139) ~[?:?]
        at org.apache.camel.impl.DefaultProducerTemplate.send(DefaultProducerTemplate.java:125) ~[?:?]
        at com.xxx.service.common.cxf.CamelService$1.lambda$null$0(CamelService.java:75) ~[?:?]

**Comment by lbc97** [comment]
你们用的什么版本 有可能是组件不兼容导致的 或者是你们项目里面排查了什么依赖

**Comment by enotsgib** [comment]
> 你们用的什么版本 有可能是组件不兼容导致的 或者是你们项目里面排除了什么依赖

目前用的是1.0.0.B003.59, 这个问题最近一个月才出现，近期代码修改未去除依赖，重启微服务时，该问题没有出现，目前只出现在补丁升级后，感觉不太像依赖的问题

**Comment by enotsgib** [comment]
我找到了rx.observable类是属于rxjava组件的，查看依赖发现是servicecomb:handler-loadbalance -> ribbon-core -> rxjava, 感觉像是服务初始化时底层框架有些什么事件没有初始化成功，导致当通过rpc去调用时，底层框架报错。

**Comment by lbc97** [comment]
你们这个版本应该不是我们开源这边的版本应该是你们自己定制的版本 完了你说的初始化没有成功 那日志里面应该会有相应的日志失败打印 可以再检查一下日志。

**Comment by enotsgib** [comment]
感谢，我再看看
