### ISSUE TITLE
TLS证书加载时遇到文件URL解析错误, 会导致启动失败, 此时打印的错误信息不清晰

### ISSUE THREAD

**Issue by yhs0092** [apache/servicecomb-java-chassis#3977]
## 问题场景

业务从 Java-Chassis 1.3.11 升级到 2.8.9.
他们的配置文件里一直会配TLS的信任证书和身份证书, 自定义扩展了一个`SSLCustom`根据文件名生成文件全路径.
在Windows开发环境下, 证书不存在, 在 1.3.11 版本`org.apache.servicecomb.foundation.vertx.VertxTLSBuilder#isFileExists`方法只检查指定路径在磁盘上是否存在, 不存在就返回`false`不加载证书, 因此不会报错.
但升级  Java-Chassis 2.8.9 后, 新增了从ClassLoader加载 resource 的逻辑, 传入`D:\xxx\yyy\server.p12`这种文件路径会遇到文件URL解析错误:
```
Caused by: java.lang.IllegalArgumentException: name
	at sun.misc.URLClassPath$Loader.findResource(URLClassPath.java:703)
	at sun.misc.URLClassPath.findResource(URLClassPath.java:225)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:572)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:570)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findResource(URLClassLoader.java:569)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1089)
......
	at org.apache.servicecomb.foundation.vertx.VertxTLSBuilder.isFileExists(VertxTLSBuilder.java:179)
	at org.apache.servicecomb.foundation.vertx.VertxTLSBuilder.buildTCPSSLOptions(VertxTLSBuilder.java:116)
	at org.apache.servicecomb.foundation.vertx.VertxTLSBuilder.buildClientOptionsBase(VertxTLSBuilder.java:98)
	at org.apache.servicecomb.foundation.vertx.VertxTLSBuilder.buildHttpClientOptions(VertxTLSBuilder.java:91)
	at org.apache.servicecomb.foundation.vertx.VertxTLSBuilder.buildHttpClientOptions(VertxTLSBuilder.java:86)
	at org.apache.servicecomb.foundation.vertx.client.http.HttpClientOptionsSPI.createHttpClientOptions(HttpClientOptionsSPI.java:134)
```

这个异常看着令人费解, 以为是业务配了什么叫"name"的配置值,
但从实际的报错位置`sun.misc.URLClassPath.Loader#findResource`来看, 是表示`findResource`输入的`name`参数有问题, 解析不出合适的URL.
```java
        URL findResource(final String name, boolean check) {
            URL url;
            try {
                url = new URL(base, ParseUtil.encodePath(name, false));
            } catch (MalformedURLException e) {
                throw new IllegalArgumentException("name");
            }
      //  ....
```

## 期望

能否优化一下`VertxTLSBuilder.isFileExists`方法的逻辑, 不要直接抛出原始的异常, 最好是包装或者转换一下异常, 提醒业务是什么文件路径下找不到证书.

**Comment by yhs0092** [comment]
这里还有一个日志打印的优化项, 
https://github.com/apache/servicecomb-java-chassis/blob/4f59e71f5607b642f38fe07172d2c8a3acffe218/core/src/main/java/org/apache/servicecomb/core/SCBEngine.java#L319-L338

在`SCBEngine#run`方法中, `printServiceInfo()`方法是在`finally`语句块中调用的, 这个方法需要从`RegistryUtils`获取一些微服务信息, 依赖于注册发现模块初始化成功. 因此, 可能SCBEngine的初始化流程在注册发现模块初始化完成之前就抛出异常, 在finally中调用`printServiceInfo()`, 由于`RegistryUtils`还没有初始化`serviceRegistry`属性, 会再触发一个空指针异常, 实际上打印在标准输出里的错误信息是第二个空指针异常, 掩盖了问题根因, 标准输出打印的错误信息如下:
```
java.lang.NullPointerException
	at org.apache.servicecomb.serviceregistry.RegistryUtils.getAppId(RegistryUtils.java:162)
	at org.apache.servicecomb.serviceregistry.ServiceCenterRegistration.getAppId(ServiceCenterRegistration.java:72)
	at org.apache.servicecomb.registry.RegistrationManager.lambda$info$5(RegistrationManager.java:320)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.apache.servicecomb.registry.RegistrationManager.info(RegistrationManager.java:318)
	at org.apache.servicecomb.core.bootup.ServiceInformationCollector.collect(ServiceInformationCollector.java:26)
	at org.apache.servicecomb.core.bootup.BootUpInformationCollector.collect(BootUpInformationCollector.java:24)
	at org.apache.servicecomb.core.SCBEngine.printServiceInfo(SCBEngine.java:349)
	at org.apache.servicecomb.core.SCBEngine.run(SCBEngine.java:338)
	at org.apache.servicecomb.core.SCBApplicationListener.onApplicationEvent(SCBApplicationListener.java:89)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:940)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
```
