### ISSUE TITLE
2.8.4 Vertx的BlockedThreadChecker不断抛出IllegalMonitorStateException 异常，导致CPU占用达到99%

### ISSUE THREAD

**Issue by yanghao605** [apache/servicecomb-java-chassis#4130]
![image](https://github.com/apache/servicecomb-java-chassis/assets/73453250/6ac359f0-2a14-4bb5-babc-b19daeef9dd9)
使用的是2.8.4版本的SDK
现象是：业务进程出现过OOM，后续BlockedThreadChecker在执行过程中也因OOM抛出异常
日志如下：
```
OOM caused by java heap space occurred, allocate size: 48 bytes, type: Ljava/util/WeakHashMap$EntryIterator;
 garbage-first heap   total 524288K, used 329140K [0x00000000e0000000, 0x0000000100000000)
  region size 1024K, 0 young (0K), 0 survivors (0K)
 Metaspace       used 118670K, capacity 127785K, committed 128356K, reserved 258048K
  class space    used 15242K, capacity 16640K, committed 16792K, reserved 145408K
current stack trace:
	at java.util.WeakHashMap$EntrySet.iterator(WeakHashMap.java:971)
	at io.vertx.core.impl.btc.BlockedThreadChecker$1.run(BlockedThreadChecker.java:51)
	- locked <0x00000000e2a38fb0> (a io.vertx.core.impl.btc.BlockedThreadChecker)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Exception in thread "vertx-blocked-thread-checker" 
	java.lang.OutOfMemoryError: Java heap space
		at java.util.WeakHashMap$EntrySet.iterator(WeakHashMap.java:971)
		at io.vertx.core.impl.btc.BlockedThreadChecker$1.run(BlockedThreadChecker.java:51)
		at java.util.TimerThread.mainLoop(Timer.java:555)
		at java.util.TimerThread.run(Timer.java:505)
```
初步怀疑是OOM导致的BlockedThreadChecker抛出异常，没有复现条件
是否可以考虑将BlockedThreadChecker的时间周期拉长，或者关闭该检测机制

**Comment by liubao68** [comment]
如果已经发生OOM，任何涉及内存分配的操作，都会出现类似问题。 似乎修复这个毫无意义。

**Comment by yanghao605** [comment]
问题在于后续服务是正常运行的，只有这个线程在一直抛出异常

**Comment by yanghao605** [comment]
当时Java进程中有三个BlockedThreadChecker线程，其中只有一个线程一直在抛出异常，也无法修复

**Comment by liubao68** [comment]
> 问题在于后续服务是正常运行的，只有这个线程在一直抛出异常

这个说不过去呀。 如果服务是正常的，那么这个线程抛出OOM的原因是什么了？总的存在占满内存的地方， 需要进一步分析内存占用情况。
