### ISSUE TITLE
servicecomb 3.1.1 Caused by: java.lang.IllegalStateException: Generate swagger operation failed cause=duplicate param model

### ISSUE THREAD

**Issue by SheepPP** [apache/servicecomb-java-chassis#4342]
servicecomb 3.1.1
response body as below, fail to generate swagger operation and fail to start application. when servicecomb 2.x is used, the case is ok.

public class MyClass {
    private List<Event> events;
}

public class Event {
   private String lineId;
   private List<Event> subNodes = new ArrayList<>();
}

Caused by: java.lang.IllegalStateException: Generate swagger operation failed, method=MyController:querySomeths, cause=duplicate param model: Event
	at org.apache.servicecomb.swagger.generator.core.AbstractSwaggerGenerator.scanMethods(AbstractSwaggerGenerator.java:240) ~[swagger-generator-core-3.1.1.jar:3.1.1]
	at org.apache.servicecomb.swagger.generator.core.AbstractSwaggerGenerator.generate(AbstractSwaggerGenerator.java:122) ~[swagger-generator-core-3.1.1.jar:3.1.1]
	at org.apache.servicecomb.swagger.generator.SwaggerGenerator.generate(SwaggerGenerator.java:33) ~[swagger-generator-core-3.1.1.jar:3.1.1]
	at org.apache.servicecomb.swagger.engine.SwaggerEnvironment.createProducer(SwaggerEnvironment.java:120) ~[swagger-invocation-core-3.1.1.jar:3.1.1]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.registerSchema(ProducerProviderManager.java:98) ~[java-chassis-core-3.1.1.jar:3.1.1]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.registerProducerMetas(ProducerProviderManager.java:87) ~[java-chassis-core-3.1.1.jar:3.1.1]
	at org.apache.servicecomb.core.provider.producer.ProducerProviderManager.init(ProducerProviderManager.java:73) ~[java-chassis-core-3.1.1.jar:3.1.1]
	at org.apache.servicecomb.core.SCBEngine.doRun(SCBEngine.java:359) ~[java-chassis-core-3.1.1.jar:3.1.1]
	at org.apache.servicecomb.core.SCBEngine.run(SCBEngine.java:315) ~[java-chassis-core-3.1.1.jar:3.1.1]

**Comment by liubao68** [comment]
Can you share your service definition code so that we can reproduce the problem?

**Comment by SheepPP** [comment]
Nested event and event list in the response body in the same controller, already find the solution to fix this problem.
