### ISSUE TITLE
transport-highway 1.3.x -> 2.8.x后，启动进程，报错ServiceComb init failed.

### ISSUE THREAD

**Issue by woo202403** [apache/servicecomb-java-chassis#4411]
Exception in thread "main" java.lang.IllegalStateException: ServiceComb init failed.
	at org.apache.servicecomb.core.SCBEngine.run(SCBEngine.java:342)
	at org.apache.servicecomb.core.SCBApplicationListener.onApplicationEvent(SCBApplicationListener.java:89)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:430)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:387)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:952)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:594)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:95)
	at org.apache.servicecomb.foundation.common.utils.BeanUtils.init(BeanUtils.java:62)
	at org.apache.servicecomb.foundation.common.utils.BeanUtils.init(BeanUtils.java:53)
	at org.apache.servicecomb.samples.pojo.consumer.PojoConsumerMain.main(PojoConsumerMain.java:44)
Caused by: java.lang.NullPointerException: At least one Registration implementation configured. Missed to include dependency ? e.g. <artifactId>registry-service-center</artifactId>
	at org.apache.servicecomb.registry.RegistrationManager.assertPrimaryNotNull(RegistrationManager.java:104)
	at org.apache.servicecomb.registry.RegistrationManager.getMicroservice(RegistrationManager.java:98)
	at org.apache.servicecomb.core.SCBEngine.createProducerMicroserviceMeta(SCBEngine.java:402)
	at org.apache.servicecomb.core.SCBEngine.doRun(SCBEngine.java:379)
	at org.apache.servicecomb.core.SCBEngine.run(SCBEngine.java:329)
	... 13 more

**Comment by woo202403** [comment]
添加registry-service-center解决，请忽略
```xml
    <dependency>
      <groupId>org.apache.servicecomb</groupId>
      <artifactId>registry-service-center</artifactId>
    </dependency>
```

**Comment by woo202403** [comment]
添加registry-service-center解决，请忽略
