### ISSUE TITLE
Java-Chassis需要适配Vert.x新form参数限制配置项

### ISSUE THREAD

**Issue by yhs0092** [apache/servicecomb-java-chassis#4461]
## 问题现象

业务发送 `x-www-form-urlencoded` 格式的body, 在升级 Java-Chassis 2.8.17 后遇到报错.

## 代码分析

代码位置:

![image](https://github.com/user-attachments/assets/0faef510-98bc-44b6-a1ce-732f05037050)

如上图, Vert.x的`HttpServerOptions` 中新增了 `maxFormFields` 和 `maxFormBufferedBytes` 配置, CSE目前没有适配, 取的是默认值 `maxFormFields=256` 和 `maxFormBufferedBytes=1024`.
如果业务发送的是表单请求, 表单参数的名字或值长度大于`1024`, 则**可能**触发 Netty 报 `TooLongFormFieldException` 异常, 报错位置如下:

https://github.com/netty/netty/blob/2e218bbd0a416d6e8a7abb5e2d180fe9f19a9968/codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java#L321-L342

```java
    public HttpPostStandardRequestDecoder offer(HttpContent content) {
        checkDestroyed();

        if (content instanceof LastHttpContent) {
            isLastChunk = true;
        }

        ByteBuf buf = content.content();
        if (undecodedChunk == null) {
            undecodedChunk =
                    // Since the Handler will release the incoming later on, we need to copy it
                    //
                    // We are explicit allocate a buffer and NOT calling copy() as otherwise it may set a maxCapacity
                    // which is not really usable for us as we may exceed it once we add more bytes.
                    buf.alloc().buffer(buf.readableBytes()).writeBytes(buf);
        } else {
            undecodedChunk.writeBytes(buf);
        }
        parseBody();
        if (maxBufferedBytes > 0 && undecodedChunk != null && undecodedChunk.readableBytes() > maxBufferedBytes) {
            throw new TooLongFormFieldException();   // <---- 会从这个位置抛异常
        }
```

**注意, 是可能触发**. 因为Netty是分段读取 socket buffer 进行处理的. 有可能出现表单参数的名字或值超过了限制, 但由于Netty分段读取的buffer长度仍小于`1024`, 处理完成之后Netty将缓存长度清零准备迎接下一段buffer, 此时`undecodedChunk.readableBytes()`仍不会超过限制. 实际触发时可以选一个远远超过`1024`的长度进行测试.

## 次生问题

Java-Chassis的`RestBodyHandler`中处理这种异常时, 判断如果捕获的异常是 `DecoderException` 就获取它的 cause 作为异常信息. 但是在这种故障场景下, `DecoderException` 的 cause 为 null, 导致最终打出来的异常显示为一个空指针异常, 很有迷惑性.

https://github.com/apache/servicecomb-java-chassis/blob/86a682e42365f595746d37d2f5fab22380b1f684/transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestBodyHandler.java#L312-L317

![image](https://github.com/user-attachments/assets/86826c09-7962-46c8-9e7e-d12ce7bd7d90)

最终Java-Chassis打印的日志片段样例:
```
2024-08-07 09:12:22.899 [transport-vert.x-eventloop-thread-5] ERROR - [VertxRestDispatcher.java:failureHandler:87] - [] - http server failed.
java.lang.NullPointerException: null
	at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:196) ~[vertx-web-4.4.9.jar!/:4.4.9]
	at org.apache.servicecomb.transport.rest.vertx.RestBodyHandler$BHandler.lambda$new$2(RestBodyHandler.java:316) ~[transport-rest-vertx-2.8.17.jar!/:2.8.17]
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277) ~[vertx-core-4.4.9.jar!/:4.4.9]
	at io.vertx.core.http.impl.HttpEventHandler.handleException(HttpEventHandler.java:89) ~[vertx-core-4.4.9.jar!/:4.4.9]
	at io.vertx.core.http.impl.Http1xServerRequest.handleException(Http1xServerRequest.java:679) ~[vertx-core-4.4.9.jar!/:4.4.9]
	at io.vertx.core.http.impl.Http1xServerRequest.onData(Http1xServerRequest.java:566) ~[vertx-core-4.4.9.jar!/:4.4.9]
	at io.vertx.core.http.impl.Http1xServerRequest.lambda$pendingQueue$1(Http1xServerRequest.java:136) ~[vertx-core-4.4.9.jar!/:4.4.9]
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:255) ~[vertx-core-4.4.9.jar!/:4.4.9]
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:134) ~[vertx-core-4.4.9.jar!/:4.4.9]
	at io.vertx.core.http.impl.Http1xServerRequest.handleContent(Http1xServerRequest.java:150) ~[vertx-core-4.4.9.jar!/:4.4.9]
```

## 期望

Java-Chassis 增加配置项适配 Vert.x 新开放的配置项, 包括:
- io.vertx.core.http.HttpServerOptions#maxFormBufferedBytes
- io.vertx.core.http.HttpServerOptions#maxFormFields

优化日志, 避免在报错时只打印空指针异常信息.

**Comment by liubao68** [comment]
可以提供下复现代码吗？

**Comment by yhs0092** [comment]
> 可以提供下复现代码吗？

其实复现不需要写代码, 只要启动一个基于 Java-Chassis 开发的HTTP服务端就行了. 报错的代码在 Netty 和 Vert.x 里, 不需要用户基于 Java-Chassis 开发对应的接口.
只需要在发送请求的时候创建一个key或者value很长的form表单请求即可, 例如:
```bash
$ curl -v -XPOST 'http://localhost:30001/benchmark/body' --data 'msgtttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttmsgtttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttmsgtttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttmsgtttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttmsgttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt=t'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:30001...
* Connected to localhost (127.0.0.1) port 30001 (#0)
> POST /benchmark/body HTTP/1.1
> Host: localhost:30001
> User-Agent: curl/7.88.1
> Accept: */*
> Content-Length: 8512
> Content-Type: application/x-www-form-urlencoded
>
< HTTP/1.1 500 Internal Server Error
< Content-Type: */*
< content-length: 35
<
{"message":"Internal Server Error"}* Connection #0 to host localhost left intact

```

**Comment by liubao68** [comment]
这个问题感觉有点说不通，业务存在 key 大于等于 1024 的情景吗？ 还是只是为了测试？
