### ISSUE TITLE
原有项目是springmvc改造成rest api的，swagger生成报错

### ISSUE THREAD

**Issue by zouwenxmu** [apache/servicecomb-java-chassis#905]
Controller定义的请求接口格式
public void query(HttpServletRequest request, HttpServletResponse response)

Caused by: org.apache.servicecomb.foundation.common.exceptions.ServiceCombException: [simple type, class javax.servlet.http.HttpServletResponse] is interface. Must be a concrete type.
	at org.apache.servicecomb.swagger.extend.ModelResolverExt.checkType(ModelResolverExt.java:102)
	at org.apache.servicecomb.swagger.extend.ModelResolverExt.resolveProperty(ModelResolverExt.java:134)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:103)
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79)
	at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:58)
	at org.apache.servicecomb.swagger.generator.springmvc.processor.parameter.SpringmvcDefaultParameterProcessor.process(SpringmvcDefaultParameterProcessor.java:38)
	at org.apache.servicecomb.swagger.generator.core.OperationGenerator.scanMethodParameters(OperationGenerator.java:293)
	at org.apache.servicecomb.swagger.generator.core.OperationGenerator.generate(OperationGenerator.java:176)
	at org.apache.servicecomb.swagger.generator.core.SwaggerGenerator.scanMethods(SwaggerGenerator.java:246)
	... 23 more

**Comment by jeho0815** [comment]
参数列表不支持HttpServletResponse，当前只支持HttpServletRequest，异常返回可以通过抛异常的方式
```
throw new InvocationException(400, "Request Error", "An error!");
```
或者使用
```
    @RequestMapping(value = "/test", produces = {"application/json"}, method = RequestMethod.GET)
    @ApiResponses({
            @ApiResponse(code = 500, message = "Internal error", response = User.class),
            @ApiResponse(code = 200, message = "normal", response = Test.class),
            @ApiResponse(code = 302, message = "normal")
    })
    public ResponseEntity<Object> getTest(@RequestParam(value = "name") String name) {
        if (name == null) {
            User u = new User();
            u.setName("test");
            return ResponseEntity.status(302)
                    .header("Location", "www.baidu.com")
                    .body(new InvocationException(Status.FOUND, ""));
        }
        Test test = new Test();
        test.setName("bb");
        ResponseEntity<Object> resp = ResponseEntity.ok(test);
        return resp;
    }
```

**Comment by zhangzc0419** [comment]
> 参数列表不支持HttpServletResponse，当前只支持HttpServletRequest，异常返回可以通过抛异常的方式
> 
> ```
> throw new InvocationException(400, "Request Error", "An error!");
> ```
> 或者使用
> 
> ```
>     @RequestMapping(value = "/test", produces = {"application/json"}, method = RequestMethod.GET)
>     @ApiResponses({
>             @ApiResponse(code = 500, message = "Internal error", response = User.class),
>             @ApiResponse(code = 200, message = "normal", response = Test.class),
>             @ApiResponse(code = 302, message = "normal")
>     })
>     public ResponseEntity<Object> getTest(@RequestParam(value = "name") String name) {
>         if (name == null) {
>             User u = new User();
>             u.setName("test");
>             return ResponseEntity.status(302)
>                     .header("Location", "www.baidu.com")
>                     .body(new InvocationException(Status.FOUND, ""));
>         }
>         Test test = new Test();
>         test.setName("bb");
>         ResponseEntity<Object> resp = ResponseEntity.ok(test);
>         return resp;
>     }
> ```

支持HttpServletRequest但不支持HttpServletResponse的原因是？

**Comment by wujimin** [comment]
ServiceComb中通信与业务是解耦的

**Comment by liubao68** [comment]
Clear long time not updated issue. Please feel free to submit a new one if problem happended again.
